### ISSUE TITLE
Ne plus utiliser le graph mirror pour les données importées via LDP PATCH

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#1002]
## Problématique
Le fait que les données importées via LDP PATCH se retrouvent dans le graph `http://semapps.org/mirror` oblige à systématiquement requêter ce graph et donc à faire des requêtes SPARQL compliquées [telles que montrées ici](https://github.com/assemblee-virtuelle/semapps/issues/996#issuecomment-1168765938) *même quand l'instance ne reflète (mirror) aucune autres instances*.

Je crains que ça va empirer les performances qui ne sont pas bonnes, et qui posent déjà des problèmes à @simonLouvet et à moi. SI on a des millions de triples dans le graph mirror, il est possible qu'on doive le requêter juste pour trouver une seule ressource importée via LDP PATCH.

De plus ça ajoute une particularité à SemApps: un développeur qui veut récupérer les ressources d'un container via SPARQL va être obligé de prendre en compte le graph `http://semapps.org/mirror` pour recevoir l'intégralité des ressources. Il faudrait partout mettre en garde sur ce point. Personnellement je n'ai pas envie que nos données deviennent structurées de manière tellement particulière qu'on est obligé de passer par le semantic data provider pour aller les trouver. Je trouve que c'est contraire à l'esprit des LOD.

La possibilité de réfléter (*mirror*) une autre instance est un plus, une option, mais ça ne doit pas venir perturber les développeurs qui veulent simplement obtenir les données de l'instance elle-même.

Par ailleurs, je trouve que ça apporte de la confusion, car l'importation via LDP PATCH n'a aucun rapport avec la fonctionnalité de "miroir", et donc ça n'a pas de sens que ça se retrouve dans un graph appelé `http://semapps.org/mirror`. D'ailleurs cette fonctionnalité n'a pas gérée par le MirrorService mais par le LdpService.

## Proposition

Je propose d'enregistrer ces données simplement dans le dataset par défault. Comme il s'agit d'importation "manuelle" et volontaire, cela ne va pas représenter des millions de triples. Elles pourront être requêtées comme n'importe quelle autres données, ce qui facilitera le travail des développeurs.

Si une données importées via LDP PATCH fait également partie de données miroirs, alors je propose de juste l'ignorer et de continuer la synchronisation manuelle. Il y aura des données en doublon, mais là encore, ces données ne représenteront pas des millions de triples. A la limite, dans un second temps, on pourra envisager de se baser sur la même synchronisation ActivityPub que les données miroirs.

Au lieu d'utiliser le prédicat `semapps:singleMirroredResource` (dont le nom contribue donc à cette confusion), je proposerais d'utiliser `semapps:lastSynchronized` ([comme c'était prévu dans l'issue](https://github.com/assemblee-virtuelle/semapps/issues/698#issuecomment-863343802)). L'avantage c'est que ça apporte une information pertinente, alors que le nom de domaine référencé par `semapps:singleMirroredResource` ne sera plus utile.

## Alternative

Ne plus utiliser le default graph (#996) ce qui simplifie un peu les requêtes SPARQL. Mais les problèmes de performances risquent de rester car on requêtes plus de données. De plus on ne règle pas les problèmes d'incohérences soulignés plus haut.

**Comment by nikoPLP** [comment]
> Au lieu d'utiliser le prédicat `semapps:singleMirroredResource` (dont le nom contribue donc à cette confusion), je proposerais d'utiliser `semapps:lastSynchronized` ([comme c'était prévu dans l'issue](https://github.com/assemblee-virtuelle/semapps/issues/698#issuecomment-863343802)). L'avantage c'est que ça apporte au moins une information pertinente, alors que le nom de domaine référencé par `semapps:singleMirroredResource` n'était pas utilisé.

Je me sers de `singleMirroredResource` dans le code, et de sa valeur (le nom de domaine). 

En effet je n'ai pas utilisé lastSynchronized car ca ne me servait a rien de savoir la derniere synchronisation (qui est periodique, et la meme plus ou moin spour toutes les single resources)

**Comment by nikoPLP** [comment]
Pour clarifier :
- LDP PATCH n ést pas réservé aux données qui viennent d'un autre serveur. Le PATCH sur le container permet d'ajouter ou d'enelver des resources dans ce container. Cela peut etre des resources locales ou des resources distantes. D'ailleurs, lorsqu'on ajoute une resource dans un container, la seule chose que LDP specifie c'est qu'un triplet `ldp:contains` y soit ajouté. Et c'est ce qu'on fait. LDP ne specifie rien sur la resource en elle meme. Le fait que nous decidons de faire une copie locale d'une resource distante ajoutée dans un container, est propre a semapps.
- Lorsqu'on fait un LDP CONTAINER GET, on obitent la liste de toutes les resources qui sont contenues dans ce container, et on recoit aussi le contenu de chacune de ces resources. Ca je ne suis pas sur que ca fasse aprtie de la spec LDP, et j'ai toujours considéré pour ma part que c'était un probleme. Ca fait beaucoup trop de données renvoyées, et dans certain cas, ce n'est surement pas ce que l'utilisateur du GET voulait. C'est aussi un probleme qui m'a empeché d'implementer la synchronisation avec les activityPubs en utilisant CREATE, car lorsque le serveur de mirroir fait un GET sur un container qui vient de changer (UPDATE) il recoit tout, y compris les resources qui viennent d'etre ajoutées, et donc c'est pour cette raison que j'ai enlevé les CREATE, car sinon on envoyait l'information deux fois.
- cela dit, l ímplementation actuelle du LDP container GET n'est pas plus lente qu'avant, meme si elle doit prendre certaines resources dans le graph mirroir, car le code est bien fait, et il n'y a pas d'UNION. je vais chercher chaque resource une part une, et si une resource est dans le graph mirroir, alors je vais la cherche la bas, sinon on la prend depuis le default graph. Donc avoir un graph mirroir ne ralentit pas les requetes LDP
- je comprends que vous tuliser beaucoup de requetes SPARQL depuis le frontend, et que ces requetes ont du etre modifiées. D'une part, je m'interroge sur cette situation de fait. Je pensais que le frontend de semapps etait basé sur un middleware LDP. Il me semble questionnable le choix de passer de plus en plus par du SPARQL. Ca rend la dependance du frontend sur semapps tres forte. C'est une question ouverte a mon avis. Surtout si on maintient l'objectif d'avoir d'autres logiciels frontend qui seraient basés sur semapps middleware (come Startin'blox).
- enfin, une des solutions est en effet de passer tout le contenu du defaultGraph dans un graph nommé (mainGraph ?) qui permettrait d'utiliser l'option `tdb:unionDefaultGraph=true` et le raccourci SPARQL `urn:x-arq:DefaultGraph` sans avoir besoin de faire des UNIONS explicitement. A noter que l'UNION du graph mainGraph et mirrorGraph se fera tout facon en sous main, et que les perfs seront identiques. Enfin a ce sujet, je ne suis pas sur que ce soit une tres bonne idee d'utiliser l'option `tdb:unionDefaultGraph=true` ni le raccourci `urn:x-arq:UnionGraph` car il va faire l'union de tous les graphes nommés, y comrpis le graph des ACLs.
- et a propos des performances, dont j'entends parler assez souvent, je me rends aussi compte que la plupart des problemes de performances sont liés à la maniere dont vous ecrivez vos requetes SPARQLs. Certes nous savons que les ACLs abaissent les performances(mais seulement dans les cas compliqués ou un droit n'est pas trouvé immediatement et qu'il faut remonter dans les containers), et maintenant j'entends que le nombre de triple qui existent dans le dataset affectent les performances. Si c'est le cas, c'est que votre requete est mal ecrite. En effet, ce symptome indique que votre requete parcourt l'ensemble des triples dans le dataset, ce qui est tres mauvais ! Donc dès que vous remarquez des performances qui se degradent lorsque le Dataset augmente en taille, vous avez a coup sur un probleme avec la requete SPARQL elle meme, pas avec le systeme sousjacent. 
- A noter aussi que si vous mettez des données mirroir dans le defaultGraph, avec une config avec ACLs activés, alors il faudra rajouter une permission Read pour `anon` sur cette resource. sinon elle ne pourra pas etre lue.

Bref, je comprends le questionnement, mais je pense que la solution proprosée un peu vite, mérite plus de reflexion.

Enfin, je me questionne sur :

> Le fait que les données importées via LDP PATCH se retrouvent dans le graph http://semapps.org/mirror oblige à systématiquement requêter ce graph et donc à faire des requêtes SPARQL compliquées même quand l'instance ne reflète (mirror) aucune autres instances.

Dans quelle mesure avez vous besoin de parcourir toutes les données d'un container ? Ca arrive aussi souvent que ca? et pourquoi passer par SPARQL quand le service LDP fait ca tres bien.
A part ce cas, je ne vois pas trop pourquoi il faudrait systematiquement inclure le graph des mirroir dans vos requetes SPARQL.
Il faudrait que je regarde la liste de vos requetes SPARQL et a quoi elles servent.
Avez vous une telle liste quelque part?

**Comment by simonLouvet** [comment]
Comme je l'ai mentionné à la dernière réunion technique, je ne mettais pas rendu compte du comportement différent entre les données synchronisées par fetch régulier et des données synchronisées par activity pub. Je pense que les 2 modes sont utiles mais devrait dépendre du type de serveur avec lequel on veut se synchroniser que du cas d'usage (import d'une entité vs miroir complet). Une donnée importée devrait pour moi être rafraîchi par fetch régulier si le serveur ne supporte pas de synchronisation activity pub et par activity pub sinon. Des données miroirs (un serveur ou un container complet) devrait pour moi être rafraîchi par fetch régulier si le serveur ne supporte pas de synchronisation activity pub et par activity pub sinon.

A la question dans quel graph, je n'ai pas d'avis tranché. Le fait que ces ressources soient dans un ou des graphs spécifiques correctement nommé ne ma choque pas et je suis même plutôt pour notamment pour la maintenance. Je n'ai pas de visibilité sur les impacts en terme de performance mais si la dégradation de performance est significative dans le cas de graphs dédié, je préférerais que tous les triplets soient dans le mm graph.

Concernant les performance et les questions de @nikoPLP , j'ai commencé une revue de performance qui va se clôturer ce début de semaine : https://pad.lescommuns.org/myZS93qkTw6h1W4etdQ7Mw?both

**Comment by nikoPLP** [comment]
> Une donnée importée devrait pour moi être rafraîchi par fetch régulier si le serveur ne supporte pas de synchronisation activity pub et par activity pub sinon

ceci n'est pas possible en l' état actuel car on ne peut pas souscrire a un acteur activitypub pour seulement une resource. Lorsqu'on souscrit a l'acteur `relay` (qui est le nom que nous avons choisi) alors on recoit les mises a jour de toutes les resources du serveur. Donc on ne peut pas faire de souscription pour une resource seulement. C'etait prevu dans les specs, mais c'est passé en tache optionnel, et ce n ést donc pas encore implementé.

**Comment by nikoPLP** [comment]
> Concernant les performance et les questions de @nikoPLP , j'ai commencé une revue de performance qui va se clôturer ce début de semaine : https://pad.lescommuns.org/myZS93qkTw6h1W4etdQ7Mw?both

Je viens de regarder le PAD Simon, et c'est une bonne idée en effet de faire des tests de performance de maniere structurée.

Je vois la requete qui commence par `FILTER(?containerUri IN(<http://localhost:3000/organizations>))`.

Ce genre de requete est un tres bon exemple de ce qu'il ne faut pas faire.

ce filtre doit parcourir tous les triples du dataset (ca deja c'est tres mauvais) puis il doit comparer la string de chaque sujet de triples avec la liste donnée.

Si on veut partir d'un container, c'est tres simple, et c'est tres important de commencer par quelque chose qui resemble a:
```
<http://localhost:3000/organizations> ?p ?o
```
directement dans le WHERE.

ou bien en utilisant seulement la ligne suivante, modifée ainsi :
```
<http://localhost:3000/organizations> ldp:contains ?s1.
```

**Comment by simonLouvet** [comment]
> > Concernant les performance et les questions de @nikoPLP , j'ai commencé une revue de performance qui va se clôturer ce début de semaine : https://pad.lescommuns.org/myZS93qkTw6h1W4etdQ7Mw?both
> 
> Je viens de regarder le PAD Simon, et c'est une bonne idée en effet de faire des tests de performance de maniere structurée.
> 
> Je vois la requete qui commence par `FILTER(?containerUri IN(<http://localhost:3000/organizations>))`.
> 
> Ce genre de requete est un tres bon exemple de ce qu'il ne faut pas faire.
> 
> ce filtre doit parcourir tous les triples du dataset (ca deja c'est tres mauvais) puis il doit comparer la string de chaque sujet de triples avec la liste donnée.
> 
> Si on veut partir d'un container, c'est tres simple, et c'est tres important de commencer par quelque chose qui resemble a:
> 
> ```
> <http://localhost:3000/organizations> ?p ?o
> ```
> 
> directement dans le WHERE.
> 
> ou bien en utilisant seulement la ligne suivante, modifée ainsi :
> 
> ```
> <http://localhost:3000/organizations> ldp:contains ?s1.
> ```

je vais faire des tests dans ce sens

**Comment by simonLouvet** [comment]
> on ne peut pas souscrire a u

Je comprends mais le serveur qui reçoit la notification pour une ressource qu'il ne possède pas peut simplement l'ignorer non?

**Comment by nikoPLP** [comment]
> Je comprends mais le serveur qui reçoit la notification pour une ressource qu'il ne possède pas peut simplement l'ignorer non?

oui en efet, ca va lui faire tout drole quand meme de recevoir des updates pour chaque resource du serveur distant, alors qu'il est interessé par juste une resource :)

C'est un choix a faire ;)

on avait choisit de ne pas aller dans ce sens et de faire un POLL CRON a la place.

A noter que c'est toujours prevu de creer des acteur pour chaque resource dans la tache " Passer par ActivityPub pour la synchronisation des données publiques - 3 JH (option)"

(il n'y a pas d'issue correspondante. il faut voir ca dans #451)

**Comment by srosset81** [comment]
Tu es sûr que `FILTER(?containerUri IN(<http://localhost:3000/organizations>))` pose problème ? On l'utilise au cas où on fait une recherche sur plusieurs containers (`FILTER(?containerUri IN(<http://localhost:3000/organizations>, <http://localhost:3000/projects>))` ).

Ce n'est pas un triple, donc je ne pensais pas que ça lançais une requête mais que ça permettait simplement de dire `?containerUri = http://localhost:3000/organizations OU http://localhost:3000/projects`

**Comment by srosset81** [comment]
Apparemment `FILTER` pose bien un problème de performance et il faudrait plutôt utiliser `VALUES`

https://stackoverflow.com/questions/20004956/how-to-improve-slow-query-using-filter-id-in

D'après l'auteur de ce message, en utilisant VALUES au lieu de FILTER, il est passé de requêtes à 14s à des requêtes à 2-3s !

Si c'est le cas, c'est une super nouvelle, merci @nikoPLP ! :-)

**Comment by srosset81** [comment]
Suite à un appel avec @nikoPLP on a décidé de laisser tomber ce refactoring, pour deux raisons:
- Les performances ne devraient pas être affectée par cette UNION supplémentaire
- Comme de toute façon le PATCH sur un container LDP n'est pas censé importer la donnée externe dans le dataset, un développeur qui se base uniquement sur les specs ne s'attend pas à retrouver les données dans le dataset. Le fait que ce soit importé dans le graph mirroir est donc un "plus" dont pourront profiter les développeurs plus avancés.

Je ferme donc cette issue et on la réouvrira si nécessaire.

**Comment by simonLouvet** [comment]
@nikoPLP & @srosset81  Utiliser le Values à la place du Filter ne change pas grand chose.
https://pad.lescommuns.org/myZS93qkTw6h1W4etdQ7Mw?both

**Comment by srosset81** [comment]
3 à 10% c'est pas rien quand même, et avec un dataset de 900'000 triplets j'imagine que le gain est plus important encore.
