### ISSUE TITLE
Gérer le slug dans la création de ressources

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#101]
Comme indiqué dans les specs https://www.w3.org/TR/ldp/ (exemple 15). si on passe un argument `Slug` dans le header lors de la création d'une ressource, utiliser ce slug au lieu d'un UUID.

Si le slug existe déjà, ajouter un nombre après (?)

**Comment by simonLouvet** [comment]
fix by https://github.com/assemblee-virtuelle/semapps/pull/111
