### ISSUE TITLE
Miroir: si une resource a été effacée, le serveur miroir ne l'efface pas

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#1013]
Voir https://github.com/assemblee-virtuelle/semapps/blob/next/src/middleware/packages/ldp/services/resource/methods.js#L12-L31

Si le serveur miroir n'arrive pas à obtenir une ressource via fetch, il envoie un message d'erreur via `this.logger.warn`. Mais rien ne se passe.

S'il y a une erreur 404 ou même 401 (plus le droit d'accéder à la ressource), il faudrait que la ressource soit supprimée du graph miroir.

Mais peut-être garder la relation `ldp:contains` sur le container ? Ou la supprimer aussi ?

Qu'en penses-tu @nikoPLP ?

**Comment by nikoPLP** [comment]
en effet il faudrait l'enlever si on obtient une 404 ou 401. 
A mon avis, il faudrait aussi dans ce cas enlever le ldp:contains
Je peux le faire. dites moi ce que vous en pensez

**Comment by srosset81** [comment]
@nikoPLP Oui effectivement il faudrait aussi supprimer le `ldp:contains` du container parent.
