### ISSUE TITLE
Enlever ou améliorer cache VOID

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#1017]
Le cache sur l'endpoint VOID n'est pas pratique du tout car, quand il est mis à jour, le navigateur ne le sait pas et charge une ancienne version.

https://github.com/assemblee-virtuelle/semapps/blob/next/src/middleware/packages/void/service.js#L272-L275

@nikoPLP tu disais que c'était requis par la spec ? J'ai de la peine à le croire tant c'est peu pratique et source de problèmes.

Sinon il faudrait au moins un mécanisme type ETag qui permet d'identifier s'il y a eu une mise à jour ou pas.

**Comment by srosset81** [comment]
J'ai supprimé le cache (f772bb2ecc035678984e1c93539217f83adcab39) car l'absence de mise à jour faisait planter toute la plateforme des Chemins de la Transition. Je laisse ouvert pour qu'on voit avec @nikoPLP si une solution via ETag est envisageable. Sinon je propose d'ignorer le cache: je pense que la plupart des endpoints VOID sont statiques car ils sont utilisés pour des bases de données documentaires. Nous on a besoin qu'il soit toujours à jour, car on l'utilise pour déterminer les données à charger.

**Comment by nikoPLP** [comment]
> tu disais que c'était requis par la spec ?

dans notre spec du travail sur l'interop. C'etait dans le cahier des charges de mon travail. Mais pas de probleme que tu aies enlevé le cache.
