### ISSUE TITLE
Améliorer l'affichage des libellés tronqués dans le menu

### ISSUE THREAD

**Issue by VincentFarcy** [assemblee-virtuelle/semapps#1023]
**Tension**
juste une amélioration visuelle

**Proposition**
Lorsque les noms de ressources sont trop longs ils sont purement et simplement tronqués dans le menu :   
![image](https://user-images.githubusercontent.com/55813208/185090679-ebf6e25a-7eb2-488a-b525-457d2ddad0b9.png)
Avec un peu de css on peut obtenir : 
![image](https://user-images.githubusercontent.com/55813208/185090859-af0f8024-ad78-494e-996c-1d0f4679d836.png)

**Alternatives**
Une autre solution pour maintenir le libellé complet :  
![image](https://user-images.githubusercontent.com/55813208/185091084-8953c7a3-a2b2-4c32-bbc0-b8193b9a6f87.png)

**Comment by fluidlog** [comment]
Merci pour cette issue, perso, j'aime bien conserver les deux lignes, tout en pensant à ajouter des "..." pour ne pas qu'il y ait une 3ème ligne... :)

**Comment by VincentFarcy** [comment]
j'ai fait une version avec une prop labelNbRows pour choisir le nb de lignes avant le ellipsis (1 ligne par défaut)
