### ISSUE TITLE
Ligne "Créer..." absente lors de l'utilisation du composant MultiServerAutocompleteArrayInput

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#1048]
**Décrivez le bug**
PAD de référence : https://pad.lescommuns.org/PasDeLigneCreerLorsDeLAffectationDesCompetences

Lors de l'ajout de compétence, nous utilisons le composant AutocompleteArrayInput.
Celui-ci, utilisé dans les chemins de la transition par exemple, permet de créer de nouvelles compétences directement depuis l'input d'affectation, en ajoutant une ligne "Créer..." à la fin de la liste de proposition de choix, et affichant une boite de dialogue permettant de créer une nouvelle compétence (via ESCO par exemple).
Or, dans le projet Carto4CH, j'ai récupérer ce code, mais en utilisant la fonction lié à l'interopérabilité MultiServerAutocompleteArrayInput. Et dans ce cas, la ligne "Créer..." n'apparait pas, ou alors, elle apparait faiblement en blanc sur 2 millimètres d'épaisseur...

![image](https://user-images.githubusercontent.com/6891994/193298504-754a8e66-cb75-4e72-b6a8-03cb144e04a8.png)

**Etapes pour reproduire**
1. Aller sur 'person'
2. Cliquer sur l'onglet des relations
3. Se rendre dans l'input des compétences
4. Essayer d'ajouter une nouvelle compétence à la liste, le bouton "Créer..." en bas de la liste n'apparait pas.

**Comportement attendu**
Le bouton "Créer..." devrait apparaitre en bas de la liste,
![image](https://user-images.githubusercontent.com/6891994/193299074-0e4c92e4-1f28-4a51-990e-836ef1fb6c82.png)
(mais avec en plus la précision du nom des serveurs en parallèle)
 pour accéder à la boite de dialogue 
![image](https://user-images.githubusercontent.com/6891994/193299228-2a52ca23-55f1-45af-8157-75502dca4925.png)

**Système**
Reproductible en version middleware 43 et frontend 36, avec le code des chemins de la transition, et l'adaptation pour utiliser l'interopérabilité.

**Comment by fluidlog** [comment]
J'ai commencé à bosser dessus : 
[Problème décrit aussi ici](https://pad.lescommuns.org/ComprehensionLexiconAutocompleteInput?view#Probl%C3%A8me-d%E2%80%99affichage-du-%E2%80%9CCr%C3%A9er%E2%80%9D)

PAD de description de ce que je comprends : 
https://pad.lescommuns.org/ComprehensionLexiconAutocompleteInput (voir les problèmes à la fin : 

Avec un focus sur le composant : 
https://pad.lescommuns.org/ComprehensionAutocompleteInput

Si vous souhaitez travailler sur ce bug, merci de me contacter, car j'ai bien envie d'aller jusqu'au bout !
Et surtout, ne me donnez pas la solution ! :)

**Comment by fluidlog** [comment]
**Résumé de la proposition de correction :** 
Lorsqu'on utilise la props **optionText** avec une fonction, et la props **Create**, la ligne **Créer** n'apparait pas.
C'est dû à un plantage dans la fonction, à cause de la ligne "Créer" justement, qui est différente des autres lignes (choices). Il faut donc prévoir le cas et distinguer les deux.
Pour éviter le plantage, il faut ajouter une ligne : 
```sas=
  if (!record || !server) return "Créer "+suggestion ;
```
Et pour compléter le mot "Créer" par la suggestion (lettre entrées au clavier dans l'input), il faut ajouter : 
```sas=
  const [suggestion, setSuggestion] = useState("");
  const matchSuggestion = useCallback(
    (filterValue, choice) => {
      setSuggestion(filterValue)
      return ( choice[optionText].toLowerCase().match(filterValue.toLowerCase()) )
    }, [optionText]
  );
```

Les fichiers impactés sont donc : 
* input-components/src/MultiServerAutocompleteArrayInput.js
* et input-components/src/OptionRenderer.js

Il faudra donc publier une nouvelle version de l'**input-component**.

**Comment by fluidlog** [comment]
Finalement, il semble que suite au passage en RA4, le bug a été corrigé (RA utilise à présent le composant Autocomple de MUI).

**Comment by srosset81** [comment]
Oui j'ai dû tout réécrire ce composant pour la mise à jour RA4
On peut fermer l'issue (et la PR associée) alors ?

**Comment by fluidlog** [comment]
Oui, j'ai fait pas mal de test, je pense que c'est bon, merci ! :)
