### ISSUE TITLE
Documenter les filtres spécifiques au semantic data provider

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#1076]
Il y en a 4:

- `sparqlWhere`: pour passer une requête SPARQL construite (en SPARQL.js)
- `_predicates`: pour ne retourner que certains prédicats (sinon retourne toute la ressource)
- `_servers`: pour sélectionner les serveurs à requêter (sinon utiliser les serveurs indiqués dans le data model)
- `blankNodes`: pour indiquer les blankNodes à déréférencer (sinon déréférence les blank nodes indiqués dans le data model ou l'endpoint VOID)

**Comment by simonLouvet** [comment]
@srosset81 je ne trouve pas la doc dans dev.semapps.org. normal? trouvé sur semapps.org.

**Comment by srosset81** [comment]
semapps.org est à jour
dev.semapps.org je n'ai pas pu le mettre à jour car problème d'espace disque.
