### ISSUE TITLE
Problème de CSS lors du rafraichissement des pages du site Semapps

### ISSUE THREAD

**Issue by VincentFarcy** [assemblee-virtuelle/semapps#1081]
**Décrivez le bug**
[Une description claire et concise du bug.](https://dev.semapps.org/)
Lors du rafraichissement des pages du site ou lors d'un c/c d'une url, le CSS est cassé.

**Etapes pour reproduire**
1. Aller sur ['...'](https://dev.semapps.org/)
2. Cliquer sur Middleware dans la navbar
3. Faire F5
4. Le CSS est cassé

**Comportement attendu**
Une description claire et concise de ce que à vous vous seriez attendu.

**Captures d'écran**
Si ça peut être utile, ajoutez ici des captures d'écrans pour expliquer le problème.
![image](https://user-images.githubusercontent.com/55813208/202140770-34b9330c-e793-4085-b4cd-2ec6f61a6886.png)

**Système**
Chrome 107.0.5304.107

**Comment by srosset81** [comment]
Réglé !
