### ISSUE TITLE
Arborescence des Thématiques + Multi sélection de thématique 

### ISSUE THREAD

**Issue by BastienSig** [assemblee-virtuelle/semapps#1096]
Ajout d'un composent supplémentaire alternatif ReferenceFilterTree.js.
ce composant s'utilise à la place de ReferenceFilter et permet d'afficher les thématiques en arborescence.
exemple : 

- Thématique 1
  - Thématique 1.1
  - Thématique 1.2
- Thématique 2
- Thématique 3
  - Thématique 3.1
  - Thématique 3.2
    - Thématique 3.2.1

Ce composant supporte la multiselection et permet via le SparqlWhere de filtrer avec plusieurs thématiques.

**Comment by BastienSig** [comment]
Pr obsolète, Le bute était de proposer la multi sélection. Mais ça ne fonctionne pas avec le cache redis.
Et nous avons stoppé le développement de cette feature pour se concentrer sur une sélection unique mais ergonomique et travaillé. (Mauvaise ergonomie en multi sélection, pas très intuitif)

**Comment by mguihal** [comment]
Ca vaudrait le coup de retravailler un jour sur cette feature de multi-sélection quand même je pense, ne serait-ce que pour se mettre à niveau vis-à-vis de la concurrence (par ex. Gogocarto gère cette feature)
