### ISSUE TITLE
Config pour déployer automatiquement sur Vercel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#112]
https://github.com/marketplace/actions/zeit-now-deployment
https://zeit.co/docs/v2/git-integration

**Comment by bouviermullerp** [comment]
@srosset81 I believe this issue is done, isnt'it ?

**Comment by srosset81** [comment]
Ah non en fait les déploiements sont fait pour le site web, pas pour le frontend SemApps :-)

**Comment by srosset81** [comment]
C'est fait ! 
Maintenant on aura un déploiement d'Archipel à chaque nouvelle PR. Lorsque la PR sera mergée sur `master`, elle sera automatiquement déployée sur archipel.assemblee-virtuelle.org. 

Au niveau des config Vercel, je lance un `npm run bootstrap` à la racine de /src/frontend, ce qui a pour résultat que, même si on n'a pas encore publié le package (ce qui se fait normalement seulement quand on a mergé sur master) on pourra quand même voir les modifications sur le package.

Cerise sur le gâteau: le déploiement du site web semapps.org ne se fait maintenant que si on a modifié le dossier website. De même le déploiement d'Archipel ne se fait que si on a modifié le dossier /src/frontend.

Remarque importante: les déploiements sur les PR et ceux sur la branche `next` utilise le middleware dev.data.virtual-assembly.org, alors que les déploiements fait sur la branche `master` utilisent le middleware data.virtual-assembly.org. Cela permet de faire de vrais tests sans corrompre les données de prod.

Visible ici: https://github.com/assemblee-virtuelle/semapps/pull/630

Ping @simonLouvet
