### ISSUE TITLE
inclure les service Auth et WebId dans Core

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#1132]
**Problématique**
un serveur Semapps qui n'est configuré qu'avec le package core ne peut pas démarrer si les service webId et Auth ne sont pas mis en place

**Composants concernés**
- core
- webid
- auth
**Proposition**
inclure les deux service dans core avec des configurations à fournir. Cela pourrait necessiter un refactoring de Auth qui depend du mixin.

**Comment by simonLouvet** [comment]
le composant core à besoin des composants auth et webId car il créé un service webACL, webFinger, AcivivityPub qui ont besoin de l'actor relay (et de la notion de user en generale) et donc des service webId et auth pour intergair avec cet acteur.

Il est donc possible de ne pas avoir besoin de mettre en place les service webId et Auth à condition de desactiver les ces service dans le paramétrge du service core.

`
{
    webacl: false,
    webfinger : false,
    activitypub : false
}
`

**Comment by simonLouvet** [comment]
proposition : proposer plusieurs core :
- non securisé
- sécurisé
- sécurisé + AtivitityPub

**Comment by srosset81** [comment]
Seul le service `auth.account` est vraiment nécessaire dans l'état pour utiliser les services webacl / webfinger / activitypub. S'il n'y a pas besoin d'authentification, il est possible d'ajouter seulement ce service, comme j'ai fait ici:

https://github.com/assemblee-virtuelle/activitypub-bridge/blob/master/services/auth.account.service.js

Dans ce cas, le service webId n'est pas nécessaire.

Il faudrait refactorer les services webacl / webfinger / activitypub pour que cette dépendance disparaisse.

**Comment by srosset81** [comment]
Je ferme puisque pas de réaction.
