### ISSUE TITLE
No record when we change ontology in MarkdownInput component

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#1141]
**Décrivez le bug**
Ordinary, MarkdownInput use "pair:description" to save description. If you replace "pair:description" by "heco:hasDescription" (in front, in context and in database), there's no error in middleware logs, but it doesn't save nothing.

**Etapes pour reproduire**
1. Change for exemple ThemeEdit.js with new predicate
2. Change ThemeShow.js with the same
3. save + F5 -> the markdown field is empty, and no triplet stored in database (no INSERT in middleware logs)

**Comportement attendu**
A new triplet in database using new predicate

**Système**
Chrome/brave

**Comment by fluidlog** [comment]
Doc : https://pad.lescommuns.org/Carto4chPasDEnregistrementSiChangementPredicatMarkdownInput

**Comment by fluidlog** [comment]
Actualy, when I come back to "pair:description", and when it's declared in context.json, it doesn't succeed.
If I remove it from context.json, it works well... Unbelievable ! :(

**Comment by srosset81** [comment]
I don't think it has to do with the MarkdownInput component. Probably more to do with the JSON context. Make sure you empty the Redis cache if you use it.
