### ISSUE TITLE
No display type & status in ReferenceInput

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#1142]
**Décrivez le bug**
For exemple in organization Edit, input of type & status are empty.
When you refresh page, it display the content.

**Etapes pour reproduire**
1. Open an organization which have a type or/and a status
2. Clic "Edit" button
3. See input field Type & status empty

**Comportement attendu**
Display the content of type & status field

**Système**
Chrome, firefox

**Comment by fluidlog** [comment]
Doc : https://pad.lescommuns.org/Carto4chNonAffichageDuContenuDeReferenceInput

**Comment by srosset81** [comment]
I cannot reproduce the problem. If I go to https://archipel.assemblee-virtuelle.org/Organization/https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2Fassemblee_virtuelle/show and click on "Editer", the status and types appear correctly.

**Comment by fluidlog** [comment]
Actually, when I test, the first time, it's OK, I refresh with Ctrl+F5, come back on the show, then Edit, and the problem appears each time...
If I open a new tab in chrome, restart, it's OK until I refresh with Ctrl+F5.

**Comment by fluidlog** [comment]
This morning, I can't reproduce it the first time, but when I wait after some minutes, the problème appear.

![image](https://github.com/assemblee-virtuelle/semapps/assets/6891994/fc6071ce-93c6-4c14-8f9f-670d6ff265fd)

In Archipel : 

![image](https://github.com/assemblee-virtuelle/semapps/assets/6891994/8760f653-e86b-4e51-ba2b-28a44a258045)

(see exemple in the PAD)

**Comment by fluidlog** [comment]
I've modify locally the code of ReferenceInput, because in some case (see https://pad.lescommuns.org/Carto4chNonAffichageDuContenuDeReferenceInput), value is an array.

```
const format = value => {
  // If value is an array, return value[0]
  if (Array.isArray(value)) return value[0]
  // If there is no value, return immediately
  if (!value) return value;
  // If the value is an object with an @id field, return the uri
  return typeof value === 'object' ? value.id || value['@id'] : value;
};
```
