### ISSUE TITLE
Can't find recordId using ShowWithPermissions in PageShow when call by HomePage

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#1149]
**Décrivez le bug**
If you use ShowWithPermissions in PageShow when it's call by HomePage with ShowContextProvider, an error appear.
Error: useGetRecordId could not find the current record id. You need to use it inside a RecordContextProvider, or inside a supported route, or provide the record id to the hook yourself.

**Etapes pour reproduire**
1. Edit app.js with dashboard={HomePage}
2. In HomePage, call PageShow with ShowContextProvider
3. in PageShow, use ShowWithPermissions in spite of archipelago layout show
4. display http://localhost:4000/, and see error.

**Comportement attendu**
The HomePage must display

**Captures d'écran**
![image](https://github.com/assemblee-virtuelle/semapps/assets/6891994/0f10fc8e-b844-4b95-af81-068e0c43ab90)

**Système**
Chrome

**Comment by fluidlog** [comment]
Voir https://pad.lescommuns.org/SimplificationDuBoRa4?view#Probl%C3%A8me-avec-PageShow-provenant-de-HomePage

**Comment by srosset81** [comment]
The problem is clearly indicated in the error message: you must add a `ShowContextProvider` to your `HomePage` component. It is configured automatically for `/show` pages, but not custom pages.

**Comment by fluidlog** [comment]
It's what I do (see code in PAD). I use ShowContextProvider in my HomePage.
But I use a spécial context may be... (minicourse)
