### ISSUE TITLE
réflexion sur l'uri des users "system"

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#116]
Je n'ai pas compris pourquoi les profils foaf des users soient avec une uri de type /user/id plutôt que ldp/foaf:Person/id. Je suis toujours ok pour des alias de manière à ce que ldp/foaf:Person/id soit accessible à travers alias/user/id et peut être user/id (a spécifier) grâce à de la configuration du serveur (par fichier ou backoffice). Est ce que c'est pour différencier les users "métier" des users "system"? si c'est le cas, je pense qu'il est possible de les différencier par un triplet. Cela me semble un terrain glissant de les différencier par l'uri notamment par ce que le container http://host:port/users n'existe pas et que nous allons permettre au user d'importer un profil externe.

**Comment by srosset81** [comment]
> Cela me semble un terrain glissant de les différencier par l'uri notamment par ce que le container http://host:port/users n'existe pas et que nous allons permettre au user d'importer un profil externe.

J'ai créé un path particulier justement pour éviter que http://host:port/users soit un container à part entière ! Car on ne veut pas que les utilisateurs puissent POSTer dans /users : il faut impérativement qu'ils passent par l'autentification. Avec ce que j'ai fait, c'est le service `webid` qui contrôle tout le processus, même s'il passe par le service `ldp` pour éviter de répéter du code (c'est l'avantage d'une architecture modulaire).

On aurait aussi pu utiliser un container persisté en triple store ("container standard"), ou un alias. J'ai pensé dans un premier temps implémenter les alias mais cela me semblait être un gros travail en soi.

**Comment by bouviermullerp** [comment]
Est-ce qu'on peut fermer cette issue @simonLouvet @srosset81 ?

**Comment by simonLouvet** [comment]
ok pour moi. l'API user authentifié  et un container de pair:Person ne sont pas la même chose

**Comment by simonLouvet** [comment]
> Est-ce qu'on peut fermer cette issue @simonLouvet @srosset81 ?

ok pour moi. l'API user authentifié et un container de pair:Person ne sont pas la même chose. l'API des user Authentifiés sert pour l'authentification, la gestion de droits alors que'un api de type container de pair:Person sert à stoker des datas "classique" sur une personne.

Si seul l'API user authentifié existe, cela veut dire que toute données lié à une personne sont rattachées directement au user authentifié.
Si seul l'API de container pair:Person existe, cela veut dire qu'il n'y a pas de notion de user authentifié (donc pas d'ACL) et que les data sont en OpenData. ATTENTION : risque majeur d'infraction RGPD et éthique
Si les 2 existent sur une appli, cela veux dire que il y a une logique de rattachement des données "classique" à un compte utilisateur. ATTENTION : complexité de rattachement de data à un compte complexe à prévoir et non encore développé.
Cela me sert également de conclusion pour la #335 concernant les Users suite a sprint review du 12/07/2020
