### ISSUE TITLE
[Middleware 0.6.0-alpha-1] Uploaded images responses do not always work

### ISSUE THREAD

**Issue by mguihal** [assemblee-virtuelle/semapps#1185]
**Décrivez le bug**
Hi, not sure if this is really a bug or a breaking change, but on the latest version of middleware (0.6.0-alpha-1), the response for an uploaded image may not work correctly, responding a JSON instead of binary image.

After investigation, I found that there https://github.com/assemblee-virtuelle/semapps/blob/next/src/middleware/packages/ldp/services/api/actions/get.js#L83-L95 the type required for images is `http://semapps.org/ns/core#File`, but in some cases, the uploaded files have the type `semapps:File`. It seems that it's only for old uploaded files (the newer files uploaded have the `http://semapps.org/ns/core#File` type and it's working well).

In some other files, the `semapps:File` type is still visible in code (ex: https://github.com/assemblee-virtuelle/semapps/blob/next/src/middleware/packages/ldp/services/resource/actions/delete.js#L43), and in the documentation too (https://semapps.org/docs/middleware/ldp/image-processor).

**Comment by srosset81** [comment]
If a file description is registered as `semapps:File` strings in the triple store, it means we didn't pass the right context when storing the resource.

It's maybe an old bug. The best would be to do a simple migration on the triplestore, where you convert `semapps:File` to `http://semapps.org/ns/core#File`. A single SPARQL update can do that.

The fact we have `semapps:File` in some parts of the code is not a bug, as long as the context is good. But it's an usage that is prone to bugs nonetheless. We should systematically expand received JSONLD resources or compact them with a controlled context. I'm thinking about a small library to make it easier...

**Comment by mguihal** [comment]
> It's maybe an old bug.

It's actually the default file description when we upload a file on Archipelago master branch (using Semapps 0.4.0-rc.1), so it's not so old :)

> The best would be to do a simple migration on the triplestore

I can, but I'm sure I will not be the only one with this bug...
If Semapps is not backwards compatible between versions, we need to include either:
- Minimal: A database migration guide for each release with Sparql queries to execute when upgrading, and the same queries necessary when downgrading
- Better: Automatic database up and down migration service in middleware (maybe as a subservice in semapps/triplestore?), in the way other migration services works (such as https://www.npmjs.com/package/db-migrate)

**Comment by srosset81** [comment]
How many people/instance does that concern ? Only a few. I wouldn't bother about automatic migrations until we have a larger user base.

**Comment by mguihal** [comment]
I close this issue, as a db migration service has been added to Archipelago.  
See https://github.com/assemblee-virtuelle/archipelago/pull/141 for more details.

Maybe one day we may move it here.
