### ISSUE TITLE
Créer un module SemApps pour gérer les OpenBadge

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#120]
Le standard [OpenBadge](https://openbadges.org/get-started/), promu notamment par Mozilla, utilise une ontologie et du JSON-LD :

http://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html

Grâce à notre architecture modulaire, il serait peut-être possible de gérer la création et la récolte d'OpenBadge. En lien avec l'ontologie PAIR, cela aurait ouvrirait plein de perspectives !

**Comment by GuillaumeAV** [comment]
Olalala ooh oui ! Notamment pour les chemins de la transition pour lesquels
on veut implémenter les open badges !

**Comment by srosset81** [comment]
En cours sur https://activitybadges.org Je ferme cette vieille issue.
