### ISSUE TITLE
Premiers tests d'intégration pour le serveur LDP

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#126]
Avec le CRUD

**Comment by srosset81** [comment]
Ils sont en train d'envisager la création d'outils pour faciliter les tests sur les services Moleculer, on aura peut-être avantage à attendre que ce soit prêt avant de continuer les tests, à moins qu'ils ne nécessitent pas d'attendre des événements.

https://github.com/moleculerjs/rfcs/issues/3

**Comment by simonLouvet** [comment]
TODO : CRUD sur la couche basse et la couche haute. GET dans  tous les type accept sur la couche basse
