### ISSUE TITLE
Service HTTP Signature

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#128]
Se baser sur ces packages:
https://github.com/digitalbazaar/http-signature-header
https://github.com/joyent/node-http-signature

Deux actions:
- `signature.sign`
- `signature.verify`

**Comment by simonLouvet** [comment]
peux tu préciser l'usage stp.

**Comment by srosset81** [comment]
@simonLouvet Pour signer et vérifier les messages ActivityPub qui sont envoyés de serveur à serveur. 
https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization
