### ISSUE TITLE
Semapps documentation website is not up to date

### ISSUE THREAD

**Issue by mguihal** [assemblee-virtuelle/semapps#1287]
Hello,

I spotted that the website https://semapps.org/docs seem to not be up to date with current repository doc files.

Example: 
- https://semapps.org/docs/middleware/signature/ is still on the website, whereas it is replaced by crypto service in the repository

Is this website redeployed manually? What is the process to update it? Can it be redeployed automatically when something is merged/released here?

**Comment by srosset81** [comment]
I tried to deploy it but I have an error on Docusaurus build:

```
#0 3.100 [INFO] [en] Creating an optimized production build...
#0 3.522 [ERROR] Error while parsing Markdown front matter.
#0 3.522 This can happen if you use special characters in front matter values (try using double quotes around that value).
#0 3.533 [ERROR] Loading of version failed for version current
#0 3.533 [ERROR] Unable to build website for locale en.
#0 3.534 [ERROR] YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 3, column 1:
```

Indeed it is not redeployed automatically. I've noticed recently there is a [Github action to call scripts through SSH](https://github.com/appleboy/ssh-action), it looks like it would be an easy way to redeploy the website (we would just need to call `docker compose build website && docker compose up -d website`). Tell me if you want to tackle this issue, I can give you SSH access to the server (and I can give you SSH access anyway, I just need your public SSH key)

**Comment by srosset81** [comment]
Done here https://github.com/assemblee-virtuelle/semapps/pull/1289

**Comment by mguihal** [comment]
Nice, thanks!
