### ISSUE TITLE
Créer un DBAdapter Moleculer pour LDP

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#130]
**Pourquoi ?**

Moleculer propose un certain nombre d'adaptateurs qui permettent de facilement enregistrer des données. 

https://moleculer.services/docs/0.13/moleculer-db.html

Si on proposait un adaptateur LDP (ou triple store, à voir ce qui est plus pertinent), on pourrait permettre à n'importe quel service Moleculer d'enregistrer du JSON-LD soit avec MongoDB, soit avec un triple store.

Cela serait utile pour des petits services qui ont juste besoin de se plugger sur le triple store, mais qui voudraient aussi proposer une option MongoDB au cas où l'on n'a pas accès à un triple store.

**Comment ?**

Se baser sur l'adapter Mongo existant:
https://github.com/moleculerjs/moleculer-db/tree/master/packages/moleculer-db-adapter-mongo

L'API pourrait ressembler à ça:
```javascript
const { ServiceBroker } = require("moleculer");
const DbService = require("moleculer-db");
const LdpDBAdapter = require("moleculer-db-adapter-ldp");

const broker = new ServiceBroker();

// Create a Mongoose service for `post` entities
broker.createService({
    name: "projects",
    mixins: [DbService],
    adapter: new LdpDBAdapter("http://localhost/ldp/pair:Project"),
});

broker.start()
// Create a new project
.then(() => broker.call("projects.create", {
   "@context": "http://virtual-assembly.org/ontologies/pair#",
   "type": "Project",
   "name": "SemApps"
}))

// Get all projects
.then(() => broker.call("projects.find").then(console.log));
```

**Comment by srosset81** [comment]
Ping @simonLouvet @nikoPLP :-)

**Comment by nikoPLP** [comment]
Oui c'est tres cool comme idée !
Il me semble que le plus simple serait un adaptor LDP, plutot que sparql, car tout le boulot pour les CRUDS est deja fait dans le middleware LDP vers sparql, donc LDP est vraiment ben adapté pour faire un adaptor ;)
Qu'en pensez vous ?

**Comment by simonLouvet** [comment]
ok sur le principe. LDP c'est une surcouche de HTTP donc ca me semble être une couche d'architecture trop haute et j'aurais tendance à faire l'adapter sur le tripleStore. Cependant, si nous dissociations le service LDP de l'interface http (#125 )  c'est ok de faire un adapter sur le service mais on le peut pas dire que c'est un adapter LDP car la couche de service n'est pas LDP qui est l'interface HTTP.

**Comment by nikoPLP** [comment]
Tres bien, ce serait un adapteur triplestore alors, qui en interne, utilise les CRUDs resultant de la sissociation entre API HTTP et action moleculer. Ca me parait une bonne solution

**Comment by srosset81** [comment]
D'accord avec la solution ! :-)
