### ISSUE TITLE
Code watch does not work for Typescript files

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#1300]
If I run `yarn run watch` on the @semapps/activitypub-components package, and modify a TS file, nothing happens.

If I modify a JS file, the package is rebuilt.

Any idea @Laurin-W or @mguihal ?

**Comment by mguihal** [comment]
Hello,
Yes you need to add --ext ts,tsx,js option

It is already done here: https://github.com/assemblee-virtuelle/semapps/blob/master/src/frontend/packages/semantic-data-provider/package.json#L15

**Comment by srosset81** [comment]
Thanks @mguihal ! I added the option on all packages
