### ISSUE TITLE
Show error message to user, if authProvider login fails

### ISSUE THREAD

**Issue by Laurin-W** [assemblee-virtuelle/semapps#1310]
Right now, there is nothing shown to the user, when I'm trying to log in using the login component and an error is thrown:
An error is thrown, e.g. here:
https://github.com/assemblee-virtuelle/semapps/blob/21411f86a47a74b759118570d3db59ed028fd92b/src/frontend/packages/auth-provider/src/authProvider.js#L52

**Comment by srosset81** [comment]
Probably something to do on the LocalLoginPage component or equivalent, as shown in this example:

https://marmelab.com/react-admin/useLogin.html

**Comment by Laurin-W** [comment]
Ah thanks, so this will go here: https://github.com/activitypods/activitypods/blob/master/app-framework/react/src/components/PodLoginPage.tsx

Created an issue for APods https://github.com/activitypods/activitypods/issues/301
