### ISSUE TITLE
Finaliser WebID

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#137]
S'assurer qu'on respecte bien toutes les spécifications de WebID:
https://www.w3.org/2005/Incubator/webid/spec/identity/

**Comment by simonLouvet** [comment]
+ refactoring de Connector pour lui passer une méthode de webID pour pouvoir retrouver l'uri du WebId à partir du token plutôt que de lui fournir une méthode depuis le runner

**Comment by simonLouvet** [comment]
Apres consultation de de Ruben et Henry, et Echange avec @srosset81 nous somme arriver à la conclusion que [le théorème de toujours référencer un élément du monde réel (Thing) par un document numérique](https://www.w3.org/TR/cooluris/) était inapproprié dans l'état d'avancement actuel du projet et potentiellement pour le projet lui-même. Cela vient notamment du fait que une ressource sérialisé dans différents formalisme (triple, html,json-ld..) est référencé avec la même uri et est sérialisé différemment en fonction du header Accept.
Par conséquent le fait que un Agent référencé par un webId doivent être fourni à travers un PersonalProfileDocument selon la norme webId  est ignoré pour le moment. Cela remettrait en cause toute la manière dont le serveur délivre les données toute uri qui référence une Thing devrait faire une redirection 303 vers le document qui la décrit.
