### ISSUE TITLE
Impossible d'envoyer un message

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#144]
1 - Login
2 - Follow a user
3 - Send a message with a title and a message
4 - Error -> http://playground.semapps.org:5000/messages/?recipientUri=http://51.68.81.68:3000/users/simon.louvet.zen

![Capture d’écran 2020-02-06 à 09 06 29](https://user-images.githubusercontent.com/36893311/73917616-0e5b3300-48c0-11ea-90a7-8ff4868348ee.png)

**Comment by srosset81** [comment]
Je ferme cette issue puisque les fonctionnalités basiques (et très buggées) d'ActivityPub ont été enlevées du playground pour le moment.

**Comment by bouviermullerp** [comment]
@srosset81 cette issue n'est pas reproductible dans le DMS alors ?

**Comment by srosset81** [comment]
@bouviermullerp Il n'y a pas de fonctionnalités ActivityPub dans le DMS.
