### ISSUE TITLE
Impossible de se connecter ...

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#146]
Je ne sais plus si c'est normal ou pas ... 

Quand j'essaie de me connecter sur l'oidc des communs je tombe systématiquement sur : 
"_Vous devez vérifier votre courriel pour activer votre compte_."

Je pensais l'avoir activé .. Et puis le mail n'arrive jamais ...

**Comment by srosset81** [comment]
@GuillaumeAV Ce bug me semble être du côté des Communs, on ne peut pas faire grand chose.

**Comment by srosset81** [comment]
Assigné à @simonLouvet

**Comment by simonLouvet** [comment]
mail et messages envoyé à marc qui est a maintainer de login.lescommuns.org

**Comment by simonLouvet** [comment]
Problème avec login.lescommuns.org résolu.
La réinitialisation du mot de passe est réparé.
En cas de grosse complication ou corruption du compte (comme c'était le cas pour guilaume) il faut supprimer le compte sur le serveur OIDC
