### ISSUE TITLE
Implémenter les fonctionnalités Github

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#147]
- Fork : Je peux dupliquer une donnée et son contexte sur une autre instance par exemple, et la faire évoluer indépendamment de la branche principale. Tout en conservant l'historique et la "généalogie" du fork -> Ce qui revient à créer une branche. 

- Merge : Je peux décider de fusionner des branches en revenant à la source ou en actualisant la source. 

- Pull request : Je peux proposer à qui de droit l'intégration d'évolutions souhaitables
Exemples (liés à une ontologie ad hoc) : 
  - Ajouter une relation "s'interesse à" entre "Sebastien Rosset" & "ActivityPub"

  - Ajouter une relation "est le parrain de / est parrainé par" entre "Thierry" & "Niko" 
=> Dans le formulaire, la question pourrait être "Choisis un parrain"
=> Le parrain identifié pourrait choisir d'accepter ou non en validant la "pull request" de devenir le parrain de ... 
Au passage, ceci est un exemple de fonctionnalité/service data/ontology driven ;-)

 

-

**Comment by srosset81** [comment]
Avec l'activité Offer on pourrait déjà offrir une sorte de pull request simplifiée :

https://socialhub.activitypub.rocks/t/idea-for-a-new-suggest-activity/328
