### ISSUE TITLE
Développer l'application mobile

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#16]

**Comment by srosset81** [comment]
Ca correspond à quoi cette issue @bouviermullerp ?

**Comment by bouviermullerp** [comment]
@srosset81 c'est un cas que j'ai ouvert à l'ouverture du projet lors de la création du backlog. ça correspond à s'assurer qu'on peut accéder à SemApps sur mobile, mais comme j'ai l'impression que le titre est suffisamment explicite, je me demande si j'ai bien compris ta question.

**Comment by srosset81** [comment]
Pour moi une application mobile c'est différent d'un site qui est accessible sur mobile (et qui est donc "responsive" comme on dit). Une application mobile, c'est ce que développe Reconnexion par exemple, avec déploiement dans les stores Google Play et Apple.

J'ai quand même de la peine avec cette issue car on a déjà plusieurs sortes d'interface, alors de quoi parle-t-on ? Du DMS ? Du playground ? SemApps en tant que backend/middleware peut être accédé par mobile mais ce n'est pas spectaculaire ;-)

**Comment by bouviermullerp** [comment]
@srosset81 cette issue a été créé au lancement du projet, à l'époque j'avais créé tout une série d'issue pour constituer un backlog et offrir de la visibilité sur ce qu'on pourrait développer et générer des discussions. 
Si elle te gène, on peut la fermer, il n'y a pas grand chose à faire pour le moment, si ce n'est discuter sur la pertinence de l'issue - et donc la spécifier.

**Comment by ReX-AV-Gab** [comment]
Oui, on la ferme.
