### ISSUE TITLE
Installer un logiciel pour présenter la documentation

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#163]
Si on veut que SemApps soit utilisé par d'autres développeurs, et que d'autres développeurs puissent contribuer, il faut qu'on ait une documentation technique claire, lisible et à jour.

Il faudrait notamment que chaque package, et même chaque service, soit documenté précisément.

Nous avons déjà décidé de mettre la documentation technique directement sur le repo Github, afin que le versioning puisse être fait correctement, et pour pouvoir, à terme, demander à ce que chaque PR soit accompagnée de documentation adéquate.

Cependant pour faciliter la lecture, et notamment pour s'y retrouver dans tous les packages / services qu'on va proposer, il me semble important d'utiliser un logiciel qui permettrait de présenter correctement toute cette documentation.

Il existe plusieurs outils qui permettent de générer un site de documentation à partir de fichiers markdown commités directement sur Git. Voilà ceux que j'ai trouvé parmi les solutions les plus populaires:

https://docsify.js.org (12k stars)
https://vuepress.vuejs.org (15k stars)
https://docusaurus.io (15k stars)
https://www.mkdocs.org (9k stars)

Est-ce que vous en voyez d'autres ?

Parmi les points qui me semblent importants à vérifier:

- Bien adapté pour documenter des API complexes (microservices, packages...)
- Gestion du versioning (= possibilité de générer une doc pour chaque version)
- Gestion multi-langue (sauf si on décide de tout écrire en anglais, pour toujours)
- SEO friendly

J'avoue avoir une préférence pour Docusaurus car, malgré qu'il soit proposé par Facebook, il a l'avantage de documenter des logiciels complexes comme Babel et React. Mais Vuepress a l'air bien complet aussi.

Des avis @simonLouvet @nikoPLP ?

**Comment by srosset81** [comment]
Une autre option serait d'utiliser le même logiciel que pour la doc Moleculer: https://hexo.io/
L'avantage serait de rester dans l'écosystème :-)

**Comment by simonLouvet** [comment]
j'aurais tendance à prendre le plus réputé qui répond à notre besoin :  Docusaurus
