### ISSUE TITLE
Proposer une CLI pour créer un projet SemApps

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#182]
Create React App propose un [système de templates](https://create-react-app.dev/docs/custom-templates), qui permet de créer un nouveau projet sur certaines bases.
NextJS propose également un système qui permet de créer un projet via [une ligne de commande](https://nextjs.org/docs#setup).

Il serait intéressant de proposer un outil similaire pour SemApps, un package nommé par exemple `@semapps/create-app` qui permettrait de lancer un nouveau projet en une ligne de commande.

En le lançant on aurait des questions de ce genre:

```
$ yarn create @semapps/app [directory name]
   - What template do you want to use for the middleware ?
     [X] LDP
     [ ] ActivityPub
     [ ] Solid POD
   - Do you need to install a data management system ? [Y/n]
   - Do you want to install a local instance of Jena ? [Y/n]
   - What is the URL of your distant Jena instance ?
```

Si l'utilisateur choisit d'installer une instance Jena local, il faudrait passer par Docker, mais je pense que c'est possible de le faire via NPM / Yarn.

**Comment by srosset81** [comment]
Autre projet qui propose une installation en une ligne de commande:
https://factor.dev/guide/quickstart

**Comment by GuillaumeAV** [comment]
Ooh ce serait beau !!

Le lun. 16 mars 2020 à 10:40, Sébastien Rosset <notifications@github.com> a
écrit :

**Comment by srosset81** [comment]
Autre inspiration:
https://github.com/moleculerjs/moleculer-cli
On pourrait d'ailleurs se baser sur les templates moleculer pour proposer des middleware "prêts à l'emploi"

**Comment by srosset81** [comment]
Fait dans ce repo: https://github.com/assemblee-virtuelle/semapps-template-ldp
