### ISSUE TITLE
Timeout après connexion OIDC

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#185]
![image](https://user-images.githubusercontent.com/5068825/76956260-fbeb0500-6913-11ea-9dcb-762a278b187f.png)

**Comment by simonLouvet** [comment]
au retour d'une authentification

**Comment by nikoPLP** [comment]
a  propos du bug "nginx" c'est le serveur middleware qui n'a pas repondu. je ne vois rien dans les logs car le docker a été redémarré par la suite. i lfaudrait refaire la meme manip qui a conduit a cette heure, et indiquer l'heur et minute exacte de la manip, pour qu'on retrouve dans les logs. En tout cas, c ést un probleme du middleware, pas de nginx.

**Comment by srosset81** [comment]
Il est possible que j'ai fait un déploiement à ce moment.
@simonLouvet peux-tu essayer de reproduire ? Sinon je propose de fermer cette issue.

**Comment by simonLouvet** [comment]
@srosset81 j'ai reproduit 2 fois, il suffit de se déconnecter globalement puis de retourner sur se connecter. @nikoPLP c'etait vers 10h12 en france. Je regarde si j'ai le temps coté middleware. @nikoPLP t'as acces au serveur OVH? cool c'est @srosset81 qui a ajouté ta clef ssh sur le serveur?

**Comment by srosset81** [comment]
@simonLouvet Oui je l'ai ajouté dans la liste des `authorized_keys` de l'user ubuntu
Je reproduits également (seulement dans le cas où on passe par le formulaire de connexion des Communs), mais je pense pas que c'est une erreur Nginx.

A noter que j'ai refait un build il y a quelques minutes, donc certaines anciennes erreurs ont été effacées (faudrait peut-être mettre les logs en dehors des containers...)

**Comment by simonLouvet** [comment]
Je reproduis en locale sans le nginx, le serveur middlware ne repond pas au retour OIDC.
