### ISSUE TITLE
LDP: gérer l'upload de fichiers

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#186]
Voir https://www.w3.org/TR/ldp-primer/ (section 2.5) et https://www.w3.org/TR/ldp/#ldpnr

**Comment by simonLouvet** [comment]
@srosset81  est ce que c'est urgent? tu as un besoin?

**Comment by srosset81** [comment]
Non pas de besoin pour le moment, c'est juste pour ne pas oublier :-)
