### ISSUE TITLE
[Playground] Fusionner les boutons Rechercher / Ajouter 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#188]
Proposer, comme dans RoamResearch, une barre de complétion sur les données existantes. Dans le cas où la donnée n'existe pas, ajouter une donnée ...

**Comment by bouviermullerp** [comment]
duplicate de assemblee-virtuelle/archipelago#171 n'est ce pas ? @GuillaumeAV
