### ISSUE TITLE
Ajouter un bouton "Sponsor" en haut du repo Github ?

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#195]
Voir la doc:
https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

On pourrait créer un compte sur https://opencollective.com ?

**Comment by GuillaumeAV** [comment]
Si vous êtes chauds, je suis chaud !

**Comment by ReX-AV-Gab** [comment]
Je suis chaud bouillant !

**Comment by srosset81** [comment]
@GuillaumeAV Je pense qu'il faut que ce soit toi qui ouvre un compte sur https://opencollective.com
Après on peut configurer le bouton sur Github.

**Comment by GuillaumeAV** [comment]
J'ai lancé une [discussion sur l'AGP SemApps en préalable](https://framavox.org/d/HbT1Ia24/est-ce-qu-on-ouvrirait-pas-un-compte-sur-open-collective-) !

**Comment by srosset81** [comment]
Du coup @bouviermullerp avait mis une objection sur le framavox.
Qu'en penses-tu @simonLouvet en tant que nouveau rôle pérennité économique ? Trop prématuré ?

**Comment by bouviermullerp** [comment]
@srosset81 pour précision, je n'avais pas émis d'objection cf [la discussion](https://framavox.org/d/HbT1Ia24/est-ce-qu-on-ouvrirait-pas-un-compte-sur-open-collective-)

**Comment by srosset81** [comment]
Ah désolé, j'avais zappé ton second message.
Je comprends mieux, et du coup je pense que ce serait intéressant de faire quelque chose suite à cette AGP ?

**Comment by srosset81** [comment]
@GuillaumeAV J'ai activé le bouton "Sponsor" en mettant un lien vers l'OpenCollective de SemApps. C'est visible dans la barre de droite du repo, et peut-être ailleurs.

![Capture d’écran de 2023-01-06 11-32-49](https://user-images.githubusercontent.com/17931931/210989952-3ee8844f-5f8e-4c42-8fe1-bfc38712a03c.png)

**Comment by srosset81** [comment]
On pourrait aussi le faire pour les sous-projets Archipelago, ActivityPods, OrganiGraph...
