### ISSUE TITLE
Visualiser les données en carte

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#2]
**Description**
Certains enregistrements ont des coordonnées (des évènements et des lieux principalement). On peut les afficher sous forme de carte géographique.

**Issues**
- [x] Composant React-Admin qui affiche les données sur une carte Leaflet #577
- [x] Pouvoir ajouter une donnée de géolocalisation dans react-admin #482

**Améliorations possibles dans le futur**
- Afficher des marqueurs de couleurs différentes selon le type de resource (classe, etc).
- Rechercher des ressources par latitude/longitude #494

**Alternatives**
- Service Moleculer pour générer un API compréhensible par GogocartoJS #435

**Estimation du temps de travail pour un développeur intermédiaire**
- @srosset81 & @simonLouvet: 6 JH

**Comment by srosset81** [comment]
Suite à la discussion de vendredi dernier, il a été convenu qu'intégrer Gogocarto en entier, avec Symfony, n'était pas désirable car trop lourd à mettre en oeuvre.

Reste le problème de la compatibilité entre le composant d'affichage [GogocartoJS](https://pixelhumain.github.io/GoGoCartoJs/), qui utilise jQuery, et React-Admin.

Une alternative, sans doute plus simple et plus légère, serait d'utiliser un composant React qui affiche une carte Openstreetmap, comme par exemple https://react-leaflet.js.org. 

L'avantage de Gogocarto c'est la gestion des catégories, mais avons-nous vraiment besoin de les afficher de côté, sachant que ces catégories seront elles-mêmes sémantisées ? Quant à l'affichage des information sur le panneau de droite, est-ce vraiment pertinent dans une interface intégrée à React-Admin ?

Il y a pas mal de questions de design là autour, en tout ça me semble trop prématuré pour qu'on essaie de chiffrer le temps nécessaire pour ce chantier.

**Comment by bouviermullerp** [comment]
Merci pour les précisions @srosset81 - l'analyse me semble vraiment juste et je pense qu'intérer un composant React n'est pas une alternative à négliger.
Est-ce qu'on peut envisager un chiffrage d'un design assez simple ?

En tant qu'utilisateur, quand je suis sur une liste appartenant à un concept qui a des coordonnées géographiques (évènement, organisatiion), je peux visualiser la liste sous forme de carte.
La description de la fiche que je sélectionne sur la carte s'affiche en plein écran - comportement similaire à celui qu'on a avec la vue en liste actuellement.

J'ai l'impression que c'est assez simple (mais vous me direz), et que rien que avec ça, on peut aller faire des démos encore plus pertinentes.

**Comment by srosset81** [comment]
> En tant qu'utilisateur, quand je suis sur une liste appartenant à un concept qui a des coordonnées géographiques (évènement, organisatiion), je peux visualiser la liste sous forme de carte.
> La description de la fiche que je sélectionne sur la carte s'affiche en plein écran - comportement similaire à celui qu'on a avec la vue en liste actuellement.

Quand tu dis, "s'affiche en plein écran", tu veux dire qu'on change de page, c'est ça ? Et du coup, si on veut sélectionner un autre point sur la carte, on est obligé de revenir en arrière, de recharger la carte et de retrouver un autre point géographique, quitte à devoir scroller à nouveau au bon endroit ? Ca fait un peu lourd non ? :thinking: 

L'alternative (pas beaucoup plus compliquée) serait de quand même afficher un petit popup, avec le nom de la ressource et un lien vers la page complète, [comme dans l'exemple ici](https://react-leaflet.js.org/docs/example-popup-marker/).

Autre question: dans ton scénario simple, ce serait pas du Gogocarto mais une simple carte OSM c'est ça ? (C'est l'option la plus simple, mais je veux être sûr)

**Comment by bouviermullerp** [comment]
Tu as tout juste @srosset81 - l'idée de la petite pop-up est très bonne et oui je pense à une carte OSM + leaflet, comme sur ton exemple.

> Ca fait un peu lourd non ?
Oui, c'est lourd - c'était pour trouver un "quick-win" le développement le plus léger possible qui offre les fonctionnalités de base, mais la possibilité d'un pop-up est classe ! 
L'idéal serait peut être d'afficher le détails complet de la fiche tout en laissant la carte affichée au même endroit, mais je crois qu'on arrive dans des dev un peu plus costauds.

**Comment by srosset81** [comment]
J'ai mis à jour la description du chantier suite à la discussion de ce jour, et j'ai séparé ce chantier avec celui concernant Gogocarto: https://github.com/assemblee-virtuelle/semapps/issues/435

**Comment by srosset81** [comment]
On a oublié aussi qu'il faudra gérer l'ajout de données de géolocalisation, j'ai créé une issue https://github.com/assemblee-virtuelle/semapps/issues/482 pour ça. Il faudra sans doute réévaluer ce chantier en conséquence.

**Comment by srosset81** [comment]
Suite à discussion de ce jour avec @simonLouvet, j'ai mis à jour le temps en JH en conséquence.

**Comment by bouviermullerp** [comment]
Sophox: accéder aux données OSM via SPARQL https://forums.assemblee-virtuelle.org/t/sophox-acceder-aux-donnees-osm-via-sparql/95
