### ISSUE TITLE
Sponsoriser Moleculer

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#200]
Le succès de SemApps dépend beaucoup de la qualité de code de Moleculer.

Lorsqu'on aura le budget, il serait bien de sponsoriser son créateur, afin d'encourager la maintenance et la mise à jour du logiciel.

https://opencollective.com/moleculer

**Comment by GuillaumeAV** [comment]
D'accord avec ça ! Il est important qu'on développe culture de la contribution financière pour le financement de "services communs" (par analogie à l'impot qui finance les services publics) !

**Comment by ReX-AV-Gab** [comment]
Je suis prêt à contribuer à développer cette culture, à la culture du commun.
Je suis enthousiasmé par l'idée du financement de services communs... en attendant d'ouvrir la fondation du bien commun !

**Comment by bouviermullerp** [comment]
@srosset81 est-il possible de récupérer facilement la liste de toutes les dépendances ? J'essaierai de faire un tableau avec le statut de chacune et arbitrer éventuellement un budget.
En plus, ils sont bien actif dans le développement : The next Moleculer version 0.14 is coming soon. The built-in metrics & tracing features has been rewritten completely. More powerful & extendable. Here are some screenshot about them:

**Comment by srosset81** [comment]
> @srosset81 est-il possible de récupérer facilement la liste de toutes les dépendances ? J'essaierai de faire un tableau avec le statut de chacune et arbitrer éventuellement un budget.

Tu peux voir les dépendances sur les packages NPM, par exemple:
https://www.npmjs.com/package/@semapps/activitypub puis cliquer sur "Dependencies"

> En plus, ils sont bien actif dans le développement : The next Moleculer version 0.14 is coming soon. The built-in metrics & tracing features has been rewritten completely. More powerful & extendable. Here are some screenshot about them:

Oui, ils avancent et ils répondent aussi aux demandes. Pourtant il semble qu'il y a surtout un développeur derrière ce logiciel (un dénommé "icebob"), s'il pouvait avoir plus d'intérêts financiers cela l'aiderait sans doute à tenir sur le long terme...
