### ISSUE TITLE
Présentation de notre démarche de documentation

### ISSUE THREAD

**Issue by ReX-AV-Gab** [assemblee-virtuelle/semapps#209]
Où met-on cette présentation ?
Dans le readme.md ?
On pourrait y indiquer nos choix en termes de structuration de la documentation, des cibles de la documentation et cetera, et cetera !
Je me redis qu'il serait bien de s'attarder un peu sur l'identité (Caractère de ce qui, sous des dénominations ou des aspects divers, ne fait qu'un ou ne représente qu'une seule et même réalité [CNRTL]) de SemApps !
Suis chaud, suis chaud ! :D

**Comment by srosset81** [comment]
@GuillaumeAV a créé une PR https://github.com/assemblee-virtuelle/semapps/pull/204, je suggère que tu travailles dessus directement (en te mettant sur sa branche).

**Comment by ReX-AV-Gab** [comment]
#163 
https://github.com/assemblee-virtuelle/semapps/issues/163
Installer un logiciel pour présenter la documentation #163

**Comment by GuillaumeAV** [comment]
Travailler la fiche d'identité de SemApps : de manière à pouvoir dire, à un nouveau par exemple ... "SemApps, c'est ça". 

2 façons de répondre : 
- Un projet AV
- Un outil

=> on crée une issue dédiée

**Comment by GuillaumeAV** [comment]
Présenter la démarche de documentation  : 
- Quoi : 
   - Doc interne
   - Doc externe 
- Ou : 
   - Externe : Sur doc.semapps.org
- Qui : Le cercle dédié
- Comment : En anglais ...
Etc .

**Comment by ReX-AV-Gab** [comment]
https://roamresearch.com/#/app/virtual-assembly/page/Uz-O4iO5V 
Lien vers la page documentation SemApps dans RoamResearch
