### ISSUE TITLE
Retravailler la homepage du docusaurus

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#215]
Sur https://website-3rr9j6b6k.now.sh/, nous avons : 
- Trop facile : Nous utilisons les standards du web sémantique qui permettent à de multiples systèmes d’information de s’interconnecter.
- Trop cool : SemApps intègre la spécification SOLID portée par Tim Berners Lee (inventeur du web), ainsi que le protocole ActivityPub.
- Trop bien : Nous concevons SemApps sur la base des principes suivants : Interopérabilité - Modularité - Généricité - Adaptabilité - Scalabilité - Accessibilité - Convivialité

Je me dis qu'on pourrait avoir : 
- **Cas d'usages** : Produire des graphes de données liées ; Interopérer les systèmes d'information ; Favoriser le développement de réseaux sociaux distribués ; Permettre le développement d'applications métiers sur la base d'architectures de réseaux disteibuées. 
- **En quelques mots** : SemApps est un système de gestion de données modulaire, basé sur les technologies et standards du web sémantiques. Développé par l'Assemblée Virtuelle, son objectif est de favoriser la mise en réseau des acteurs grâce à la mise en synergie de leurs systèmes d'information.
- **Sous le capot** : Un middleware assurant la communication entre les différents composants d'une application sémantique. Basé sur NodeJS - MoleculerJS - RDF - OWL - SPARQL - LDP - ActivityPub - WEB-ID - WEB-ACL - SHACL. SOLID. 

Si ca vous semble pertinent, je fais une pull request et on affine ensuite ? Ou pas ? 

https://roamresearch.com/#/app/virtual-assembly/page/af0djawNO

**Comment by ReX-AV-Gab** [comment]
Un peu de chipotage : 
- 1 ...de s’interconnecter et d'interagir.
Dans la mesure où la structure en Trop est figée, je trouve les Trop vraiment trop bien 
- 4 je peux aider en donnant un oeil critique sur les cas d'usage
- 5 Pour moi, SemApps est un système de gestion de base de connaissances interopérables et modulaires... en quelques mots (en toute la légitimité :D)
- 6 "Sous le capot, je crois qu'il ne manque rien"... dit le non-technicien
Par ailleurs, si je me souviens bien, Simon avait particulièrement mis en avant LDP (avec le web sémantique), cela aurait-il une importance quelconque ici ?
PS : soyez indulgent, je suis encore en formation dans un univers que je découvre peu

**Comment by GuillaumeAV** [comment]
Suite à une discussion avec @ReX-AV-Gab on suggère plutôt de faire une home page avec 3 entrées par type de public, par exemple : 

**Développeurs**
SemApps est un système de gestion de bases de connaissances interopérables. Construit sur une architecture modulaire (micro-services - moleculer.js), il prend la forme d'un midleware intégrant les protocoles et standards du web sémantique.

**Communautés d'utilisateurs**
SemApps permet de cartographier vos écosystèmes ; De vous interconnecter avec d'autres écosystèmes ; De favoriser le développement de réseaux sociaux décentralisés ; De permettre le développement d'applications métiers sur la base d'architectures de réseaux distribuées.

Partenaires & financeurs
...

Qu'en dites vous ?
