### ISSUE TITLE
Fiche d'identité de SemApps

### ISSUE THREAD

**Issue by ReX-AV-Gab** [assemblee-virtuelle/semapps#222]
Seriez-vous partants pour rédiger une fiche d'identité qui établirait la vision partagée de SemApps ?

**Comment by bouviermullerp** [comment]
@ReX-AV-Gab cette issue est-elle toujours active au regard des dernières mises à jour du site ?

**Comment by ReX-AV-Gab** [comment]
Et bien j'estime que non et je me permets de la closer !
