### ISSUE TITLE
Ajouter tous les champs de SemApps v1 au DMS

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#240]
Compléter le DMS pour que toutes les données qui se trouvaient dans les données de SemApps v1 apparaissent bien.

**Comment by GuillaumeAV** [comment]
A moins qu'on attende la nouvelle version de l'ontologie ?

**Comment by srosset81** [comment]
Je ferme cette issue puisqu'on a décidé de ne pas réutiliser les données de la v1
