### ISSUE TITLE
Gérer automatiquement les liens inverses

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#241]
J'ai par exemple renseigné l'orga Maisons de l'Intelligence Collective et ai mentionné qu'elle était partenaire de Assemblée Virtuelle. 

Sur la description de l'Assemblée Virtuelle (les MIC) n'apparaissent pas comme partenaire : 

Ce n'est pas forcément une mauvaise chose ..

Piste d'amélioration : 
Une notification (Activity Pub ?) pour que AV soit au courant de ce lien, et qu'elle en valide la symétrie ...

**Comment by srosset81** [comment]
Je pense que la symétrie est une affaire d'OWL mais je ne sais pas comment la mettre à l'oeuvre. Est-ce que ça pourrait se faire automatiquement via Jena ? @simonLouvet @nikoPLP 

Si on devait faire valider un tel ajout (du coup dans les deux sens), on pourrait en effet passer par une activité ActivityPub:

```
{
  type: "Offer",
  object: {
    type: "Update",
    object: {
      id: "..."
      pair:partnerOf: "..."
    }
  }
}
```

Et pour l'accepter, il y a une activité `Accept`.

**Comment by srosset81** [comment]
Après discussion avec @simonLouvet, les liens inverses ne peuvent pas se créer automatiquement, mais on pourrait gérer ça au niveau du middleware, en lisant le fichier OWL associé à l'ontologie et en ajoutant les triples inverses au moment de la création / mise à jour d'une ressource.
J'ai renommé l'issue dans ce sens.

**Comment by bouviermullerp** [comment]
c'est pushé
