### ISSUE TITLE
Convertir les données de SemApps v1 vers la nouvelle ontologie PAIR

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#243]

**Comment by simonLouvet** [comment]
Utiliser le Bus Sémantique pour faire A import + transformation + export en passant par LDP.
1ere étap : connecteur import -export
2eme etape : une fois l'ontologie owl connu, faire les transformations

**Comment by GuillaumeAV** [comment]
Hey ! 

J'ai eu une autre idée entre temps ! On pourrait baser l'inscription au meetup sur un framaforms reprenant l'ontologie pair nouvelle version, et créer une passerelle entre le Framaforms et SemApps ? On aurait du coup la chaine de traitements entre un tableur et semapps / pair ?
Plus de la donnée intéressante à visualiser ? (Davantage que les données AV d'il y a 2 ans ?)

**Comment by simonLouvet** [comment]
Le bus peut digérer le résultat du framaform si besoin.

**Comment by srosset81** [comment]
Je ferme cette issue puisqu'on a décidé de ne pas réutiliser les données de la v1
