### ISSUE TITLE
Problème quand on actualise une donnée sur le DMS

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#256]
=> J'ai changé 2 titres et complété les fiches orgas : 
* Coop des territoires
* Les chemins de la transition

Les données en question ont disparu !

**Comment by bouviermullerp** [comment]
Je reproduit toujours cette issue. A corriger en fonction de ce qu'on veut faire avec le DMS

**Comment by srosset81** [comment]
Normalement cette issue est réglée sur https://coographie.vercel.app
