### ISSUE TITLE
Gérer les relations ternaires 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#259]
Dans le cadre de la refonte de PAIR, on crée plusieurs relations ternaires entre quelques uns des concepts clés de l'ontologie : 
Acteurs - Projets
Acteurs - Activités
Acteurs - Evenements
Acteurs - Ressources 
Acteurs - Acteurs 

Ces relations ternaires permettent un typage souple plutôt que gravé dans le marbre de l'ontologie, ce qui apporte de la flexibilité et de l'extensibilité et devrait s'avérer très précieux à l'usage : Pour le confort des administrateurs et des utillisateurs ! 

Plutôt que d'avoir des relations inverses l'une de l'autre entre 2 classes, les relations ternaires font interagir 4 concept : 
- La classe source 
- La classe cible 
- La classe "Rôle"
- La classe "Association" enfin qui permet de lier les 3 premières .. 

Les types de relations sont déterminés en tant qu'individus de la classe Rôle.
Ils peuvent de ce fait porter des informations supplémentaires comme la date d'adhésion dans le cas d'un statut de _membre _ d'une organisation 

=>Nous croyons qu'il serait extrêmement pertinent d'implémenter la possibilité de gérer dans SemApps les relations ternaires ;-)

![Capture d%u2019écran 2020-05-01 à 15 07 52](https://user-images.githubusercontent.com/6160028/81059162-39115380-8ed0-11ea-8d29-1239f620b293.png)
![Capture d%u2019écran 2020-05-01 à 15 07 36](https://user-images.githubusercontent.com/6160028/81059174-40386180-8ed0-11ea-8874-513e0975100a.png)

**Comment by srosset81** [comment]
Intéressant... Cela dit, je trouve que ça rend la sémantique moins lisible. Entre les deux, celle de gauche est quand même plus facile à "lire" non ?
![Capture d’écran de 2020-05-05 14-37-06](https://user-images.githubusercontent.com/17931931/81066806-f5254b00-8edd-11ea-8b11-801ccc7ef768.png)
Techniquement c'est faisable bien sûr. Mais ça va demander d'abstraire plus de choses pour que ça reste simple pour l'utilisateur. Du coup les relations sémantiques réelles vont être cachées à l'utilisateur, ce qui est un peu dommage.

**Comment by srosset81** [comment]
Cela donne un peu l'impression qu'on contourne les limitations de RDF, qui ne supporte les [réifications](https://github.com/blazegraph/database/wiki/Reification_Done_Right) que dans la version RDF* qui n'est pas (encore ?) officielle.

**Comment by tfrancart** [comment]
Il faut les 2 : les liens directs et les relations réifiées (quand ces dernières ont un intérêt).
Sur l'exemple donné, c'est ce que fait ORG par exemple https://www.w3.org/TR/vocab-org/#overview-of-ontology, avec hasMember/memberOf pour les liens directs, et Membership pour la relation réifiée.

La question est : a-t-on suffisamment de choses à dire sur la relation pour en faire une entité à part entière dans le graphe ? la réponse n'est pas toujours oui.

**Comment by iPlumb3r** [comment]
> Intéressant... Cela dit, je trouve que ça rend la sémantique moins lisible. Entre les deux, celle de gauche est quand même plus facile à "lire" non ?
> ![Capture d’écran de 2020-05-05 14-37-06](https://user-images.githubusercontent.com/17931931/81066806-f5254b00-8edd-11ea-8b11-801ccc7ef768.png)
> Techniquement c'est faisable bien sûr. Mais ça va demander d'abstraire plus de choses pour que ça reste simple pour l'utilisateur. Du coup les relations sémantiques réelles vont être cachées à l'utilisateur, ce qui est un peu dommage.

Disons que du côté gauche on a N relations spécifiques dont la sémantique est "cablée en dur" dans des couple d'ObjectType Properties (donc plus direct à lire) et du côté droit on a 1 UNIQUE relation générique dont la sémantique est paramétré par la sélection d'un individual de la classe "Mode". 
Effectivement, cela requiers un travail de mapping entre la modélisation sou-jacente et l'interface pour que cela soit le plus transparent possible pour l'utilisateur !

**Comment by iPlumb3r** [comment]
> Cela donne un peu l'impression qu'on contourne les limitations de RDF, qui ne supporte les [réifications](https://github.com/blazegraph/database/wiki/Reification_Done_Right) que dans la version RDF* qui n'est pas (encore ?) officielle.

Oui, c'est exactement ça !
 => c'est un mode de modélisation qui permet de "contourner" la limitation intrinsèque de RDF pour réifier des relations

**Comment by iPlumb3r** [comment]
> Il faut les 2 : les liens directs et les relations réifiées (quand ces dernières ont un intérêt).
Est-ce que tu veux dire qu'une relation réifiée doit AUSSI exister en mode "normal" ...
... ou disais-tu simplement qu'il y a potentiellement dans une ontologies des relations "normales" ET des relation réifiées ?

> Sur l'exemple donné, c'est ce que fait ORG par exemple https://www.w3.org/TR/vocab-org/#overview-of-ontology, avec hasMember/memberOf pour les liens directs, et Membership pour la relation réifiée.
> 
> La question est : a-t-on suffisamment de choses à dire sur la relation pour en faire une entité à part entière dans le graphe ? la réponse n'est pas toujours oui.
Dans le cas présenté par Guillaume, la "chose à dire" est essentiellement de préciser la sémantique particulière de la relation.

**Comment by tfrancart** [comment]
> Est-ce que tu veux dire qu'une relation réifiée doit AUSSI exister en mode "normal" ...

Non ce n'est pas une obligation, encore que, quand on fait des relations réifiées, on s'aperçoit vite qu'on a envie quand même d'avoir la relation directe.

> ... ou disais-tu simplement qu'il y a potentiellement dans une ontologies des relations "normales" ET des relation réifiées ?

Oui, c'était plutôt ça le sens de ma remarque

> Dans le cas présenté par Guillaume, la "chose à dire" est essentiellement de préciser la sémantique particulière de la relation.

Ca peut se comprendre aussi comme "préciser le rôle que je joue la personne dans l'organisation".

**Comment by iPlumb3r** [comment]
> Ca peut se comprendre aussi comme "préciser le rôle que je joue la personne dans l'organisation".

Oui, je me suis exprimé de manière "générique" ...
... mais de manière plus "spécifique" c'est exactement le sens que tu dit dans le contexte de cette relation en particulier !
