### ISSUE TITLE
Gérer l'accept header application/sparql-results+json

### ISSUE THREAD

**Issue by tfrancart** [assemblee-virtuelle/semapps#263]
J'essaie de brancher Sparnatural sur https://middleware.semapps.org/sparql.
J'ai ce retour d'erreur :
```
{
  "name": "ValidationError",
  "message": "Parameters validation error!",
  "code": 422,
  "type": "VALIDATION_ERROR",
  "data": [
    {
      "type": "required",
      "message": "The 'accept' field is required.",
      "field": "accept",
      "nodeID": "--instances=max-1",
      "action": "triplestore.query"
    }
  ]
}
```

La requête envoyée est celle-ci (notez le header Accept) :

```
POST https://middleware.semapps.org/sparql

headers :

Host: middleware.semapps.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: application/sparql-results+json,*/*;q=0.9
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 670
Origin: null
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache

body :

query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E+%0ASELECT+DISTINCT+(STR(%3Flabel)+AS+%3Flibelle)+%3Fthis+WHERE+%7B+%3Fthis+rdf%3Atype+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FPerson%3E.+++%7B%7B+%3Fthis+%3Chttp%3A%2F%2Fvirtual-assembly.org%2Fpair%23preferedLabel%3E+%3Flabel+%7D+UNION+%7B+%3Fthis+%3Chttp%3A%2F%2Fvirtual-assembly.org%2Fpair%23lastName%3E+%3FlastName+.+%3Fthis+%3Chttp%3A%2F%2Fvirtual-assembly.org%2Fpair%23firstName%3E+%3FfirstName+.+BIND(CONCAT(%3FfirstName%2C+'+'%2C+%3FlastName)+AS+%3Flabel+)+%7D+%7D+.+%0A%7D%0AORDER+BY+%3Flabel+LIMIT+100
```

**Comment by simonLouvet** [comment]
@tfrancart : pour le moment il n'y a que 3 accepts possibles : 
const MIME_TYPES = {
  JSON: 'application/ld+json',
  TURTLE: 'text/turtle',
  TRIPLE: 'application/n-triples'
};

https://github.com/assemblee-virtuelle/semapps/blob/master/src/middleware/packages/mime-types/constants.js

**Comment by srosset81** [comment]
Ce serait pertinent de gérer `application/sparql-results+json` quand même non ? Faudrait ajouter ça au service `sparql-endpoint`.

**Comment by tfrancart** [comment]
OK... c'est dommage de ne pas supporter le format JSON de résultat SPARQL (https://www.w3.org/TR/2013/REC-sparql11-results-json-20130321/). Le support de ce format (et des autres, comme le format de résultat SPARQL en XML) serait le bienvenue pour que le middleware Semapps soit un endpoint SPARQL compatible.

**Comment by simonLouvet** [comment]
on a pas prévu de supporter sparql-results+json par ce que une requête sparql peut être un construct par ex et il me semble que ce n'est pas sérialisable en  sparql-results+json

**Comment by srosset81** [comment]
@simonLouvet Notre but est de fournir un endpoint SPARQL complet, donc je ne vois pas pourquoi on ne gérerait pas ce cas.
J'ai modifié le titre de l'issue.

**Comment by simonLouvet** [comment]
On pourrait considérer que  sparql-results+json = application/ld+json mais ce n'est pas vrais. sur un select par exemple ce n'est pas le même résultat il me semble.

**Comment by simonLouvet** [comment]
et comment ca se passe si le accept demandé est  sparql-results+json et que la requete est un construct? Une erreur?

**Comment by tfrancart** [comment]
Le support du [protocole SPARQL](https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321) est nécessaire si vous voulez que le middleware SemApps soit un service SPARQL compatible et interrogeable comme tel. Cela implique le support des [formats de réponse SPARQL](https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-success) JSON, XML et CSV/TSV.

> et comment ca se passe si le accept demandé est sparql-results+json et que la requete est un construct? Une erreur?

Normalement le client doit positionner le header Accept en accord avec le type de query. Les lib RDF4J ou Jena positionnent le paramètre en examinant la query envoyée.

Mais typiquement oui, si le header n'est pas cohérent ce serait un cas d'erreur. Mais ce n'est pas spécifié. Dans Virtuoso par exemple, si tu fais une requête SELECT mais que tu demandes du Turtle, tu as un bout de Turtle qui encode le résultat tabulaire du select. A l'inverse ti tu envoies un CONSTRUCT avec un Accept = CSV ou SPARQL/JSON ou SPARQL/XML tu as un format tabulaire à 3 colonnes "subject" "predicate" "object" qui encode les triplets du CONSTRUCT.

**Le support de ces formats SPARQL/JSON SPARQL/XML et SPARQL/CSV me semble primordial pour l'interopérabilité de SemApps !**

**Comment by srosset81** [comment]
@tfrancart Après discussion avec Simon, on va se contenter de passer l'header Accept à Fuseki, et si jamais il y a une erreur, on la gérera nous-mêmes. Cela permettra d'offrir toutes les fonctionnalités propres à Fuseki.
Est-ce que ce problème est bloquant pour Sparnatural ou tu peux avancer ?

**Comment by tfrancart** [comment]
> @tfrancart Après discussion avec Simon, on va se contenter de passer l'header Accept à Fuseki, et si jamais il y a une erreur, on la gérera nous-mêmes. Cela permettra d'offrir toutes les fonctionnalités propres à Fuseki.

Très bonne idée, le middleware n'a sans doute (?) aucune valeur ajoutée pour ce service SPARQL qui est offert nativement par Fuseki.

> Est-ce que ce problème est bloquant pour Sparnatural ou tu peux avancer ?

C'est un problème bloquant pour n'importe quel client SPARQL.
Ca ne m'empêche pas d'avancer sur d'autres aspects pour le moment, mais si c'était en place pour le 20, ça pourrait ajouter une petite démo sympa :-)

**Comment by bouviermullerp** [comment]
Même service que le cas #246

**Comment by simonLouvet** [comment]
The response body of a successful query operation with a 2XX response is either:

a SPARQL Results Document in XML, JSON, or CSV/TSV format (for SPARQL Query forms SELECT and ASK); or,
an RDF graph [RDF-CONCEPTS] serialized, for example, in the RDF/XML syntax [RDF-XML], or an equivalent RDF graph serialization, for SPARQL Query forms DESCRIBE and CONSTRUCT).

**Comment by simonLouvet** [comment]
analyse des comportement de semapps et de fuseky en fonction du verbe sparql et du accept :
https://docs.google.com/spreadsheets/d/1cjNmqwTdxVMo0WJrbEoPmWPTw-qgazf1JIdng88iMSs/edit#gid=2029847051

**Comment by simonLouvet** [comment]
réouvert car pas vu en sprint review
