### ISSUE TITLE
Créer une fiche d'identité pour SemApps

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#267]
Travailler la fiche d'identité de SemApps : de manière à pouvoir dire, à un nouveau par exemple ... "SemApps, c'est ça".

2 façons de répondre :

    Un projet AV
    Un outil

=> on crée une issue dédiée

**Comment by bouviermullerp** [comment]
@GuillaumeAV @ReX-AV-Gab il me semble que l'issue #222 est similaire. Si oui, peut-on la fermer ?

**Comment by GuillaumeAV** [comment]
Sources d'inspiration :  

https://roamresearch.com/#/app/virtual-assembly/page/L3luYmixT

https://www.virtual-assembly.org/semapps/

https://docs.google.com/presentation/d/17jFILmUOOBB3uNwxM0GFmk2YDGsI92YrDG4ZqGorLjc/edit?usp=sharing

https://docs.google.com/presentation/d/1fH1ZEa3Rokr_cX30tc_kk67iWKQPOUgmXc0P4lJxfN4/edit?usp=sharing

**Comment by bouviermullerp** [comment]
@GuillaumeAV @ReX-AV-Gab may we close this issue ?

**Comment by ReX-AV-Gab** [comment]
Oups, j'étais vraiment persuadé d'avoir déjà donné la réponse positive !

**Comment by GuillaumeAV** [comment]
Avec @Rouffi & @bouviermullerp on se lance dans une cartographie de c'est quoi semapps avec l'idée de mapper cet objet complexe ;) 

## Ressources 
- [Carto GV](https://docs.google.com/presentation/d/1sp1BhlzuadxDSipQjDsN3yKvh5udjFQIXsi5KfUZ1Qk/edit?usp=sharing)
- [MMMfest](http://mmmfest.fr/rechercher)
- [SemApps AV](semapps.virtual-assembly.org/)
- [Vidéo Archi](https://www.youtube.com/watch?v=oRbkokjzxTY)
- [Chantiers en cours et à venir](https://docs.google.com/document/d/1TVCOhd5xO51S4vXlgtjQUYpN2Zj5RTibj5u9Z7Xbm0U/edit?usp=sharing)
- [Instances SemApps](https://docs.google.com/spreadsheets/d/1CFfwF8f2AEqZ1B-zTS07FaluXIAtXThKALI427PIKmI/edit?usp=sharing)
- [Bac à sable v2](https://dms-srosset81.semapps.vercel.app/#/Interest)

## Architecture technique
- [Jena fuseki](https://jena.apache.org/)
- [Framework Moleculer.js](https://moleculer.services/)
- [Solid](https://solidproject.org/)
