### ISSUE TITLE
LDP Server documentation improvement

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#277]
**1 - Documenter les prérequis - et comment les installer**
npm docker docker-compose make 

**2 - Ajouter comment installer moleculer** avec un lien direct vers la [doc](https://moleculer.services/docs/0.14/moleculer-cli.html) et la ligne de commande pour l'installer npm i -g moleculer-cli

**3 - préciser les impacts de 3 questions**
Quand on lance la commande moleculer init assemblee-virtuelle/semapps-template-ldp my-project

? Do you need a local instance of Jena Fuseki (with Docker)?
? Do you need a read-only SPARQL endpoint?
Create 'my-project' folder...
? Would you like to run 'npm install'?

**Comment by balessan** [comment]
And once the installation is complete, there is no information on the README on how to access anything.

It's just because the build failed that I know it uses localhost:3000, but I do not know which service is running there when the docker-compose is starting 3 containers as shown below:

```
balessan@balessan-laptop:~/workspace/semapps$ make start
docker-compose -f docker-compose.yaml up -d --force-recreate
Recreating fuseki ... done
Recreating middleware ... done
Creating frontend     ... done
```

**Comment by srosset81** [comment]
@balessan L'issue de Pierre fait référence au [guide](https://semapps.org/docs/guides/ldp-server) qui permet de créer son propre serveur à partir d'une template moleculer. Dans ce guide, il n'y a qu'un container Docker, avec Fuseki.
La doc pour lancer le repo semapps complet (avec les 3 containers) est encore fragmentaire effectivement, je viens de créer une [issue](https://github.com/assemblee-virtuelle/semapps/issues/288) pour qu'on s'y attèle. Merci !

**Comment by srosset81** [comment]
> **1 - Documenter les prérequis - et comment les installer**
> npm docker docker-compose make

Le problème c'est que l'installation diffère de chaque OS, et qu'elle peut varier avec le temps. J'ai mis des liens vers la page pour installer NodeJS (qui inclus NPM).

> **2 - Ajouter comment installer moleculer** avec un lien direct vers la [doc](https://moleculer.services/docs/0.14/moleculer-cli.html) et la ligne de commande pour l'installer npm i -g moleculer-cli

Bonne remarque, ça a été ajouté !

> **3 - préciser les impacts de 3 questions**
> Quand on lance la commande moleculer init assemblee-virtuelle/semapps-template-ldp my-project
> 
> ? Do you need a local instance of Jena Fuseki (with Docker)?
> ? Do you need a read-only SPARQL endpoint?
> Create 'my-project' folder...
> ? Would you like to run 'npm install'?

Peux-tu expliquer ce que tu entends par impact ? Tu veux dire préciser dans la question ce que ça signifie ? N'hésites pas à faire des propositions dans ce sens !

**Comment by balessan** [comment]
@srosset81 : Yes I got that afterwards actually. During the demonstration I mean.
