### ISSUE TITLE
Enhancement on Please start by creating a localData dataset.

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#279]
Quand j'ai suivi la doc d'install, c'était tout clair sauf

Please start by creating a` localData` dataset. This is where your triples will go.

Je n'avais pas compris que 'localData' signifiait qu'il était nommé de cette manière.

Proposition de reformulation : 
Please start by create a new dataset and name it `localData`
Your triples will be stored there.

**Comment by srosset81** [comment]
OK pour une PR de ta part :-)
