### ISSUE TITLE
install jena without docker, restApi for post & dms update

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#287]
Ma machine n'a que 2Go de RAM et Docker en demande 4. J'avais par le passé déjà installé Fuseki sur cette machine, aussi, j'aimerais savoir si je peux utiliser l'install de base de fuseki plutôt que docker, et dans l'afirmative, que dois-je configurer ? 

J'ai par ailleurs remarqué que l'image Docker utilisée ne contient pas la dernière version de Fuseki (V2 au lieu de 3.15) 
Est-ce par choix ? par incompatibilité ? ou bien puis-je utiliser la dernière ? 
Merci.

Edit : je viens de tester, la 3.15 ne semble pas passer au premier abord, mais peut-être ça vient de ma machine, avec ma vieille 3.7 ça passe, le npm run dev de semapps a l'air OK.

Edit 2, tant que j'y suis, pour faire les POST, il peut être utile d'utiliser quelque chose comme https://addons.mozilla.org/fr/firefox/addon/restclient/ sinon c'est un peu hard depuis la ligne de commande windows  ;-)

edit 3: en ajoutant dans le menu Headers (pour le POST mais pas pour le GET)
Content-Type 
application/json

Edit 4 :  le nom du projet est le même (my-project) pour les deux install (LDP-server) & DMS, ça peut-être perturbant, et on peut se retrouver avec les deux "projets" dans le même dossier, si on suit la doc, alors que je suppute qu'il faille deux dossiers différents, deux packege.json différents, non ?

Edit5 : Voulant installer Dms, l'install a bloqué, -> Ctrl+c , et npm start me donne une incompatibilité de version babel_lodash -> npm update -> et là npm start OK, (react_scripts a été mis à jour)
Mais maintenant dms est ok et inscrit des foaf:Person dans mon Fuseki ;-) 

Good Job, guys +++

**Comment by GuillaumeAV** [comment]
Merci David pour tous ces commentaires pertinents ! Moi pas capable de te
répondre mais les autres te feront des retours j'imagine très bientôt !

**Comment by srosset81** [comment]
Merci beaucoup @scenaristeur pour ces retours très pertinent, on va les prendre en compte et résoudre une bonne partie des problèmes que tu évoques dès la semaine prochaine !

**Comment by srosset81** [comment]
Mes réponses avec du retard, désolé !

> Ma machine n'a que 2Go de RAM et Docker en demande 4. J'avais par le passé déjà installé Fuseki sur cette machine, aussi, j'aimerais savoir si je peux utiliser l'install de base de fuseki plutôt que docker, et dans l'afirmative, que dois-je configurer ?

Rien de particulier, si ce n'est créer un dataset `localData`. Tu peux voir ce qu'ils configure dans le [Dockerfile](https://github.com/stain/jena-docker/blob/master/jena-fuseki/Dockerfile).

> J'ai par ailleurs remarqué que l'image Docker utilisée ne contient pas la dernière version de Fuseki (V2 au lieu de 3.15)
> Est-ce par choix ? par incompatibilité ? ou bien puis-je utiliser la dernière ?

La description de l'image Docker `stain/jena-fuseki` parle de v2 mais c'est la version 3.14.0 qui est installée en vérité.

> Edit 2, tant que j'y suis, pour faire les POST, il peut être utile d'utiliser quelque chose comme https://addons.mozilla.org/fr/firefox/addon/restclient/ sinon c'est un peu hard depuis la ligne de commande windows ;-)

On recommande [Insomnia](https://insomnia.rest/), [Postman](https://www.postman.com/downloads/) mais j'ai ajouté ce plugin dans la liste.

> Edit 4 : le nom du projet est le même (my-project) pour les deux install (LDP-server) & DMS, ça peut-être perturbant, et on peut se retrouver avec les deux "projets" dans le même dossier, si on suit la doc, alors que je suppute qu'il faille deux dossiers différents, deux packege.json différents, non ?

Bonne idée, j'ai édité le guide pour que l'on install dans un dossier `my-dms` à la place.

> Edit5 : Voulant installer Dms, l'install a bloqué, -> Ctrl+c , et npm start me donne une incompatibilité de version babel_lodash -> npm update -> et là npm start OK, (react_scripts a été mis à jour)
> Mais maintenant dms est ok et inscrit des foaf:Person dans mon Fuseki ;-)

Si tu retombes sur l'erreur fais-nous signe en donnant toute la stacktrace. Merci !

**Comment by scenaristeur** [comment]
Un tuto de l'install sans Docker si ça peut vous être utile https://dfaveris.medium.com/installer-semapps-sans-docker-b92f3574f07f

**Comment by GuillaumeAV** [comment]
Trop la classe merci beaucoup @scenaristeur !!
