### ISSUE TITLE
Déployer un serveur DMS avec Now.sh

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#290]
En ajoutant un fichier now.json à la template DMS, cela permettrait à n'importe qui de facilement déployer son instance SemApps.

Il faudra cependant utiliser un triple store extérieur (p.ex https://fuseki.semapps.org/)

**Comment by bouviermullerp** [comment]
Linked to #112

**Comment by srosset81** [comment]
> Linked to #112

Non c'est différent. L'issue #112 concerne le déploiement du frontend, celle-ci le déploiement du middleware. Les problèmatiques sont très différentes.

**Comment by srosset81** [comment]
Je ne crois plus que ce soit pertinent. Vercel est plutôt sur du serverless, et ça rendrait difficile de suivre ce qui se passe.
