### ISSUE TITLE
Peaufiner la homepage du docusaurus

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#293]
Mettre des pictos, des couleurs, un habillage plus jolis ...

**Comment by bouviermullerp** [comment]
Est-ce que ce cas peut être fermé ?

**Comment by GuillaumeAV** [comment]
Nooo, il faut qu'on la peaufine ...

**Comment by srosset81** [comment]
Remplacé par https://github.com/assemblee-virtuelle/semapps/issues/405
