### ISSUE TITLE
Finaliser les vidéos du meetup

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#294]
Hello,

Dernière ligne droite avant diffusion des [vidéos du Meetup SemApps](youtube.com/playlist?list=PLw8CdIbrt0JGevxI0q4iOwXWEgO-oHUwd) : Sous-titre et traduction en anglais

[Ce tuto vous aide à corriger et valider les sous-titres en français de vos vidéos respectives dans un premier temps](https://vimeo.com/channels/assembleevirtuelle).
Puis nous les passerons à la traduction automatique en anglais dans un second temps.
Yannick Laignel se propose de corriger les sous-titres anglais.

C'est pourquoi les vidéos n'étaient pas prêtes vendredi, il y a un grand intérêt à doter les vidéos de sous-titres français et anglais au delà des usages en mode silencieux et de la diffusion élargie aux anglophones. Il s'agit de pallier la mauvaise qualité de certaines prises de son.

Correction et validation attendue avant le lundi 1er juin. Les vidéos prêtes seront diffusées au fur et à mesure et dans l'état avant la résidence du 8 au 12 juin.

Bon courage,

Merci,
Franck Calis
06 63 76 80 63

********
Pour accéder au tuto : https://vimeo.com/channels/assembleevirtuelle

Pour accéder à vos vidéos (lien à ne pas diffuser) : youtube.com/playlist?list=PLw8CdIbrt0JGevxI0q4iOwXWEgO-oHUwd

**Comment by GuillaumeAV** [comment]
Les vidéos sont enfin en ligne sur la chaine de l'Assemblée Virtuelle ! 
https://www.youtube.com/channel/UCg7sYh_Y8cHFT4s82K4SVmA/
