### ISSUE TITLE
TripleStoreAdapter: gérer le cache proprement

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#301]
Si on active le [cache](https://moleculer.services/docs/0.14/caching.html) au niveau de Moleculer, les données retournées par l'adapteur TripleStore sont automatiquement cachées pour les actions `find`, `count`, `list` et `get`.

Cela pose des problèmes, par exemple pour les containers ou les collections AP qui sont mis à jour par d'autres biais que par l'adaptateur. Il faudrait essayer de désactiver le cache pour ces services (en mettant `cache: false`) et voir si ça ne pose pas d'autres problèmes.

Si on pouvait régler ces problèmes, ce serait utile car on aurait nativement une gestion du cache et on gagnerait beaucoup en performances.

**Comment by srosset81** [comment]
Une option intermédiaire serait de désactiver le cache pour le TripleStoreAdapter, de cette manière:

https://github.com/moleculerjs/moleculer-db/issues/116

On pourrait créer un mixin `NoCacheDbService` de cette manière:

```
module.exports = {
	mixins: [DbService],

	actions: {
		find: {
			cache: false
		},
		count: {
			cache: false
		},
		list: {
			cache: false
		},
		get: {
			cache: false
		}
	},
	methods: {
		_find: {
			cache: false
		},
		_count: {
			cache: false
		},
		_list: {
			cache: false
		},
		_get: {
			cache: false
		}
	}
}
```

**Comment by simonLouvet** [comment]
j'ai pas d'autre solutions que la désactivation du cache à première vu. Sinon, il faudrait analyser les requêtes de mise à jour envoyées directement au service triplestore (pour invalider le cache des entités concernés) ou que les services  (ldp notament) qui font des mise à jour du triplestore invalident eux-même les caches concernés.
