### ISSUE TITLE
Rendre visible les rôles sur le site web

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#306]
Maintenant qu'on a défini les 13 premiers rôles de l'équipe, il me semblerait important de réfléchir à un moyen de les mettre en valeur sur le site, et de corriger ou mettre à jour [cette page](https://semapps.org/docs/governance/team).

**Comment by GuillaumeAV** [comment]
Yep ! Malheureusement je ne peux pas prioriser ça de mon côté, éventuellement courant juillet ..

**Comment by srosset81** [comment]
On verra ça vendredi ;-)

J'avais oublié que @bouviermullerp avait commencé une PR #281 là-dessus.
