### ISSUE TITLE
Permettre au middleware de se connecter à plusieurs datasets fuseki

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#313]
Il n'est pas possible de sélectionner le dataset fuseki qu'on souhaite utiliser, et donc on est obligé de multiplier les instances.
Peut être revoir le fonctionnement des API avec un /_dataset_ ?

**Comment by srosset81** [comment]
Deux manières de gérer ça concrètement:
- Permettre de configurer un container pour se baser sur un dataset
- Permettre de configurer plusieurs endpoints SPARQL
