### ISSUE TITLE
Faire la liste des extensions SemApps

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#314]
Lien vers le document de travail : https://docs.google.com/document/d/1TVCOhd5xO51S4vXlgtjQUYpN2Zj5RTibj5u9Z7Xbm0U/edit?usp=sharing

**Canevas de description**

- Pourquoi (Besoins identifiés)
- Quoi (Descriptif de la solution envisagée)
- Comment (Moyens & ressources mobilisables)
- Qui (fournisseurs et clients potentiels)
- Compétences requises
- Estimation du temps nécessaire
- Niveau d’avancement
- Niveau d’importance
- Niveau d’urgence
- Aller plus loin 

#### Formulaire sémantique intelligent à la Typeform

Formulaire de type wizard, avec un design proche de Typeform, qui permet d’entrer facilement des données sémantiques.

L’avantage d’un formulaire “wizard” est que les questions posées peuvent dépendre des réponses données, et donc être plus intelligents.

Par exemple dans une première partie du formulaire, on pourrait demander les intérêts de l’utilisateurs et, dans la deuxième partie, lui demander les organisations auxquelles il fait partie, en proposant des suggestions qui dépendent de ses intérêts.

On pourrait se baser sur ShEX pour la génération du formulaire, comme c’est fait sur le projet Holon.

#### Client ActivityPub hyper basique

###Interfaces adaptables
####React Admin 
####YesWiki
1 à 2 mois de travail
#### Omeka 
https://omeka.org
#### Notifications Etherpad

Plugin Etherpad qui créerait un serveur ActivityPub.

Chaque nouveau pad serait un acteur ActivityPub qu’on pourrait suivre et qui générerait plusieurs types de notifications:

Modifications (“Sébastien a modifié le pad”)
Expiration (“Le pad expirera dans X jours”)

Pour les modifications, il faudrait un temps d’attente suffisamment important pour éviter d’envoyer trop de messages. Si plusieurs utilisateurs modifient le pad en même temps, on pourrait envoyer un message de type “Sébastien et Gabriel ont modifié le pad”).

Le système de plugins d’Etherpad est suffisamment puissant pour permettre d’y adosser un serveur ActivityPub, avec ses propres routes ExpressJS. De plus, Etherpad est développé en NodeJS, donc on pourrait utiliser Moleculer avec le service ActivityPub de SemApps.

Il faudrait qu’un bouton “Suivre” puisse être ajouté dans la barre d’outils. A minima, il pourrait renvoyer vers un URL de notre choix (configurable par l’instance), avec l’URL de l’acteur en query string.
#### Template MoleculerJS pour des bots

Template MoleculerJS qui permettrait de créer en quelques lignes de commandes son propre bot ActivityPub autonome.
Convertisseur ActivityPub -> Mattermost/Slack

Bot ActivityPub qui écoute les activités qu’il reçoit dans son inbox et qui les transmets immédiatement à un channel Mattermost ou Slack via un webhook.

On pourrait imaginer un formulaire simple où il suffit d’entrer l’adresse d’un acteur (URI ou webfinger) ainsi que l’URL d’un webhook (Mattermost ou Slack), et cela générerait automatiquement un bot.

Ce chantier dépendrait du chantier “Descripteur d’activités ActivityPub”.
### Utilitaires
Descripteur d’activités ActivityPub

Utilitaire qui décrirait automatiquement les activités ActivityPub en une phrase compréhensible, et cela possiblement dans plusieurs langues. Ce serait une simple fonction qui prendrait une activités JSON-LD en input et renverrait une phrase en output.

Par exemple: “Sébastien a créé un événement Bal des Colibris (url)” ou “Gabriel a mis à jour le projet Salon de la Transition (url)” ou “Pierre suit maintenant Guillaume”.

Cela pourrait être utilisé par exemple pour générer automatiquement un résumé (summary) des activités ou pour créer une Note en plus d’un autre objet afin d’être compréhensible par Mastodon ou Mattermost. Cela pourrait aussi être utilisé directement pour le DMS.

Il faudrait qu’il puisse comprendre d’autres ontologies que ActivityStreams.

Il faudrait idéalement utiliser un outil de traduction type Weblate pour permettre à d’autres personnes de traduire dans d’autres langues.

Cela pourrait être diffusé sous forme de package NPM afin de pouvoir être utilisé dans le maximum de cas.

Des tests seraient faciles à mettre en place.

#### Triple store as a service (TSAAS)
Permet de créer son instance Fuseki en quelques clics.

**Comment by srosset81** [comment]
Peux-tu nous expliquer ce que tu entends par extension ?
Je ne vois pas le lien entre les éléments de ta liste...

**Comment by GuillaumeAV** [comment]
Héhé :) C'était quelque part une manière d'engager un processus de clarification et de compréhension mutuelle :) 

D'après ce que je comprends du champ des possibles, on peut envisager de plugger sur le middleware SemApps, une multiplicité d'interfaces : celles que j'ai listé plus haut. 

Outre les micro-services qui pourraient être les véritables extensions de SemApps, j'imagine qu'on peut donc envisager des "extensions de SemApps" qui ne seraient pas des micro-services SemApps mais d'autres outils / interfaces interopérés avec SemApps ... 

Je me trompe ? C'est plus clair ?

**Comment by srosset81** [comment]
Merci pour la clarification !

Cela me semble très pertinent pour SiB, Sparnatural et FluidGraph, ainsi que peut-être pour d'autres créations de @scenaristeur. Je suis partant pour réfléchir sur comment on peut mettre en valeur ces "extensions" afin de montrer l'intérêt du découplage données-interface.

Pour les autres, ça demande de passer par ActivityPub donc c'est plus complexe à mettre en oeuvre à mon avis.

PS: En revanche, j'ai plus de mal à comprendre ce que tu entends par prix ? (dans le titre de l'issue)
