### ISSUE TITLE
Pouvoir configurer les containers LDP

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#317]
#316 permet de réaliser un populate grâce au TripleStoreAdapter ou un appel direct à l'action get de ldp/ressource/get.
L'objectif est de paramétrer un container pour qu'il réalise toujours le même populate.

2 possibilités : 
persister ce paramétrage dans le TripleStore => propice à une logique backoffice/configuration par interface
ajouter un fichier de paramétrage => plus facile à mettre en oeuvre, peut être de meilleurs perfs

**Comment by srosset81** [comment]
J'ai édité le titre de cette issue car ça pourrait aussi s'appliquer à d'autres paramètres du container, comme `queryDepth` ou le dataset (voir #313)

Pour l'option 2, tu parles de fichier de paramètre, mais pour moi c'est juste une config du LDP service. Cette config peut être mise dans un fichier à part (comme les ontologies) mais rien ne l'oblige.

**Comment by srosset81** [comment]
J'ai des problématiques avec la configuration des container par settings Moleculer, car il est difficile de passer ces settings (en particulier dans mon cas, le contexte JSON-LD par défaut) à d'autres services.

Pour le maximum de flexibilité, il serait préférable que ces paramètres de containers soient enregistré dans le triple store. N'importe quel service pourrait ainsi lire ces paramètres et agir en conséquence.

Cela permettrait aussi de créer des containers "à la volée", sans qu'ils soient définis dans les settings Moleculer.

On pourrait mettre ces settings dans un graph à part, pour éviter qu'ils soient retournés par l'endpoint SPARQL. @tfrancart a fait remarqué qu'il existe une [configuration](https://jena.apache.org/documentation/fuseki2/fuseki-data-access-control.html#graph-acl) qui empêche Fuseki de retourner les données de certains graphs choisis. Elle sera sans doute utilisée pour cacher le graph avec les WebACL.

**Comment by srosset81** [comment]
Je ferme car ça a été fait dans https://github.com/assemblee-virtuelle/semapps/pull/492, via un fichier de configuration.
