### ISSUE TITLE
Mettre en valeur les projets qui utilisent SemApps en prod

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#318]
Nous avons maintenant deux projets en prod:

- https://alertes.colibris-lafabrique.org
- Data Food Consortium

Cela pourrait valoir la peine de l'indiquer sur le site web ?

**Comment by srosset81** [comment]
A noter que les deux serveurs ActivityPub sont non seulement en open source, mais bien documenté ;-)

https://github.com/reconnexion/colibris.social
https://github.com/reconnexion/activitypub-mailer

**Comment by bouviermullerp** [comment]
@srosset81 on pourrait ajouter une partie supplémentaire à la page d'accueil : 
Ils utilisent SemApps : et ajouter les logos de chaque projet avec un lien hyper texte vers chacun des projets ?
Je ne suis pas à l'aise avec la modification de la page d'accueil (un peu trop technique). J'ai besoin qu'on m'explique davantage pur le faire moi même car je ne suis pas autonome pour réaliser ma proposition.
