### ISSUE TITLE
When/Who decide to merge a pull request ? - To be discussed

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#319]
**Issue créée pour lancer une discussion**

Ca fait un moment que je me pose la question, et la lecture de la doc me fait penser que c'est important d'en discuter : qui accepte les merge, quelle est notre stratégie à ce sujet ? - que ça soit pour la doc ou pour le code.

## Documentation
Dans la partie docs/contribute/documentation, il est proposé 3 modalités de contribution : General Scheme, Propose Topics, Modify a page.
-> Je ne suis pas sur de comprendre l'avantage de [General Scheme](https://website-g5796d4ef.vercel.app/docs/contribute/documentation#general-scheme), par rapport aux 2 autres modalités.

## Code
Il n'existe pas de documentation similaire pour le code, je me demandais donc qui a le "dernier mot" pour accepté une pull resquest ? Y a-t-il une stratégie, des éléments de vérifications qu'on peut partager et qui le précise ? Je ne sais pas si c'est une bonne pratique, peut être que non ?

**Comment by srosset81** [comment]
La bonne pratique Git c'est de laisser le créateur de la PR merger une fois que tous les reviewers ont validé. C'est ce qu'on fait pour la partie code en tout cas. Cela évite de soucis techniques, quand il y a plusieurs PR qui "se mergent les unes dans les autres".

> Dans la partie docs/contribute/documentation, il est proposé 3 modalités de contribution : General Scheme, Propose Topics, Modify a page.
-> Je ne suis pas sur de comprendre l'avantage de General Scheme, par rapport aux 2 autres modalités.

A voir avec @GuillaumeAV qui avait écrit cette doc.

> Il n'existe pas de documentation similaire pour le code, je me demandais donc qui a le "dernier mot" pour accepté une pull resquest ? Y a-t-il une stratégie, des éléments de vérifications qu'on peut partager et qui le précise ? Je ne sais pas si c'est une bonne pratique, peut être que non ?

Pour l'instant nous avons décidé que les PR "code" devaient être validés par tous les membres de la "core team", c'est-à-dire Simon et moi (Niko n'étant plus dispo). Cela évoluera sans doute dans le futur lorsque nous serons plus nombreux.

Quant à la question de "qui a dernier mot", je dirais que, comme pour la gestion par consentement, on ne merge pas tant qu'il y a une objection.

**Comment by srosset81** [comment]
@bouviermullerp D'autres besoins de clarification ? On ferme cette issue ?

**Comment by bouviermullerp** [comment]
ok pour la gestion par consentement. Merci Seb
