### ISSUE TITLE
Implement Linked Data Signature

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#321]
https://github.com/digitalbazaar/jsonld-signatures

**Comment by srosset81** [comment]
According to the [Objects Integrity Proofs proposal](https://codeberg.org/fediverse/fep/src/branch/main/fep/8b32/fep-8b32.md), Linked Data Signature is outdated.

We could consider implementing Objects Integrity Proofs instead... ?

**Comment by simonLouvet** [comment]
no opinion and no ability to argue

**Comment by srosset81** [comment]
In [this report](https://swicg.github.io/activitypub-http-signature/#so-what-s-the-verdict), it is confirmed:

> Mastodon’s current implementation of LD Signatures is outdated...Furthermore, the LD Signatures specification as a whole has been superseded by [Verifiable Credential Data Integrity 1.0](https://www.w3.org/TR/vc-data-integrity/), which is largely incompatible with the earlier LD Signature spec. For this reason, it is not advised to implement support for LD Signatures.

So I close this issue as I see no point in implementing LD signature on SemApps.
