### ISSUE TITLE
Terminer le process sur les rôles

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#322]
Comment on les fait évoluer ? Est-il possible de démissionner d'un rôle ? Combien de temps dure le mandat ?

**Comment by srosset81** [comment]
Je propose a minima une réunion à la rentrée pour faire un retour sur les 3 premiers mois des rôles: qu'est-ce qui marche ? qu'est-ce qui ne marche pas ? comment on pourrait améliorer les choses ?

En holocracy il est recommandé d'avoir une réunion gouvernance tous les mois. A voir le rythme qui nous conviendra, mais je pense que 3 mois est un minimum pour garder le processus de gouvernance vivant.

**Comment by ReX-AV-Gab** [comment]
Je serais partant pour fixer une date à l'occasion d'une réunion sprint. Et plutôt favorable à cette incontournable réunion vers la fin septembre pour avoir un peu plus de recul. Merci Sébastien

**Comment by bouviermullerp** [comment]
Je me permets de t'indiquer comme contributeur de cette carte cher Gabriel !

**Comment by bouviermullerp** [comment]
Prochaine réunion gouvernance le 30/09 à 16h !
