### ISSUE TITLE
Guide pour créer son serveur ActivityPub en 5 minutes

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#324]
- Initialisation de la [template Moleculer ActivityPub](https://github.com/assemblee-virtuelle/semapps/issues/323)
- Création d'un acteur avec ses clés de signature
- Suivre un acteur Mastodon via SemApps
- Suivre l'acteur SemApps via Mastodon
- Poster un message via SemApps et vérifier qu'il apparait bien dans le fil de l'acteur Mastodon

**Comment by GuillaumeAV** [comment]
C'est génial !!!
