### ISSUE TITLE
Architecture de la doc externe semapps.org

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#325]
**Spécifications**
Déplacer la page [About](https://semapps.org/docs/about) dans une section de la *page d'accueil*
Ajouter une section "ils contribuent et utilisent SemApps" avec les logos de l'AV, CdlT, Reconnexion, Oseons, DFC (_apparté_: qu'est ce que classe comme éco-système de projet contributeurs !!! je suis fierrrrr :D )

Ajout d'une page "Code Social" et de sous-pages pour chacun des modèles.
Migrer les pages gouvernance et team dans le modèle social et humain.

_Commentaire_
Cette issue est relativement grosse et sera découpée en plus petite une fois les spec validée par l'équipe.

**Comment by srosset81** [comment]
> **Spécifications**
> Déplacer la page [About](https://semapps.org/docs/about) dans une section de la _page d'accueil_
> Ajouter une section "ils contribuent et utilisent SemApps" avec les logos de l'AV, CdlT, Reconnexion, Oseons, DFC (_apparté_: qu'est ce que classe comme éco-système de projet contributeurs !!! je suis fierrrrr :D )

Yes trop cool ! :-)

> Ajout d'une page "Code Social" et de sous-pages pour chacun des modèles.
> Migrer les pages gouvernance et team dans le modèle social et humain.

Pas sûr de bien comprendre l'idée mais je pense qu'il serait important que les pages gouvernance / équipe restent facilement accessibles.

**Comment by bouviermullerp** [comment]
lié à #318

**Comment by ValentineMathieu** [comment]
Hello tout le monde ! 
Comme convenu, @bouviermullerp et moi-même avons décidé de diviser cette issue en sous-issues, pour plus d'efficacité et de visibilité :D Rendez-vous sur les issue #405 et #406 pour nous donner vos plus beaux commentaires, et nous guider dans cette mission. Je ferme donc cette issue !
