### ISSUE TITLE
Tenir à jour le fichier clients AV / SemApps 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#329]
[Vous trouverez le tableur ici !](https://docs.google.com/spreadsheets/d/1CFfwF8f2AEqZ1B-zTS07FaluXIAtXThKALI427PIKmI/edit?usp=sharing)

**Comment by bouviermullerp** [comment]
mis à jour

**Comment by bouviermullerp** [comment]
Issue récurrente qui est prise en charge par le référent.
