### ISSUE TITLE
Séparer le package @semapps/react-admin

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#330]
Séparer le package @semapps/react-admin en 3 packages:

- `@semapps/semantic-data-provider` avec le dataProvider
- `@semapps/auth-provider` avec l'authProvider et les composants nécessaires
- `@semapps/archipelago-layout` pour les composants d'affichage

**Comment by simonLouvet** [comment]
Ca me semble cohérent.
