### ISSUE TITLE
Utiliser la nouvelle action addRoute de moleculer-web

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#334]
A [notre demande](https://github.com/moleculerjs/moleculer-web/issues/175), des actions `addRoute` et `removeRoute` ont été implémentées dans l'API Gateway (moleculer-web).

Dès que ce sera publié, on pourrait supprimer les actions `getApiRoutes` et ajouter automatiquement les routes dans la méthode `started`, qu'est-ce que vous en pensez ? Est-on sûr que c'est une bonne pratique ? En tout cas ça simplifierait la configuration des services !

Il faudra s'assurer que le service `api` existe avant d'appeler la route, pour éviter que cela génère des erreurs au cas où aucun API gateway n'est lancé. On ne peut pas ajouter une dépendance à `api` car sinon ça va bloquer le lancement en cas d'absence du service, mais il faut s'assurer que ce service `api` est bien lancé.

**Comment by simonLouvet** [comment]
déjà fait.

**Comment by srosset81** [comment]
Ah bon, où ça ?
On parle d'une action qui peut être appelée depuis un autre service Moleculer.

**Comment by simonLouvet** [comment]
Je  pensais à ce que on fait dans le service api

**Comment by srosset81** [comment]
Dans le service api on appelle la *method* addRoute, pas l'action.
