### ISSUE TITLE
Pagination inutilisable car masquée par Fab button

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#339]
Sur le dernier dms la pagination est masquée par le bouton + donc inutilisable sur mobile
![Screenshot_20200807-100146_Chrome](https://user-images.githubusercontent.com/4020744/89623869-ab118400-d895-11ea-877b-b4f3c7b20364.jpg)

**Comment by srosset81** [comment]
Fixé sur la dernière version de https://coographie.vercel.app
