### ISSUE TITLE
La création de personnes ne marche pas

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#340]
Sur https://dms-srosset81.semapps.vercel.app/, à partir de firefox, ca donne une page blanche ...

**Comment by srosset81** [comment]
Le problème venait du label de certains projets qui était à double. Cela a été réglé en utilisant la méthode `PUT` au lieu de `PATCH` pour l'édition des données.

La dernière version est visible ici https://coographie.vercel.app
