### ISSUE TITLE
Générer automatiquement les liens inverses

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#341]
Voir par exemple à partir de l'orga des Chemins de la Transition que je viens de créer ;)

**Comment by srosset81** [comment]
Pour l'instant rien n'a été fait au niveau du middleware pour générer les liens inverses à partir du fichier OWL. C'est tout un sujet...

Ping @simonLouvet

**Comment by GuillaumeAV** [comment]
C'est un joli sujet :)

**Comment by simonLouvet** [comment]
comme @srosset81 l'a evoqué, la solution la plus cohérente semble  d'analyser les fichier owl des taxonomies gérées par un semapps pour detecter (par un mini raisonneur) que ajouter un lien dans un sens est équivalent à ajouter un lien inverse et il est alors possible d'ajouter ce lien inverse de manière silencieuse ou explicite.
Il faut d'abord designer l'ergonomie et le comportement avant de le développer. 
Est ce que c'est valable pour toutes le classes?
Est ce que c'est valable pour tous les container?
Est ce que c'est c'est valable pour toutes les relations d'une classe?

**Comment by GuillaumeAV** [comment]
Ok, peut-être également demander à @tfrancart les bonnes pratiques dans ce domaine ? 

Je crois que ca concerne l'ensemble des relations entre classes oui ..

**Comment by simonLouvet** [comment]
> tions entre classes oui ..

la question est de savoir si le produit / développeurs ont besoin de pouvoir configurer certaines relation en relation inverse systématiquement et d'autre en relations normales sur le même serveur / produit

**Comment by tfrancart** [comment]
Matérialiser les liens inverses dans la base n'est pas toujours une bonne solution. Si le besoin est de _voir_ ou de _requêter_ ces liens inverses, il n'est pas nécessaire qu'ils soient matérialiser puisque ça peut se faire par des requêtes.
Si on veut pouvoir matérialiser certains liens il me semble que c'est nécessairement au cas par cas avec de la config. D'ailleurs cette config peut être faite au niveau de l'affichage ("affiche moi la propriété inverse de P1 dans cet écran"), et pas du stockage en base.

Instinctivement j'aurai tendance à dire que les couches basses de Semapps devraient être complètement agnostiques là-dessus et se contenter de créer seulement ce qui  a été explicitement demandé par l'utilisateur, sans faire aucune inférence.

En fait ca pose la question de la configuration d'un moteur d'inférence dans le triplestore utilisé.

**Comment by srosset81** [comment]
Merci pour le partage de tes réflexions @tfrancart !

C'est vrai que l'inférence peut être faite au moment du GET de la ressource, mais cela va alourdir la requête SPARQL générée par le middleware et je crains déjà qu'on va faire face à des problèmes de performances lorsqu'on aura les ACLs en place.

Faire la requête au niveau du front est trop compliqué pour le moment (dans le contexte React-Admin), et ça va multiplier encore les appels au middleware, donc poser d'autres problèmes de performances (surcharge du serveur + temps de chargement plus long pour l'utilisateur).

Je suis d'accord qu'il ne faut pas que l'inférence soit activée par défaut, mais je pense que pas mal de projets pourraient avoir ce besoin, donc cela pourrait être cohérent d'ajouter une option (désactivée par défaut) pour le permettre.
Idéalement il faudrait que ce soit un microservice distinct qui fasse office de "moteur d'inférence", mais je ne sais pas à quel point ce serait faisable dans le cadre de Moleculer.

Le problème reste cependant entier pour les ressources sur des instances distantes. Si depuis une instance A on met un lien vers une instance B, il n'y a pas moyen d'obliger l'instance B à ajouter un lien inverse. Je pense qu'ActivityPub pourrait offrir une solution à plus long terme à ce problème: on pourrait imaginer par exemple que l'instance A envoie, via ActivityPub, une _suggestion_ (via l'activity `Offer`) d'ajouter un lien inverse, que l'instance B pourrait accepter ou pas, automatiquement ou via modération.

**Comment by GuillaumeAV** [comment]
Ça à l'air top la, perspective long terme avec l'activity offer!

Le mer. 26 août 2020 à 11:57, Sébastien Rosset <notifications@github.com> a
écrit :
