### ISSUE TITLE
SemApps des Grands Voisins - BDD sémantique, installation, link sparnatural

### ISSUE THREAD

**Issue by Ancelin-Moulherat-AV** [assemblee-virtuelle/semapps#348]
J'ai besoin d'aide pour avoir une instance SemApps minimalement fonctionnelle d'ici au 15 septembre, puis-je avoir un coup de main svp ?

INFOS
Plateau Urbain va m'envoyer leurs fichiers de Voisins pour reconstituer une BDD d'acteurs.
Nous avons encore quelques restes de SemApps V1
Alain Hays propose un hébergement gratuit avec son serveur.

QUESTIONS
Comment sémantiser ce tableur ?
Où installer SemApps ? 
Les 2 actions précédentes sont-elles à la portée d'un néophyte ?
Est-ce facile d'ajouter un semantic forms pour enrichir la BDD ?
Y-t-il un tutoriel sparnatural pour faciliter son utilisation ?

**Comment by Ancelin-Moulherat-AV** [comment]
Chantiers

Simon sémantiser via le bus sémantique, pas là
Installer SemApps avec PAIR
Connection Sparnatural : pointage vers les données SemApps sans lien direct 
Local ou en ligne ? Clarifier, en ligne public et en local privé confidentiel
Cagnotte des voisins
explorer des financements

Seb prêt à mettre qq heures, installer instance, couleurs GV
Dead line instance, possibilité de MAJ

Pierre : rentre à la main les données non sémantiques + Gab aussi

Instance pas custom vers le 10, rentrer à la main un bout de data set

Simon a un workflow framaforms vers sémantique, données essentielles présentes

**Comment by Ancelin-Moulherat-AV** [comment]
Alain : serveur VPS chez contabo 1 tera
Demander aux GV budget hébergement / nom de domaine voulu = privilégier OVH
Clarifier les demandes de validation auprès des personnes concernées 
Issues doivent être une action unique affectée à une personne seule
Scinder le projet en plusieurs morceaux / issues

1 travailler la BDD (Ancelin)
2 installer SemApps (Gab)
3 mise en ligne sur serveur avec nom de domaine grands voisins (?)
4 ajouter d'un formulaire sémantique (?)
5 pointage de sparnatural vers cette BDD 

label instance GV pour github
pas de CR sur github, trouver un autre endroit
informations et actions précises sur github, lever les ambiguités

**Comment by srosset81** [comment]
@Ancelin-Moulherat-AV Pour l'installation de l'instance GV, j'aurai donc besoin:

- Accès "root" SSH à un serveur (celui d'Alain s'il est adapté, sinon un serveur OVH Cloud idéalement financé par les GV)
- Nom de domaine (ou sous-domaine) qui pointe vers l'adresse IP du serveur

Il faudrait que je puisse tester ça rapidement pour qu'il n'y ait pas de surprise plus tard.

**Comment by GuillaumeAV** [comment]
Yop ! Tu passes aux GV cette semaine Ancelin ?

Le mer. 26 août 2020 à 16:18, Sébastien Rosset <notifications@github.com> a
écrit :

**Comment by srosset81** [comment]
Je ferme cette issue puisqu'elle a été déplacée sur plusieurs autres issues.
