### ISSUE TITLE
Faciliter une réunion sur la stratégie produit pour les 6 prochains mois

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#349]
Action : 
- [ ] Framadate + convocation
- [ ] Statut des projets ad-hoc
- [ ] Fonctionnalités financées

**Comment by bouviermullerp** [comment]
Lien pour le frama : https://framadate.org/zASyILSp7oNf6P1v

**Comment by bouviermullerp** [comment]
Nouveau framadate car peu de dispo la semaine du 21 : https://framadate.org/Sywcyjbi4EbLkzUU

**Comment by bouviermullerp** [comment]
2 fonctionnalités importantes : 
- La recherche - intégrer sparnatural ?
- La fédération, pouvoir crééer des organisations ayant déjà une URI

**Comment by srosset81** [comment]
Intégrer Sparnatural dans le code React-Admin ne semble pas évident, car Sparnatural utilise jQuery et les manières de fonctionner de React et jQuery sont assez peu compatibles.
@tfrancart Tu pensais supprimer jQuery de Sparnatural, est-ce que c'est toujours prévu et, si oui, à quelle échéance ?
