### ISSUE TITLE
Reconstituer une BDD sémantique des Voisins

### ISSUE THREAD

**Issue by Ancelin-Moulherat-AV** [assemblee-virtuelle/semapps#350]
> Charlotte Gondouin va m'envoyer leurs fichiers d'ici la fin de la semaine 28 août.
> Pour voir quelle est la structuration tabulaire de ces données voir PJ ci-après.
> Une classification avait été faite pour la confidentialité des données des colonnes : avait été indiqué en haut de chaque colonne au choix sur la bdd de la saison 1 pour la carto : copil / GV / public , pour indiquer le niveau de confidentialité de la donnée
> Possibilité 1 : Simon a un workflow bus qui va de framaforms vers sémantique, données essentielles présentes
Possibilité 2 : ajouter à la main les données tabulaires

Ancienne BDD incomplète
https://matrix.virtual-assembly.org/_matrix/media/r0/download/matrix.virtual-assembly.org/WnjKkPxdaEIacEcmFcWuGOpa

Modèle de données des fichiers de Plateau Urbain
[BDD GV stucture de base.xlsx](https://github.com/assemblee-virtuelle/semapps/files/5130393/BDD.GV.stucture.de.base.xlsx)

**Comment by Ancelin-Moulherat-AV** [comment]
Start In Bloc peut faire un form sémantique pour ajouter de la donnée

**Comment by bouviermullerp** [comment]
@Ancelin-Moulherat-AV as tu des nouvelles de cette action ?
Est-ce que la sémantisation des données est toujours d'actu ?

**Comment by Ancelin-Moulherat-AV** [comment]
Hello @bouviermullerp  merci pour ta relance ! 
C'est pour cette action que j'ai obtenu 500€ de la cagnotte des voisins.

Je dois clarifier le besoin et sélectionner les BDD ainsi que les propriétés qu'on veut sémantiser selon ce que nous permet le RGPD.
Il y aura à minima le fichier des organisations de la saison 2 ainsi que d'autres petits fichiers pour compléter l'annuaire au niveau des personnes...

Je vous partage le fichier confidentiel dans lequel j'ai stocké la BDD complète envoyée par PU, il y a aussi un début de réflexion pour le mapping.

**Comment by bouviermullerp** [comment]
La première instance est livrée - 170 personnes, mail, téléphone.
Pour les organisations, salle dans laquelle ils étaient, etc..
Une seconde version va essayer d'être livrée avec des données supplémentaires.

**Comment by simonLouvet** [comment]
l'issue ne concerne maintenant que la sémantisation des données issue de tableurs des grand voisins. Attente des input que @ancelin doit fournir

**Comment by simonLouvet** [comment]
@Ancelin-Moulherat-AV cela me semble hors contexte du noyau. Est ce que je peux fermer?
