### ISSUE TITLE
Brainstormer une stratégie pour débloquer les fonds 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#351]
Poser les différents scénarios qui nous permettraient de débloquer les subventions, d'accélérer les développement et de générer des effets de levier ...

Parmi les options : 
- Le prêt à la banque  (pour la plateforme CdlT notamment)

**Comment by srosset81** [comment]
@GuillaumeAV Même question que pour https://github.com/assemblee-virtuelle/semapps/issues/392
On ferme cette issue ?

**Comment by GuillaumeAV** [comment]
Hey ! Ca va se faire via Data pLayers, on peut du coup la fermer je crois ! 

A moins que une fois la liste des spec bien chiffrée, on se rende compte qu'il nous manque des sous pour tout bien développer ce qu'on a envie de développer ?

Mais je la fermerais quand même et j'en rouvirrais une autre le moment venu ?

**Comment by srosset81** [comment]
OK ça marche !
