### ISSUE TITLE
Installer une instance SemApps pour les GV

### ISSUE THREAD

**Issue by Ancelin-Moulherat-AV** [assemblee-virtuelle/semapps#352]
**Préalable à clarifier :** 
Veut-on une instance en local sur laquelle il y aurait les données confidentielles ? Cela permettrait d'avoir une "instance jouet" sur laquelle faire des tests, et une instance public en ligne avec uniquement les données non sensibles (en attendant d'avoir un système de droit d'accès)

**Comment by Ancelin-Moulherat-AV** [comment]
Priorité pour le 15 sept : que ce soit local ou en ligne, nous avons besoin de pouvoir faire une démonstration qui fait Waouh

**Comment by Ancelin-Moulherat-AV** [comment]
Pour l'installation de l'instance GV, j'aurai donc besoin:
Besoin de Seb pour installation : 
    
Accès "root" SSH à un serveur (celui d'Alain s'il est adapté, sinon un serveur OVH Cloud idéalement financé par les GV)
    Nom de domaine (ou sous-domaine) qui pointe vers l'adresse IP du serveur

Il faudrait que je puisse tester ça rapidement pour qu'il n'y ait pas de surprise plus tard.

**Comment by srosset81** [comment]
@Ancelin-Moulherat-AV Je proposerai de ne pas mettre de données confidentielles pour le moment, quitte à supprimer celles qui le sont.

**Comment by Ancelin-Moulherat-AV** [comment]
Ok

**Comment by srosset81** [comment]
Fait https://grandsvoisins.semapps.org
