### ISSUE TITLE
Ajouter un lien vers une ressource sur un autre serveur

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#353]
![Interopérabilité entre instances SemApps (1)](https://user-images.githubusercontent.com/17931931/133049127-815f4173-e4f9-427e-83d2-da12a17adf1d.png)

Avec @simonLouvet nous avons discuté de plusieurs sujets techniques autour de la fédération avant les vacances, notamment l'ajout de liens vers des ressources sur d'autres instances.

L'idéal serait un moteur de recherche multi-instances (en mode "écosystème") qui permette, via le méchanisme d'auto-complétion, de trouver rapidement des ressources à ajouter. Différentes solution s'offrent pour cela:

- On pourrait imaginer un serveur de recherche ElasticSearch dédié qui serait informé (en mode push) des mises à jour des ressources des différentes instances d'un écosystème. Lorsqu'on l'interrogerait sur un mot-clé, il retournerait les résultats avec, pour chaque ressource, l'URI et le label (pour pouvoir afficher quelque chose sans requête l'URI). A voir avec Mnemotix.

- Autre solution à tester: les Linked Data Fragments (https://linkeddatafragments.org), proposés par Ruben Verborgh.

- Dernière solution, qui ne devrait pas être très performante mais qui pourrait être mise en place assez rapidement: une requête SPARQL multi-instances.

Une solution intermédiaire serait de demander à l'utilisateur de choisir une instance (parmi un certain nombre proposé, avec possibilité éventuellement d'ajouter une nouvelle instance), puis de rechercher sur cette instance (il suffirait d'indiquer l'endpoint SPARQL de chaque instance dans les fichiers de config). Pour ajouter un lien, on pourrait imaginer un petit bouton `( + )` qui, losrqu'on clique dessus, afficherait une modale dédiée.

Voilà un petit exemple. Il faut appuyer sur les boutons rouges pour voir la suite:

https://www.figma.com/proto/dgfKKQHSc1sm3JPw68hSL0/Id%C3%A9e-ajout-lien-SemApps?node-id=1%3A2&scaling=min-zoom

Je pense que c'est tout à fait faisable avec react-admin. Cela pourrait constituer une solution intermédiaire, en attendant de développer un moteur de recherche adapté.

**Comment by GuillaumeAV** [comment]
Héhé on entre dans le vif du sujet ! 

@tfrancart @bblfish @Rouffi   vous avez sans doute un avis sur la question ?

**Comment by tfrancart** [comment]
> Dernière solution, qui ne devrait pas être très performante mais qui pourrait être mise en place assez rapidement: une requête SPARQL multi-instances.

Plutôt qu'une requête SPARQL multi-instance, une autre solution basique serait d'envoyer la même requête SPARQL à toutes les instances et à aggréger les résultats ensuite pour les montrer à l'utilisateur.

On a le même genre de problème avec OpenArchaeo, on a utilisé la première solution que tu décris : index de recherche Lucene qui indexe toutes les sources, mais pas mis à jour en mode push, mis à jour manuellement à la demande.

**Comment by srosset81** [comment]
Décisions du jour:
- Dans un premier temps, le client pourrait lancer plusieurs requête sur les différents serveurs et agréger les résultats, sans avoir besoin de passer par le middleware.
- Les résultats ne s'afficheraient qu'une fois tous les résultats retournés par les différentes instances. Ce n'est pas idéal mais ce serait compliqué de faire autrement avec React-Admin.
- Si cela pose un problème de performances, on envisagera un serveur dédié à la recherche écosystémique.
- Il reste quand même l'option proposée dans [cette maquette](https://www.figma.com/proto/dgfKKQHSc1sm3JPw68hSL0/Id%C3%A9e-ajout-lien-SemApps?node-id=1%3A2&scaling=min-zoom). Nous en parlerons à la prochaine réunion sprint pour savoir quelle option est privilégiée.

**Comment by srosset81** [comment]
Je pensais que, pour appliquer l'option 1, il faudrait développer un serveur spécial qui se baserait sur Elasticsearch. Mais en fait on peut utiliser directement Elasticsearch sans aucune surcouche.

Il serait facile de créer un service Moleculer qui écoute quand une ressource LDP est créé / modifiée / supprimée, qui l'indexe directement sur un serveur Elasticsearch via le client Node d'ES (voir [l'exemple ici](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/introduction.html#_quick_start)).

Idéalement, il faudrait que ce service Moleculer puisse indexer les données sur plusieurs serveurs ES différents.

Ensuite une simple requête ES (effectuée depuis le front, ou via le middleware) permettrait de récupérer très rapidement les ressources qui matchent les mots-clés entrés par l'utilisateur.

**Comment by simonLouvet** [comment]
Intéressant et viable. L'indexation du triple store ne suffirait pas?

**Comment by srosset81** [comment]
Cette issue est en lien avec la requête fédérée: rechercher des ressources dispersées sur plusieurs instances SemApps.

**Comment by simonLouvet** [comment]
En fait j'avais lu trop vite que tu donnais une solution spécifique pour l'option 1 et je suis d'accord avec ce que tu dis. J'ai répondu en penssant que tu remettait le choix d'implémentation choisi pour me court terme ce qui n'est pas le cas, dsl.

**Comment by GuillaumeAV** [comment]
Au fait l'idée du [bouton rouge](https://www.figma.com/proto/dgfKKQHSc1sm3JPw68hSL0/Id%C3%A9e-ajout-lien-SemApps?node-id=1%3A2&scaling=min-zoom) (voir début du fil) est très cool je trouve ! que ce soit pour ajouter des ressources présentes sur l'instance ou ailleurs

**Comment by bouviermullerp** [comment]
> Cette issue est en lien avec la requête fédérée: rechercher des ressources dispersées sur plusieurs instances SemApps.
@srosset81 , j'ai un besoin de clarifications :)
D'après le titre, je comprends que le besoin fonctionnel auquel répond cette carte est _l'ajout d'un lien_ - je n'ai pas compris s'il existe une seconde issue pour évoquer la recherche (qui est la fonctionnalité mentionnées dans les commentaires).

En tout cas, je pense que l'ajout d'un contenu existant sur un autre serveur est la première étape. Dans la V1 de SemApps, il était possible - lors de la création de son profil - d'indiquer qu'il existant déjà ailleurs. Cela permettait de pré-remplir tous les champs et de le mettre à jour à la demande.
Avec ActivityPub, je me dit que dès que le concept de référence est mis à jour, il peut mettre à jour les concepts hébergés dans les autres instances. 
Mais cette man!ère de fonctionner est peut être trop de type fédération ?

**Comment by srosset81** [comment]
La recherche multi-instances est très liée à l'ajout de liens, car en terme d'UX, ça va être difficile d'imposer à l'utilisateur de fournir des URLs complets. Selon ce qu'on décide de faire, on pourra créer des issues plus spécifiques.

> Dans la V1 de SemApps, il était possible - lors de la création de son profil - d'indiquer qu'il existant déjà ailleurs. Cela permettait de pré-remplir tous les champs et de le mettre à jour à la demande.

C'est une toute autre question, qui mériterait sa propre issue.

> Avec ActivityPub, je me dit que dès que le concept de référence est mis à jour, il peut mettre à jour les concepts hébergés dans les autres instances.
> Mais cette man!ère de fonctionner est peut être trop de type fédération ?

C'est une discussion que j'ai eu récemment avec @nikoPLP. Le mot fédération est un peu un fourre-tout, et on gagnerait à le clarifier. Ce dont tu parles, c'est plutôt ce que je nommerai de la "synchronisation des données": permettre à des données sur une instances d'être dupliquée sur une autre instance. Faire un lien d'une instance vers une autre instance n'est pas vraiment de la fédération non plus: c'est juste le principe du lien, qui existe depuis le début du web. Donc au final il n'y a que le protocole ActivityPub qui permet vraiment de faire de la fédération.

**Comment by srosset81** [comment]
J'ai créé plusieurs issues sur le sujet:
- #450
- #449
- #461

**Comment by srosset81** [comment]
Suite à une discussion SemApps mercredi dernier, la solution présentée sur [cette maquette](https://www.figma.com/proto/dgfKKQHSc1sm3JPw68hSL0/Id%C3%A9e-ajout-lien-SemApps?node-id=1%3A2&scaling=min-zoom) semble plus adaptée en terme d'UX. Ce sera plus facile à implémenter, et les performances seront meilleures qu'une recherche aggrégée.

Je pense qu'on peut difficilement enlever l'input autocomplete, mais il faudra sans doute accepter que l'UX sera moins bonne (recherche lente, pas d'indication concernant l'instance d'où vient la ressource...)

**Comment by srosset81** [comment]
Commentaires suite à la réunion de ce jour ([voir le CR complet](https://pad.lescommuns.org/UVcvt8XGT5mUK6mvzlMCTg)):

- Pour certaines données (ex. compétences) on pourrait n'avoir qu'un serveur distant

**Comment by srosset81** [comment]
## Implémentation

Trois choses à implémenter:
- Une modale qui permet à la fois de lister les ressources en faisant une recherche par mot-clé mais aussi de créer une nouvelle ressource (avec un lien vers la page Create et le lien inverse pré-rempli) [Voir codesandbox](https://codesandbox.io/s/add-relationship-dialog-9ujme)
- Cette modale pourra se déclencher à différents endroits, par exemple avec un bouton + à côté d'un lien existant. [Voir Figma](https://www.figma.com/proto/dgfKKQHSc1sm3JPw68hSL0/Id%C3%A9e-ajout-lien-SemApps?node-id=1%3A2&starting-point-node-id=1%3A2).
- Un autocomplete qui permet la même chose que la modale, sans la création d'une nouvelle ressource.
