### ISSUE TITLE
Naviguer sur une ressource d'une autre instance

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#354]
![Interopérabilité entre instances SemApps (3)](https://user-images.githubusercontent.com/17931931/133049318-ef753164-b897-4c00-9d1b-97dcf8ea1204.png)

> Ceci est la suite des discussions avec @simonLouvet sur la fédération faites en début août.

Lorsqu'on [crée un lien vers une ressource d'une autre instance](https://github.com/assemblee-virtuelle/semapps/issues/353), le nom de cette ressource va apparaître sur la partie droite.

La question est: **qu'est-ce qui se passe lorsqu'on clique sur le nom de la ressource ?**

Par défaut, on va rester sur la même instance de SemApps. React-admin va fetcher les données distantes et les afficher comme si c'était une donnée locale. C'est la magie de la fédération.

Mais ça peut poser un problème, par exemple si l'instance distante a plus de données sur la ressource que celle qu'on affiche. Par exemple un projet sur l'instance Assemblée Virtuelle contient juste une description, mais sur une instance Grands Voisins (GV), il y a aussi un numéro de téléphone. Du coup si les données du projet GV sont affichées sur l'instance Assemblée Virtuelle, seule la description sera affichée.

**Est-ce que cela n'aurait pas plus du sens de simplement ajouter un lien vers l'autre instance SemApps ?** De cette manière, le navigateur quitte simplement l'instance Assemblée Virtuelle et va sur l'instance GV, avec son propre design et son affichage des données. On reste dans une expérience très... web ;-)

En terme Linked Data, on peut avoir des dizaines d'interfaces qui se connectent aux mêmes données. Mais au niveau des configs, l'instance Assemblée Virtuelle pourrait choisir que toutes les données GV doivent s'afficher sur une instance de SemApps localisée sur `https://grands-voisins.org/`. Lorsque React-Admin identifie une donnée GV, il suffit juste qu'il mette un lien vers cette instance.

**Comment by tfrancart** [comment]
> Mais ça peut poser un problème, par exemple si l'instance distante a plus de données sur la ressource que celle qu'on affiche. Par exemple un projet sur l'instance Assemblée Virtuelle contient juste une description, mais sur une instance Grands Voisins (GV), il y a aussi un numéro de téléphone. Du coup si les données du projet GV sont affichées sur l'instance Assemblée Virtuelle, seule la description sera affichée

C'est un scenario déjà assez avancé où la description de la même ressource est splittée entre plusieurs serveurs. Le scenario plus simple et plus courant est que des références soient faites à des ressources distantes qui portent l'intégralité de leurs propriétés.
Dans le scenario décrit il faudrait faire un merge de la description locale et de la description distante de la ressource. Mais d'ailleurs comment sait-on que la description de cette ressource est splittée ?

**Comment by srosset81** [comment]
> C'est un scenario déjà assez avancé où la description de la même ressource est splittée entre plusieurs serveurs. Le scenario plus simple et plus courant est que des références soient faites à des ressources distantes qui portent l'intégralité de leurs propriétés.
> Dans le scenario décrit il faudrait faire un merge de la description locale et de la description distante de la ressource. Mais d'ailleurs comment sait-on que la description de cette ressource est splittée ?

La ressource ne serait pas splittée. Dans mon exemple, la ressource sur l'instance GV comporterait simplement des propriétés que l'instance AV ne connait pas, et ne peut donc pas afficher. Donc plutôt que d'afficher la ressource GV sur l'instance AV (avec certaines propriétés qui ne s'affichent pas), il pourrait être plus pertinent de simplement faire un lien vers l'instance GV.

**Comment by srosset81** [comment]
Décision du jour: en parler avec toute l'équipe lors de la prochaine réunion sprint.

Remarques:
- Les liens vers les interfaces SemApps pourraient être calculés à partir du fichier `ecosystem.json` ou `archipel.json` qui répertorierait toutes les instances "cousines".
- On pourrait activer ou non ces liens "réels" au niveau de la config de l'interface, ou alors (éventuellement) au niveau des options de l'utilisateur.

**Comment by srosset81** [comment]
## Implémentation

- Adapter ChipField ou AvatarField en ajoutant une prop `remoteFrontends` ou `blankTarget`. La prop peut-être:
  - un boolean
  - une fonction qui reçoit le `record` et renvoie un boolean
- Si false, on affiche la donnée distante dans la même interface 
- Si true, le lien renvoie vers l'URI de la ressource (qui redirige ensuite vers l'interface préférée)
  - Un indicateur (icône, couleur) permet d'avertir l'utilisateur qu'il va être renvoyé sur un autre site
- Si la donnée est celle du serveur par défaut, elle s'affiche toujours à l'intérieur de la même interface
- Si aucune props n'est passée, on assume un boolean `false` (on reste toujours sur la même interface)

## Pas compris dans estimation

- Mettre lien vers ressource distante lorsqu'il s'agit d'une relation réifiée (membres d'une organisation p.ex.)
