### ISSUE TITLE
Bug quand on veut modifier une personne

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#358]
Exemple : https://dms-srosset81.semapps.vercel.app/#/User/https%3A%2F%2Fdata.virtual-assembly.org%2Fpersons%2Fbenoit_ferchaud

Quand on clique sur le bouton éditer, une page blanche apparaît...

**Comment by srosset81** [comment]
Le site est maintenant https://coographie.vercel.app, merci d'utiliser celui-là pour les tests.

Je reproduits effectivement sur https://coographie.vercel.app/#/User/https%3A%2F%2Fdata.virtual-assembly.org%2Fpersons%2Fbenoit_ferchaud

**Comment by GuillaumeAV** [comment]
C'est résolu, c'est trop cool ! Merci ;)
