### ISSUE TITLE
Traiter les compétences et les centre d'intérêt comme les autres classes

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#362]
Avec possibilité d'ajout d'une description. 
Avec les relations : ex : 
* Développement web est une compétence de Sébastien Rosset
* Jardinage est un centre d'intérêt de Chuck Norris

**Comment by srosset81** [comment]
Pas sûr de comprendre, mais je crois que c'est bon.

**Comment by GuillaumeAV** [comment]
Oui elle date un peu cette issue .. Je crois qu'on peut la fermer en effet, d'autant plus que le next step sera de gérer ces items à l'aide de bases de connaissances dédiées ;)
