### ISSUE TITLE
Quand on veut compléter le profil d'une personne, nombre d'individus limité

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#363]
Quand on veut compléter le profil d'une personne en ajoutant des projets / orgas / Compétences / Intérêts, on est limité à une vingtaine d'entrées (classées par ordre alphabétique ou pas) alors qu'il y en a bien plus ;)

**Comment by GuillaumeAV** [comment]
Autre sujet, un petit mécanisme de complétion sur la liste déroulante serait très user friendly ;)

**Comment by srosset81** [comment]
@GuillaumeAV L'auto-complétion marche déjà ! :-D Une recherche SPARQL est lancé dès qu'on tape une lettre dans le champ principal. A noter toutefois que:

- les accents sont pour le moment [pris en compte](https://github.com/assemblee-virtuelle/semapps/issues/1214)
- la recherche est faite sur le mot entier: une recherche sur "la" va retourner autant "Laure" que "Guillaume"

Par défaut, react-admin affiche 25 résultats maximum, moins ceux qui sont déjà sélectionnés. Je peux augmenter à 100 ou plus (via la prop `perPage` de `ReferenceArrayInput`), mais après ça peut poser un problème de lenteur, sur des mobiles notamment. Il faut mettre une limite de toute façon...

Autre possibilité: on ne peut afficher la liste (via `shouldRenderSuggestions`) que lorsque l'utilisateur a tapé un caractère, ou deux, ou trois ? Et à ce moment on affiche tous les résultats. Cela serait peut-être plus clair: plutôt que d'aller chercher une ressource dans la liste complète, l'utilisateur taperait quelques lettres et il aurait rapidement la ressource qu'il cherche.

Ping @bouviermullerp

**Comment by GuillaumeAV** [comment]
Yop ! L'enjeu est de pouvoir sélectionner 100% des résultats possibles, parce que par exemple, si Seb est membre de l'AV, je veux pouvoir le dire, même s'il est le 50000ème par ordre alphabétique .. La solution, complétion à partir de 2 ou 3 caractères me semble pertinente ...

**Comment by srosset81** [comment]
C'est fait sur https://archipel.assemblee-virtuelle.org
Désormais la liste de suggestion ne s'affiche que quand on tape 2 caractères

**Comment by GuillaumeAV** [comment]
Génial !!
