### ISSUE TITLE
Ajouter des événements sur Coographie 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#368]
A partir de PAIR : https://www.virtual-assembly.org/ontologies/pair/index-fr.html
Ce serait très utile !

**Comment by srosset81** [comment]
@GuillaumeAV Peux-tu dire ce que tu attends comme propriétés et comme relations avec les autres classes existantes ?

**Comment by GuillaumeAV** [comment]
Yop ! 

Sur la base de https://www.virtual-assembly.org/ontologies/pair/index-fr.html

Propriétés : 
#label
#description
#aboutPage : Article, FB, Twitter par exemple
#homePage : HelloAsso
#startDate
#endDate

**Relations :**
hasInterest / interestOf : Par exemple SemApps (Projet) ou interopérabilité (Thema)
deliveredBy / delivers : SemApps (Projet) 
localizedBy : (Place) Exemple Grands Voisins, mais il faut avoir le concept de lieu .. 

=> Je suis surpris qu'on ait pas les relations "Organisé par" / "Participe à" dans cette version de l'ontologie ... Ca diminue l'intérêt ..

**Comment by srosset81** [comment]
Merci !

> => Je suis surpris qu'on ait pas les relations "Organisé par" / "Participe à" dans cette version de l'ontologie ... Ca diminue l'intérêt ..

Pour "Participe à" on a `involves`, j'ai utilisé ça pour les projets.

**Comment by srosset81** [comment]
C'est fait 
https://archipel.assemblee-virtuelle.org/#/Event

**Comment by GuillaumeAV** [comment]
Trop bien !!
