### ISSUE TITLE
Les liens Intérêts & Compétences ne sont pas cliquables

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#370]
Ils ne sont en fait pas cliquables ... Issue en lien avec #362

**Comment by srosset81** [comment]
Le problème avec intérêts et compétence, c'est que si on rend les liens cliquables, on aura une page toute blanche avec juste le titre.
Est-ce vraiment ce que l'on veut ?
Je pensais qu'on attendrait d'avoir la complétion DbPedia/Wikidata avant d'améliorer cet aspect...

**Comment by GuillaumeAV** [comment]
Oui, dans la v1 on avait avait une complétion sur dbpedia, dont on récupérait les contenus : on avait donc pas de page blanche, mais les définitions des thèmes & compétences ... 
Hâte à ce sujet qu'on attaque le sujet DBpedia / Wikidata / Interop / LOD !

**Comment by srosset81** [comment]
Je corrige le titre de l'issue. Les liens inverses fonctionnent, c'est juste qu'ils ne sont pas visibles.

**Comment by bouviermullerp** [comment]
@GuillaumeAV peut-on fermer cette issue ? les liens sont cliquables maintenant.

**Comment by GuillaumeAV** [comment]
Aaah super merci  !!
