### ISSUE TITLE
Faire une newsletter régulière sur les avancées de SemApps

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#374]
Je me dis qu'on serait mûr pour sortir tous les 2-3 mois une petite newsletter avec les avancées réalisées sur SemApps. Il me semble qu'il y a de la matière à partager, et pas mal de gens potentiellement intéressés 🤔

Ce pourrait même être inclus dans un potentiel "blog" présent sur le site web (Docusaurus gère ça facilement)

**Comment by ValentineMathieu** [comment]
@srosset81 yes je pense que c'est une très bonne idée ! Je me lance sur le sujet début octobre une fois mes missions pour les CDLT bouclées :) est-ce qu'il y a des CR actus semapps pour que je récupère déjà un bon nombre d'infos ?

**Comment by srosset81** [comment]
@ValentineMathieu Début octobre serait parfait pour l'envoi !
J'ai fait un premier jet ici https://github.com/assemblee-virtuelle/semapps/pull/391, il y a pas mal de cases à remplir mais les principales actus sont là.
Je me disais qu'on pourrait passer par http://tinyletter.com (aussi utilisé par SOLID) qui est gratuit jusqu'à 5000 inscrits je crois.

**Comment by bouviermullerp** [comment]
A Gabriel d'ajouter un ou 2 paragraphes avant envoie.

**Comment by ReX-AV-Gab** [comment]
Fait :)

**Comment by ValentineMathieu** [comment]
@srosset81 @ReX-AV-Gab J'aimerais envoyer la newsletter aujourd'hui, je finis juste d'apporter les dernières modifications à la [version en anglais](https://pad.lescommuns.org/JyhTMTeYSjuU0-5bXghO_A) que j'ai proposé :) Est-elle bien ready ? il me semble, mais elle est notée "not ready" sur la pull request donc je pose la question quand même !

**Comment by srosset81** [comment]
@ValentineMathieu Ca a l'air tout bon ! J'ai mis la PR en ready.
Du coup tu mets l'anglais sur la PR (pour le docusaurus), et tu envoies en français ?

**Comment by ValentineMathieu** [comment]
@srosset81 Anglais ajouté à la PR :) je peux la merge ? Yes je pensais l'envoyer en francais comme demandé, peut être je peux donner un lien vers le PAD de la version anglaise pour les intéressés ? ou la faire suivre directement derrière la version française (risque que ce soit un peu long), qu'en penses-tu ? Sinon j'ai bien demandé à Guillaume, je me réfère à la synthèse du tableau AV membres et sympathisants pour l'envoi, c'est ok ?

**Comment by srosset81** [comment]
> Anglais ajouté à la PR :) je peux la merge ?

Tu peux supprimer le français ? Le site est 100% en anglais pour le moment.
Lorsqu'on aura une version française, on pourra retrouver le texte et le mettre.

> Yes je pensais l'envoyer en francais comme demandé, peut être je peux donner un lien vers le PAD de la version anglaise pour les intéressés ? 

:+1: 

> Sinon j'ai bien demandé à Guillaume, je me réfère à la synthèse du tableau AV membres et sympathisants pour l'envoi, c'est ok ?

Si Guillaume est OK ça me va, je ne connais pas les fichiers de l'AV.
S'assurer qu'il y a bien les personnes qui ont participé aux meetups SemApps.

**Comment by ValentineMathieu** [comment]
J'ai supprimé le français :) J'ai copié le texte sur mon PAD au cas où, mais sinon j'imagine que vous en avez une copie quelque part. Je prépare l'envoi, et je redemande confirmation à Guillaume pour les participants du meetup !

**Comment by ValentineMathieu** [comment]
@srosset81 Tout est bon au niveau de la liste des contributeurs/sympathisants/CA (+ participants aux meetup), j'ai bien tout inscris sur Tinyletter, configuré la newsletter, et envoyé. Cependant, en vérifiant auprès de Guillaume ce matin, j'ai l'impression que l'envoi ne s'est pas effectué. J'ai donc contacté Tiny Letter Support pour voir avec eux quel était le problème, car je me suis renseigné et je n'en vois aucun. N'hésite pas à me dire si tu reçois la newsletter. Merci beaucoup pour tes retours !

**Comment by ValentineMathieu** [comment]
@assemblee-virtuelle/semapps **J'ai besoin de vos avis** : comme vous avez pu le voir dans le dernier post que j'ai publié sur Element, je voudrais utiliser MailPoet, outil déjà utilisé par l'AV, pour envoyer notre NL. Cependant, la liste des abonnés à la NL de l'AV (800) ont choisi de s'abonner à la NL de l'AV et pas à celle de SemApps (même si c'est lié). 
J'en ai parlé avec @bouviermullerp, qui m'a suggéré d'ajouter un lien vers une inscription à la NL de SemApps, dans la NL de l'AV qui va être envoyée. Est-ce que cela vous semble pertinent ? Pour un soucis de choix/consentement je trouve que oui (car j'utiliserais la partie synthèse du tableau AV membres et sympathisants sinon) mais je suis ouverte à vos propositions :) 
Merci d'avance !

**Comment by srosset81** [comment]
Je pense qu'il faudrait quand même inscrire "de force" les gens qui ont manifesté un intérêt pour SemApps, soit en participant à un meetup, soit en contribuant, soit en étant lié d'une manière ou d'une autre au projet. J'imagine que la sélection n'est pas facile. Mais si on part de 0 avec que des inscriptions volontaires, on risque d'envoyer la première newsletter à 10 personne ;-P

**Comment by ValentineMathieu** [comment]
> Je pense qu'il faudrait quand même inscrire "de force" les gens qui ont manifesté un intérêt pour SemApps, soit en participant à un meetup, soit en contribuant, soit en étant lié d'une manière ou d'une autre au projet. J'imagine que la sélection n'est pas facile. Mais si on part de 0 avec que des inscriptions volontaires, on risque d'envoyer la première newsletter à 10 personne ;-P

pas faux !

**Comment by J9rem** [comment]
Sauf que pour rester en conformité avec le RGPD, nous ne pouvons pas inscrire de force des gens qui n'ont pas explicitement exprimé leur envie d'être sur cette liste de diffusion.

Au moins, est-ce que @ValentineMathieu tu peux trouver un moyen de leur envoyer un lien de validation d'inscription ? S'ils ne font rien, ils ne sont pas inscrits.
S'ils cliquent sur le lien, ils sont inscrits et consentent automatiquement à être sur la liste.

Il y a ça sur la framaliste (SYMPA). C'est super pratique et ça reste compatible RGPD

**Comment by J9rem** [comment]
J'ai fait ça pour une liste de personnes intéressées par la transition à Lorient.
En un week-end, plus de 70 personnes ont cliqué sur le lien.

**Comment by ValentineMathieu** [comment]
@J9rem oui c'est ce que je me disais :/ 
Cela peut être une bonne idée, si j'ai bien compris il suffirait de créer une framaliste avec tout le tableau des contributeurs et sympathisants de semapps, et cela va leur envoyer un mail leur permettant d'accepter ou non de faire partie de cette liste d'envoi de la NL ? Parce que MailPoet n'a pas de fonction de la sorte, un mail de confirmation s'envoie une fois l'inscription faite à la NL

**Comment by J9rem** [comment]
Attention framaliste est surchargé, peut-être installé un serveur SYMPA chez nous ?
mais en termes de passage des filtres antispam mailpoet et autres sont plus robustes

**Comment by ValentineMathieu** [comment]
@J9rem je n'ai pas tellement compris haha, on pourrait en parler en privé ? ou quelqu'un de compétent dans ce domaine pourrait réagir ?

**Comment by ValentineMathieu** [comment]
Grâce à l'aide de @J9rem je vais tester l'utilisation d'une framaliste pour permettre aux contributeurs/sympathisants de nous autoriser ou non à recevoir la NL SemApps, que j'enverrai probablement à l'aide de Mailpoet, je vous tiens au courant des avancées :) N'hésitez pas à commenter si vous avez des suggestions et autres avis à partager !
