### ISSUE TITLE
Tester Traefik

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#389]
Tester [Traefik](https://containo.us/traefik/) comme solution pour remplacer la combinaison Nginx/Certbot pour les déploiements en prod.

@nikoPLP tu connais ce logiciel ? Il a l'air pas mal !

**Comment by simonLouvet** [comment]
Testé et approuvé @srosset81 !

config plus simple que avec Nginx. Pas de manip autre que bien renseigner le docker-compose. Renouvellement automatique de certificat https.

exemple : https://gitlab.com/fluidlog/cartofabmob-server/-/blob/master/docker-compose-prod.yaml

**Comment by srosset81** [comment]
Excellent !
