### ISSUE TITLE
Obtenir un prêt bancaire

### ISSUE THREAD

**Issue by ReX-AV-Gab** [assemblee-virtuelle/semapps#392]
**Projet :** obtenir un prêt bancaire en faisant valoir le règlement à venir de la facture sur justificatifs des CdlT Grand Est. Facture d’un montant de 97.155 € (commun mobilisé : SemApps).

**Finalité :** être en mesure de faire face aux prochaines rétributions des membres de l’équipe

**Cadre :** Garantir des conditions matérielles permettant la contribution des contributeurs 

**Prochaine action :** Contacter l’interlocuteur concerné à l’AV pour présenter ce projet, obtenir des éléments et savoir qui fait quoi

Mathieu (comptabilité AV) en a été informé.

**Comment by GuillaumeAV** [comment]
Il est possible qu'on puisse éviter le prêt bancaire grâce au financement ANCT, réponse dans les prochains jours !

**Comment by srosset81** [comment]
Où est-ce que ça en est ? On peut fermer cette issue @GuillaumeAV ?

**Comment by GuillaumeAV** [comment]
Oui, je la ferme, c'est( stand-by avec grand est la ...
