### ISSUE TITLE
Définir un concept de référence

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#393]
**Prérequis** : Je suis utilisateur de la plateforme A (par exemple CdlT Grand-Est) sur laquelle j'ai créé un profil.

Je souhaite me créer une identité sur la plateforme B (par exemple Passerelle Normandie). Je peux indiquer - à la création de mon profil - que mon identité référence est celle de plateforme CdlT.

**Questions** : Comment respecter la vie privée ? Est-ce que je doit être connecté à la fois à la plateforme A et la plateforme B pour associer mes 2 profils ?

**Comment by srosset81** [comment]
Will be possible with Pods.
