### ISSUE TITLE
Visualiser les données en calendrier

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#397]
**Description**
Certains enregistrements ont des dates de début et de fin (des évènements principalement). On peut les afficher sous forme de calendrier.

**Implémentation**
- Créer un composant React qui utilise la librairie [React Big Calendar](http://jquense.github.io/react-big-calendar/) ou autre pour afficher une liste via un itérateur React-Admin ([voir example ici](https://marmelab.com/react-admin/List.html#using-a-custom-iterator))
- Passer en paramètre du composant React une fonction qui prend une ressource et retourne les données nécessaires: label, date de début, date de fin, URI (pour le lien)

**Estimation du temps de travail pour un développeur intermédiaire**
- @srosset81 & @simonLouvet: 4 JH

**Comment by GuillaumeAV** [comment]
C'est génial !!! J'ai hâte !!!

**Comment by bouviermullerp** [comment]
J'étais un peu précurseur alors en créant l'issue #3 l'année dernière au tout début du projet :D 
En tout cas, plusieurs clients vont avoir besoin de cette vue, passerelle normandie et CdlT à minima.

**Comment by srosset81** [comment]
Suite à la discussion de ce jour, on a décidé qu'il serait préférable d'utiliser un composant gratuit comme [React Big Calendar](http://jquense.github.io/react-big-calendar/examples/) pour éviter de bloquer des projets commerciaux avec la license de 500$ de [React Scheduler](https://devexpress.github.io/devextreme-reactive/react/scheduler/).

@simonLouvet va regarder s'il retrouve son benchmarks avec les solutions existantes.

Le problème principal que je revois maintenant avec React Big Calendar, c'est qu'on doit des [variables SASS](https://github.com/jquense/react-big-calendar#custom-styling) pour modifier le thème, ce qui serait compliqué à intégrer dans le code existant (c'est nécessaire même juste pour modifier la couleur par défaut). Si Simon trouve une solution avec une modification plus facile du thème, ce serait idéal.

**Comment by srosset81** [comment]
J'ai mis à jour la description du chantier, y compris l'estimation faite ce jour.

**Comment by srosset81** [comment]
J'ai noté que React-Admin entreprise edition utilise ce composant:
https://fullcalendar.io/docs/react
Ca a l'air de bien s'intégrer dans le design:
https://marmelab.com/ra-enterprise/modules/ra-calendar

**Comment by simonLouvet** [comment]
Les fonctions les plus intéressante sont payante mais c'est la lib de référence
