### ISSUE TITLE
Evaluer la faisabilité du projet Humus

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#398]
- [Voici la maquette](https://xd.adobe.com/view/9b62f4c7-8774-4e85-8d94-fb9f0ee35c42-ce31/screen/fedb3f3c-dfa6-4420-96ec-14a3ba096bdb)
- [Plus des éléments de présentation](https://drive.google.com/drive/folders/1BaOyShLCnt2X_6ArEHIC_2MpVxIQ6_7E?usp=sharing)
- Est-ce intéressant pour nous ? Pour eux ? 
- Le budget de 47 000 + 25 000 + 25 000 est-il suffisant ? 
- On propose un premier package à 10 ou 20k€ pour qu'ils testent le concept et puissent choisir quelle stratégie ensuite ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV est-ce que tu énergises cette carte ?

**Comment by GuillaumeAV** [comment]
Hellooo ! 

oui en effet, j'énergise cette carte, on a eu un appel la semaine dernière avec la responsable du projet, elle a bien compris le contexte qui est le notre : R&D, incertitude liée aux difficultés techniques et aux cofinancements (on est pas sur du Wordpress) 

Elle comprend également l'approche agile et sa pertinence dans ce contexte. 

Les 2 gros besoins sont la carte et le fil d'actus. Elle est par ailleurs prête à nous faire complètement confiance sur l'approche techno "parce que c'est vous qui avez la vision"... 

On partirait du coup sur une approche agile avec des sprints pour 37 000€ dans un premier temps .. 

Marie Lechevalier serait le PO : Elle est très cool, motivée, curieuse de nos technos et a l'air plutôt bonne ... 

[Voici le doc ou je prend des notes](https://docs.google.com/document/d/14r2hihgj3sMsCIx6eZ6Jk8OZ97ULgbPyWxMljO7Epak/edit?usp=sharing)

La suite au prochain épisode !

**Comment by bouviermullerp** [comment]
@GuillaumeAV à fermer ?

**Comment by GuillaumeAV** [comment]
C'est une bonne question, la responsable m'a recontacté il y a 2 semaines, pour un démarrage du projet en septembre ... Pour l'instant ils n'ont pas les sous cependant, je la ferme donc et la rouvrirai le cas échéant !
