### ISSUE TITLE
Visualiser les données en graph

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#4]
**Question originale de Pierre :**
"Il est possible de visualiser tous les enregistrements sous la forme d'un graph (comme Flodio ?)"

**Description**
L'objectif est de fournir une vue en graph en réseau, soit pour l'ensemble d'un Semapps, soit pour une donnée précise. Mais contrairement à l'application CartoSemapps actuelle, celle-là devra être intégrée à Semapps en tant que service optionnel.

**Comment**
Par l'intégration du code de Flodio, en le rendant compatible REACT (sans JQuery).

**Issues liées**
- [x] Rendre compatible la carto en réseau avec REACT #597 

**Estimation du temps de travail en JH (profil intermédiaire)**
@simonLouvet : 1/2 (proto)
@fluidlog : 5

**Comment by fluidlog** [comment]
Simon a commencé à tester l'intégration de D3 dans react admin.
J'ai donc commencé une doc pour y mettre les explications de ce qu'il a fait, et mon analyse pour l'estimation
https://pad.lescommuns.org/SrBR_GvSQqK-cav9qM_Ebw#
Je pense terminer l'estimation avant la fin du mois de janvier.
