### ISSUE TITLE
Créer un logo SemApps

### ISSUE THREAD

**Issue by ValentineMathieu** [assemblee-virtuelle/semapps#401]
Point discuté avec Sebastien
Le travail sera entrepris dès demain en collaboration avec @anika-d !
N'hésitez pas si vous avez commentaires :)

**Comment by GuillaumeAV** [comment]
Génial !!! 

Quelques idées peut être .. (mais que ca ne vous bride pas !)
Des noeuds, des liens, des hexagones
Ou peut-être, idée de l'instant : Le [super schéma de la stratégie AV](https://www.youtube.com/watch?v=44jUwTHAeU8&t=13s) sous la forme du logo opensource en mode simplifié & stylisé ? C'est peut être débile hein ;)

**Comment by ValentineMathieu** [comment]
@GuillaumeAV Ce n'est absolument pas débile Guillaume, chaque remarque est bonne à prendre ! Ca nous a donné des pistes dans la conception du logo, on a déjà pas mal de versions différentes hâte de vous les proposer :D

**Comment by anika-d** [comment]
Hello! Avec @ValentineMathieu on vous propose une première version du logo [ici](https://www.canva.com/design/DAEKwpDHa0I/2EKD_wNX6l8Bn9M3543Iyg/view?utm_content=DAEKwpDHa0I&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink). 

- Vous verrez il y a plusieurs versions avec juste le S de SemApps

- la couleur évidemment peut évoluer car on ne savait pas trop quelle couleur prendre 

- à la fin on a plusieurs versions avec le nom complet intégré au logo. 

On attend vos retours sur ce qui vous plait/déplait !

**Comment by ValentineMathieu** [comment]
PS : On a eu une autre idée de logo (2 dernières pages) mais on a pas encore fini, on a besoin de photoshop pour continuer donc on vous préviendra quand ce sera terminé

**Comment by simonLouvet** [comment]
je ne trouve pas le lien vers le canvas

**Comment by srosset81** [comment]
@simonLouvet https://www.canva.com/design/DAEKwpDHa0I/2EKD_wNX6l8Bn9M3543Iyg/view?utm_content=DAEKwpDHa0I&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by simonLouvet** [comment]
Est ce que les travaux précédents de Benoît ferchaud et @GuillaumeAV ont été considérés ?

**Comment by bouviermullerp** [comment]
Compte rendu d'un appel avec @ValentineMathieu - elle va appeler @BenoitFerchaud avec @anika-d pour énergiser cette carte (dans la semaine)

**Comment by BenoitFerchaud** [comment]
Je suis un peu surpris que les journées de travail fournies par moi-même il y a quelques mois soit à peine évoquée, et seulement au 8e message. Je rappelle que j'avais soumis ce travail en disant clairement que s'il n'était pas respecté je ne ferai plus de bénévolat en design. Le lien vers le travail ( et non les "idées" ) fourni aurait dû se trouver dès le premier message de ce ticket. Ainsi que le lien vers le canal dédié dont vous connaissiez bien l'existence ( notamment Pierre qui avait été invité à le suivre ) : https://matrix.to/#/!kIEzmyjCVHqKMoLNUf:matrix.org?via=matrix.org&via=matrix.virtual-assembly.org
https://www.figma.com/file/RYGi4GaRTuFRYs0MstHOnQ/Planche-Id%C3%A9es-Logo-SemApps?node-id=0%3A1

Je trouve cette attitude dommageable, pour moi, ainsi que pour Valentine et Anika qui ont compris qu'il fallait créer un logo au lieu de finaliser celui retenu.

**Comment by bouviermullerp** [comment]
Salut @BenoitFerchaud, 
Je prends ma part de responsabilité, j'ai appris que Valentine allait travailler sur le logo, j'ai pensé qu'il fallait que je lui parle de ton taff et quand on s'est appelé, on a parlé de tellement de sujets que c'est passé à la trappe, je m'en excuse.
Ca aurait été cool que Valentine et Anika partent de ton travail, sauf qu'elles ne l'ont pas fait, elles sont arrivés à un résultat que je trouve assez chouette et du coup je me dit que c'était pas plus mal, que ça remet de l'énergie dans un chantier qui n'en avait plus - et c'est probablement la meilleur de respecter un travail.

(je crois aussi que c'est mieux de laisser à Valentine et Anika le soin d'exprimer ce qui est dommageable pour elle et de ne pas le supposer à leur place)

**Comment by BenoitFerchaud** [comment]
C'est aussi de ma faute @bouviermullerp , car je crois que tu m'avais dit de créer le ticket et que je t'avais demandé de le faire pour moi. Je ne peux pas t'en vouloir de l'avoir oublié. On va certainement se voir bientôt avec Valentine et Anika, je n'ai pas encore regardé ce qui a été fait mais je suis évidemment d'avis d'essayer d'en retirer quelque chose dans la mesure du possible.

**Comment by ValentineMathieu** [comment]
Lien pour le [PAD charte graphique](https://pad.lescommuns.org/FVoMMJ89TPKYqC8FkXza5w)

**Comment by ValentineMathieu** [comment]
Je ferme cette issue, étant donné qu'elle est reprise dans l'issue #410 charte graphique ! :)
