### ISSUE TITLE
Les liens inverses ne semblent pas implémentés avec les projets ?

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#403]
Exemple avec SemApps & Gabriel : 

- [SemApps](https://archipel.assemblee-virtuelle.org/#/Project/https%3A%2F%2Fdata.virtual-assembly.org%2Fprojects%2Fsemapps/show)
- [Gabriel](https://archipel.assemblee-virtuelle.org/#/User/https%3A%2F%2Fdata.virtual-assembly.org%2Fpersons%2Fgabriel_henry/show)

**Comment by srosset81** [comment]
Gabriel est mis comme "Responsable" (`pair:hasResponsible`) de SemApps.
Sur la page de Gabriel, on affiche les projets dont il est "Participant" (`pair:memberOf`) et non pas Responsable.
C'est donc normal qu'il n'y ait pas de lien inverse dans ce cas. Il faudrait ajouter une rubrique sur la page des utilisateurs concernant les projets dont la personne est responsable.
