### ISSUE TITLE
Modifier l'architecture de la page d'accueil du site SemApps

### ISSUE THREAD

**Issue by ValentineMathieu** [assemblee-virtuelle/semapps#405]
Sous-issue créée à partir de l'issue #325. 
Idée serait de proposer un modèle pour une nouvelle page d'accueil à partir de Canvas (avec la participation de @anika-d si possible) qui aurait pour but d'être traduite en Javascript par la suite.

Composantes proposées pour cette page : 
- Intégrer le nouveau logo SemApps (après validation de l'équipe) ==> voir issue #401 
- Intégrer l'écosystème de contributeurs/clients de SemApps (Grands Voisins, Assemblée Virtuelle, CDLT, Reconnexion, Oseons, DFC...) en nuage de point par exemple
- Intégrer la section "About" en dessous, plutôt sous forme de texte 
- Potentiellement proposer 1 ou 2 schémas représentatifs du projet logiciel (ex : réseau distribué comme dans le PPT, ou stratégie de déploiement)
- Laisser le bloc avec Images/mots-clés/détail mais proposer peut être de nouvelles images

**Comment by ValentineMathieu** [comment]
Hello @assemblee-virtuelle/semapps ! Avec @anika-d on a bien avancé sur cette maquette de page d'accueil ! On l'a faite dans les couleurs de notre logo en attendant d'avoir un échange téléphonique avec Benoit, mais bien évidemment tout ceci est modifiable ! :) n'hésitez pas à nous apporter vos commentaires et idées, même si ce n'est pas encore fini à 100%. Je vous partage le [lien canva](https://www.canva.com/design/DAELDIilV7g/-uIE5dwXaibKQblx4cNwXQ/view?utm_content=DAELDIilV7g&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton), et pour ceux étant membres de l'AV sur cette plateforme, il est accessible dans les créations de l'asso

**Comment by srosset81** [comment]
Super top ! Beau travail :-)

**Comment by Alice-Po** [comment]
@ValentineMathieu Est ce qu'on a une charte graphique ?

**Comment by ValentineMathieu** [comment]
@Alice-Po On est sur le coup avec @BenoitFerchaud et @anika-d :)

**Comment by ValentineMathieu** [comment]
Étant donné que cette issue ne peut plus avancer tant que la charte graphique n'est pas finie, je la replace dans le backlog :)
