### ISSUE TITLE
Fusionner les pages Team et Governance du site web

### ISSUE THREAD

**Issue by ValentineMathieu** [assemblee-virtuelle/semapps#406]
Sous Issue de l'Issue #325 
Idée serait de créer du lien entre ces deux pages, de les rendre plus graphiques/visuelles, et de simplifier/réorganiser la page Governance qui est trop longue. La modélisation de ces idées se fera également par Canvas et sera partagée à l'ensemble de l'équipe pour être soumise à des modifications, et enfin être traduite en Javascript (le Markdown ne permettant pas de mettre en place ces idées).

Page Team : 
- Réorganiser l'équipe sous forme d'organigramme (design à penser en terme de gouvernance partagée, peut être code couleur pour grouper les membres par compétences..)
- Ajouter Valentine en tant que contributrice
- Exemples d'idées pour créer cette organigramme : photo de chaque contributeur, son rôle principal dans l'équipe, ses compétences, lien vers son/ses rôles de référent dans la gouvernance
- ajouter ID Riot

Page Governance : 
- réorganiser cette page en sections avec l'intitulé de la mission (design encore à imaginer, peut être sous forme de cases ou autre..) 
- On cliquerait sur une mission ce qui nous donnerait accès aux détails (purpose & responsibilities + lien vers page Team personne élue pour cette mission )

**Comment by ValentineMathieu** [comment]
@assemblee-virtuelle/semapps J'ai travaillé sur des exemples de pages team et governance (c'est toujours fait avec notre logo et ses couleurs mais cela peut changer), ce n'est pas fini, j'attends de recevoir les apports d'Anika, mais je vous partage [le lien](https://www.canva.com/design/DAELOKkzMJ0/WPK0u2SmizYLxkqcKNrynA/view?utm_content=DAELOKkzMJ0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) si vous voulez y jeter un coup d'oeil :) Sinon @anika-d de son côté a finalisé les dernières versions du logo que nous proposions, en attendant le zoom avec Benoit.

**Comment by srosset81** [comment]
@ValentineMathieu Les notions de "Scrum master" et de "Product owner" ne sont plus trop d'actualités, ce qui compte maintenant ce sont plutôt les [rôles](https://semapps.org/docs/governance/organisation%20and%20role).

J'aime bien la présentation en cercles, mais je crains que ce soit difficile à transformer en HTML, surtout du HTML qui s'adapte aux différentes tailles d'écrans (paramètre malheureusement incontournable aujourd'hui).

**Comment by ValentineMathieu** [comment]
@srosset81 merci pour ton retour ! Je vais re-proposer une disposition différente, peut être que je pourrais essayer de fusionner les pages team et governance si cette dernière n'est plus tellement d'actualité ? Ok je vais tenter de simplifier tout cela :)

**Comment by srosset81** [comment]
Oui je pense qu'une fusion aurait du sens !

**Comment by ValentineMathieu** [comment]
@assemblee-virtuelle/semapps Hello tout le monde ! J'ai apporté pas mal de modifications aux pages team et governance, que j'ai décidé de fusionner suite aux conseils de Sébastien ! Je me suis permise de reformuler certaines phrases (surtout dans la présentation de l'organisation des rôles SemApps), dites moi ce que vous en pensez :) Et @srosset81 j'ai essayé de faire plus simple que les cercles qu'on avait proposé au début avec Anika, dis moi si cela te convient. Merci !

**Comment by ValentineMathieu** [comment]
@srosset81 est-ce que j'ai besoin de détailler chaque rôle comme je l'ai fais pour l'onboarding, ou un modèle suffit ?

**Comment by srosset81** [comment]
Salut @ValentineMathieu 
J'aime bien, notamment la séparation en trois équipes.
Je reste quand même un peu inquiet pour l'intégration dans le site web. Je ne sais pas si j'aurai beaucoup de temps à consacrer à ça, et ça va être pas mal de boulot. Est-ce qu'il y a d'autres personnes qui ont des capacités en intégration React ?

**Comment by simonLouvet** [comment]
@ValentineMathieu j'aime boen le découpage que tu as fait dans les 3 "méta-role" et je pense que tu peux t'en servir pour structurer plus globalement ta pensée/présentation. Le dernier slide reprends des termes que nous n’utilisons pas volontairement. Par contre tu mets en évidence les technicals advisors et nous n'avons pas identifié ce rôle et je pense que cela manque. Le probleme c'est que nous ne demandons à pas à ces personnes d'être actives et de s'organiser car nous sollicitons au besoin en fonction des problématique. Il sont également censé "valider" nos choix technologique ce qu n'est pas vraiment encore le cas.

**Comment by srosset81** [comment]
Pour le site de l'AV, @Alice-Po a suggéré ce site comme inspiration: https://www.rust-lang.org/governance

**Comment by ValentineMathieu** [comment]
> @ValentineMathieu j'aime boen le découpage que tu as fait dans les 3 "méta-role" et je pense que tu peux t'en servir pour structurer plus globalement ta pensée/présentation. Le dernier slide reprends des termes que nous n’utilisons pas volontairement. Par contre tu mets en évidence les technicals advisors et nous n'avons pas identifié ce rôle et je pense que cela manque. Le probleme c'est que nous ne demandons à pas à ces personnes d'être actives et de s'organiser car nous sollicitons au besoin en fonction des problématique. Il sont également censé "valider" nos choix technologique ce qu n'est pas vraiment encore le cas.

Merci pour ton retour @simonLouvet ! En effet, j'ai pensé que c'était plus simple de diviser un peu la team en "meta-role" étant donné que mon travail était de mettre en lumière votre gouvernance, et non pas les cercles qui étaient définis à l'origine. La dernière slide n'est plus d'actualité, je l'avais laissé à la fin du canva pour m'inspirer ;)
N'hésitez pas à me dire si vous avez une meilleure idée de division des rôles

**Comment by ValentineMathieu** [comment]
Étant donné que cette issue ne peut plus avancer tant que la charte graphique n'est pas finie, je la replace dans le backlog :)

**Comment by srosset81** [comment]
Comme dit vendredi dernier, je me propose de reprendre cette issue en m'inspirant de ce qui avait été proposé par @anika-d  et @ValentineMathieu, mais en simplifiant afin que ce soit simple à mettre en page (HTML basique, adapté aux mobiles).
Il me semble qu'il y a une certaine urgence à améliorer ces pages, et qu'on ne peut pas attendre la charte graphique (il faudra de toute façon qu'on revoie tout le site une fois cette charte graphique adoptée)

**Comment by fluidlog** [comment]
Suite à notre discussion avec Seb pour fusionner les onglets About / Team & Governance sur le site [Semapps.org](http://semapps.org/), j'ai créé un PAD pour que vous puissiez suivre.
Merci de vérifier / ajouter des choses vous concernant au cas où j'en aurais oublié. Je vous tiendrai au courant lorsque je publierai le contenu (avant la fin de la semaine normalement)
https://pad.lescommuns.org/Lq4zHk8hQZeel7SzlsZw_A
