### ISSUE TITLE
Informer les utilisateurs coographie

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#407]
Envoyer un email à tous les utilisateurs/personnes de coographie qui verront leur profil supprimé afin de respecter le RGPD (ces personnes avaient été créées suite au meetup)
lié à #385

**Comment by srosset81** [comment]
@bouviermullerp C'est possible de le faire maintenant !

**Comment by srosset81** [comment]
@bouviermullerp Ping ?

**Comment by bouviermullerp** [comment]
J'embarque cette information dans la prochaine newsletter @srosset81 lié à #528
