### ISSUE TITLE
Faciliter une réunion UX Design

### ISSUE THREAD

**Issue by Rouffi** [assemblee-virtuelle/semapps#408]
Présentation de la vision et compréhension de Semapps d'un point de vue Design d’expérience utilisateur sous la forme de Slides lors d'une première réunion d'1h.

Ordre du jour proposé :
- Présentation des **ressources** identifiées (technique, documentation, graphique, humaine, ...)
- Présentation des **Challenges** pour les utilisateurs (architecture d'information visuelle, gestion des données, accessibilité, ...)
- Présentation d'une méthodologie orientée Design Thinking (persona, journey map, Wireframe, Design pattern, ...)
- Discussion et partage
- Définition et priorisation des prochaines actions

Objectif long terme :
- Documentation et mise en avant des cas d'usages
- Apporter de nouvelles briques d'un point de vue ergonomie pour rendre Semapps plus 'sexy' aux non techniciens

**Comment by ReX-AV-Gab** [comment]
Pour info, il y a une réflexion en cours sur le concept de chantier numérique permettant notamment aux contributeurs potentiels de mettre le pied à l'étrier rapidement et de façon relativement autonome sur un périmètre maîtrisé.

**Comment by srosset81** [comment]
Hâte de voir cette présentation ! Un petit framadate ? :-)

**Comment by GuillaumeAV** [comment]
Hâte aussi de voir cette présentation, désolé de n'avoir pas pu être là au dernier sprint ou tu pensais présenter tes premiers travaux @Rouffi  !

**Comment by Rouffi** [comment]
Voici un framadate https://framadate.org/dTBCR4l83okMySH2

**Comment by srosset81** [comment]
Hey @Rouffi  j'ai l'impression que les dates sont passées ;-)
On propose lundi 7 à 14h pour voir si les gens sont toujours disponibles ?
