### ISSUE TITLE
ajout la possibilité de fournir une base_url au sparql endpoint

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#409]
Le service ldp permet de lui fournir un baseUrl ce qui permet notamment que le servuer ldp reponde à un path de type http://domaine/middleware/container.
Le service saprql_endpoint ne le permet pas.

contournement possible : https://github.com/data-players/passerelle_normandie/blob/main/server/services/api.service.js

exemple ci dessous du contournement
SEMAPPS_HOME_URL = http://domaine/middleware/
sparqlRoutes[0].path finale = http://domaine/middleware/sparql.
``` javascript
    const sparqlRoutes = await this.broker.call('sparqlEndpoint.getApiRoutes');
    let path=sparqlRoutes[0].path;
    if (path.indexOf('/')===0){
      path= path.substring(1);
    }
    sparqlRoutes[0].path = new URL(process.env.SEMAPPS_HOME_URL).pathname +path;
```

**Comment by srosset81** [comment]
Fixed by https://github.com/assemblee-virtuelle/semapps/issues/409
