### ISSUE TITLE
Ajout du Code Social au site vitrine

### ISSUE THREAD

**Issue by ValentineMathieu** [assemblee-virtuelle/semapps#416]
Sur les conseils de Pierre, je pensais donner l'accès au code social de l'AV sur le site vitrine de SemApps, je pense l'ajouter sur [les maquettes](https://www.canva.com/design/DAELDIilV7g/share/preview?token=EZYIyhruCv3hRjO_-aUC6g&role=EDITOR&utm_content=DAELDIilV7g&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) des pages de présentation "About SemApps". 
Cependant, j'ai cru comprendre que ce code social était en refonte en ce moment ? Est-ce que je partage donc [cette version](https://www.virtual-assembly.org/wp-content/uploads/2018/02/Code-social-AV-2018-02-01-Version-approuv%C3%A9e-lors-de-lAG-du-2018-02-01.pdf) ou une nouvelle est plus d'actualité ? 

Dites moi ce que vous en pensez @assemblee-virtuelle/semapps :)

**Comment by simonLouvet** [comment]
je pense qu'on peut le publier en précisant qu'il est en cours de refonte

**Comment by ValentineMathieu** [comment]
Étant donné que cette issue ne peut plus avancer tant que la charte graphique n'est pas finie, je la replace dans le backlog :)
