### ISSUE TITLE
Ajouter un WebID au package sparql-endpoint

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#417]

**Comment by simonLouvet** [comment]
peux tu expliquer @srosset81 , du mal a comprendre la proposition.

**Comment by srosset81** [comment]
Contrairement au package `ldp`, le package `sparql-endpoint` ne passe pas le webID de l'utilisateur loggé à Fuseki.

**Comment by simonLouvet** [comment]
ok j'ai compris merci. Je suppose que c'est pour pouvoir appliquer des ACL à une requête SPARQL.

**Comment by srosset81** [comment]
Vu aujourd'hui avec Niko, pas nécessaire car c'est passé via le contexte.
