### ISSUE TITLE
Permettre d'insérer des triples dans un graph donné

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#418]
Ajouter un paramètre `graph` à l'action `triplestore.insert` qui permettrait d'insérer des triples dans un graph donné:

Selon les [specs](https://www.w3.org/TR/sparql11-update/#insertData), la requête SPARQL ressemble à ça:

```sparql
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ns: <http://example.org/ns#>
INSERT DATA
{ GRAPH <http://example/bookStore> { <http://example/book1>  ns:price  42 } }
```

**Comment by simonLouvet** [comment]
++

cela va de pair avec le fait de pouvoir spécifier un graph dans l'api sparql ou que l'api sparql requete tous les graphs.

**Comment by srosset81** [comment]
Je ne crois pas que "requêter tous les graph" est possible avec SPARQL. Il faut impérativement connaître le nom du graph pour pouvoir le requêter.

**Comment by simonLouvet** [comment]
Oui mais je parle de l'API http

**Comment by simonLouvet** [comment]
@srosset81 je precise étant donné que tu est confus :-).
j'aimerai que le enpoint sparql de semapps  puisse exécuter la requête souhaité sur tous les graph OU que le graph soit précisé de manière simple (en paramètre l'url par ex?).
Je pense qu'il faudrait également qu'un container LDP puisse être configuré pour être "bganché" sur un graph.
Je me pose aussi la question de la relation entre dataset et graph dans fueki. Je crois comprendre que des graph différents ont chacun leur dataset ais pas sur de moi.

**Comment by simonLouvet** [comment]
on en discute vendredi prochain (20/11) ?

**Comment by srosset81** [comment]
Les datasets et les graphs sont deux choses indépendantes, chaque dataset pouvant avoir plusieurs graphs. J'ai l'impression que l'on mélange les choses-là...
Quant au package `sparql-endpoint`, je ne vois pas l'intérêt de pouvoir préciser le graph en paramètre, puisqu'on peut faire ça très bien à l'intérieur de la requête SPARQL elle-même. Ce que tu proposes reviendrait à modifier la requête SPARQL envoyée au serveur, ce qui pourrait générer pas mal de bugs.

**Comment by simonLouvet** [comment]
> Les datasets et les graphs sont deux choses indépendantes, chaque dataset pouvant avoir plusieurs graphs. J'ai l'impression que l'on mélange les choses-là...
> Quant au package `sparql-endpoint`, je ne vois pas l'intérêt de pouvoir préciser le graph en paramètre, puisqu'on peut faire ça très bien à l'intérieur de la requête SPARQL elle-même. Ce que tu proposes reviendrait à modifier la requête SPARQL envoyée au serveur, ce qui pourrait générer pas mal de bugs.

oui, on peut mettre plusieurs graph dans un dataset mais je n'en voie pas beaucoup l’intérêt. Mon besoin est de pouvoir isoler une parti de l'information pour pouvoir ajouter un jeux de triplet à un semapps sans perturber le dataset principale et pouvoir le requête depuis le API.

**Comment by srosset81** [comment]
Du coup ça n'a pas de lien avec cette issue, qui est liée à d'autres besoins...

**Comment by tfrancart** [comment]
> Je ne crois pas que "requêter tous les graph" est possible avec SPARQL. Il faut impérativement connaître le nom du graph pour pouvoir le requêter.

Si c'est possible, de 2 façons :
  - façon simple : le comportement par défaut de la plupart des triplestores est que quand aucun graph n'est explicitement donné dans la requête, la requête porte sur tous les graphes. Dans Fuseki c'est contrôlé par l'option `tdb2:unionDefaultGraph true`
  - plus exotique, il est possible de mettre l'identifiant du graphe en variable 

```
# Return all graphs that contain a foaf:Person
SELECT DISTINCT ?g
WHERE { GRAPH ?g { ?x a foaf:Person } }
```

**Comment by nikoPLP** [comment]
Pour les besoins des webacl, un graph contenant les ACLs est ajouté dans le dataset. Et l'option `unionDefaultGraph` n'est pas mise car nous utilisons les caracterisques d'isolation des graphs pour optimiser les requetes sur les ACLs.
En gros, et pour faire court, lorsque `unionDefaultGraph` est utilisé, ce sont tous les grpahs nommés qui sont joints et qui se comportent comme le graph par défaut lorsqu'on fait une requete sans spécifier sur quel graph on requete.
Il existe cependant toujours un vrai `defaultGraph` dans chaque dataset, et lorsqu'on utilise l'option `unionDefaultGraph`, le vrai `defaultGraph`devient masqué, et n'est alors plus accessible que par un raccourcis. Et il n'est pas inclus dans l'union dont nous parlons ci-dessus.
Bref, ca ne nous interesse pas du tout que les utilisateurs de semapps aient accès a l'union de tous les graphs nommés, car ça voudrait dire qu'ils auraient accès aussi au graph qui contient les ACLs. 
En plus, pour des raisons de performances, il n'est jamais bon de faire une requete sur l'ensemble des graphs, car elle est plus longue. Elle doit parcourir tous les graphs pour aboutir.
Enfin, pour persister un graph nommé dans Jena, il faut le dire dans le fichier de config du dataset. Sinon, le graph nommé est un graph en mémoire seulement.
Tout ceci complique beaucoup l'utilisation pratique des graphs nommés, et je ne la recommande pas, a priori.
Pour notre cas d'usage classique, tout se passe dans le `defaultGraph`, et il n'y a pas de graph nommé, à part celui des ACLs, qui est caché et inaccessible au utilisateur lamba. il faut passer par la web interface pour gagner accès à ce graph. 

il est deconseillé de le faire, car manipuler les ACLs directement en sparql est un peu cavalier, le format des nos WebACLs pourrait ne pas etre respecté, et nos APIs webacl du middleware pourraient disfonctionner. En aucun cas le moteur de sécurité des WebACL serait affecté, et aucun leak de donnée n'en résulterait. Mais les GUIs de modification des ACLs pourraient etre affectées.

Cependant, si un utilisateur est interessé par la fonctionalité des graph nommés, il est possible d'en ajouté dans le fichier de config du dataset. on peut choisir de protéger ce graph nommé par le mechanisme des ACL, ou non (tout depend de comment il est créé dans le fichier de config du dataset). Dans tous les cas, il ne faut pas utiliser l'option `unionDefaultGraph` car elle affecterait gravement les perfs.

Ca reste de la haute voltige... et pas mal de probleme. Donc mon avis c'est de se passer des graphs nommés.

En ce qui concerne cette issue, il me semble qu'elle est tres simple et concerne seulement l'action `triplestore.insert`. Je viens d'ajouter l'option dans cette action. L'issue sera donc fermée lorsque la PR sera acceptée.
