### ISSUE TITLE
Créer un service Moleculer pour gérer le fichier de context

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#424]
- Nom du service `ContextService` ?
- Nom du package `@semapps/context` ?

A inclure:
- Sortir le code d'ApiService
- Une action `getUrl` pour récupérer l'URL du fichier

Idéalement:
- Construire le fichier de context selon certains paramètres (notamment l'objet `ontologies`) et le mettre en cache. A faire peut-être plus tard ?

**Comment by simonLouvet** [comment]
++

**Comment by srosset81** [comment]
Fait dans le service jsonld
