### ISSUE TITLE
Proposer un container LDP racine

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#429]
Les [specs sur les webACL](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm) parlent de "containers racine" (_root containers_), c'est en lien avec des "users' accounts", donc on voit que c'est pensé plutôt en relation avec un serveur SOLID et un POD. 

Le document LDP Primer parle aussi de "root container", et le mets en relation avec un utilisateur:
https://www.w3.org/TR/ldp-primer/#docstore

Cependant, il pourrait être intéressant qu'à la base d'une instance SemApps (donc dans `/`), on liste tous les containers. 

Les containers seraient alors simplement indiqués avec le prédicat `ldp:contains`.

Cela permettrait à n'importe qui d'explorer le contenu de l'instance, ce qui n'est pas possible pour le moment (si on ne connait pas l'URL des containers, on ne peut rien faire).

**Comment by simonLouvet** [comment]
++
précision : si le sparql endpoint est activé, il est possible de connaitre les container par une requete sparql

**Comment by srosset81** [comment]
Proposition d'implémentation:
- Lorsqu'on crée un container via `ldp.container.create`, le persister automatiquement dans le container parent, si celui-ci existe. (Ou ajouter une option pour ça dans le service `ldp.container` si on veut pas que ce soit obligatoire)
- Si on veut avoir un container racine, il faut le spécifier dans le fichier `containers.js`.

**Comment by srosset81** [comment]
Question restante:
- Comment est-ce qu'on affiche les container enfants dans le container parent ? Est-ce qu'on indique seulement l'URL du container, avec le problème qu'on ne sait pas que c'est un sous-container sauf si on va l'explorer ? Si on déréférence le container enfant, ça risque de rendre la lecture difficile.

@scenaristeur tu sais comment c'est géré au niveau d'un pod SOLID ? Les dossiers/containers sont-ils marqués comme tels ou bien est-ce qu'il faut fetcher l'URL pour savoir que c'est un container ?

**Comment by simonLouvet** [comment]
@srosset81  ca me parait cohérent dans l’ensemble. Avant d'essayer de répondre aux question il y a un point que je ne suis pas sur d'avoir compris. Les Users seraient bien dans un container enfant?

**Comment by scenaristeur** [comment]
@srosset81 sur Solid, les containers sont définis de la sorte : exemple /testcontainer/ dans https://spoggy-test6.solidcommunity.net/public/
container vide  : 
```
@prefix : <#>.
@prefix tes: <>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix terms: <http://purl.org/dc/terms/>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.

tes:
    a ldp:BasicContainer, ldp:Container;
    terms:modified "2021-01-27T10:39:40Z"^^XML:dateTime;
    st:mtime 1611743980.686;
    st:size 4096.
```
![image](https://user-images.githubusercontent.com/4020744/105979919-86ec6e00-6094-11eb-95e8-adcd529909b1.png)

Le même container contenant un fichier bidule.txt
```
@prefix : <#>.
@prefix tes: <>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix terms: <http://purl.org/dc/terms/>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.
@prefix pl: <http://www.w3.org/ns/iana/media-types/text/plain#>.

tes:
    a ldp:BasicContainer, ldp:Container;
    terms:modified "2021-01-27T10:41:29Z"^^XML:dateTime;
    ldp:contains <bidule.txt>;
    st:mtime 1611744089.652;
    st:size 4096.
<bidule.txt>
    a pl:Resource, ldp:Resource;
    terms:modified "2021-01-27T10:41:29Z"^^XML:dateTime;
    st:mtime 1611744089.656;
    st:size 1.
```

--> definition d'un container :     a ldp:BasicContainer, ldp:Container; +  ldp:contains <bidule.txt>; (pour chaque ressource et container

Le même avec un sous dossier : 
```
@prefix : <#>.
@prefix tes: <>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix terms: <http://purl.org/dc/terms/>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix sou: <sousdossier/>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.
@prefix pl: <http://www.w3.org/ns/iana/media-types/text/plain#>.

tes:
    a ldp:BasicContainer, ldp:Container;
    terms:modified "2021-01-27T10:44:49Z"^^XML:dateTime;
    ldp:contains <bidule.txt>, sou:;
    st:mtime 1611744289.299;
    st:size 4096.
<bidule.txt>
    a pl:Resource, ldp:Resource;
    terms:modified "2021-01-27T10:41:29Z"^^XML:dateTime;
    st:mtime 1611744089.656;
    st:size 1.
sou:
    a ldp:BasicContainer, ldp:Container, ldp:Resource;
    terms:modified "2021-01-27T10:44:49Z"^^XML:dateTime;
    st:mtime 1611744289.439;
    st:size 4096.
```

lui même défini par 
```
@prefix : <#>.
@prefix sou: <>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix terms: <http://purl.org/dc/terms/>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.

sou:
    a ldp:BasicContainer, ldp:Container;
    terms:modified "2021-01-27T10:44:49Z"^^XML:dateTime;
    st:mtime 1611744289.439;
    st:size 4096.

```

**Comment by srosset81** [comment]
> @srosset81 ca me parait cohérent dans l’ensemble. Avant d'essayer de répondre aux question il y a un point que je ne suis pas sur d'avoir compris. Les Users seraient bien dans un container enfant?

Le dossier `/users` dans `pair-ldp-server` est déjà un container. Et oui, dans cette optique, il deviendrait un container enfant du container racine, si un tel container est défini.

**Comment by scenaristeur** [comment]
Pour les users, au vue des cas d'usages que j'envisage, je dirais oui, les users doivent être traités comme un container enfant de rootContainer accessible (à voir après pour les droits de read/write) afin de pouvoir être liés au ressources, comme par exemple le createur d'une ressource, des groupes d'utilisateurs affectés à une tache...

**Comment by srosset81** [comment]
Merci @scenaristeur.

Intéressant que le sous-container soit lui-même défini comme un `ldp:Resource` en plus de `ldp:BasicContainer, ldp:Container`, lorsqu'il est lu depuis le container parent, mais pas quand il est lu directement. J'imagine que c'est parce que, dans un container, on ne peut avoir que des ressources ?

En faisant un `GET` sur https://spoggy-test6.solidcommunity.net/public/testcontainer avec le header `Accept: application/ld+json`, j'obtiens ça:

```json
[
  {
    "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/",
    "http://purl.org/dc/terms/modified": [
      {
        "@value": "2021-01-27T10:54:00Z",
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
      }
    ],
    "@type": [
      "http://www.w3.org/ns/ldp#BasicContainer",
      "http://www.w3.org/ns/ldp#Container"
    ],
    "http://www.w3.org/ns/ldp#contains": [
      {
        "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/bidule.txt"
      },
      {
        "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/sousdossier/"
      }
    ],
    "http://www.w3.org/ns/posix/stat#mtime": [
      {
        "@value": "1611744840.932",
        "@type": "http://www.w3.org/2001/XMLSchema#decimal"
      }
    ],
    "http://www.w3.org/ns/posix/stat#size": [
      {
        "@value": "4096",
        "@type": "http://www.w3.org/2001/XMLSchema#integer"
      }
    ]
  },
  {
    "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/bidule.txt",
    "http://purl.org/dc/terms/modified": [
      {
        "@value": "2021-01-27T10:41:29Z",
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
      }
    ],
    "@type": [
      "http://www.w3.org/ns/iana/media-types/text/plain#Resource",
      "http://www.w3.org/ns/ldp#Resource"
    ],
    "http://www.w3.org/ns/posix/stat#mtime": [
      {
        "@value": "1611744089.656",
        "@type": "http://www.w3.org/2001/XMLSchema#decimal"
      }
    ],
    "http://www.w3.org/ns/posix/stat#size": [
      {
        "@value": "1",
        "@type": "http://www.w3.org/2001/XMLSchema#integer"
      }
    ]
  },
  {
    "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/sousdossier/",
    "http://purl.org/dc/terms/modified": [
      {
        "@value": "2021-01-27T10:44:49Z",
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
      }
    ],
    "@type": [
      "http://www.w3.org/ns/ldp#BasicContainer",
      "http://www.w3.org/ns/ldp#Container",
      "http://www.w3.org/ns/ldp#Resource"
    ],
    "http://www.w3.org/ns/posix/stat#mtime": [
      {
        "@value": "1611744289.439",
        "@type": "http://www.w3.org/2001/XMLSchema#decimal"
      }
    ],
    "http://www.w3.org/ns/posix/stat#size": [
      {
        "@value": "4096",
        "@type": "http://www.w3.org/2001/XMLSchema#integer"
      }
    ]
  }
]
```

C'est assez brut comme JSON (ils s'embêtent pas avec du compactage). Je remarque qu'en plus de l'URI du sous-container, il retourne son type, ainsi que sa taille et date de modification, mais j'imagine pas son contenu (`ldp:contains`)

**Comment by srosset81** [comment]
Et voilà ce que ça donne avec un bon [framing](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%5B%7B%22%40id%22%3A%22https%3A%2F%2Fspoggy-test6.solidcommunity.net%2Fpublic%2Ftestcontainer%2F%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fmodified%22%3A%5B%7B%22%40value%22%3A%222021-01-27T10%3A54%3A00Z%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%7D%5D%2C%22%40type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23BasicContainer%22%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23Container%22%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23contains%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fspoggy-test6.solidcommunity.net%2Fpublic%2Ftestcontainer%2Fbidule.txt%22%7D%2C%7B%22%40id%22%3A%22https%3A%2F%2Fspoggy-test6.solidcommunity.net%2Fpublic%2Ftestcontainer%2Fsousdossier%2F%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23mtime%22%3A%5B%7B%22%40value%22%3A%221611744840.932%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23decimal%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23size%22%3A%5B%7B%22%40value%22%3A%224096%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23integer%22%7D%5D%7D%2C%7B%22%40id%22%3A%22https%3A%2F%2Fspoggy-test6.solidcommunity.net%2Fpublic%2Ftestcontainer%2Fbidule.txt%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fmodified%22%3A%5B%7B%22%40value%22%3A%222021-01-27T10%3A41%3A29Z%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%7D%5D%2C%22%40type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Fiana%2Fmedia-types%2Ftext%2Fplain%23Resource%22%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23Resource%22%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23mtime%22%3A%5B%7B%22%40value%22%3A%221611744089.656%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23decimal%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23size%22%3A%5B%7B%22%40value%22%3A%221%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23integer%22%7D%5D%7D%2C%7B%22%40id%22%3A%22https%3A%2F%2Fspoggy-test6.solidcommunity.net%2Fpublic%2Ftestcontainer%2Fsousdossier%2F%22%2C%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fmodified%22%3A%5B%7B%22%40value%22%3A%222021-01-27T10%3A44%3A49Z%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23dateTime%22%7D%5D%2C%22%40type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23BasicContainer%22%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23Container%22%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23Resource%22%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23mtime%22%3A%5B%7B%22%40value%22%3A%221611744289.439%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23decimal%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23size%22%3A%5B%7B%22%40value%22%3A%224096%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23integer%22%7D%5D%7D%5D&frame=%7B%22%40context%22%3A%7B%22dc%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22ldp%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fldp%23%22%2C%22posix%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fposix%2Fstat%23%22%7D%2C%22%40id%22%3A%22https%3A%2F%2Fspoggy-test6.solidcommunity.net%2Fpublic%2Ftestcontainer%2F%22%7D):

```
{
  "@context": {
    "dc": "http://purl.org/dc/terms/",
    "ldp": "http://www.w3.org/ns/ldp#",
    "posix": "http://www.w3.org/ns/posix/stat#"
  },
  "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/",
  "@type": [
    "ldp:BasicContainer",
    "ldp:Container"
  ],
  "dc:modified": {
    "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
    "@value": "2021-01-27T10:54:00Z"
  },
  "ldp:contains": [
    {
      "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/bidule.txt",
      "@type": [
        "http://www.w3.org/ns/iana/media-types/text/plain#Resource",
        "ldp:Resource"
      ],
      "dc:modified": {
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
        "@value": "2021-01-27T10:41:29Z"
      },
      "posix:mtime": {
        "@type": "http://www.w3.org/2001/XMLSchema#decimal",
        "@value": "1611744089.656"
      },
      "posix:size": {
        "@type": "http://www.w3.org/2001/XMLSchema#integer",
        "@value": "1"
      }
    },
    {
      "@id": "https://spoggy-test6.solidcommunity.net/public/testcontainer/sousdossier/",
      "@type": [
        "ldp:BasicContainer",
        "ldp:Container",
        "ldp:Resource"
      ],
      "dc:modified": {
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime",
        "@value": "2021-01-27T10:44:49Z"
      },
      "posix:mtime": {
        "@type": "http://www.w3.org/2001/XMLSchema#decimal",
        "@value": "1611744289.439"
      },
      "posix:size": {
        "@type": "http://www.w3.org/2001/XMLSchema#integer",
        "@value": "4096"
      }
    }
  ],
  "posix:mtime": {
    "@type": "http://www.w3.org/2001/XMLSchema#decimal",
    "@value": "1611744840.932"
  },
  "posix:size": {
    "@type": "http://www.w3.org/2001/XMLSchema#integer",
    "@value": "4096"
  }
}
```

**Comment by scenaristeur** [comment]
ta question a disparu... mais non, si tu veux avoir son contenu, tu dois faire un get avec son url, mais c'est vrai que ça manque un peu parfois, dans certains cas, ça peut être utile de savoir s'il est vide, ou combien de ressources/ il contient
mais c'est assez compréhensible est proche d'un système de fichier, quand tu listes un folder sur linux/windows, tu n'as pas plus de détails sur les sous dossiers

**Comment by scenaristeur** [comment]
ah oui, le framing ça le fait, mais ça donne quoi si tu as une arborescence avec des tonnes de sous-dossiers  et de ressources ? tu ramènes tout ? 
Si oui, y'a un moment ou il faut stopper, quand même, d'autant qu'une des ressources pourrait références un container enfant du rootContainer... ;-)

**Comment by scenaristeur** [comment]
et ne sont pas ici listés les .acl qui gèrent les droits .meta
exemple : https://spoggy-test6.solidcommunity.net/public/testcontainer/bidule.txt.acl auquel tu ne dois pas avoir accès

**Comment by srosset81** [comment]
> ta question a disparu... mais non, si tu veux avoir son contenu, tu dois faire un get avec son url, mais c'est vrai que ça manque un peu parfois, dans certains cas, ça peut être utile de savoir s'il est vide, ou combien de ressources/ il contient
> mais c'est assez compréhensible est proche d'un système de fichier, quand tu listes un folder sur linux/windows, tu n'as pas plus de détails sur les sous dossiers

Oui ça me semble cohérent, en tout cas ça serait lourd à traiter si on retournait le contenu des containers enfants.
Du coup au niveau de la requête SPARQL qu'on devra faire, il suffira de *filter out* `ldp:contains` des resources retournées, et on aura quelque chose de cohérent et d'utilisable.

> ah oui, le framing ça le fait, mais ça donne quoi si tu as une arborescence avec des tonnes de sous-dossiers et de ressources ? tu ramènes tout ?

Le framing se contente d'ordrer les données fournies, il ne va pas commencer à déréférencer des URLs. Donc si on n'inclut pas le contenu des containers dans la requête, il n'y aura pas de soucis.

**Comment by scenaristeur** [comment]
> Intéressant que le sous-container soit lui-même défini comme un ldp:Resource en plus de ldp:BasicContainer, ldp:Container, lorsqu'il est lu depuis le container parent, mais pas quand il est lu directement. J'imagine que c'est parce que, dans un container, on ne peut avoir que des ressources ?

- dans le premier cas, on lit le parent, et pour lui oui, c'est une ressource
- dans le deuxième cas c'est juste un container ;-)
je n'ai jamais vu sur Solid de IndirectContainer ni DirectContainer comme évoqué ici https://www.w3.org/TR/ldp/#ldpc-container

**Comment by srosset81** [comment]
Fait ici https://github.com/assemblee-virtuelle/semapps/pull/642
