### ISSUE TITLE
Implémenter WebID-OIDC

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#434]
Nécessaire pour proposer un POD SOLID havec SemApps https://github.com/assemblee-virtuelle/semapps/issues/433

https://github.com/solid/webid-oidc-spec

Je ne sais pas s'il y a une implémentation qui existe en NodeJS ?

**Comment by GuillaumeAV** [comment]
J'en ai trouvé une ;) https://github.com/ksaito-hiu/idsrv

**Comment by srosset81** [comment]
Je teste la fermeture d'issue...

**Comment by srosset81** [comment]
Ca marche ! La checkbox sur https://github.com/assemblee-virtuelle/semapps/issues/433 a bien été mise à jour.
Il faut juste attendre 10-15 secondes que cela soit fait.

**Comment by srosset81** [comment]
Implémentation commencée pour ActivityPods. Je ferme cette issue qui date...
