### ISSUE TITLE
Débuter une écriture collaborative du code social - version résumée

### ISSUE THREAD

**Issue by ValentineMathieu** [assemblee-virtuelle/semapps#440]
Un travail sur le code social de SemApps avait déjà été initié par @bouviermullerp. Je prends donc l'initiative de revaloriser ce travail qui avait été laissé dans le yeswiki, en débutant une réécriture collaborative de ce document. 

Je vais ouvrir 2 requests (que je mettrai en lien dans cette issue) : 
- [une](https://github.com/assemblee-virtuelle/semapps/pull/442) pour la version synthétique/résumée du code social.
- une pour la partie plus détaillée, associée à l'issue #441 

Cette issue concerne le travail sur la version résumée du code social.

Libre à vous d'y contribuer :)

**Comment by bouviermullerp** [comment]
Merci Valentine. Je me demande si cette issue n'est pas "trop grosse" ?
Est-ce que ça vaut le coup d'avancer modèle par modèle peut être ? En tout cas faire une issue + PR pour la version synthétique et une issue + PR pour la version détaillée ?

**Comment by ValentineMathieu** [comment]
@bouviermullerp Oui c'est vrai qu'il vaudrait mieux la diviser, je pense modèle par modèle ca va être un peu lourd, mais je peux créer une autre issue et modifier celle ci pour avoir la forme issue résumée/PR, issue détaillée/PR :) merci pour tes conseils !
