### ISSUE TITLE
Débuter une écriture collaborative du code social - version détaillée

### ISSUE THREAD

**Issue by ValentineMathieu** [assemblee-virtuelle/semapps#441]
Un travail sur le code social de SemApps avait déjà été initié par @bouviermullerp. Je prends donc l'initiative de revaloriser ce travail qui avait été laissé dans le yeswiki, en débutant une réécriture collaborative de ce document.

Je vais ouvrir 2 requests :

- une pour la version synthétique/résumée du code social, associée à l'issue #440 
- une pour la partie plus détaillée (qui sera associée à cette issue)

Cette issue concerne le travail sur la version détaillée du code social.

Libre à vous d'y contribuer :)

**Comment by srosset81** [comment]
Je ferme ces issues CodeSocial car on a jamais réussi à se mettre d'accord sur le fait de faire un code social pour le projet.
