### ISSUE TITLE
Gérer owl:SymmetricProperty

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#456]
**Tension**
L'ontologie PAIR a des propriétés `partnerOf`, `nourishes` et `cooperateWith` qui sont de type `owl:SymmetricProperty`. Cela n'est pas géré par l'InferenceService que j'avais mis en place, et donc quand on ajoute une relation de ce type, la relation inverse n'est pas créée.

**Proposition**
Gérer cette propriété dans l'InferenceService

**Comment by simonLouvet** [comment]
à la différence du inverseof, cooperateWith l'applique au même prédicat
