### ISSUE TITLE
Passer tout sur Traefik

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#460]
**Problématique**
Pour l'instant on utilise encore Nginx et Certbot, mais c'est lourd à gérer, ça ne marche pas bien pour plusieurs domaines.

**Proposition**
Passer à Traefik qui est beaucoup plus léger et facile.

**Composants concernés**
- https://github.com/assemblee-virtuelle/semapps/blob/master/docker-compose-prod.yaml
- https://github.com/assemblee-virtuelle/semapps_coographie/blob/master/docker-compose-prod.yaml

**Comment by simonLouvet** [comment]
++

**Comment by srosset81** [comment]
Je l'ai fait pour coographie aujourd'hui. Reste le fichier du repo principal.
