### ISSUE TITLE
Afficher un fil d'actualité personnalisé

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#462]
**Description**
Afficher sur une page spéciale le contenu de son inbox ActivityPub, c'est-à-dire son fil personnalisé, avec les activités de tous les comptes qu'on suit.

**Issues liées**
- [ ] Permettre de suivre (ou ne plus suivre) un utilisateur ou une organisation
- [ ] Afficher sur la page des utilisateurs les comptes qu'ils suivent
- [ ] Afficher une page spéciale dans React Admin avec le fil personnalisé
- [ ] Formatter les actualités en fonction de leur type, et cela le plus génériquement possible

**Estimation du temps de travail en JH**
- @srosset81:
- @simonLouvet:

**Comment by srosset81** [comment]
Off topic for SemApps. But I'm building it for Mastopod...

**Comment by GuillaumeAV** [comment]
Génial !! On pourra l'utiliser sur Archipelago aussi ??

**Comment by srosset81** [comment]
Il faudra l'enrichir, pour l'instant ça n'affiche que les messages et les "boosts" (retweet)
En tout cas le chargement de la boîte de réception a été bien amélioré, avec possibilité d'un "infinite loader" (https://github.com/assemblee-virtuelle/semapps/pull/1237)
