### ISSUE TITLE
Présenter SemApps au Fosdem !!!!!

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#465]
[Voir les call for proposals ! 
](https://fosdem.org/2021/news/2020-12-06-accepted-developer-rooms/) C'est **NOW** !!

Notamment :
- Beyond blockchain, distributed web
- Collaborative Information and Content Management Applications
- Graph Systems and Algorithms

Event les 6 & 7 February 2021

Et à IndieWeb en juillet ?? https://indieweb.org/2020/West

**Comment by srosset81** [comment]
"Beyond blockchain, distributed web" c'est organisé par des gens d'Holochain, j'ai pas l'impression que ça colle avec SemApps.

Si on est retenu, il faut enregistrer une conférence avant le 16 janvier

**Comment by GuillaumeAV** [comment]
On peut envisager d'enregistrer le truc pendant la résidence ... 
Pas d'objection à ce qu'on candidate ? Qui serait motivé pour pitcher ? Si personne, à minima Glenn Roland et moi-même, on pourra se chauffer, mais c'est mieux si d'autres que moi se chauffent hein ;)
On peut envisager de faire des propositions sur plusieurs sujets .. 

Perspective : recruter du dev
Prérequis souhaitable : Angliciser un peu au moins le github ... 

@srosset81 @tfrancart @bouviermullerp @simonLouvet @Alice-Po  ca vous chauffe ?

**Comment by bouviermullerp** [comment]
Pas d'objection à ce qu'on candidate ! Laisser Glenn pitcher, ça me plait bien, ça lui permettrait de rentrer un peu plus dans le projet.

**Comment by srosset81** [comment]
Pas d'objection non plus, et intéressé de voir comment d'autres peuvent présenter SemApps ;-)

Par contre pour angliciser le Github, je pense qu'il faut concertation. On a déjà un site web en anglais, avec toute la doc et même des tutos. Si des anglophones sont intéressés, ils ont déjà de la matière. Par contre si on doit s'obliger à discuter les issues en anglais, avec tout ce que cela implique en terme d'incompréhension et de fatigue, il faudrait vraiment que ça soit utile.
