### ISSUE TITLE
Quel design pour Archipel ?

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#473]
Cette issue a vocation a préciser les concepts et relations à inclurent dans archipels et éventuellement à les hiérarchiser (peut être qu'on ne souhaite pas mettre tous les concepts aux même niveaux).

Questions : 
- Qui décide ? Est-ce que c'est une décision collégiale par consentement ?
- Quelle est la raison d'être de Archipel ? Qui sont ces utilisataurs ? Pourquoi Archipel ? Peut être que répondre à ces questions éclairera les spécifications

**Comment by bouviermullerp** [comment]
De mon point de vue, j'ai de la difficluté à voir les concepts compétences, documents "au même niveau" (dans l'interface) que les concepts "majeurs" de PAIR (Projets, Acteurs, Idées, Ressources).
Je rêve de naviguer dans les autres concepts (documents, compétences, etc..) mais d'une manière différente.

Et vous ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV

**Comment by GuillaumeAV** [comment]
Oui moi aussi, et je me demande ce qu'en pense @Rouffi ? 
Y aura un brainstorming design à la résidence ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV j'espère qu'il y en aura un - la question est qui s'empare de ce sujet ? Archipel est une instance de SemApps - et je ne crois pas qu'un rôle SemApps ai pour périmètre Archipel. Faut-il créer un nouveau rôle ?

**Comment by GuillaumeAV** [comment]
@Rouffi tu viens pas à la résidence ?
