### ISSUE TITLE
Authentification - créer son profil

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#48]
En tant qu'utilisateur, je peux créer/déclarer mon profil.

**Comment by srosset81** [comment]
- Créer un `WebIdService` géré par Moleculer
- Après l'authentification, si l'utilisateur n'existe pas encore, un profil est automatiquement créé avec les informations disponibles (email, nom, etc.)

Endpoints:
- `GET /me` renvoie le profil FOAF de l'utilisateur s'il est connecté, null sinon -> `webid.view`
- `GET /users/userId` renvoie le profil FOAF d'un utilisateur -> `webid.view`
- `PATCH /me` édite le profile FOAF -> `webid.update`

Frontend:
- Ajout d'un bouton Connexion dans la navbar
- Après connexion, on est redirigé vers la page profil.
- La page appelle l'endpoint `/me`
- On peut modifier les données de son profil.

Identification:
- Pour CAS, l'URI WebID est enregistrée dans le JWT
- Pour OIDC, on trouve l'URI WebID via une requête SparQL avec l'adresse email. A voir plus tard si on fait comme CAS.

**Comment by srosset81** [comment]
@simonLouvet @nikoPLP J'ai mis à jour mon commentaire ci-dessus, dites-moi si quelque chose ne joue pas.
