### ISSUE TITLE
Les participants à SemApps n'apparaissent pas sur archipel 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#480]
**Décrivez le bug**
En lecture seulement, les participants à SemApps n'apparaissent pas ... 
J'ai par contre ajouté une nouvelle personne (Valentine) sur Archipel, que j'ai ensuite ajouté en tant que participante à SemApps et elle apparait. 
Sans doute en lien avec la mise à jour de l'ontologie ? 

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org/
2. Cliquer sur SemApps
3. Voir qu'il n'y a que Valentine comme participante en lecture. (En édition il y a du monde)

**Comportement attendu**
Il faudrait voir poutquoi ca ne s'affiche pas ...

**Comment by simonLouvet** [comment]
same as #521
