### ISSUE TITLE
Les documents ne peuvent être liés aux personnes 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#481]
**Décrivez le bug**
Guillaume n'est pas lié au document le concernant.
Le document n'est pas lié à la personne le concernant. 

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org/
2. Cliquer sur https://archipel.assemblee-virtuelle.org/#/Document/https%3A%2F%2Fdata.virtual-assembly.org%2Fdocuments%2Fcode-social-guillaume-rouyer/show
3. Voir l'erreur

**Comportement attendu**
Que les relations entre personnes et documents apparaissent bien ;)

**Comment by simonLouvet** [comment]
linked to #521
