### ISSUE TITLE
L'entrée de dates ne marche pas sous Firefox

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#484]
**Décrivez le bug**
On ne peut saisir les dates, ni les horaires sur les entités de type événement. 

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org/#/Event/https%3A%2F%2Fdata.virtual-assembly.org%2Fevents%2Fagora-des-archipels/show
2. Cliquer sur Date de début / fin
3. Voir l'erreur

**Comportement attendu**
Une pop-up avec un calendrier pour sélectionner la date et l'heure serait idéal

**Comment by srosset81** [comment]
@GuillaumeAV J'ai l'impression que le problème est réglé, du moins je n'ai plus d'erreur quand je suis les étapes pour reproduire le bug.
Concernant cette remarque:
> Une pop-up avec un calendrier pour sélectionner la date et l'heure serait idéal

Il y a un popup qui est disponible en cliquant tout à droite du champ.

**Comment by GuillaumeAV** [comment]
Hey ! Je suis désolé, ca ne marche toujours pas de mon côité, quand j'essaie de renseigner des dates sur un event que je crée ... 
Exemple : https://archipel.assemblee-virtuelle.org/#/Event/https%3A%2F%2Fdata.virtual-assembly.org%2Fevents%2Fatelier-refonte-assemblee-virtuelle-1/show

**Comment by srosset81** [comment]
J'ai besoin de plus de détails car je ne reproduis toujours pas.
- Si tu as une erreur, merci de faire un screenshot ou un copier-coller.
- S'il y a un autre comportement qui ne marche pas, il faut le préciser.

> Pour info, pour pouvoir enregistrer une date, il faut la remplir en entier, avec date et heure. Le mieux est de passer par le popup, en cliquant sur l'icône à droite du champ. Je viens de remarquer que si tu ne mets que la date mais pas l'heure, c'est pas enregistré. C'est peut-être ça ton problème ?

**Comment by GuillaumeAV** [comment]
Désolé ! 

En fait, chez moi ca marche sur Chrome mais pas sur Firefox : Voici une vidéo pour mon expérience sur firefox ;) https://drive.google.com/file/d/1yWPMnMENfLMgOJrm1cuO7M56_t-sHhMS/view?usp=sharing

**Comment by srosset81** [comment]
Ah merci d'avoir identifié ça ! :-)

Le DateTimeInput est un composant core de react-admin.
Je vais voir pour mettre à jour react-admin vers la dernière version et, sinon, poster un bug chez eux.

**Comment by srosset81** [comment]
Ah c'est un problème connu sous Firefox: https://github.com/marmelab/react-admin/issues/2685
Ils recommendent d'utiliser un autre composant: https://github.com/vascofg/react-admin-date-inputs
Je m'en occupe

**Comment by srosset81** [comment]
@GuillaumeAV Le fix est déployé sur Archipel
