### ISSUE TITLE
Les personnes ne s'affichent pas sur les événements

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#485]
**Décrivez le bug**
Je me suis renseigné en tant que participant à un event, mais ca n'apparait pas en lecture. 

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org/#/Event/https%3A%2F%2Fdata.virtual-assembly.org%2Fevents%2Fagora-des-archipels/show
2. Cliquer sur éditer / puis afficher
3. Voir l'erreur

**Comportement attendu**
Afficher les personnes en lecture

**Comment by srosset81** [comment]
Même problème que https://github.com/assemblee-virtuelle/semapps/issues/480, je ferme.
