### ISSUE TITLE
update de semapps

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#490]
**Tension**
j'ai installé semapps avec ```moleculer init assemblee-virtuelle/semapps-template-ldp my-project```, mais je ne trouve pas comment récupérer la dernière version

**Proposition**
Existe-t-il un truc du style ```moleculer pull``` équivalent à un ```git pull``` pour récupérer le dernier code, mettre à jour mon serveur ? 

**Alternatives**
Mettre cette info dans la doc, svp ;-)

**Comment by simonLouvet** [comment]
les template se basent su une version des composants moleculer. Si le template n'est pas préparé avec les dernières versions des composants, il n'y a pas de magie. Tu peux modifier le package.json obtenu pour pointer vers les dernières versions mais il y aura sans doute des breaking change.

**Comment by srosset81** [comment]
Je confirme que ce n'est pas possible de rendre une mise à jour automatique.
Mettre à jour les versions des packages dans `package.json` devrait suffire dans la plupart des cas, mais il peut y avoir des breaking changes (j'ai commencé à les [marquer comme telle dans mes PRs](https://github.com/assemblee-virtuelle/semapps/search?q=breaking+changes&type=issues), en attendant qu'on gère mieux le versioning).

**Comment by srosset81** [comment]
Je ferme cette issue puisqu'une mise à jour automatique n'est pas possible.
Vendredi on a créé une issue https://github.com/assemblee-virtuelle/semapps/issues/508 pour mettre à jour les templates avec les dernières versions des packages Moleculer.
