### ISSUE TITLE
Rendre plus flexible le choix des containers ActivityPub

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#491]
**Tension**
En vue des différents chantiers ActivityPub (notamment https://github.com/assemblee-virtuelle/semapps/issues/448), il est nécessaire de revoir un peu le package `@semapps/activitypub` afin qu'il s'intègre mieux avec LDP. 

Pour le moment, les acteurs doivent être dans un container `/actors` et les objets générés dans un container `/objects`. Il faudrait rendre ça plus flexible, afin qu'on puisse avoir des acteurs dans les containers `/organizations`, `/users`, etc, et que les objets créées via ActivityPub puissent être ajoutés dans les bons containers.

**Proposition**
Créer un fichier `containers.js` qui serait utilisé par le service LDP (et qui pourrait à terme permettre de définir des options propres aux containers) mais aussi par le service ActivityPub, dans le but de déterminer dans quel container mettre les objets, et à quel container associer des acteurs.

**Comment by GuillaumeAV** [comment]
Rien à voir avec PAIR j'imagine ? 
Peut-être que la logique de PAIR pourrait être inspirante, avec les différents niveaux d'abstraction / généricité des classes "Acteur", "Agent", "Sujet" ?

**Comment by srosset81** [comment]
Avec ActivityStreams (l'ontologie utilisée par ActivityPub) il y a trois classes principales: `Actor`, `Activity` et `Object`.
Changer cette ontologie n'est pas trop en notre pouvoir...
