### ISSUE TITLE
Améliorer la classe Document

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#493]
**Tension**
J'aimerais pouvoir utiliser la classe documents pour faire de la veille ... Pouvoir renseigner l'URL du doc, et le rattacher à des thèmes, compétences, idées, agents  ... Sujets en général ce qui ne semble pas être le cas à l'heure actuelle 

**Proposition**
- Permettre une complétion sur l'ensemble des sujets.
- Permettre de renseigner une URL

**Alternatives**
A terme, on pourra faire un module d'ontologie dédié à la veille avec des propriétés et et ajouter des fonctionnalités spécifiques dans SemApps ;)

**Comment by srosset81** [comment]
Me semble hors scope...
