### ISSUE TITLE
Utiliser les containers plutôt que des requêtes SPARQL pour lister les ressources

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#495]
**Tension**
Les requêtes SPARQL sont lentes et prennent du CPU à Fuseki. On fait beaucoup de ces requêtes lorsqu'on liste des données sur React-Admin. 

**Proposition**
On pourrait plutôt utiliser les données des containers qui, elles, sont mises en cache. On ne ferait une requête SPARQL que si on passe des paramètres particuliers (recherche par mots-clés, filtres...).

**Comment by simonLouvet** [comment]
++

**Comment by srosset81** [comment]
C'est possible depuis un moment avec le paramètre `list.fetchContainer` du DataModel (https://semapps.org/docs/frontend/semantic-data-provider/data-model)
