### ISSUE TITLE
Améliorer la gestion des containers LDP

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#497]
**Problématique**
Les résultats retournés dans les containers ne sont pas toujours bien formattés. Voir par exemple https://data.virtual-assembly.org/organizations et en particulier les URI `https://data.virtual-assembly.org/organizations/colibris` et `https://data.virtual-assembly.org/organizations/transiscope` qui sont imbriqués au mauvais endroit.

**Proposition**
Plutôt que faire une requête qui recherche toutes les données d'un seul coup, faire pour chaque ressource un appel à l'action `ldp.resource.get`. Cela permettra de mieux profiter du cache Redis, mais aussi de plus facilement ajouter la [pagination LDP](https://github.com/assemblee-virtuelle/semapps/issues/176).

**Composants concernés**
Action `ldp.container.get`

**Comment by simonLouvet** [comment]
@srosset81 j'ai compris ta proposition mais pas le probleme.

**Comment by srosset81** [comment]
Il faut chercher les URIs `https://data.virtual-assembly.org/organizations/colibris` et `https://data.virtual-assembly.org/organizations/transiscope` dans le container https://data.virtual-assembly.org/organizations

**Comment by srosset81** [comment]
Après réflexion, ce n'est pas évident à mettre en place car il faut adapter non seulement pour le JSON-LD, mais aussi pour le Turtle et les autres format. Cela va compliqué le code et ça risque de générer des bugs.

Je vais voir si la PR https://github.com/assemblee-virtuelle/semapps/pull/503 règle le bug indiqué et, si c'est le cas, je fermerai cette issue.
