### ISSUE TITLE
Authentification sans SSO

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#498]
**Description**
Cela pourrait intéresser certaines instances SemApps de permettre de créer des comptes utilisateurs sans avoir à configurer l'accès à un SSO.

**Issues liées**
- [ ] Formulaire de connexion
- [ ] Formulaire de création de compte
- [ ] Formulaire de récupération de mot de passe
- [ ] Envoi d'emails à la création de compte et pour récupérer le mot de passe
- [ ] Enregistrement du mot de passe crypté et de l'email dans un graph protégé ?

**Estimation du temps de travail en JH**
- @srosset81:
- @simonLouvet:

**Comment by simonLouvet** [comment]
Cela pourrait simplifier l'ergonomie mais va poser des problèmes d'interopérabilité. Un user sur une instance ne pourra pas agir (voir naviguer) sur une seconde si elles ne partagent pas le mm sso.

**Comment by srosset81** [comment]
@simonLouvet Je ne crois pas qu'on peut faire ça avec l'implémentation actuelle qui utilise OIDC/CAS.
Il faudra pour cela implémenter [WebID-OIDC](https://github.com/assemblee-virtuelle/semapps/issues/434).

**Comment by simonLouvet** [comment]
@srosset81 C'est justement pour faire cela pour j'ai poussé à avoir un ou des SSO et pas une authentification "locale". l’implémentation actuelle n'et peut être pas suffisante pour le faire mais c'est bien l'objectif. Lorsque Semapps ne gérait pas lui même un token et que les user était authentifié en OIDC (le front communiquait avec les serveur grâce au token fourni par le fournisseur OIDC directement), cela devait fonctionné. Je ne me suis pas rendu compte d'une régression.

**Comment by srosset81** [comment]
@simonLouvet Même si deux instances SemApps utilisent le même SSO, un webID doit bien être créé sur l'une ou l'autre des instances. Comment déterminer l'instance de référence pour l'utilisateur ? A mon avis, c'est impossible sans un mécanisme tel que WebID-OIDC, mais on pourra en reparler.

**Comment by simonLouvet** [comment]
@srosset81 tu as raison pour le webId. Une mécanique comparable au webid-oidc semble nécessaire. Piste à réfléchir : Il serait assez facile de update le serveur OIDC avec un webid associé au profil de manière à l'inclure dans le token.

**Comment by srosset81** [comment]
> @srosset81 tu as raison pour le webId. Une mécanique comparable au webid-oidc semble nécessaire. Piste à réfléchir : Il serait assez facile de update le serveur OIDC avec un webid associé au profil de manière à l'inclure dans le token.

Les Communs, par exemple, pourraient attacher un WebID à chaque utilisateur ? Avec quel URI ?

**Comment by simonLouvet** [comment]
> > @srosset81 tu as raison pour le webId. Une mécanique comparable au webid-oidc semble nécessaire. Piste à réfléchir : Il serait assez facile de update le serveur OIDC avec un webid associé au profil de manière à l'inclure dans le token.
> 
> Les Communs, par exemple, pourraient attacher un WebID à chaque utilisateur ? Avec quel URI ?

Une uri fourni par une instance Semapps. Si pas de webId dans le token, l'instance SemApps pourrait créer un profil locale et l'ajouter (par API) eu serveur OIDC. La prochaine fois que le token est transmis à un serveur SemApps, il contiendrait l'uri du webId.

**Comment by srosset81** [comment]
Ah si c'est possible, ça pourrait être une solution intermédiaire.
J'ai créé une issue spécifique https://github.com/assemblee-virtuelle/semapps/issues/502

**Comment by GuillaumeAV** [comment]
Huum le SSO c'est cool je trouve, je me dis d'ailleurs, c'est sans doute hors sujet cependant, que ce serait cool de rattacher à login.lescommuns, la possibilité de renseigner un profil perso riche avec des données sémantiques, par exemple liées à pair:person / foaf:person ? Ou c'est peut-être débile ?

**Comment by srosset81** [comment]
Si on peut lier un compte sur le SSO Les Communs avec un webId (URL du profil de l'utilisateur), comme le suggère Simon dans son précédent commentaire, alors oui ce serait possible de lier le compte avec des données sémantiques riches.
