### ISSUE TITLE
Page blanche quand j'édite un event

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#501]
**Décrivez le bug**
Une description claire et concise du bug.

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org/#/Event/https%3A%2F%2Fdata.virtual-assembly.org%2Fevents%2Fagora-des-archipels
2. Voir l'erreur

**Comportement attendu**
Qu'on puisse voir l'interface de saisie et éditer ;)

**Captures d'écran**
Si ça peut être utile, ajoutez ici des captures d'écrans pour expliquer le problème.

**Comment by fluidlog** [comment]
Pour info, j'ai eu aussi une page blanche lorsque j'ai édité le projet Flodio.

**Comment by simonLouvet** [comment]
same as #511
