### ISSUE TITLE
Mettre à jour les templates Moleculer

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#508]
https://github.com/assemblee-virtuelle/semapps-template-ldp
https://github.com/assemblee-virtuelle/semapps-template-activitypub

**Comment by srosset81** [comment]
Les derniers breaking changes sont listés ici, attention à bien les prendre en compte:
https://github.com/assemblee-virtuelle/semapps/issues?q=label%3A%22breaking+changes%22+is%3Aclosed

**Comment by s-ol** [comment]
These two PRs should be all that is required as far as I can tell, but I would appreciate someone who knows the project better to confirm everything works as expected.

- assemblee-virtuelle/semapps-template-activitypub#1
- assemblee-virtuelle/semapps-template-ldp#3

**Comment by srosset81** [comment]
Thanks a lot ! I've suggested a fix for the activitypub template.
@sauvagemathilde could you have a look at @s-ol's work ?
