### ISSUE TITLE
Ne pas pouvoir modifier le contenu d'un autre profil sur archipel

### ISSUE THREAD

**Issue by J9rem** [assemblee-virtuelle/semapps#509]
**Décrivez le bug**
Il est possible de modifier le contenu du profil d'un autre utilisateur sur Archipel

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org
2. Se connecter
3. Cliquer sur `personnes`
4. Choisir une personne
5. Cliquer sur `éditer`
6. Faire une modification
7. Sauvegarder

**Comportement attendu**
Ne pas pouvoir modifier le contenu d'un autre profil

**Notes**
devrait être pris en compte par #52

**Comment by simonLouvet** [comment]
Je pense que ce n'est pas un bug mais une fonctionnalité

**Comment by srosset81** [comment]
Je ferme car cela sera ajouté via le chantier sur les webacl https://github.com/assemblee-virtuelle/semapps/issues/52
