### ISSUE TITLE
Endpoint VOID pour récupérer des informations d'une instance SemApps

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#517]
**Tension**
Faire du 100% standards sémantique c'est bien, mais si on pouvait offrir un endpoint qui retournerait des statistiques sur une instance SemApps, ça permettrait à @fluidlog de pouvoir générer une jolie CartoDesCartos, ou d'afficher une liste complète d'instance un peu comme le fait [PeerTube](https://instances.joinpeertube.org/instances) ou [Mastodon](https://instances.social/).

**Proposition**
Créer un endpoint (URL à déterminer) qui retourneraient des données à déterminer.

- URL de l'endpoint SPARQL
- Fichier de context par défaut
- ...

On peut s'inspirer de Mastodon, qui retourne [ce type de données](https://framapiaf.org/api/v1/instance):

![Capture d’écran de 2021-01-18 16-59-30](https://user-images.githubusercontent.com/17931931/104937898-9c83d880-59ae-11eb-98d3-0fa3fcb566f6.png)

Cerise sur la gâteau, on pourrait décrire ces données de manière sémantique, avec une ontologie spécifique ;-)

**Comment by scenaristeur** [comment]
Le vocabulaire Hydra a l'air d'être fait pour décrire une API est les actions que l'on peut effectuer sur une ressource 🙂
- http://www.hydra-cg.com/spec/latest/core/
- https://youtu.be/fJCtaNRxg9M
- https://nordicapis.com/hydra-for-hypermedia-apis-benefits-components-and-examples/

**Comment by srosset81** [comment]
Concernant Hydra, le projet API Platform a adapté React-Admin pour plus facilement utiliser des API de type Hydra.

https://api-platform.com/docs/admin/

Cette adaptation pourrait nous fournir de belles inspirations.

**Comment by srosset81** [comment]
Une autre information qu'il serait très pertinent d'avoir dans un endpoint de ce type, c'est les interfaces qui permettent de voir les données. Ca permettre à une instance SemApps qui voudrait envoyer un utilisateur directement sur une autre interface de savoir comment s'y prendre.

Par exemple pour `data.virtual-assembly.org`, on pourrait avoir une info de type:
```
  preferredFront: { 
    `pair:Organization`: 'https://archipel.assemblee-virtuelle.org/Organization/{URI}/show`,
    `pair:Project`: 'https://archipel.assemblee-virtuelle.org/Project/{URI}/show`,
  }
```

**Comment by srosset81** [comment]
Informations qu'il serait intéressant de retourner suite à la réunion de ce jour ([voir le CR complet](https://pad.lescommuns.org/UVcvt8XGT5mUK6mvzlMCTg)):

- Est-ce que l'instance accepte/encourage l'ajout de relation inverses en PATCH ?
- Quelles sont les ontologies qu'elle accepte / reconnaît ?

**Comment by srosset81** [comment]
Bonne nouvelle, l'ontologie [void](https://www.w3.org/TR/void/) permet de renseigner déjà pas mal d'informations. Voilà ce que ça pourrait donner en Turtle:

```ttl
:VirtualAssembly a void:Dataset;
    dcterms:title "Virtual Assembly";
    dcterms:description "Virtual Assembly ecosystem";
    dcterms:modified "2020-11-17"^^xsd:date;
    dcterms:license <http://www.opendatacommons.org/norms/odc-by-sa/> ;
    void:feature <http://www.w3.org/ns/formats/N-Triples> ;
    void:sparqlEndpoint <https://data.virtual-assembly.org/sparql>;
    void:rootResource <https://data.virtual-assembly.org/> ;
    void:uriSpace "https://data.virtual-assembly.org/";
    void:vocabulary <http://purl.org/dc/terms/> ;
    void:classPartition [
        void:uriSpace "https://data.virtual-assembly.org/organizations/";
        void:class pair:Organization ;
        void:entities 35 ;
    ];
```

L'autre bonne nouvelle, c'est que cette ontologie recommande une URL de type `.well-known` pour trouver facilement les données:

https://data.virtual-assembly.org/.well-known/void

J'ai aussi regardé l'ontologie [D-Cat](https://www.w3.org/TR/vocab-dcat/), elle est plus récente mais il manque des informations par rapport à ce dont on a besoin.

J'ai ajouté cette issue dans https://github.com/assemblee-virtuelle/semapps/issues/451 car on va sans doute devoir la réaliser dans le cadre du chantier interop.

Ping @nikoPLP @simonLouvet @tfrancart

**Comment by fluidlog** [comment]
Super ! Merci :)
Voici d'ailleurs le PAD du projet META : https://pad.lescommuns.org/-ioDLrRJTuCtMh-9xDSjcA#

**Comment by srosset81** [comment]
## Implémentation

- Service Moleculer VOID
- Prendre en compte le WebID
- Va chercher informations via SPARQL ou dans le fichier container.js
- S'assurer qu'il y ait les bonnes infos pour cacher côté client le fichier de config VOID (dépend de WebID)

**Comment by fluidlog** [comment]
Il semble que cette issue porte l'amélioration bien pratique d'afficher les enfants du conteneur racine.
