### ISSUE TITLE
Server should give infos about the created resource

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#523]
**Tension**
Server does not give the url of the created resource  

**Proposition**
Server should give infos about the created resource
same as https://github.com/solid/community-server/issues/441

according to https://stackoverflow.com/questions/38927335/how-to-get-header-location-value-from-a-fetch-request-in-browser
or https://stackoverflow.com/questions/39020385/fetch-api-not-returning-the-location-header

it seems the server should just expose it with something like

Access-Control-Expose-Headers: Location
so we can access Location value with :
response.headers.get('Location');

![image](https://user-images.githubusercontent.com/4020744/105181372-01b10880-5b2c-11eb-99f9-d13b5a1f729d.png)

**Comment by srosset81** [comment]
I think this has been fixed a while ago. It is much used.
