### ISSUE TITLE
Rédaction de la newsletter de Février

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#528]
Idéation collective sur un PAD avant de le passer sur GitHub https://pad.lescommuns.org/tl0ZtvLjQH61QXYzfYegZA

**Comment by srosset81** [comment]
Je pense qu'il faut qu'on s'atèle à une newsletter, ça fait trop longtemps qu'on ne donne plus de nouvelles. Les données dans le pad sont en partie périmées, ou sont trop datées pour que ça ait encore de l'intérêt.

Du coup j'ai créé une PR dédiée: https://github.com/assemblee-virtuelle/semapps/pull/746

On pourra en profiter pour annoncer les WebACL.
