### ISSUE TITLE
Création des containers lorsque semapps est lancé

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#531]
**Tension**
Pouvoir créer des containers pendant que semapps tourne

**Proposition**
Il semblerait que la création des containers s'effectue dans la config de semapps et soit donc figée une fois que semapps est lancé. Par exemple /persons au premier démarrage, mais lors de l'utilisation, il peut arriver que l'on ai besoin de créer d'autres containers comme '/workspaces', '/todos'... or cela ne semble pas possible sans arrêter semapps, ajouter ces containers dans la config semapps et redémarre semapps, ce qui peut être gênant. 
Il est donc impossible d'enregistrer des infos dans des containers qui n'auraient pas été prévus avant le lancement de semapps ?

**Question**
Peut-on créer des containers à la volée ?

**Comment by srosset81** [comment]
Les containers peuvent être créés à la volée en appelant le service `ldp.container`, mais il manquera la route API.
La route API pourra être ajoutée à la volée lorsque @sauvagemathilde aurait fini cette issue: https://github.com/assemblee-virtuelle/semapps/issues/334

En revanche, on peut maintenant associer des configs spécifiques aux containers ([voir par exemple ce fichier](https://github.com/assemblee-virtuelle/semapps/blob/master/src/middleware/boilerplates/pair-ldp-server/containers.js)), et ce n'est pas possible avec des containers créés à la volée.

C'est un problème à propos duquel on a déjà parlé avec @simonLouvet. Une alternative, au lieu d'un fichier json, aurait été d'enregistrer les configurations dans le triple store. Mais ça pose d'autres problèmes et questionnements...

**Comment by srosset81** [comment]
J'ai pensé à un moyen de définir les options des containers à la volée https://github.com/assemblee-virtuelle/semapps/issues/535

Du coup je ferme cette issue car elle sera résolue par les issues #334 et #535
