### ISSUE TITLE
documentation, description des api / services sur la page d'accueil

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#532]
**Tension**
la page d'accueil/racine du server 127.0.0.1:3000 indique 404 not found

**Proposition**
il serait utile d'avoir à cet endroit une description / documentation des services, containers, paths (/sparql...) disponibles accessibles, offerts comme le ferait une api classique, au format json
Je veux bien jeter un oeil si vous me dites dans quel fichier je peux changer ce contenur

**Comment by srosset81** [comment]
On a prévu deux fonctionnalités dans ce sens:
- Afficher les containers à la racine https://github.com/assemblee-virtuelle/semapps/issues/429
- Créer un endpoint pour récupérer des informations sur l'instance (dont l'endpoint sparql) https://github.com/assemblee-virtuelle/semapps/issues/517

Comme il y a déjà des issues spécifiques, je ferme celle-ci.
Si tu veux te coller à l'une ou l'autre, bienvenue ;-) Je suis dispo pour réfléchir avec toi aux détails.
