### ISSUE TITLE
Accepter le format JSON par défaut partout

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#542]
**Problématique**
Lorsque je dois appeler `ldp.resource.get` ou `ldp.container.get` depuis d'autres services, c'est toujours pour avoir les données en JSON. Cela oblige à importer les `MIME_TYPES` du package `@semapps/mime-types` partout.

**Proposition**
Plutôt que d'imposer de fournier un `accept` ou un `contentType`, avoir le format JSON par défault.

**Comment by srosset81** [comment]
OK pour toi @simonLouvet ?

**Comment by simonLouvet** [comment]
Il me semble que le accept par défaut est déjà configurable dans le options du container et géré au niveau du ldp.resource.get. get.js ligne 45. ok pour faire la même chose pour le content-type.
Nous pourrions souhaiter différencier la configuration du container (au sens appi) du service associé et ne pas mélanger les configuration des deux couches dans containers.js.
pas d'objection dans l'absolue à ce que ldp.resource.get et ldp.container.get accepte et renvoie du json-ld par défaut.

**Comment by srosset81** [comment]
Replaced with https://github.com/assemblee-virtuelle/semapps/issues/1226
