### ISSUE TITLE
Mettre en place une stratégie UX

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#543]
- Trouver / associer des UX designers
  - Pistes actuelles Romain Rouyer, Fabrice Liut
- Proposer des réunions de travail UX
- Participer aux réunions techniques du vendredi lorsqu'il y a des sujets UX

**Comment by GuillaumeAV** [comment]
Lise Gloria pourrait également rejoindre la team, j'ai un call lundi avec Fabrice et je m'occupe de ce sujet globalement la semaine prochaine !

**Comment by srosset81** [comment]
Je ferme car ça me semble plus adapté, maintenant que SemApps n'est plus un produit
