### ISSUE TITLE
Assurer un suivi des personnes qui s'approchent de SemApps

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#544]
- Faire un fichier des contributeurs potentiels ?

**Comment by GuillaumeAV** [comment]
Yop ! J'amorce le suivi des personnes qui s'approchent de SemApps [sur ce doc](https://docs.google.com/spreadsheets/d/1sr9QOyLhzlvz_ERbfkBANXawcKbKf0DlzBfcIOi6I5o/edit?usp=sharing) ! 

Si quelqu'un veut m'aider à structurer le gsheet j'en serais très heureux !
