### ISSUE TITLE
Transférer tout ce qui est sur Roam Research sur le wiki Github

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#546]
Passer tout ce qui est sur Roam Research en faisant une valoratisation du contenu

https://github.com/assemblee-virtuelle/semapps/wiki

**Comment by J9rem** [comment]
J'ai terminé le transfert des informations depuis Roam Research https://roamresearch.com/#/app/virtual-assembly/page/af0djawNO

1. Création de la page [SemApps en quelques mots](https://github.com/assemblee-virtuelle/semapps/wiki/SemApps-en-quelques-mots) et ajout à la page [d'accueil](https://github.com/assemblee-virtuelle/semapps/wiki)
2. Création de la page [Nos outils](https://github.com/assemblee-virtuelle/semapps/wiki/Nos-outils-...) et ajout à la page [d'accueil](https://github.com/assemblee-virtuelle/semapps/wiki) et la page [Je découvre SemApps, par où commencer ? ...](https://github.com/assemblee-virtuelle/semapps/wiki/Je-decouvre-SemApps-par-ou-commencer)
3. Ajout/copie des CR dans la page [Réunions Sprints SemApps](https://github.com/assemblee-virtuelle/semapps/wiki/R%C3%A9unions-Sprints-SemApps)
4. Ajout/copie des liens et CR dans la page [Réunions gouvernance SemApps](https://github.com/assemblee-virtuelle/semapps/wiki/R%C3%A9unions-gouvernance-SemApps)
5. Mise à jour de la partie canaux de discussion dans la page [Je découvre SemApps, par où commencer ? ...](https://github.com/assemblee-virtuelle/semapps/wiki/Je-decouvre-SemApps-par-ou-commencer) en mettant les informations pour hubl.
6. suppression des pages de travail que j'avais créées temporairement sur le wiki pour faire le transfert.

Je clos l'issue car je trouve que c'est assez consistant déjà.

**Comment by srosset81** [comment]
Super boulot, merci !

**Comment by GuillaumeAV** [comment]
Génial bravo @J9rem !!
