### ISSUE TITLE
Fournir au groupe projet un calendrier de financements acquis

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#548]

**Comment by GuillaumeAV** [comment]
Oui ce serait top ! Petite question, il faut une compta prévisionnelle côté DP, une autre côté SemApps, une autre côté AV : N'y aurait il pas un enjeu à s'accorder sur une structure commune et à automatiser les partages d'infos ? 

A ce sujet, je me permets de partager le super outil de prévisionnel financier de Finacoop .. https://www.finacoop.fr/boite-a-outils/#previsionnel-financier-fisy-finacoop-essentiel-5-ans-compatible-excel-et-google-sheet
