### ISSUE TITLE
Garder un historique de qui a financé quoi

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#550]
Garder un historique de qui (organationss/projets) a financé quoi (chantiers ?) afin de pouvoir le communiquer

Cela permettra de mettre en valeur les contributions aux communs.

En lien peut-être avec https://github.com/assemblee-virtuelle/semapps/issues/318

**Comment by GuillaumeAV** [comment]
Oui en effet, ce serait super ! 
Sur SemApps, on pourrait le modéliser en utilisant _offered "MoneyBasedRessource"_

**Comment by J9rem** [comment]
@bouviermullerp a initié ce document : https://pad.lescommuns.org/mjckrHy3TTuXq3qt7XJ9yw?both# qu'en pensez-vous ?
