### ISSUE TITLE
Décider des prochaines classes à ajouter à Archipel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#554]
On a pas mal de développeurs débutants en ce moment. Ce serait bien de les mettre sur l'ajout de classes à Archipel, mais encore faut-il savoir quoi et dans quel ordre de priorité.

Objectif: créer des issues claires (taggées `Archipel`) avec la classe, les relations et propriétés désirées

**Comment by srosset81** [comment]
A mon avis il faut réfléchir en terme d'usages et plus précisément: qu'est-ce qui serait utile pour l'AV ? Qu'est-ce qu'on pourrait mettre en place comme pratiques ?

Par exemple:
- Créer des événements pour les réunions
- Créer des documents de compte-rendu
- Rendre visible les rôles de l'AV et de SemApps
- Avoir un CRM des organisations partenaires
- Etc...

**Comment by srosset81** [comment]
@GuillaumeAV @bouviermullerp 
Pour le prochain sprint de 2 semaines qui commence maintenant, @capucinemasson est motivée pour faire avancer Archipel. Auriez-vous une idée d'une classe qui pourrait être ajoutée, sans qu'elle demande un travail spécial ? (p.ex. les rôles ce n'est pas possible tant que @simonLouvet n'a pas terminé les [relations réifiées](https://github.com/assemblee-virtuelle/semapps/issues/526))

**Comment by GuillaumeAV** [comment]
Salut ! 

Je me suis dit que ce serait utile d'avoir une arborescence des classes, sans avoir besoin de passer par protege ... 
Du coup, voici [une arborescence de l'ontologie PAIR](https://docs.google.com/document/d/1jsvD2ly_yt1IqtCZxYSnjwBjNYClziG-rl63ExyejHo/edit?usp=sharing), [complémentaire du diagramme](https://raw.githubusercontent.com/assemblee-virtuelle/pair/master/3-Dissemination/Diagrammes-PAIR-Winter-2020/PAIR%20Core%20Subjects-2020-WinterEdition.png) et de la [documentation](https://www.virtual-assembly.org/ontologies/pair-2020-winter/index-en.html)

Génial que tu te motives @capucinemasson !!

**Comment by GuillaumeAV** [comment]
La comme ça je dirais : 
- Idées : Pour pouvoir partager des idées sur tout et n'importe quoi #brainstorming, feedbacks, amélioration continue, idéation
- Tâches : Pour tester une gestion des tâches liées à l'asso via SemApps
- Lieu : Pour cartographier notre communauté
- Types : L'implémentation des différents types nous permettrait de gagner à fond en structuration des données ..

On aurait les principaux concepts PAIR sans les ressources qui posent quelques problèmes pour le moment et sans les intentions ..

**Comment by srosset81** [comment]
Les plus simples semblent Idées et Lieux. Il s'agira juste de déterminer les relations et propriétés qu'on veut implémenter.

Pour les tâches, je me demande si, au niveau de la pratique, ça ne va pas entrer en conflit avec les issues Github ? En clair, est-ce que les contributeurs de l'AV vont passer par SemApps pour ça, alors que ça marche déjà plutôt bien sur Gituhub ? A moins qu'on crée un service pour sémantiser les issues Github :-P L'API de Github est [plutôt bien foutue](https://docs.github.com/en/rest/reference/issues) et ça devrait être facile en lecture (pour l'écriture ce sera une autre paire de manche, même si c'est aussi possible...) 

Je propose qu'on attende l'avis de @bouviermullerp 

> PS: D'ailleurs pour le site de chantiers collaboratifs j'avais proposé de lier les chantiers aux issues Github, je pensais appeler l'API Github depuis le frontend, mais pourquoi pas transformer les issues en `pair:Tasks` via un service Moleculer ? Comme ça on traiterait les données comme les autres.
>
> PPS: Autre usage: pour les différents rôles (AV + SemApps), on pourrait lister les tâches liées à un rôle en fonction du label :-)

**Comment by bouviermullerp** [comment]
Salut !
Je m'excuse pour le manque de réactivité, mon ordi est mort il y a 3 jours et c'est donc tout mon setup qui est tombé - ça m'a pris du temps de rmonter une config avec les bouts d'ordi que j'avais récupéré (et c'est pas encore fini :-/ )

> A mon avis il faut réfléchir en terme d'usages et plus précisément: qu'est-ce qui serait utile pour l'AV ? Qu'est-ce qu'on pourrait mettre en place comme pratiques ?

Ce passage est hyper intéressant :) et c'est (de mon point de vue) la clef qui permettra de déduire les réponses (quelles classes ?).

Autrement dit, est-ce qu'on a déterminé : 
- La raison d'être de Archipel ? 
      - Est-ce que c'est un espace de démo dans lequel on met le maximum de choses pour pouvoir faire des présentation de tout (et auquel cas on peut ajouter toutes les classes de PAIR ?)
      - Est-ce qu'on préfère se concentrer sur des usages internes à l'asso ?
      - Est-ce qu'on préfère en faire un outil de cartographie communautaire ? (ce dernier point me motive)
- A qui est destiné Archipel, pour qui héberge-t-on, maintient on cette instance ?
      - Quel que soit la réponse, elle sera déterminante pour sélectionner nos utilisateurs (cibles) (si c'est un Archipel pour faire des démos, alors les utilisateurs c'est nous, SemApps en interne, si c'est pour la communauté interne de l'AV alors les contributeurs (et on peut faire un Github-like?; si c'est pour le réseau de l'AV, alors une cartographie de l'eco système avec les acteurs, leurs idées ça peut être pas mal, mais de mon côté, c'est surtout leur besoin, leurs enjeux, leurs ressources qui sont intéressants à ce stade).


Si on se fait un Archipel pour cartographier notre réseau, je suis chaud pour l'utiliser et aller faire des interviews (podcast par exemple) sur les besoins, resources, envies de chacun. Pourquoi pas y associer des podcasts (travail en cours avec Lison).

Vilà, c'est difficle pour moi de répondre à la question sans avoir une vision plus "méta", une stratégie. Et pour moi, cette cartographie eco-systémique est vraiment cool, et pourra être utile pour faire des démos (même si ce n'est pas les démo qui conduiront l'orientation stratégique).

**Comment by srosset81** [comment]
Merci @bouviermullerp d'amener ces réflexions intéressantes et même essentielles :-)

Voilà mon avis sur les différentes raison d'être potentielles que tu as énoncées:

**1. Pour créer une espace de démo**
Pour moi c'est le moins intéressant. Cela ne va motiver personne de remplir des données si elles sont juste à usage de démo. S'il faut faire une vraie démo plus tard, je pense que ce sera plus simple de générer automatiquement des données bidons.

**2. Pour les contributeurs de l'AV**
Là je vois un vrai potentiel d'utilisation de la plateforme. Si les réunions, les compte-rendus, les différents cercles, les chantiers, les tâches, les contributeurs, les partenaires, etc, pouvaient se matérialiser via cette instance SemApps, cela permettrait d'avoir un réel cas d'usage. Etant au CA de l'AV, je pense qu'il y a de vrais besoin de ce côté-là.

**3. Pour cartographier l'écosystème**
Cela me semble intéressant mais j'ai plus de peine à situer concrètement une telle instance. De quel écosystème parle-t-on précisément ? Par nature, un écosystème peut continuellement s'étendre. Je pense qu'on peut amener des organisations partenaires à remplir leur profil, mais j'ai des doutes qu'elles viendront ajouter leurs événements, leur compte-rendus, sur une enième plateforme. Du coup ça va faire une instance nécessairement plus statique, qui permettra peut-être de visualiser l'écosystème, mais qui aura un usage quotidien réduit.

J'ai l'impression que le nom de domaine archipel.assemblee-virtuelle.org que l'on a finalement choisi pour héberger cette instance montre l'ambiguité du projet. Si c'est une plateforme à usage de l'AV, alors pourquoi parle-t-on d'un archipel ? (ce serait plutôt une île qu'un archipel) Si c'est pour cartographier un écosystème, pourquoi est-ce un sous-domaine de l'AV et pas d'une autre organisation ?

Je me demande aussi si vouloir faire une instance qui regrouperait l'ensemble des acteurs de "l'écosystème" n'est pas un contre-sens dans la philosophie du web sémantique et de SOLID. Est-ce qu'il ne serait pas plus logique de commencer à faire une instance AV, qui soit un miroir de l'activité de l'association, et ensuite de la relier à d'autres instances d'autres associations lorsqu'elles apparaîtront ?

Ou peut-être s'agit-il de deux projets qui ont leur propre sens et qu'il s'agirait de différencier clairement ? En tout cas pour moi le premier a un pérmiètre bien défini et un interlocuteur unique (l'AV), tandis que le deuxième devrait sans doute demander une concertation avec un grand nombre d'acteurs.

Ce sont en tout cas des questions fondamentales, qu'il sera sans doute nécessaire d'aborder de vive voix.

**Comment by bouviermullerp** [comment]
Très juste, je suis en phase avec tes réflexions @srosset81 .

Dans l'atente d'une discussion de vive voix (et d'une décision :) ), et pour ne pas bloquer les développeurs débtants, aurait-on un espace de "bac à sable" dans lequel on puisse venir ajouter une classe/jouer ? (je pense éventuellement à la précédente instance DMS ?) Sinon, possible de se limiter a du local ?

Pour alimenter la réflexion sur les usages 2 & 3 : 
- #2 interne à l'asso. Est-il possible de creuser ta réflexion ? En terme d'usage, je pense qu'il y forcément besoin d'un outil pour capturer les CR, les tâches, les partenaires, ... J'ai l'impression que SemApps est un outil _surdimensionné_ pour ce besoin, alors que d'autres pourrait le remplir. Autrement dit, quel est le besoin d'interopérabilité sous jacent ?

- #3 eco-système. Dans ma tête, je fait le parallèle avec la raison d'être de l'AV: favoriser les synergies des acteurs de la transition par la mise en réseau de leur système d'information (qui peut se rapporter au point #2 :) )
Il me semble que la place de l'AV ne se trouve pas sur le partage (simple) d'évènement, mais sur une analyse et une mise en action de "comment peut on mettre en réseau, mutualiser). Par exemple, un collectif ami pourrait remplir son profil sur archipel (dans l'attente d'avoir son instance) et nous, on viendrait cartographier/Référencer ses besoins, ses ressources, ses challenges. On pourrait également cartographier les différentes briques de SemApps et lesquelles il a financer, les quelles il a besoin, etc.. (est-ce que tu vois ou je veux en venir ?). Un cas d'usage que vient de publier Solucracy (avec notr ami Grezi) pour expliciter peut etre un peu mieux https://solucracy.org/fr/carto-acteurs-locaux

**Comment by tfrancart** [comment]
Bonjour

La définition d'arborescence détaillées de types ne devrait pas se faire directement dans PAIR. Cela devrait prendre la forme de vocabulaires contrôlés type SKOS, donc des _instances_ de IdeaType, ResourceType, ActivityType, OrganizationType, etc... organisées hiérarchiquement.

Ces arborescences pourront ne pas avoir le même cycle de vie que le modèle PAIR. Ces vocabulaires contrôlés seront distribués dans des fichiers à part entitère.

Cela permet à des utilisateurs de redéfinir plus facilement leur propres types. Egalement d'étendre plus facilement la liste des types.

Cela permet de distribuer/visualiser ces vocabulaires contrôlés dans des outils types Skosmos : http://vocabs.sparna.fr

Cependant, s'il y a certain types de choses pour lesquelles des propriétés plus précises sont nécessaire, alors ces types feront l'objet de sous-classes dans l'ontologie.

Ce ne change rien du tout sur le fond et sur la nécessité (ou pas de le faire), je précise juste mon point de vue sur l'implémentation technique de la chose.

A+
Thomas

**Comment by srosset81** [comment]
> Dans l'atente d'une discussion de vive voix (et d'une décision :) ), et pour ne pas bloquer les développeurs débtants, aurait-on un espace de "bac à sable" dans lequel on puisse venir ajouter une classe/jouer ? (je pense éventuellement à la précédente instance DMS ?) Sinon, possible de se limiter a du local ?

Il est possible de faire des modifications sur Archipel en local puis même de les déployer sur un URL temporaire avec [Vercel](https://vercel.com/download). C'est aussi possible de faire une branche à part avec ces changements, même s'ils ne sont pas amenés à être fusionnés avec la branche principale.
La précédente instance DMS est toujours là mais elle n'est plus mise à jour.


> Pour alimenter la réflexion sur les usages 2 & 3 :
> 
> * #2 interne à l'asso. Est-il possible de creuser ta réflexion ? En terme d'usage, je pense qu'il y forcément besoin d'un outil pour capturer les CR, les tâches, les partenaires, ... J'ai l'impression que SemApps est un outil _surdimensionné_ pour ce besoin, alors que d'autres pourrait le remplir. Autrement dit, quel est le besoin d'interopérabilité sous jacent ?

C'est une bonne question. On passe beaucoup par Github pour le moment et ça marche plutôt bien. Ce qui manque actuellement c'est de la visiblité sur les rôles/cercles (important pour dynamiser la gouvernance à mon avis). Pour les partenaires, le CA est en train de réfléchir à un CRM, mais je trouve dommage de passer par un nouvel outil alors que SemApps pourrait bien convenir. Et il y aussi cette question de "chantiers collaboratifs" qui me semble important, mais qui ne regarde pas seulement l'AV, même si ces chantiers pourraient se réaliser dans le cadre de l'AV.

Il n'y a pas un fort besoin d'interopérabilité sur ces différents sujets, mais pour moi l'intérêt c'est surtout d'être dans la philosophie de l'open data. Si toutes ces informations sont ouvertes, on pourra imaginer de nouveaux outils pour voir/traiter ces données, ou permettre à des partenaires de les utiliser. Tant qu'on reste sur Github, on est assez bloqué.

> * #3 eco-système. Dans ma tête, je fait le parallèle avec la raison d'être de l'AV: favoriser les synergies des acteurs de la transition par la mise en réseau de leur système d'information (qui peut se rapporter au point #2 :) )
>   Il me semble que la place de l'AV ne se trouve pas sur le partage (simple) d'évènement, mais sur une analyse et une mise en action de "comment peut on mettre en réseau, mutualiser). Par exemple, un collectif ami pourrait remplir son profil sur archipel (dans l'attente d'avoir son instance) et nous, on viendrait cartographier/Référencer ses besoins, ses ressources, ses challenges. On pourrait également cartographier les différentes briques de SemApps et lesquelles il a financer, les quelles il a besoin, etc.. (est-ce que tu vois ou je veux en venir ?). Un cas d'usage que vient de publier Solucracy (avec notr ami Grezi) pour expliciter peut etre un peu mieux https://solucracy.org/fr/carto-acteurs-locaux

Je vois mieux. Je suis un peu surpris par la phrase "nous, on viendrait cartographier/référencer ses besoins, ses ressources, ses challenges", car je pensais pas que c'était dans notre raison d'être de faire le travail nous-mêmes, mais pourquoi pas ! Le risque c'est qu'on prenne une jolie photo d'un instant T, mais que ces données deviennent rapidement obsolètes, alors que si ce sont des données qui sont utiles pour les organisations, elles seront naturellement plus à jour.

Concernant les "briques de SemApps", pour moi c'était quelque chose qui était justement de l'ordre de l'interne à l'AV, mais ça dépend du point de vue j'imagine ;-)

En fait, plutôt que de se demander si c'est des choses "internes" ou "externes" à l'AV, j'ai l'impression qu'une meilleure question serait: est-ce que l'instance archipel.assemblee-virtuelle.org est AV-centric, c'est-à-dire qu'elle met en avant les technologies, besoins, projets, etc, de l'AV, ou bien est-ce qu'elle est organisation-agnostic, et donc l'AV n'est pas privilégiée par rapport à d'autres organisations ?

Bref, j'ai un peu la tête qui tourne là, mais il y a des grosses discussions à avoir, à mon avis aussi en lien avec la refonte de l'AV.

**Comment by GuillaumeAV** [comment]
Helloo tout le monde ! 

Très intéressante cette discussion ! Voici ci-dessous ma vision ... 

Sur la définition et le périmètre d'archipel, je me dis qu'Archipel est un "produit" basé sur SemApps + PAIR, destiné à outiller les organisations, communautés, archipels dans leurs modes d'organisation en réseau. 

Là ou SemApps adresse le **volet technique** des modes d'organisation en réseau, Archipel en adresse le **volet métier** : 

- Base de connaissance sémantique & collaborative : Alimenter collectivement une base de connaissance communautaire
- Annuaire des PAIRs : Disposer d’un annuaire sémantique de la communauté : Des acteurs, des organisations, des projets + leur contexte : leurs amis, leurs responsables, leurs contributeurs etc
- Agenda : Créer et partager des agendas "sémantiques" avec possibilité de filtrer par thématique, acteur, projet, date, etc.
- Market place : Matching sur les concepts de l'ontologie, mais également sur des concepts issus de sources externes : DBpedia par exemple (version sémantique de Wikipedia).
- Gestion de projet 
- Etc.

archipel.assemblee-virtuelle.org constitue la vitrine du produit Archipel, et doit permettre à l'Assemblée Virtuelle de travailler en réseau, en adressant les fonctions listées ci-dessus ... 
Cette perspective inclut nécessairement une dimension cartographie communautaire : On ne peut pas travailler en réseau sans avoir accès à l'information sur le réseau ... 
On peut je crois du coup synergiser plutôt qu'opposer les 2 approches : usage interne collaboratif (finalité) + cartographie (moyen)
Si on fait la preuve de concept qu'on bosse efficacement en réseau grâce à archipel, d'autres communautés seront potentiellement chaudes pour faire de même, et on pourra alors s'intéropérer ...  

Seuls les membres et partenaires AV devraient pouvoir y accéder en écriture (Après on aura les ACL ce sera plus fin..., on pourra même donner des droits en écriture sur une partie de la base en mode bac à sable ?)

**Comment by simonLouvet** [comment]
Il me semble que nous avions décidé en Normandie que archipel devait être (entre autre) notre espace de démo technique et que cela prévalait au besoin fonctionnel de l'AV. Nous en étions arrivé à cette conclusion notamment par rapport au menu arborescent. Est ce que nous remettons en cause cette décisions?

**Comment by GuillaumeAV** [comment]
Pour moi ce n'est pas incompatible, au contraire ... Il faut qu'on soit en capacité de démontrer qu'Archipel peut être utile et fonctionnel pour une communauté ..

**Comment by srosset81** [comment]
Pour moi la décision qui a été prise pendant la résidence était de ne pas trop s'occuper de l'UX d'Archipel, car le périmètre de cette plateforme est trop flou. On restait donc plutôt sur une interface type "backoffice", et c'est dans ce sens qu'a été ajouté le menu hiérarchique de côté. Mais pour moi ça ne voulait pas dire qu'Archipel devenait un "espace de démo technique". Il faut quand même qu'il permette d'inclure des données pertinentes pour l'AV. Je me cite volontiers:

> Cela ne va motiver personne de remplir des données si elles sont juste à usage de démo. S'il faut faire une vraie démo plus tard, je pense que ce sera plus simple de générer automatiquement des données bidons.

Comme nous n'avons pas été en capacité de prendre une décision en 2 semaines, je propose de rester pour le moment sur la décision de la résidence concernant Archipel, en attendant qu'on trouve un espace de discussion sur le sujet. De mon côté, j'ai proposé au CA de faire un mini-site basé sur SemApps qui présente les différents rôles que nous avons définis pour la gouvernance de l'AV (cf https://github.com/assemblee-virtuelle/vie-asso-av/issues/104). Je trouve qu'en faisant ça, on reste dans la philosophie du web sémantique, à savoir de proposer de multiples interfaces basées potentiellement sur les mêmes données. 

Dernières remarque: pour inclure les rôles dans data.virtual-assembly.org, on va ajouter un container `/groups` et  une classe `pair:Group` (on ne peut pas utiliser le concept de `pair:Role`, car il pourra y avoir plusieurs relations par rapport à ces rôles: référent, soutien, contributeur). Du coup je vois cet après-midi si un des débutants SemApps est motivé pour ajouter `pair:Group` sur le "back-office" Archipel, ce qui sera un exercice facile et utile.

**Comment by GuillaumeAV** [comment]
Super ! Si tu implémentes les rôles sur le mini site, ça pourrait valoir le coup d'implémenter aussi les tâches non ?

**Comment by srosset81** [comment]
J'ai créé des issues pour les ajouts qui peuvent être fait en vue de la [nouvelle instance SemApps](https://github.com/assemblee-virtuelle/semapps/wiki/R%C3%A9union-brainstorming-interface-AV-17-02-2021):

https://github.com/assemblee-virtuelle/semapps/issues/599
https://github.com/assemblee-virtuelle/semapps/issues/600
https://github.com/assemblee-virtuelle/semapps/issues/601

L'idée est donc qu'un bon UX soit proposé sur la nouvelle instance, mais qu'on rende tout de même ces données visibles sur Archipel avec un UX basique type "back-office".

Du coup je ferme cette issue qui est résolue pour le moment.
