### ISSUE TITLE
Indiquer les breaking changes sur les releases

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#562]
Trouver la manière la plus efficace et la plus facile pour noter les breaking changes sur les releases:

https://github.com/assemblee-virtuelle/semapps/releases

**Comment by srosset81** [comment]
Attention: pour l'instant on a un tag pour le middleware, et le tag pour le frontend n'est pas publié. On ne peut donc pas noter les breaking changes sur le frontend. 

Au préalable, il faudrait donc voir si on arrive à dissocier les packages frontend et middleware. ?

@simonLouvet

**Comment by simonLouvet** [comment]
j'ai vu ca et c'a fait chi...
la seul solution que je voies c'est front.X.X.X / back.X.X.X pour différencier les 2.

**Comment by srosset81** [comment]
J'ai vu certains projets OS qui faisaient ça en effet, mais je ne retrouve plus lesquels. Je regarde s'il y a d'autres solutions.

Sinon je suis tombé sur ce logiciel qui permet d'automatiser pas mal de choses. Mais je sais pas s'il pourrait bien gérer des packages front/back différents. Je vais y passer un peu de temps.
https://github.com/release-it/release-it

**Comment by srosset81** [comment]
Pour info j'ai fait un publish des packages du front, il y avait des breaking changes mais j'ai pas fait une major release car sinon les packages front serait passé avant les packages middleware au niveau du numéro de version, et ça aurait rendu les choses encore plus illisibles.
Il faut donc qu'on résolve ce problème front/middleware avant de pouvoir appliquer nos décisions.

**Comment by srosset81** [comment]
Une solution serait d'utiliser le mode independent pour le versioning.
https://samhogy.co.uk/2018/08/lerna-independent-mode-with-semver.html
Cela a pour résultat que, plutôt que d'avoir qu'un seul tag pour tout le repo, on aurait un tag par package.
On pourrait quand même forcer le packages front et middleware d'être publiés ensemble.
L'inconvénient au niveau des releases https://github.com/assemblee-virtuelle/semapps/releases c'est qu'on aurait 20 tags qui s'ajouteraient en même temps, donc plus difficile de rendre visible. On pourrait éventuellement utiliser le blog https://semapps.org/blog pour informer des releases.

Autre réflexion: plutôt que d'utiliser uniquement le versioning X.Y.Z, on pourrait utiliser X.Y.Z-beta.1, X.Y.Z-beta.2. Cela permettrait de publier des packages beta, utilisables immédiatement par nous, mais de publier une version majeur que lorsque tout est prêt. On éviterait ainsi d'augmenter trop rapidement les numéros de versions. De plus, les développeurs sauraient qu'en utilisant un package marqué comme beta, il y a plus de risques qu'il y ait des problèmes.

**Comment by srosset81** [comment]
@simonLouvet J'ai fait une release en utilisant l'independent versioning: https://github.com/assemblee-virtuelle/semapps/commit/8706ec9f710755edc5bbdf56ea7c475b1875bd85
Ca ne change pas grand chose, sauf qu'il faut valider le choix de version pour chaque package.
Le changement principal c'est que ça crée un tag pour chaque package https://github.com/assemblee-virtuelle/semapps/releases
C'est un peu moins clean, mais ça pourrait permettre de mieux gérer le numéro de version pour le front et le middleware.
Pour éviter de multipler le numéro de minor changes, je propos d'utiliser le suffixe `-alpha.X`, comme je l'ai fais. Ca permettrai de regrouper des breaking changes et de publier l'ensemble des breaking changes (pour une nouvelle version mineur) dès que l'on est prêt, sans toutefois devoir attendre.

**Comment by simonLouvet** [comment]
J'y ai réfléchi plusieurs fois depuis nos dernière discussions et j'ai une autre proposition que  `"version": "independent"`.
nous pourrions tout simplement avoir deux application différentes en terme de package. Actuellement tout est relié à @semapps. nous pourion dissocié les tags en @semapps-server et @semapps-archipel et @semapps-dms et @semapps-react....
Cela résout le probleme des tags, ne remet pas en cause le mono-repo et me semble plus lisible pour les utilisateurs (développeurs).

Je ne voie pas vraiment l’intérêt des alpha sauf pour des versions majeurs. je ne voie pas le probleme de multiplier le numero de minor change.

**Comment by srosset81** [comment]
C'est une idée intéressante. Normalement le [scope](https://docs.npmjs.com/cli/v6/using-npm/scope) est lié à une organisation, mais apparemment c'est possible de faire des scopes différents.
Personnellement j'éviterai quand même de démultiplier les scopes. Je me limiterais à `semapps-front` et `semapps-back`.

> Cela résout le probleme des tags, ne remet pas en cause le mono-repo et me semble plus lisible pour les utilisateurs (développeurs). 

Ca ne les résout pas, car en version non-indépendent, le tag est lié au numéro de version, pas au nom des packages. Mais je vais regarder si, avec Lerna, on peut créer des tags avec un scope (genre `front-0.1.18`).

> Je ne voie pas vraiment l’intérêt des alpha sauf pour des versions majeurs. je ne voie pas le probleme de multiplier le numero de minor change.

L'avantage des alpha/canary/etc c'est qu'on peut publier plusieurs BC et les tester sur des projets, sans multiplier les releases. Si tu fais 10 changements mineurs avec BC, non seulement tu devras augmenter le numéro de version mineur, mais il faudra publier 10 release qui documentent les BC. C'est donc plus léger et plus facile (pour les développeurs core comme pour les développeurs "utilisateurs") de regrouper et de sortir une version mineur quand il y a un vrai changement.

Je dis pas qu'il faut le faire tout de suite, mais c'est un outil super utile à long terme, et c'est pour cela que ça existe ;-)

**Comment by srosset81** [comment]
Il y a une option [--tag-version-prefix](https://github.com/lerna/lerna/blob/main/commands/version/README.md#--tag-version-prefix) qui permettrait de tagger les packages `frontend-0.1.2` ou `middleware-0.2.3` mais sans pour autant que ça ne change le numéro de version sur NPM (d'après ce que je comprends).

Du coup on aurait plus besoin d'utiliser le versioning `independent`.

Je suis pour essayer ça. 

Quant à changer le scope du package, ça me semble être un gros changement qui ne doit pas être pris à la légère. Il a l'intérêt de bien dissocier les packages front et back, mais ça fait des noms de packages à rallonge (`semapps-front@semantic-data-provider`). De plus, si à un moment on a des packages "utilitaires" qui peuvent être utilisés en frontend et backend, on ne saura plus comment les tagger.

**Comment by simonLouvet** [comment]
Cette solution me semble pertinente

**Comment by srosset81** [comment]
Je viens de publier des packages front et middlware, et j'ai testé, ça marche bien:
https://github.com/assemblee-virtuelle/semapps/releases
Ca va permettre de pouvoir attacher des messages aux releases, notamment pour indiquer les breaking changes.

**Comment by simonLouvet** [comment]
j'ai pas compris comment attacher des messages.

**Comment by srosset81** [comment]
On peut lier une release à chaque tag.
Ca peut être fait manuellement ici: https://github.com/assemblee-virtuelle/semapps/releases/new
Il y a une option dans Lerna pour faire ça de manière plus automatique: https://github.com/lerna/lerna/tree/main/commands/version#--create-release-type
C'est à expérimenter...
