### ISSUE TITLE
Prendre en compte les droits ACL en lecture et en écriture

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#569]
Se référer à ce document: https://hackmd.io/LD_u-qoNQhm2p-UMEflTjg

**Comment by nikoPLP** [comment]
Je propose de modifier ceci :
Fuseki reçoit du middleware un header X-SemappsUser avec `anon` si l’utilisateur n’est pas connecté.
Car l'absence de ce header, ou l'absence d'une valeur, est déjà utilisé comme un synonyme de `system`.
Ca marche pour vous @srosset81 et @simonLouvet ?

**Comment by nikoPLP** [comment]
Pouvons nous décider à propos de ça :
Questions:
- A quoi correspond `acl:Append` pour les containers et pour les resources ?
    - Pour les containers: possibilité d'ajouter une nouvelle resource dans le container.
    - Pour les resources: possibilité d'ajouter des triplets à la resource, mais pas d'en supprimer.
- A quoi correspond `acl:Write` pour les containers ?
    - possibilité de modifier les paramètres du container (nom?, ... quoi d'autre?)
    - possibilité d'ajouter ou d'enlever des resources. Si la ressource est contenue uniquement dans ce container, alors elle doit etre supprimée au moment ou elle est enlevée du container. Cecic ne peut etre fait que si l'utilisateur à le droit WRITE sur la resource. 
    - ~~Possibilité d'ajouter des resource ou de supprimer le **lien** vers certaines resources. La suppression de la resource elle-même dépend de ses propres ACLs.~~

**Comment by nikoPLP** [comment]
The permissions are only checked on the Subject of any tuple. Therefor all relations to other resources are visible when the user has access to a Resource and if the relation is of the form AccesibleResource -> relation -> AnyOtherResource.

Note that blank nodes cannot receive Authorization with webACL so I don't know what to do with them. Let anyone see them? or nobody?

**Comment by srosset81** [comment]
> The permissions are only checked on the Subject of any tuple. Therefor all relations to other resources are visible when the user has access to a Resource and if the relation is of the form AccesibleResource -> relation -> AnyOtherResource.

Cela semble être inévitable. Un utilisateur qui n'a pas accès pourra voir l'URI de la ressource, mais pas son contenu.

> Note that blank nodes cannot receive Authorization with webACL so I don't know what to do with them. Let anyone see them? or nobody?

Aïe on avait pas pensé à ça. :-/ Les blank nodes sont généralement liés à une ressource avec un ID. Voir par exemple le prédicat `pair:hasLocation` sur cette URI: https://data.virtual-assembly.org/organizations/cheznous_mareuil. Ne pourrait-on pas vérifier les ACL de la ressource parent ? 

Remarques:
- Dans l'exemple ci-dessus, il peut y avoir plusieurs blank nodes imbriqués les uns dans les autres (Place > PostalAddress).
- Si le blank node n'est pas relié à une ressource IDentifiée, cela veut dire qu'il est en théorie visible nulle part (node orphelin). A mon avis on peut dire à ce moment qu'il n'est visible de personne.

Si c'est trop compliqué, on pourrait dire que les blank nodes sont visibles de tous, mais ça laisse quand même une faille au niveau des données.

**Comment by srosset81** [comment]
> Pouvons nous décider à propos de ça :
>
> * A quoi correspond `acl:Append` pour les containers et pour les resources ?
>   
>   * Pour les containers: possibilité d'ajouter une nouvelle resource dans le container.
>   * Pour les resources: possibilité d'ajouter des triplets à la resource, mais pas d'en supprimer.

Cela semble cohérent.

> * A quoi correspond `acl:Write` pour les containers ?
>   
>   * possibilité de modifier les paramètres du container (nom?, ... quoi d'autre?)
>   * possibilité d'ajouter ou d'enlever des resources. Si la ressource est contenue uniquement dans ce container, alors elle doit etre supprimée au moment ou elle est enlevée du container. Cecic ne peut etre fait que si l'utilisateur à le droit WRITE sur la resource.
>   * ~Possibilité d'ajouter des resource ou de supprimer le **lien** vers certaines resources. La suppression de la resource elle-même dépend de ses propres ACLs.~

Il faut qu'on en rediscute. C'est pas clair pour moi.

**Comment by nikoPLP** [comment]
> The permissions are only checked on the Subject of any tuple. Therefor all relations to other resources are visible when the user has access to a Resource and if the relation is of the form AccesibleResource -> relation -> AnyOtherResource.
> 
> Note that blank nodes cannot receive Authorization with webACL so I don't know what to do with them. Let anyone see them? or nobody?

Decision: blank nodes that are not attached to any resource, should not be returned !

**Comment by nikoPLP** [comment]
> Il faut qu'on en rediscute. C'est pas clair pour moi.

Clarification: il s'agit des cas où une ressource se treouve dans plusieurs containers et qu'on appele une API qui enlève la ressource d'un des containers, puis ainsi de suite jusqu'à enlever la ressource de son dernier container. Dans ce cas, la ressource se retrouve sans container, ce qui va lui poser un problème pour avoir une URI...

Mais, comme pour le moment, les actions attach et detach une ressource de son container, ne sont pas accessibles publiquement, et que la ressource ne peut etre détruite que par l'action DELETE (qui se charge d'enelever la ressource de son container), alors le problème ne se pose pas pour le moment.
