### ISSUE TITLE
Connaître les droits ACL d'une ressource ou d'un container

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#571]
## Raison d'être
En terme de frontend, c'est très utile de pouvoir connaître les droits sur une ressource ou un container. Cela évite par exemple de mettre un bouton "Editer" si l'utilisateur n'a que des droits de visualisation. Cela évite d'attendre l'erreur 403 !

## Spécifications
Il existe une [spécification](https://github.com/solid/web-access-control-spec/blob/master/README.md#acl-resource-location-discovery) pour découvrir les ACL d'une ressource.

```
HEAD /docs/file1 HTTP/1.1
Host: example.org

HTTP/1.1 200 OK
Link: <file1.acl>; rel="acl"
```

## Implémentation
Dans notre cas, pour faciliter la gestion des routes API, les ressources seront localisées sur un URL de type `/_acl/{resourcePath}`. Par exemple pour `/organizations/assemblee-virtuelle`, les ACLs seront visibles sur `/_acl/organizations/assemblee-virtuelle`.

Quelques remarques concernant cet endpoint:
- Seules les utilisateurs qui ont un droit `acl:Control` sur la ressource peuvent voir tous les droits ACL associés.
- Les utilisateurs qui n'ont pas le droit `acl:Control` pourront seulement voir leurs propres permissions.
- Si la ressource n'a pas de permissions spécifiques, il faut retourner les permissions par défaut du container parent.
- Le même méchanisme est utilisé pour connaître les ACL des containers. Pour connaître les droits sur le container racine (et donc les droits par défaut sur tout le serveur LDP), il suffira de fetcher l'URL `/_acl`

> C'est au middleware de gérer cette gestion des droits, Fuseki ne s'occupe pas des droits sur les webacl car ces triplets là sont invisibles sur l'endpoint SPARQL public.

**Comment by nikoPLP** [comment]
implementé ainsi :

- `GET /_acl/{resourcePath}`
    - Retourne les droits sur la ressource.
        - Si l'utilisateur a un droit `acl:Control` sur la ressource, retourne toutes les informations, sinon retourne seulement les informations qui concerne l'utilisateur connecté.
        - Dans tous les cas, retourne les `acl:default` de tous les containers parents (auxquels l'utilisateur a acces).
        - Si la ressource est un container, retourne les droits du container.

- `GET /_rights/{resourcePath}` permet d'obtenir un object JSON qui contient 4 boolean membres: un pour chaque mode de permission (read, write, append, control)
-  `POST /_rights/{resourcePath}` permet d'obtenir un sous-ensemble des permissions du GET. si on n'est interessé que par la permission write, il suffit d'envoyer dans le body du POST :
```
{ rights : { write: true } }
```

**Comment by srosset81** [comment]
Si je comprends bien le path `/_acl` retourne des ACLs conformes aux standards WebACL, alors que le path `/_rights` renvoie un JSON plus facilement digestible côté frontend ?
C'est intéressant comme option, merci. Après au niveau frontend, je pense que j'essaierai quand même de privilégier l'utilisation des standards pour que l'interface ne soit pas dépendante d'un serveur SemApps.
