### ISSUE TITLE
Modifier les droits ACL d'une ressource ou d'un container

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#572]
## Raison d'être
Il serait important que, depuis le frontend, on puisse facilement changer les droits sur une ressource ou un container. Cela permettrait, par exemple, de donner un droit d'écriture sur une ressource. Il faudrait pour cela passer par des standards.

## Spécifications
Dans les [anciennes specs](https://www.w3.org/wiki/WebAccessControl), il est expliqué le moyen de modifier les ACL d'une ressource LDP. Mais cela passe par une requête SPARQL update (`application/sparql-update`) qui semble dangereuse et sans doute plus trop d'actualité.

Il est indiqué dans les implémentations que, dans le projet [rwwPlay](https://github.com/read-write-web/rww-play), les ACL sont éditables en utilisant le protocole LDP.

Cette dernière approche semble plus cohérente que du SPARQL update.

> Il serait toutefois intéressant de connaître l'avis de l'équipe SOLID et/ou Startin'Blox sur ce point. 

## Implémentation
- On fait un PUT ou PATCH sur l'endpoint `/_acl/{resourceUri}`, de la même manière que les ressources LDP.
- Cette opération n'est autorisée que si l'utilisateur connecté à un droit `acl:Control`

**Comment by nikoPLP** [comment]
A ce propos, il reste une incertitude sur comment appeler les resources (RDF nodes) qui contiennent les info d'authorization pour chaque resource.
la doc webACL met des `<#authorization1>` dans ses exemples. Mais il faut rajouter une baseURL... et surtout, comment créer cet identifiant ? un numéro de série ? un compteur incrémental ?
Voir ce que que fait inrupt [ici](https://forum.solidproject.org/t/how-to-change-the-sharing-settings-for-a-resource/114/22)
Apparement ils créent un noeud `acl:Authorization` par type de droit : `ControlReadWrite`, `Read`, `ReadWrite` ...
C'est pas bete, ca permet de savoir où aller chercher le bon noeud `acl:Authorization` quand on veut rajouter ou enlever des permissions.

enfin, dans ce document, on trouve un `defaultForNew`... tiens tiens... ca ne fait pas partie de la spec, mais ca repond a notre question des "templates" de permission.
Voir ce document ou l'option est [débatue](https://github.com/solid/solid-spec/blob/master/acl-inheritance.md)

Dans l'attente de vos feedbacks, @srosset81, @simonLouvet et Thomas ou les personnes proche de Solid/Inrupt.

**Comment by srosset81** [comment]
Je trouve que l'option `defaultForNew` est la plus facile à utiliser, la plus performante et qu'elle mériterait d'être mise en avant, même si on se doit de respecter toutes les autres options des specs. Apparemment elle est déjà implémentée dans le serveur Solid.

https://github.com/solid/solid-spec/blob/master/acl-inheritance.md

Ping @tfrancart pour info.

**Comment by nikoPLP** [comment]
le PATCH ne pourra qu'ajouter des `agent`, `agentClass` ou `agentGroup`.
le PUT remplacera toutes les données `agent`, `agentClass` ou `agentGroup`. Voir si un diff de l'existant ne serait pas plus sain à faire. Le reste des données visibles dans le fichier acl ne sont pas modifiables. 

Les permissions héritées d'un container sont affichées dans le fichier d'acl d'une ressource, mais ne sont pas modifiables par PATCH ou PUT sur la ressource en question. Il faut se rendre sur le fichier ACL du container pour les modifier.

Pour une ressource, nous gérons 4 `Authorization` différentes: `#Read` `#Write` `#Append` et `#Control`.
En dessous, se trouvent les Authorization qui viennent d'un container, avec une URI de la forme: https://domain.com/_acl/container1#DefaultRead

Pour un container, nous gérons 8 `Authorization` différentes: `#Read` `#Write` `#Append`, `#Control`, `#DefaultRead`, `#DefaultWrite`, `#DefaultAppend`, `#DefaultControl`.
En dessous, seront affichées les Authorization qui viennent des containers parents. non modifiable in-situ non plus.
