### ISSUE TITLE
Attribuer les droits à la création d'une ressource

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#573]
## Spécifications
Dans les dernières specs de WebACL, il a été décidé de ne pas prendre en compte la notion de [Resource Owner](https://github.com/solid/web-access-control-spec/blob/master/README.md#resource-owners). 
Il faut néanmoins donner certains droits (surtout `acl:Control`) au créateur d'une ressource pour qu'il puisse continuer à la gérer.

## Implémentation
- Quand un utilisateur crée une ressource, lui donner les droits `acl:Read`, `acl:Write` et `acl:Control` sur cette ressource.
- Si la ressource est créée par un utilisateur anonyme (mode "wiki"), donner les droits `acl:Read` et `acl:Write` à tous les agents ([foaf:Agent](https://github.com/solid/web-access-control-spec/blob/master/README.md#public-access-all-agents)]

Le service `webacl` pourrait écouter les événements `ldp.resource.created` et attribuer les droits à ce moment.
On pourrait imaginer une config dans le service `webacl` qui permettrait de définir quels sont ces droits par défaut.

**Comment by nikoPLP** [comment]
les droits doivent etre ajouté au triple store AVANT de créer les triples de la resource elle même.

**Comment by nikoPLP** [comment]
Voir [ce commentaire à propos de `defaultForNew`](https://github.com/assemblee-virtuelle/semapps/issues/572#issuecomment-783442281)

**Comment by nikoPLP** [comment]
l'action `webacl.resource.addRights` avec les parametres suivants est appelée avant de créer la resource dans le triplestore.
```
{
      resourceUri: '< URI of the resource >', 
      webId: 'system' // ne pas changer
      newRights: {
          anon: {
            read: true,
            write: true,
            append: false,
            control: false,
          },
          user: {
            uri: '<URI of owner>'
            read: true
            write: true
            append: false
            control: true
          }
     } 
}
```

attention: utilisez addRigths avec le paramatre newRights seulement pour les nouvelles resources pas encore créées. pour les resources deja existantes, utilisez `additionalRights`

**Comment by nikoPLP** [comment]
Pour les nouveaux containers, la logique est la suivante :
- si c'est le system qui crée le container, on applique les droits Read pour anon, et Read+Write pour tous les utilisateurs identifiés.
- si c'est l'utilisateur anonymous qui crée le container, on donne Read et Write a anonymous.
- si c'est un utilisateur authentifié qui crée le container, on donne Read+Write+Control pour cet utilisateur.

Nous n'ajoutons as de droits par defaut sur les nouveux containers. il faut le faire par la suite, si besoin, en appelant `addRights` avec le parametre `additionalRights`

Enfin, iil semble que 2 options a propos des droits des containers se trouvent dans le code. `allowAnonymousEdit` et `allowAnonymousDelete`.

* `allowAnonymousEdit` concerne :
    * POST sur le container : la creation de nouvelle resource dans ce container. Cette permission n'est pas ajoutée pour le moment en webacl lors de la création du container. question: faut il rajouter Append pour les anonymous sur chaque container au moment de sa création ?
    * PUT et  PATCH sur la resource (cad modifier la resource). il faudrait donc mettre des droits DefaultWrite pour anonymous, sur le container. ce n'est pas fait pour le moment.
* `allowAnonymousDelete` concerne la suppression d'une ressource dans le container. il faudrait ajouter DefaultWrite pour anonymous sur le container, et aussi Write pour anonymous, sur le container lui-meme. Ce n'est pas fait pour le moment.

@srosset81 ?

**Comment by srosset81** [comment]
`allowAnonymousEdit` et `allowAnonymousDelete` avaient été ajoutés de manière temporaire et elle est peu utilisée.
Je pense qu'il pourrait être plus clair d'utiliser une option qui se rapproche de celle de l'action `webacl.resource.addRights` dont tu donnes un exemple au-dessus.
