### ISSUE TITLE
Gérer correctement les erreurs de permission

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#574]
Si un utilisateur essaie de voir ou modifier une ressource sans en avoir le droit, Fuseki doit renvoyer une erreur claire, et le middleware doit renvoyer une erreur 403 au frontend.

**Attention**: Si on fait une requête de type `DELETE { } INSERT { } WHERE { }` et que l'utilisateur a seulement le droit `acl:Append`, la requête `INSERT` va fonctionner mais pas la requête `DELETE`. Il faut que toute la requête soit refusée.

**Comment by nikoPLP** [comment]
Une issue avec un patch corrigeant ce probleme dans fuseki a été soumis à Jena.
https://issues.apache.org/jira/browse/JENA-2055

en attendant, il suffit de rempalcer le fichier `fuseki-server.jar` par celui que je vens de compiler. Mais... je ne sais pas comment l'envoyer (il fait 29 MB)

**Comment by nikoPLP** [comment]
> Si on fait une requête de type `DELETE { } INSERT { } WHERE { }` et que l'utilisateur a seulement le droit `acl:Append`, la requête `INSERT` va fonctionner mais pas la requête `DELETE`. Il faut que toute la requête soit refusée.

Cette partie a été vérifiée. Si le delete est refusé, c'est toute la transaction qui est annulée et on recoit bien une erreur 403

**Comment by nikoPLP** [comment]
The issue in Jena is fixed, it will appear in the next version 4.0.0. When it is released, we will switch to that version.
I already tested with their working branch and it works well.
https://issues.apache.org/jira/browse/JENA-2055
