### ISSUE TITLE
Gérer des groupes webACL

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#575]
## Spécifications

Les specs WebACL permettent de définir des [groupes d'agents](https://github.com/solid/web-access-control-spec/blob/master/README.md#groups-of-agents). On utilise pour ça la classe `vcard:Group`:

```turtle
<#Accounting>
    a                vcard:Group;
    vcard:hasUID     <urn:uuid:8831CBAD-1111-2222-8563-F0F4787E5398:ABGroup>;
    dc:created       "2013-09-11T07:18:19Z"^^xsd:dateTime;
    dc:modified      "2015-08-08T14:45:15Z"^^xsd:dateTime;

    # Accounting group members:
    vcard:hasMember  <https://bob.example.com/profile/card#me>;
    vcard:hasMember  <https://candice.example.com/profile/card#me>.
```

On peut ensuite donner les droits d'une ressource à un groupe plutôt qu'à un utilisateur en particulier, via le prédicat `acl:agentGroup`.

## Implémentation
- Lorsqu'on crée une organisation, on pourrait créer un `vcard:Group` et lorsqu'on y ajoute des membres, on les marquent comme membre (`vcard:hasMember`) de ce groupe.
- D'autres classes, comme les `Roles` PAIR, pourraient être plus adéquat. Cela permettrait d'ajouter par exemple un groupe de modérateur, ou d'administrateurs.
- Quelle que soit l'ontologie utilisée, il faudra trouver le moyen de synchroniser les données métiers avec les groupes WebACL.
  - Cela pourrait éventuellement être fait par le service ci-dessous, qui pourrait être configuré pour écouter l'ajout de certaines relations et ajouter ou supprimer les membres en fonction.
  - Une autre possibilité serait de définir quelque part (dans l'ontologie PAIR ?) une relation [owl:sameAs](https://www.w3.org/TR/owl-ref/#sameAs-def) ou [owl:equivalentProperty](https://www.w3.org/TR/owl-ref/#equivalentProperty-def). Et ensuite utiliser l'inférence service pour synchroniser les données.

Il y a aussi le problème de créer une route pour accéder au groupe, afin qu'il soit consultable.
-  Si on attache le `vcard:Group` à une données métier, on pourrait utiliser directement l'URI de la classe métier, sans avoir besoin de recréer des URIs spécifiques.
- Autre possibilité: définir un container spécial avec comme chemin `/_groups/`
- Sinon, comme pour ActivityPub, on pourrait configurer un container LDP avec un `acceptedTypes` défini à `vcard:Group`. Le service Moleculer saurait que c'est dans ce container qu'il faut mettre les groupes.

## Service Moleculer
On pourrait créer un service `webacl.group` avec ces actions:

- `create({ groupUri })` 
  - Crée un `vcard:Group` avec l'URI indiqué
- `attach({ resourceUri })`
  - Attach le type `vcard:Group` à une ressource existante
- `addMember({ groupUri, userUri })`
   - Ajoute un utilisateur dans un groupe (`vcard:hasMember`)
- `getMembers({ groupUri })`
   - Retourne tous les membres du groupe
- `isMember({ groupUri, userUri })`
   - Retourne true si l'utilisateur est déjà membre du groupe

**Comment by srosset81** [comment]
Comme le dit @tfrancart dans [son commentaire ici](https://github.com/assemblee-virtuelle/semapps/issues/526#issuecomment-773884192), les associations dans PAIR vont ressembler à ça:

> </users/guillaume/membership1> a pair:MembershipAssociation .
</users/guillaume/membership1> pair:membershipActor </users/guillaume> .
</users/guillaume/membership1> pair:membershipRole </roles/admin> .
</users/guillaume/membership1> pair:membershipOrganization </organizations/virtual-assembly> .

On pourrait imaginer un listener Moleculer qui écoute la création de telle entités et qui crée automatiquement des groupes webACL correspondant. Par exemple dans ce cas, on pourrait créer un `vcard:Group` avec un URL de type `/organizations/virtual-assembly/groups/admin` qui aurait pour membre `Guillaume`. Ce groupe pourrait aussi être un `pair:Group`, qui serait `pair:partOf` de l'organisation AV.

**Comment by nikoPLP** [comment]
je propose de donner une option pour créer des groupes ACL independant de toute autre ontologie, pour le moment.
Evidemment, connecter les groupes avec des relations existantes (notamment avec le subPropertyOf vcard:memberOf ) sera a terme interessant. C'est deja implementé dans le code Jena (mais il reste a activer les inferences)

De toute facon, il faudra toujours avoir la possibilité de créer des groupes webacl "vanilla". 

Je propose de les mettre sous l'url `/_group/`. C'est une URL réservée car les données de ces groupes seront enregistrées dans le graph des ACLs, donc  ce n'est pas un container.

A noter qu'on a deja `/_acl/` et `/_rights/`

@srosset81 ?

**Comment by srosset81** [comment]
OK pour moi !
Oui la réflexion autour de comment lier un groupe avec des relations existantes sera vue plus tard.
