### ISSUE TITLE
Image uploadée ne s'affiche pas correctement dans le navigateur

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#576]
**Décrivez le bug**
Si j'upload cette image via le composant React-Admin, elle s'affiche bien en thumbnail, mais si je la charge seul, le JPEG s'affiche en format texte.
![MONTFRANC_JohanBarrot_DJI_FINAL-e1605546466528](https://user-images.githubusercontent.com/17931931/107260562-85c92280-6a3e-11eb-8635-66c58feb8832.jpg)

Voir l'exemple ici:
https://colibris.social/files/outilslibres.png

**Comportement attendu**
Afficher l'image directement dans le navigateur

Il y a probablement un problème de MIME type.

**Comment by srosset81** [comment]
Le `content-type` est effectivement `application/ld+json`, alors qu'il devrait être `image/jpeg`

**Comment by simonLouvet** [comment]
probleme résolu par #844 . Le fichier ne devait pas être correctement finalisé.

**Comment by srosset81** [comment]
Non c'est autre chose. Ce n'est pas un problème d'upload mais d'header sur les images.
L'issue qui est résolue est celle-ci: https://github.com/assemblee-virtuelle/semapps/issues/821

**Comment by simonLouvet** [comment]
J'ai vérifié : le header et le content-type semblent ok maintenant

**Comment by srosset81** [comment]
@simonLouvet Le content-type du fichier qui pose problème (dans l'exemple) est bien enregistré dans le triple store, le problème c'est que le middleware renvoie un content-type de type JSON:

```ttl
<https://colibris.social/files/outilslibres.png>
        a       <http://semapps.org/ns/core#File> ;
        <http://semapps.org/ns/core#fileName>
                "outilslibres.png" ;
        <http://semapps.org/ns/core#localPath>
                "uploads/files/outilslibres.png" ;
        <http://semapps.org/ns/core#mimeType>
                "image/png" .
```

**Comment by simonLouvet** [comment]
je ne comprends pas pourquoi ce probleme se produit sur  https://colibris.social/. Il me faudrait debugger pour comprendre pourquoi le content-type n'est pas bien valué. Est ce que c'est bien les dernière version du serveur qui sont deployés?

**Comment by srosset81** [comment]
Ce n'est pas spécifique à colibris.social, il se produit aussi sur Archipel:
https://data.virtual-assembly.org/files/coopmuns.png

**Comment by srosset81** [comment]
Je remets ce que j'ai mis dans le chat:

> Après mise à jour des données de l'AV (data.virtual-assembly.org), j'ai mieux identifié le bug:
> ça marche bien au premier chargement, mais l'image se met dans le cache Redis, et au second chargement, le même problème apparait.
> En fait il faudrait pas que les images soient mises en cache, car ça n'apporte rien (c'est surtout utile pour éviter de trop soliciter le triple store)
> En plus ça fait gonfler le cache Redis inutilement
> Pour le cache on utilise le cache Redis de Moleculer: https://moleculer.services/docs/0.14/caching.html#Redis-cacher
> Par défaut il n'est pas activé en local
> Au niveau de Redis, l'image est enregistrée avec un header JSON.
> Cela dit je sais pas si, avec le système de cache Moleculer, on peut dire qu'on veut cacher un résultat que sous certaine condition.
> Sinon tant pis, on pourra aussi cacher les images/fichiers (mais il faudra un bon header)

**Comment by simonLouvet** [comment]
> Je remets ce que j'ai mis dans le chat:
> 
> > Après mise à jour des données de l'AV (data.virtual-assembly.org), j'ai mieux identifié le bug:
> > ça marche bien au premier chargement, mais l'image se met dans le cache Redis, et au second chargement, le même problème apparait.
> > En fait il faudrait pas que les images soient mises en cache, car ça n'apporte rien (c'est surtout utile pour éviter de trop soliciter le triple store)
> > En plus ça fait gonfler le cache Redis inutilement
> > Pour le cache on utilise le cache Redis de Moleculer: https://moleculer.services/docs/0.14/caching.html#Redis-cacher
> > Par défaut il n'est pas activé en local
> > Au niveau de Redis, l'image est enregistrée avec un header JSON.
> > Cela dit je sais pas si, avec le système de cache Moleculer, on peut dire qu'on veut cacher un résultat que sous certaine condition.
> > Sinon tant pis, on pourra aussi cacher les images/fichiers (mais il faudra un bon header)

Il me semble que la meilleur solution est de ne pas mettre en cache redis et de demander au navigateur de mettre en cache (header) @srosset81  @Superdrac
