### ISSUE TITLE
Regrouper les types et statuts dans des mêmes containers

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#585]
**Problématique**
Nous allons bientôt ajouter pas mal de classes sur data.virtual-assembly.org, et notamment les types. Dans l'ontologie il y a beaucoup de types différents (TaskType, ProjectType, GroupType) et beaucoup de statuts différents (TaskStatus, ProjectStatus, etc).

**Proposition**
Créer un container `/types` et un container `/status` sur data.virtual-assembly.org qui regroupera toutes ces classes.

Cela pourrait éventuellement poser problème au niveau du data provider de React-Admin mais je pense rien d'impossible, et je trouve positif de pouvoir regrouper plusieurs types de classes dans un même container, surtout lorsqu'elles ont la même classe parent.

Ping @simonLouvet

**Comment by srosset81** [comment]
J'ai commencé à le faire pour les CDLT, ça marche bien. Quelques petites adaptations au niveau des inputs, afin qu'un `pair:Project` ne puisse choisir un type que parmi les `pair:ProjectType`. Je le commite bientôt sur Archipel.

**Comment by simonLouvet** [comment]
> **Problématique**
> Nous allons bientôt ajouter pas mal de classes sur data.virtual-assembly.org, et notamment les types. Dans l'ontologie il y a beaucoup de types différents (TaskType, ProjectType, GroupType) et beaucoup de statuts différents (TaskStatus, ProjectStatus, etc).
> 
> **Proposition**
> Créer un container `/types` et un container `/status` sur data.virtual-assembly.org qui regroupera toutes ces classes.
> 
> Cela pourrait éventuellement poser problème au niveau du data provider de React-Admin mais je pense rien d'impossible, et je trouve positif de pouvoir regrouper plusieurs types de classes dans un même container, surtout lorsqu'elles ont la même classe parent.
> 
> Ping @simonLouvet

Ca me convient très bien.
