### ISSUE TITLE
L'effacement des ressources n'est pas complet

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#587]
**Décrivez le bug**
Si on fait un `DELETE` sur une ressource, les blank nodes liées à la ressource ne sont pas effacés. On peut les retrouver dans le triple store, même s'ils sont orphelins puisqu'aucune ressource ne permet de les retrouver.

**Comportement attendu**
Il faudrait qu'en plus des triplets liés directement à la ressource, on efface tous les blank nodes liés à cette ressource.

**Comment by srosset81** [comment]
A cause de ce problème on a des informations à double:
https://dev.data.virtual-assembly.org/organizations/data_players

**Comment by srosset81** [comment]
Fait ici https://github.com/assemblee-virtuelle/semapps/commit/0bc8f2e1da34c266e6cccdd4044f6b2851818cad

**Comment by srosset81** [comment]
Le code ne marche pas, il y a une violation des permissions. Du coup je l'ai enlevé, à voir plus tard, les blank nodes orphelins ne sont pas très graves.

**Comment by srosset81** [comment]
Pour mémoire, voilà la requête SPARQL qui permet de supprimer les blank nodes orphelins:

```
DELETE {
  ?s ?p ?o .
}
WHERE {
  ?s ?p ?o .
  FILTER(ISBLANK(?s))
  FILTER(NOT EXISTS {?parentS ?parentP ?s})
}
```

S'il y a des blanks nodes dans les blank nodes, il faut la lancer plusieurs fois.

**Comment by srosset81** [comment]
Résolu temporairement ici: https://github.com/assemblee-virtuelle/semapps/pull/948/commits/d71883e5812cfde555033285579c93306bfe9607

Tous les blank nodes orphelins sont automatiquement effacés après `ldp.resource.delete` et `ldp.container.clear`. C'est une opération très légère, et de toute façon les actions n'attendent pas qu'elle soit terminée. J'ai laissé un TODO avec une possible solution de code (qui ne marche pas complètement) si jamais on veut refactorer ça dans le futur.

**Comment by nikoPLP** [comment]
> Le code ne marche pas, il y a une violation des permissions. Du coup je l'ai enlevé, à voir plus tard, les blank nodes orphelins ne sont pas très graves.

Il fallait surement inverser l'ordre des triplets effacés.
faire d'abord l éffacement des blanknodes,
puis seulement apres effacer la resource.
