### ISSUE TITLE
Poster un nouvel article de blog

### ISSUE THREAD

**Issue by pdehaye** [assemblee-virtuelle/semapps#594]
**Tension**
Votre dernier (et premier) [article de blog](https://semapps.org/blog) date de septembre 2019. En meme temps le projet a l'air extremement actif sur Github.  

**Proposition**
Je propose que vous ecriviez un article tres bref mettant a jour sur le progres du projet depuis 2019.

**Comment by GuillaumeAV** [comment]
Salut @pdehaye ! 

En effet, on est pas très bon sur la comm' externe, et pourtant on a conscience que ce serait cool de partager des news, d'autant plus qu'il y en a plein !! 
Du coup, je prends l'initiative, c'est parti pour une newsletter SemApps #2 ! 
@srosset81 @simonLouvet @bouviermullerp @fluidlog @nikoPLP  @scenaristeur @tfrancart @J9rem @sauvagemathilde @capucinemasson  & co 
n'hésitez pas à partager [vos news en mode bullet points sur ce doc](https://pad.lescommuns.org/nme-FnXCS6WJsn_e1jP6Fw#) ! 
@bouviermullerp & @J9rem dites moi si vous voulez coordonner le truc au titre de vos rôles comm' / infoculteur, ou si vous préférez que j'assume jusqu'au bout ma prise d'initiative ;) 

@pdehaye merci d'avoir lancé la dynamique, si tu veux nous rejoindre [sur notre chat, welcome](https://app.element.io/#/room/#semapps:matrix.virtual-assembly.org), et si ca te dit qu'on se fasse une petite visio pour que je te raconte le projet et nous raconter qui tu es, avec grand plaisir ! 

Proposition : La publier le 8 mars ?

**Comment by bouviermullerp** [comment]
@GuillaumeAV j'ai pas été bon sur le timing, mais j'avais créé une issue et un pad à ce sujet : la #528 !
Merci du rappel @pdehaye - tu trouveras la précédente newsletter Autonome 2020 [à cette adresse](https://www.virtual-assembly.org/semapps-news/)

**Comment by J9rem** [comment]
@GuillaumeAV d'après la définition du rôle [Infoculteur](https://semapps.org/docs/governance/organisation-and-roles#information-gardening---informational-heritage) la rédaction des lettres d'informations n'est pas dans mon périmètre.
Je dois juste faire attention à ce que la substantifique moelle du contenu de chaque lettre d'info soit résumé dans un endroit accessible à tous.
Donc @GuillaumeAV me concernant tu fais ce que tu veux en lien avec le rôle Communication.
perso, je ne souhaite pas m'impliquer.
Merci de m'avoir solliciter ;-)
