### ISSUE TITLE
Faire le point sur les 3 projets de carto en réseau

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#596]
**Problématique**
Actuellement, au sein de l'AV, 3 projets de carto en réseau existent (Spoggy, Flodio et Grezzi).
L'objectif de ce projet est d'étudier comment on pourrait converger sur les cartos en réseaux effectuées spécifiquement sur Semapps.

**Proposition**
Organiser des réunions pour lister l'existant des fonctionalités de chaque logiciel, et voir quelle fonctionnalité pourrait être effectuée avec un code commun.

**Estimation du temps de travail en JH (profil intermédiaire)**
@scenaristeur : 2
@fluidlog : 2
@Adrien : ?

**Comment by fluidlog** [comment]
Une première réunion a eu lieu entre Adrien, David et Yannick le 11/12/2020
Un PAD a été créé pour ce projet, listant l'existant des 3 projets avec leurs fonctionnalités.
https://pad.lescommuns.org/k52s_XG-TMue-WTaCsy8Hg?view#

**Comment by fluidlog** [comment]
La prochaine réunion aura lieu vendredi 26/02/2021

**Comment by scenaristeur** [comment]
De mon côté, les données de visualisation (visjs) sont assez simples et je crois que pour D3 c'est assez similaire ?
Ça se résume à deux tableaux : un tableau
 nodes et un tableau edges du type 
```
nodes = [
{ id: 'node1', label: 'le premier noeud'},
{ id: 'node2', label: 'le second noeud'},
]
edges = [
{id:'edge1', from:'node1', to: 'node2', label: 'premier lien'},
{id:'edge2', from:'node2', to: 'node1', label: 'lien dans lautre sens'},
]
```
Il me paraît peu pertinent d'effectuer une requête sparql sur semapps pour extraire les triplets et reconstruire les tableaux de noeuds alors que l'on peut partir directement du jsonld.
En parcourant une Resource jsonld, on peut assez facilement constituer les arrays nodes et edges. 

Par exemple, en utilisant l'aliasing de jsonld, 
On peut facilement transformer le @id (jsonld) en id (visjs) ou le pair:label en label

Comme dans cette vidéo https://youtu.be/UmvWk_TQ30A

![Screenshot_20210221-201833_YouTube](https://user-images.githubusercontent.com/4020744/109152747-325c1180-776c-11eb-9578-065bb9dff00e.jpg)

**Comment by scenaristeur** [comment]
chargement du jsonld 

`Suite à notre conversation  d'hier
un proto de chargement des containers jsonld semapps
dans une page html (sans webpack ;-)) et avec un module /class
https://scenaristeur.github.io/ipgs/simple.html
le source https://github.com/scenaristeur/ipgs/blob/main/public/simple.html et https://github.com/scenaristeur/ipgs/tree/main/public/simple

les nodes seraient certainement à nettoyer, mais voilà l'idée
utilisé par exemple là https://scenaristeur.github.io/ipgs/?url=https://data.virtual-assembly.org/organizations/
`

**Comment by GuillaumeAV** [comment]
Super classe @scenaristeur !!

**Comment by fluidlog** [comment]
Création d'une issue de type "chantier" pour suivre sur le long terme les travaux effectués par le groupe.
Voir : https://pad.lescommuns.org/k52s_XG-TMue-WTaCsy8Hg#
Je vais donc fermer cette issue, qui est devenue "temporaire" pour ne pas polluer le kanban technique.

**Comment by fluidlog** [comment]
Voir chantier : https://github.com/assemblee-virtuelle/semapps/issues/691
