### ISSUE TITLE
Rendre compatible la carto en réseau avec REACT

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#597]
**Problématique**
L'objectif de cette issue est de faire fonctionner la carto en réseau dans Semapps, c'est à dire de la rendre compatible avec React.

**Proposition**
Attention au JQuery contenu dans Semantic UI présent dans le code de Flodio...

**Comment by fluidlog** [comment]
A suivre ici : https://pad.lescommuns.org/SrBR_GvSQqK-cav9qM_Ebw#

**Comment by fluidlog** [comment]
Pour info, j'ai complété le PAD : https://pad.lescommuns.org/SrBR_GvSQqK-cav9qM_Ebw?view
Avec l'explication que m'a donné Simon la semaine dernière.
A présent, j'attends de faire qq issue Semapps en mars pour commencer l'intégration en Avril ou mai (projet Fabmob en parallèle et prioritaire).

**Comment by srosset81** [comment]
Hors scope...
