### ISSUE TITLE
Carto des cartos (en réseau)

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#598]
**Tension**
Difficulté à connaitre rapidement la liste de tous les serveurs et projets Semapps et de savoir qui fait quoi.

**Proposition**
Créer un serveur semapps spécifique, avec peut-être une ontologie spécifique, faire une carto dessus, et mettre cette carto en accueil de CartoSemapps.

**Comment by fluidlog** [comment]
Un PAD a été ouvert pour ça : https://pad.lescommuns.org/iHx4e9rDTLC7Szn8YuTxgA#
Une réunion aura lieu entre Pierre et Yannick mercredi 4/03/20

**Comment by srosset81** [comment]
Hors scope de ce repo
