### ISSUE TITLE
Ajouter pair:Group à Archipel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#599]
Reprendre les mêmes prédicats que `pair:Organization`

> Prérequis: ajouter un container `/groups` sur le middleware

**Comment by srosset81** [comment]
@capucinemasson @mathildesauvage 
Mathilde a dit vendredi que vous aviez des erreurs lors de la création de groupes. Aviez-vous noté le prérequis ci-dessus qui indiquait qu'il fallait créer un container /groups sur le middleware ? C'est le fichier /src/middleware/boilerplates/pair-ldp-server/containers.js qui doit être édité. Si vous ne travaillez pas avec un middleware local, je vous propose de faire une PR pour qu'il soit ajouté sur data.virtual-assembly.org (je m'occuperai de le déployer ensuite).

**Comment by capucinemasson** [comment]
Hello Sebastien,

On a bien édité
sur  /src/middleware/boilerplates/pair-ldp-server/containers.js.
Normalement ca c'est bon. Maintenant, notre serveur nous indique ces
erreurs dans la console. Qu'en pense tu ? Si tu dispo tu peux aussi nous
retrouver ici  jusqu'a 17h30. Tu t'introsuis les screens des erreurs.
Merci beaucoup par avance

Capucine et Mathilde

Participer à la réunion Zoom
https://us04web.zoom.us/j/75542539276?pwd=cEZ6RDY2RXhUSWJPcE1rQmU0UU5Ldz09

[image: Capture d’écran 2021-04-13 à 16.25.08.png]
[image: Capture d’écran 2021-04-13 à 16.25.18.png]




Le lun. 12 avr. 2021 à 12:28, Sébastien Rosset ***@***.***> a
écrit :

**Comment by srosset81** [comment]
Salut @capucinemasson 
J'ai vu ton message trop tard. Par ailleurs tes captures d'écran ne sont pas passées dans ton commentaire Github.
S'il y a des soucis pour lancer le middleware en local, je propose que vous fassiez une PR avec la modif et que je déploie sur data.virtual-assembly.org
