### ISSUE TITLE
Ajouter pair:Task à Archipel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#600]
**Propriétés**
- `label`
- `description`

**Relations**
- `partOf` -> Project
- `concerns` -> Group
- `assignedTo` -> [Person]
- `hasType` -> TaskType
- `hasStatus` -> TaskStatus

> Prérequis: ajouter un container /tasks sur le middleware

**Comment by fluidlog** [comment]
J'ai commencé à ajouter les classes dans le frontend (pour l'instant en local chez moi).
Plus d'infos dans le PAD : https://pad.lescommuns.org/PoW1qZkNRe-Zdt98RtaFlQ?view
