### ISSUE TITLE
Configurer un groupe ACL de superadmin

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#610]
**Tension**
Par défaut, il n'y a aucune authorisation `acl:Control` sur les containers LDP. Cela fait qu'on ne peut pas les changer. De même une ressource créé anonymement n'a aucune authorisation `acl:Control` donc il est impossible de modifier les droits d'accès, sauf en insérant des triples directement dans Fuseki.

**Proposition**
Ajouter une configuration au service `webacl` qui permet de créer automatiquement un groupe ACL `superadmin` avec des utilisateurs définis comme tels:

```js
  superadmins: [
    'https://data.virtual-assembly.org/users/srosset81`
  ]
```

Donner le droit `acl:Control`, `acl:Write`, `acl:DefaultControl` et `acl:DefaultWrite` sur tous les containers à ce groupe d'utilisateurs. Cela lui permettra de contrôler n'importe quelle resource et n'importe quel container. 

L'avantage est qu'il sera facile d'ajouter des super-admins.

**Comment by nikoPLP** [comment]
je dirais, cette config pourrait etre plutot dans le service ldp. c'est lui qui crée les containers, et leurs donne les droits par default.

je peux faire un settings qui prend une variable d'environnement avec l'URI de l'utilisateur qui sera propriétaire du groupe superAdmin, et qui pourra par la suite y rajouter des membres

**Comment by srosset81** [comment]
Fait ici https://github.com/assemblee-virtuelle/semapps/pull/642
