### ISSUE TITLE
Imaginer une interface pour gérer les droits sur une ressource

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#611]
Avec les ACL, un utilisateur qui crée une ressource va pouvoir choisir avec qui il veut partager les différents droits. On pourrait imaginer qu'il y ait un lien "Droits d'accès" en haut à droite (avec les liens Editer, Voir, etc), qui affiche une modal ou qui permette d'accéder à une page particulière.

Il y a 4 droits à gérer:

- Read
- Write (ajout et effacement de données)
- Append (ajout de donnée, mais pas effacement)
- Control (même droit que le créateur)

> On peut éventuellement choisir d'ignorer le droit Append pour simplifier l'interface.

De plus ces droits peuvent s'appliquer à différents profils:

- Tous les utilisateurs
- Tous les utilisateurs connectés
- Un utilisateur en particulier
- Un groupe en particulier

Il faudra prévoir de pouvoir chercher un utilisateur, mais aussi un groupe.

Est-ce que quelqu'un a des idées ou des exemples d'interface ? 
Dans mon précédent job, on avait codé une interface comme ça:

![Capture d’écran de 2021-03-02 09-04-30](https://user-images.githubusercontent.com/17931931/109617155-55087480-7b36-11eb-8078-9079e1cd9677.png)

Elle est plus simple, mais je pense qu'on aura de toute façon une partie qui listera les droits existants, et une autre qui permettra d'ajouter de nouveaux droits.

**Comment by GuillaumeAV** [comment]
Dans SemApps v1, on avait 2 champs avec complétion (Qui peut accéder en lecture ? Qui peut accéder en écriture ?) et les utilisateurs renseignaient par complétion les champs. Pour la lecture ils pouvaient cocher une case "Open data".

Pour la v2 qui est plus fine, une proposition (attention qui est hyper innovante ;) ) pourrait être d'avoir les cases à cocher en haut à droite comme tu le suggères, sous un onglet "Partager" façon google :

- Peuvent lire
    - Tous les utilisateurs (y compris non connectés)
    - Tous les utilisateurs connectés
    - Ajoutez des utilisateurs ou des groupes en particulier

- Peuvent enrichir (pas de suppression possible)
    - Tous les utilisateurs (y compris non connectés)
    - Tous les utilisateurs connectés
    - Ajoutez des utilisateurs ou des groupes en particulier

- Peuvent modifier  
    - Tous les utilisateurs (y compris non connectés)
    - Tous les utilisateurs connectés
    - Ajoutez des utilisateurs ou des groupes en particulier

- Peuvent administrer
    - Tous les utilisateurs (y compris non connectés)
    - Tous les utilisateurs connectés
    - Ajoutez des utilisateurs ou des groupes en particulier

Et mettre une configuration par défaut : 
- Lire : Utilisateurs connectés
- Enrichir : Utilisateurs connectés 
- Modifier : Créateur
- Administrer : Créateur

**Comment by srosset81** [comment]
J'aime bien le terme "Enrichir", je crois que ça va bien avec la philosophie du web sémantique. "Administrer" c'est bien aussi.
Dans la configuration par défaut, j'autoriserai quand même la lecture aux utilisateurs non-connectés.

Pour l'interface tu proposes donc de reprendre ça...

![Capture d’écran de 2021-03-02 11-45-19](https://user-images.githubusercontent.com/17931931/109637257-d7039800-7b4c-11eb-9353-cf3bf37ff86d.png)

... mais en mettant 4 cases à cocher (Lire / Enrichir / Modifier / Administrer) au lieu d'un seul choix comme Google ?

![Capture d’écran de 2021-03-02 11-47-12](https://user-images.githubusercontent.com/17931931/109637483-22b64180-7b4d-11eb-914b-5da30ed293c6.png)

C'est vrai que c'est pas mal. Compacte et efficace. On pourrait avoir "Tous les utilisateurs" et "Tous les utilisateurs connectés" en haut de la liste, et si on veut, par exemple, ne donner aucun droit aux utilisateurs non-connectés, il suffirait de décocher toutes les options ?

**Comment by GuillaumeAV** [comment]
Huum je crois qu'on se comprend, cependant je précise que je verrais bien (à l'inverse de google) :
- en entrées de formulaire les types d'accès (ce qqui supposerait donc d'avoir 4 entrées de formulaire)
- puis en cases à cocher les utilisateurs (pas connectés, connectés, individus ou groupes en particuliers à remplir par complétion ou via des adresses mails)

**Comment by srosset81** [comment]
Du coup je vois absolument pas ce que tu vois, et je t'invite à faire un figma ou autre.

**Comment by GuillaumeAV** [comment]
Voila un figma pour matérialiser ce que j'essayais de dire .. Mais je suis pas sur que ce soit pertinent hein ;)
https://www.figma.com/file/yBjGKU923bGxqnk8hxAQnG/Essai-interface-ACL?node-id=0%3A1

**Comment by srosset81** [comment]
Hmm je trouve que sur ta proposition la visibilité des utilisateurs et des groupes est très faible. Il faut cliquer deux fois juste pour voir les utilisateurs ? En plus si un utilisateur a plusieurs droits, il faudra cliquer sur plusieurs + pour le voir.

**Comment by GuillaumeAV** [comment]
Oui Google n'a pas doute pas fait les choses au hasard ..

**Comment by srosset81** [comment]
Voilà ma proposition:

![Capture d’écran de 2021-03-02 16-56-04](https://user-images.githubusercontent.com/17931931/109675588-3aef8600-7b78-11eb-89a0-f6d14cf50baf.png)

Elle a l'avantage d'être basée sur du [véritable code](https://codesandbox.io/s/acl-rights-rbi24) en Material-UI ;-)

**Comment by simonLouvet** [comment]
++

**Comment by srosset81** [comment]
Je vais implémenter ça prochainement dans le cadre du financement de PDGE.
Je n'inclurais pas la gestion des groupes dans un premier temps car elle pose pas mal de questions, et je pense que c'est bien de déjà voir les problématiques qui vont naître de l'usage.

Il faudra aussi prévoir la gestion des droits au niveau du container, lorsqu'un utilisateur a un droit `acl:Control` sur le container. Il y a deux droits au niveau du container: 
- ceux du container lui-même (qui a droit d'ajouter une ressource, par exemple) 
- les droits par défauts qui vont être appliqués sur les ressources.

Je propose que dans un premier temps, on ne permette de gérer que le second type de droits via cette interface.

**Comment by GuillaumeAV** [comment]
C'est déjà un premier pas absolument génial !!!!
