### ISSUE TITLE
Assigner des ACL par défaut sur Archipel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#615]
**Tension**
Dès que le travail de Niko sera fini, on va essayer de déployer les ACLs sur Archipel. Comme il n'y avait pas de droits ACL jusqu'à maintenant, il va falloir qu'on décide comment on gére ça à partir de maintenant.

**Proposition**
- Les utilisateurs auront un droit `acl:Control` et `acl:Write` sur leurs propres profils. Les autres utilisateurs auront seulement un droit `acl:Read`.
- Aucune ressource actuelle n'ayant un propriétaire, nous allons donner un droit `acl:Read` à tous les utilisateurs. Le droit `acl:Write` ne sera donné qu'aux utilisateurs connectés.
- Les utilisateurs qui créent une nouvelle ressource auront un droit `acl:Control` sur la ressource. Cela permettra de savoir qu'ils en sont les créateurs et, dans le futur, de leur donner la possibilité de changer les droits. Les droits `acl:Read` et `acl:Write` seront les mêmes que pour les ressources précédemment créées (ressource visible de tous, mais modifiable seulement par les utilisateurs connectés).

Plus tard, nous mettrons en place un [groupe superadmin](https://github.com/assemblee-virtuelle/semapps/issues/610) qui nous permettra de reprendre progressivement le contrôle des données, par exemple en redonnant un droit `acl:Control` aux utilisateurs qui seraient légitimes.

**Alternatives**
- Rester en mode "wiki" et permettre aux utilisateurs non-connectés de modifier une ressource existante.
- Pour les ressources nouvellement créées, ne donner le droit `acl:Write` qu'au créateur (problème: tant qu'on n'a pas ajouté une [interface pour modifier les droits](https://github.com/assemblee-virtuelle/semapps/issues/611), le créateur ne pourra pas donner un droit d'écriture plus large)

**Comment by GuillaumeAV** [comment]
Hey ! 
De mon point de vue, je trouverais dommage de rester en mode wiki, l'un des objectifs étant d'expérimenter les fonctionnalités ACL... 
Pour l'intérêt de l'expérimentation,  je proposerais donc la deuxième option qui suppose néanmoins d'implémenter l'interface de modification des droits .. Qui peut le plus pouvant faire le moins, on pourra facilement communiquer sur le fait qu'en fonction des cas d'usage, on peut mettre des droits non restrictifs de type wiki pour utilisateurs non connectés. 
Resterait la question de l'interface de modif des droits .. Je commente direct sur l'issue #611  ;)

**Comment by srosset81** [comment]
L'interface pour modifier les droits va prendre du temps à être implémentée. Compte-tenu des chantiers actuels, j'estime que ce ne sera pas disponible avant fin mars.
Mais Archipel restera fonctionnel pendant ce temps.

Par contre ce qu'il sera urgent de faire, c'est https://github.com/assemblee-virtuelle/semapps/issues/612 car sinon l'expérience utilisateur sera pas top. Ca pourrait peut-être être inclus dans le budget/spec des PDGE ?

**Comment by simonLouvet** [comment]
La proposition me parait cohérente : read pour tous et write pour les connecté. Je pense même qu'il faut garder cela comme base pour les ressources nouvellement créée (pouvoir configurer sur le container?) à terme.

**Comment by nikoPLP** [comment]
> Plus tard, nous mettrons en place un [groupe superadmin](https://github.com/assemblee-virtuelle/semapps/issues/610) qui nous permettra de reprendre progressivement le contrôle des données, par ex

je pense que ca vaudrait le coup de faire ca des maintenant. ca eviterait aisni d'avoir a injecter des triples dans  le graph des acls a la main.

on peut tres bien rajouter ces permissions au données actuelles
