### ISSUE TITLE
Les relations de document ne s'affichent pas bien dans la colonne de droite

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#632]
**Décrivez le bug**
Sur la droite des documents, il y a juste des micro bulle sans rien dedans

**Etapes pour reproduire**
1. Aller sur code social de Guillaume Rouyer
2. Voir l'erreur

**Comment by srosset81** [comment]
Oui noté. Je dois faire une amélioration de fond pour le régler, cela prendra un petit peu de temps.

**Comment by srosset81** [comment]
Ce sera réglé par https://github.com/assemblee-virtuelle/semapps/issues/643
