### ISSUE TITLE
Déduire l'URI de la ressource par son slug

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#636]
Plutôt qu'avoir des URLs de type:

`https://archipel.assemblee-virtuelle.org/Organization/https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2Fassemblee_virtuelle/show`

déduire l'URI du slug en fonction du container défini dans les options.

`https://archipel.assemblee-virtuelle.org/Organization/assemblee_virtuelle/show`

Il faut un système assez flexible pour quand même pouvoir passer un URI complète, au cas où la ressource vient d'un autre serveur.

**Comment by fluidlog** [comment]
@srosset81 Toujours d'actualité ?

**Comment by srosset81** [comment]
Oui

**Comment by srosset81** [comment]
We did that for Destination Oasis (https://github.com/nouvel-air/oasis)
It is mostly a frontend feature, which can be implemented by websites which need a better SEO.

**Comment by mguihal** [comment]
Oh, I hadn't see this issue before, but that's a great news that something like this was already made for another project 😍 I've been thinking about doing this for Archipelago for a few weeks now.

How did you managed to do that for Oasis? I didn't find where is the rewrite mechanism in the linked repository

**Comment by srosset81** [comment]
> How did you managed to do that for Oasis? I didn't find where is the rewrite mechanism in the linked repository

https://github.com/nouvel-air/oasis/blob/master/frontoffice/src/pages/DetailsPage/DetailsPage.jsx#L31-L35
