### ISSUE TITLE
Faire un meetup en avril

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#641]
D'ici à avril, on devrait avoir les WebACL en prod et peut-être même la complétion wikidata.

Cela pourrait être un bon moment pour faire une petite présentation-célébration non ? Dans un format visio pas prise de tête ?

Qu'en pensez-vous @assemblee-virtuelle/semapps ?

**Comment by fluidlog** [comment]
Cela a été fait en ligne si je ne m'abuse :)...
