### ISSUE TITLE
Générer automatiquement un pair:label pour les classes Person

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#643]
Actuellement la classe Person est la seule qui n'utilise pas de `pair:label`, ce qui oblige à faire toutes sortes d'adaptation.

En utilisant la prop `transform` ([voir la doc ici](https://marmelab.com/react-admin/CreateEdit.html#transform)), on pourrait facilement compiler le prénom et le nom afin de générer un `pair:label` automatiquement.

**Comment by simonLouvet** [comment]
++ sur le principe.

J'aurais plus mis cette transformation de données au niveau du dataProvider en terme d'architecture.

**Comment by srosset81** [comment]
Le data provider ne devrait pas être dépendant de l'ontologie utilisée.

**Comment by simonLouvet** [comment]
> Le data provider ne devrait pas être dépendant de l'ontologie utilisée.

J'ai pas compris ta réponse (le lien avec ma proposition/remarque). Je parlais de pourvoir indiquer au DataProvider des transformations à faire sur les data  par configuration.

**Comment by srosset81** [comment]
Ce serait une option en effet. Sauf que ça prend du temps à implémenter et documenter, alors que la solution que je propose est réglée en une ligne de code, et cela avec du code standard React-Admin.
Je l'ai implémentée ici https://github.com/assemblee-virtuelle/semapps/pull/654
