### ISSUE TITLE
difference de comportement lors d'ajout d'une limit sur https://colibris.social/sparql

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#646]
En repartant de la requête de @fluidlog

la requête 
```
      CONSTRUCT {
        ?s0 ?p0 ?o0
      }
      WHERE
      {
        ?s0 ?p0 ?o0 .
      }
```
me renvoie 5575 objets dans @graph

![image](https://user-images.githubusercontent.com/4020744/110993491-a8b96000-8377-11eb-9128-c3aca90f922b.png)

mais si j'ajoute une limite 100 à ma requête, j'ai quelque chose de totalement différent 

```
      CONSTRUCT {
        ?s0 ?p0 ?o0
      }
      WHERE
      {
        ?s0 ?p0 ?o0 .
      }
LIMIT 100
```

![image](https://user-images.githubusercontent.com/4020744/110993717-ef0ebf00-8377-11eb-9bf8-37bd63a83a2a.png)

je pense que c'est à cause du CONSTRUCT qui ne récupère qu'un partie des triples, mais c'est bizarre d'avoir la propriete 'contains' contenant un tableau de strings à la place du @graph contenant un tableau d'objets

**Comment by srosset81** [comment]
Ce n'est pas un bug, mais c'est effectivement une difficulté pour faire une requête SPARQL en CONSTRUCT avec une LIMIT. La limite s'applique au nombre de triples recherchés, pas au nombre de ressources (les ressources n'existent pas pour le triple store).

@tfrancart m'avais recommandé de faire un sub-SELECT dans le WHERE, mais son message était dans le chat Matrix et je ne peux pas le retrouver pour le moment (potentiellement il a été détruit dans l'incendie d'OVH).

**Comment by tfrancart** [comment]
Syntaxe générale pour un sous-select avec un limit, puis un construct par-dessus:

```
CONSTRUCT {
  ?x ?p ?o .
}
WHERE {
  # récupération des triples que l'on veut sur les ?x
  ?x ?p ?o
  # le sous-select est obligatoirement entre accolades
  # le sous-select s'exécute obligatoirement avant le reste
  {
    SELECT ?x
    WHERE {
      # critères sur ?x
    }
    # nombre limite de ?x
    LIMIT 100
  }
}
# pas de limit sur le construct
```

**Comment by srosset81** [comment]
Merci beaucoup !
