### ISSUE TITLE
FilteredArrayField & ReifiedArrayField pour show les relation réifiées

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#647]
**Tension**
Le ArrayField classique ne permet pas d'afficher toutes les personnes qui ont un role dans une organsiation groupé par rôle. Besoin issue du projet Passerelle Normandie

**Proposition**
implémenté FilteredArrayField qui permettra d'afficher un ArrayField en filtrant son contenu
implémenté ReifiedArrayField qui affichera plusieurs FilteredArrayField groupé par un attribut configurable (le rôle dans notre cas)

**Comment by srosset81** [comment]
OK pour FilteredArrayField.
Je ne serai pas pour merger ReifiedArrayField dans le repo semapps car on sort des bonnes pratiques de React-Admin (un seul label par Field)

**Comment by simonLouvet** [comment]
@srosset81 si je ne merge pas ReifiedArrayField, il faudra faire du code spécifique pour afficher les relation réifié groupées par une des propriété de la relation.

**Comment by srosset81** [comment]
Il suffit que tu gardes ce composant sur le repo spécifique, et que tu ne les mettes pas dans @semapps/semantic-data-provider

**Comment by simonLouvet** [comment]
> Il suffit que tu gardes ce composant sur le repo spécifique, et que tu ne les mettes pas dans @semapps/semantic-data-provider

Oui, ce que tu dis fonctionne pour Passerlle-Normandie mais ne pourra pas être réutilisé pour un autre projet si ce n'est pas inclue dans le noyau. Je pense que c'est une fonctionnalité utile. Rien que Archipel je suis parti pour présenter les relations réifiées comme pour passerelle.
