### ISSUE TITLE
Migrer Parlepeuple vers SemApps

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#649]
**Description**
Il existe toujours une instance de parlepeuple [ici](https://lemondeapres.org/) pour montrer les différentes fonctionnalités de parlepeuple qui forme comme un réseau social. (les fonctionnalités sont assez similaires à communecter).

Ce chantier est destiné à recevoir les estimations de @nikoPLP suite à la discussion que nous avons eu le 14 Mars.
Peut-être est-il intéressant ce casser ce chantiers en chantier plus petit ?

**Issues liées** - pas d'issue lié pour le moment
- [ ] Titre de l'issue liée #

**Estimation du temps de travail en JH**
- @srosset81:
- @simonLouvet:
- @nikoPLP

**Comment by bouviermullerp** [comment]
La région Bourgogne Franche-Comté a récemment mis en place un réseau social local grâce à l'outil libre HumHub (https://www.humhub.com/en). Voir ici leur implémentation : https://resonum-bfc.fr/dashboard

**Comment by fluidlog** [comment]
@bouviermullerp que fait-on de cette issue ?

**Comment by srosset81** [comment]
Je ferme comme c'est un peu hors-sujet et sans doute que ça va pas se faire prochainement.
