### ISSUE TITLE
Définir la notion de template

### ISSUE THREAD

**Issue by J9rem** [assemblee-virtuelle/semapps#661]
Lors de la réunion SemApps du [31 mars 2021](https://github.com/assemblee-virtuelle/semapps/wiki/R%C3%A9union-planning-SemApps-31-03-2021), nous avons parlé d'avoir des templates.

Toutefois, cette notion peut représenter différentes notions:
- onthologie
- tempalte css
- une version archipel
- ...

Je m'occupe de caler une réunion pour définir cette notion et affiner le besoin de tempaltes.

**Comment by fluidlog** [comment]
Cette notion a été récemment discuté ici : https://pad.lescommuns.org/JB4oKkzSQdyFwvDLC6jJnA
Nous n'utilisons plus la notion de template, ni boilerplate, Archipelago a été sorti de SemApps et sera un "produit".
