### ISSUE TITLE
S'inspirer des https://contribateliers.org de Framasoft

### ISSUE THREAD

**Issue by J9rem** [assemblee-virtuelle/semapps#662]
- S'inspirer des https://contribateliers.org de Framasoft voire créer un partenariat ?
_Vient des échanges du [31 mars 20210](https://github.com/assemblee-virtuelle/semapps/wiki/R%C3%A9union-planning-SemApps-31-03-2021)_

@GuillaumeAV est-ce toi qui suit cette issue ?

**Comment by fluidlog** [comment]
A été rappelé dans le chat... (je ferme pour faire du ménage de printemps :) )
