### ISSUE TITLE
Proposer une install party pendant les 10 ans de l'AV

### ISSUE THREAD

**Issue by J9rem** [assemblee-virtuelle/semapps#663]
Proposer une install party pendant les 10 ans de l'AV
(cf. [échanges du 31 mars 2021](https://github.com/assemblee-virtuelle/semapps/wiki/R%C3%A9union-planning-SemApps-31-03-2021))

@GuillaumeAV je te l'ai assigné car il me semble que tu avais énergisé cette idée mais n'hésite pas à assigner aux autres bonnes personnes.

**Comment by GuillaumeAV** [comment]
Oui c'est moi qui avait proposé cette idée en effet, au côté des **aPAIRos** : proposition d'événements de carto collaborative des PAIRs au sein des communautés d'utilisateurs d'archipelago !
Je suis sûr que ca pourra boter notre cher ami @Ancelin-Moulherat-AV !

**Comment by srosset81** [comment]
Je suis partant moi aussi !
Idéalement il faudrait qu'on soit une petite équipe de 2-3 personnes pour accompagner les installeurs.

**Comment by GuillaumeAV** [comment]
Helloo ! 

Au passage ! Réservez votre semaine du 21 au 26 juin pour les 10 ans de l'Av à El Capitan !
