### ISSUE TITLE
Il manque les relations inverses aux rôles .. 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#669]
**Décrivez le bug**
Quand je vais sur le profil de Guillaume je ne retrouve pas les orgas dont je suis associé (DP), Admin (AV) etc...

**Etapes pour reproduire**
1. Aller sur 'Guillaume '
2. Voir l'erreur

**Comportement attendu**
Avoir les relations inverses ... Mais peut-être est-ce lié l'issue à ce sujet dans l'ontologie ?

**Comment by srosset81** [comment]
Lié à https://github.com/assemblee-virtuelle/pair/issues/166, on ne peut rien faire.
