### ISSUE TITLE
Proposer une rencontre du club des utilisateurs !

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#670]
Suite à la réunion planification, la proposition est d'organiser une visio d'échanges entre représentants des premières communautés d'utilisateurs de SemApps / Archipelago, parmi lesquels (**complétez si j'en oublie**) : 

1. Archipel AV
2. Passerelle Normandie
3. Colibris
4. Chemins de la Transition
5. UTT
6. FabMob
7. DataFood Consortium
8. Prats de Mollo
9. Aimeraudes 
10. Glocal Low Tech

NB
On voit poindre l'enjeu de l'interopérabilité : 
- Des instances entre elles 
- Avec des bases de connaissances type Wikidata / Compétences ... 

@bouviermullerp t'es chaud ? Je participe si besoin avec grand plaisir !

**Comment by srosset81** [comment]
P**ain ça commence à faire un paquet d'instances ! :laughing:

**Comment by bouviermullerp** [comment]
Je suis très très chaud, et je crois aussi que j'atteint la limite de mes capacités cognitives, je vais énergiser cette carte mais là j'ai besoin de temps, ou de déléguer.

**Comment by fluidlog** [comment]
Carto des cartos, animation de la communauté Semapps, Réunions sur les Actus de l'écosystème AV en 2022, je pense que nous répondons à ces attentes et que nous pouvons fermer cette issue assez ancienne...
