### ISSUE TITLE
Permettre au semantic data provider d'aggréger les données de plusieurs serveurs

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#674]
**Tension**
Actuellement le semantic data provider utilisé par l'interface Archipel ne lit les données d'une classe donnée (par exemple des événements) que d'un URL de container LDP ou d'un endpoint SPARQL. Mais du coup cela ne montre pas vraiment l'intérêt de dissociation de l'interface et des données. 
Si on pouvait aggréger les données de différents serveurs, cela permettrait, par exemple, d'afficher les événements proposés par l'AV + Passerelle Normandie + les CDLT, tout cela sur une seule interface :D

**Proposition**
Permettre d'aller chercher des données sur plusieurs endpoints SPARQL ou plusieurs containers LDP.
Au lieu de passer une seule config, on pourrait permettre de passer un tableau de configs ?

**Comment by GuillaumeAV** [comment]
Olala ca aussi c'est excitant !!

**Comment by fluidlog** [comment]
En cours avec les travaux sur la fédération...
