### ISSUE TITLE
Intégrer un forum de discussion du type Discourse à Archipel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#675]
**Description**
Nous avons pas mal réfléchi à [intégrer un tchat Hubl sur des pages SemApps](https://github.com/assemblee-virtuelle/semapps/issues/464), mais cela pose actuellement des problèmes techniques qui ne dépendent de Startin'Blox. Une alternative plus simple serait d'intégrer des forums type [Discourse](https://www.discourse.org/).

On pourrait imaginer qu'en bas de chaque page d'Archipel, il y ait un espace pour lancer des sujets de discussion. On pourrait voir les dernières discussions sur le sujet et, en cliquant dessus, voir le fil de la discussion.

L'intérêt d'un forum de discussion par rapport à un tchat c'est que les informations sont plus pérennes, et qu'elles sont plus faciles à retrouver via un moteur de recherche, alors que par nature les discussions par tchat sont éphémères et synchrones.

On pourrait utiliser ActivityPub, dont l'ontologie ActivityStreams a l'avantage d'intégrer des notions de "réponse à", "auteur", etc.

**Issues liées**
- [ ] Titre de l'issue liée #

**Estimation du temps de travail en JH**
- @srosset81:
- @simonLouvet:

**Comment by GuillaumeAV** [comment]
C'est génial je vote pour ! Mais je vais peut-être arrêter de mettre des message sans aucune valeur ajoutée ;)

**Comment by srosset81** [comment]
Tu peux mettre une réaction :+1: sur le message ;)

**Comment by srosset81** [comment]
Possible maintenant avec les commentaires.
