### ISSUE TITLE
Gestion des utilisateurs

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#68]
- Pouvoir créer un nouvel utilisateur, idéalement en RDF ou JSON-LD.
- Pouvoir lister tous les utilisateurs existants
- Pouvoir récupérer un utilisateur

**Comment by srosset81** [comment]
@bouviermullerp J'ai splitté cette story : https://github.com/assemblee-virtuelle/semapps/issues/84 https://github.com/assemblee-virtuelle/semapps/issues/78 https://github.com/assemblee-virtuelle/semapps/issues/52 https://github.com/assemblee-virtuelle/semapps/issues/85

Cela facilitera la gestion et nous permettra de discuter de chaque point.

**Comment by srosset81** [comment]
A priori il faudrait trois endpoints:
- `POST /user`
- `GET /user/{id}`
- `GET /user`

**Comment by simonLouvet** [comment]
Je m'oriente plutôt vers ce type d'API

- CREATE one
  - POST /container/pair:actor + data sans son type
  - POST /subject + data avec son type (mais /subject n'est pas un container alors  bof, moins que /subject soit le container généraliste dans lequel on peut tout poster)

- READ one
  - GET /subject/{id}

- READ all
  - GET /container/pair:actor

- UPDATE one
  - PUT /subject/{id}
  - PATCH /subject/{id}

- DELETE one
  - DELETE / ubject/{id}

**Comment by simonLouvet** [comment]
voir #84
