### ISSUE TITLE
Séparer les données des relations dans l'édition des ressources

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#680]
Faire sur Archipel comme on a fait pour les CDLT:
https://app.lescheminsdelatransition.org/Path/https%3A%2F%2Fdata.lescheminsdelatransition.org%2Fpaths%2Fchemin-des-low-tech

Code source:
https://github.com/chemins-de-la-transition/semapps

**Comment by GuillaumeAV** [comment]
Yes !

**Comment by BastienSig** [comment]
Je l'ai fais pour les personnes et les organisations, ça me paraissait pertinent pour ces entités. Est ce nécessaire de le faire pour les autres ?

**Comment by GuillaumeAV** [comment]
Hello Bastien ! 
Aah super ! De mon coté, je me dis que c'est bien si on a toujours la même interface et j'aurais donc tendance à le faire pour toutes les classes .. 
D'ailleurs, je me demande s'il ne serait pas pertinent de mettre les relations en premier onglet et les données en deuxième ...

**Comment by BastienSig** [comment]
Très bien je vais l'appliquer pour tous. 
Pour le switch Relation/données, je peux très simplement les inverser donc pas de problème la dessus pour moi.

**Comment by GuillaumeAV** [comment]
Attends le retour de @srosset81 tout de même, et peut-être de @bouviermullerp également ! Je n'oserais prendre ce genre de décisions tout seul ;)

**Comment by BastienSig** [comment]
Oui tu as raison. J'attend la réponse.

**Comment by bouviermullerp** [comment]
C'est important d'avoir une homogénéité dans nos écrans, donc oui pour l'implémenter sur tous les écrans !

Par contre, il me semble que c'est plutôt commun de remplir d'abord les données avant les relations. En tout cas, le design général est suremnet à affiner car les champs sont très large (ils font quasiment tout l'écran).

**Proposition**: respecter les spécifications de départ : Séparer les données des relations dans l'édition des ressources, pour les Project Acteurs Idées Ressources et créer une autre issue pour un design un peu meilleur.
