### ISSUE TITLE
Amélioration du dataModel utilisé par le semantic data provider

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#686]
**Problématique**
Actuellement il est possible de configurer différents paramètres mais on ne comprend pas trop à quoi ils servent:

```js
  dataModel: {
    types: ['pair:Organization'],
    containerUri: REACT_APP_MIDDLEWARE_URI + 'organizations',
    dereference: ['pair:hasLocation/pair:hasPostalAddress'],
    slugField: 'pair:label'
    filter: { ... } 
  }
```

Pour clarifier:
- Le paramètre `types` est utilisé pour la création de nouvelles ressources, mais aussi pour faire une requête SPARQL.
- `containerUri` est utilisé pour poster des ressources, mais aussi pour faire une requête lorsqu'aucun `types` n'est fourni.
- `dereference` est utilisé pour la requête SPARQL.
- `slugField` est utilisé pour savoir quel champ utiliser pour le slug lors de la création d'une ressource
- `filter` permet de filtrer les résultats lors de la requête SPARQL

**Proposition**
C'est une double proposition:
- Mieux séparer ce qui concerne la requête de ce qui concerne la création de ressources.
- Permettre dans le futur de pouvoir agréger plusieurs requêtes

Voilà ce que je propose:

```js
  dataModel: {
    sources: [{
      sourceType: "sparql" // "sparql" ou "container". On pourrait imaginer d'autres types dans le futur
      sparqlEndpoint: ... // Optionel. Sinon cela utilise l'endpoint défini par défaut dans le data provider
      classes: ['pair:Organization', 'as:Organization'], // Recherche une resource qui matche toutes les classes
      containerUri: REACT_APP_MIDDLEWARE_URI + 'organizations', // Si spécifié, on ne retourne que les ressources qui sont dans le container
      dereference: ['pair:hasLocation/pair:hasPostalAddress'],
      forceArray: [...],
      filter: { ... } // Autres options pour les requêtes SPARQL
    },
    {
      sourceType: "container",
      containerUri: REACT_APP_MIDDLEWARE_URI + 'other-organizations',
      filter: { ... } // Filtrage après coup des ressources
    }],
    create: [{
      containerUri: process.env.REACT_APP_MIDDLEWARE_URI + 'organizations', // Le container où la ressource est postée
      classes: ['pair:Organization', 'as:Organization'], // Le type de la resource créée
      append: { 'pair:partOf': 'AV' } // Des données qu'on veut ajouter à la création
      titleField: 'pair:label' // Utilisé pour le slug, mais peut-être aussi pour la génération de formulaire de création
    }]
  }
```

**Composants concernés**
@semapps/semantic-data-provider. Cela occasionnera sans doute des breaking changes.

**Comment by srosset81** [comment]
Issues liées:
- #674
- #495

**Comment by srosset81** [comment]
Réflexions du jour:
- Pour les sourceType, penser l'architecture en termes de "plugins" (Wikidata, Gogocarto...)
- On pourrait imaginer dans le futur avoir plusieurs choix de cibles pour la création

**Comment by srosset81** [comment]
A prendre en compte aussi:

- Ajouter un champ `specialFields` au niveau des sources pour faire des recherches SPARQL par latitude/longitude ou par startDate/endDate. Voir [cette issue](https://github.com/assemblee-virtuelle/semapps/issues/494).

**Comment by fluidlog** [comment]
@srosset81 Je me suis permis de te l'assigner, vu qu'elle est liée à plusieurs issues que tu suis de près... :)

**Comment by srosset81** [comment]
Elle a été faite dans le cadre du chantier interop.
