### ISSUE TITLE
Automatiquement ajouter les dates de création, de mise à jour et le créateur

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#688]
Actuellement nous n'avons pas moyen de connaître les dates d'ajout ou de mise à jour des ressources. C'est une information qui serait pourtant utile à bien des égards. @tfrancart n'est pas favorable à l'ajout de ces notions dans l'ontologie PAIR (voir https://github.com/assemblee-virtuelle/pair/issues/161), car il s'agit plutôt de meta-données liées à la documentation et [Dublin Core](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) serait plus adaptée.

Je propose du coup d'ajouter ces prédicats:
- `purl:created`: Date de création de la ressource
- `purl:modified`: Date de mise à jour de la ressource
- `purl:creator`: WebID du créateur de la ressource, s'il est connu

Y aurait-il une objection à ce que cela soit fait automatiquement côté middleware ? Cela pourrait aussi être fait côté frontend, en ajoutant une props `transform` sur tous les composants `Create` et `Edit` de React-Admin, mais ça me semble un peu lourd. Autre option: le mettre dans le data provider.

Ping @simonLouvet

**Comment by simonLouvet** [comment]
++

**Comment by tfrancart** [comment]
je ne suis pas favorable à introduire ces propriétés dans PAIR. Il ne s'agit pas de la description des entités décrites par PAIR mais de la description des _notices_ de ces entités dans SemApps. PAIR peut être utilisé en dehors de SemApps et SemApps doit pouvoir fonctionner avec autre chose que PAIR.
Comme ces propriétés seront positionnées de façon automatique par SemApps (pas de problème pour cela), ces propriétés peuvent être soit dans une ontologie technique SemApps, soit on réutilise les propriétés DublinCore (et je ne vois pas de problème pour ce cas d'usage).

Il faudra bien être clair sur la sémantique de ces propriétés qui caractérisent le _document dans SemApps_ qui décrit l'entité, et non pas l'entité elle-même. Parfois on créé systématiquement une autre ressource représentant le document lui-même pour lui attacher ces métadonnées (ex: data.bnf), mais c'est super lourd. Si ces propriétés sont dans un autre espace de nom / dans une autre ontologie que PAIR cette distinction pourra suffire.

**Comment by srosset81** [comment]
> je ne suis pas favorable à introduire ces propriétés dans PAIR. Il ne s'agit pas de la description des entités décrites par PAIR mais de la description des _notices_ de ces entités dans SemApps. PAIR peut être utilisé en dehors de SemApps et SemApps doit pouvoir fonctionner avec autre chose que PAIR.

Oui on est d'accord là-dessus :-) Une raison de plus de ne pas utiliser PAIR pour ça.

> Comme ces propriétés seront positionnées de façon automatique par SemApps (pas de problème pour cela), ces propriétés peuvent être soit dans une ontologie technique SemApps, soit on réutilise les propriétés DublinCore (et je ne vois pas de problème pour ce cas d'usage).

:+1: 

> Il faudra bien être clair sur la sémantique de ces propriétés qui caractérisent le _document dans SemApps_ qui décrit l'entité, et non pas l'entité elle-même. Parfois on créé systématiquement une autre ressource représentant le document lui-même pour lui attacher ces métadonnées (ex: data.bnf), mais c'est super lourd. Si ces propriétés sont dans un autre espace de nom / dans une autre ontologie que PAIR cette distinction pourra suffire.

Oui tu fais bien de le rappeler. Et effectivement créer un autre document pour gérer les méta-données serait trop lourd à gérer. En utilisant l'ontologie Dublin Core, je pense que ça aidera à comprendre qu'on fait référence au document et non pas au projet, à l'organisation, etc.

**Comment by srosset81** [comment]
Décision du jour:
- On le fait au niveau du middleware
- Pas d'option pour activer ou désactiver
- On va proposer des "core ontologies" pour s'assurer que Dublin Core, RDF, etc, sont inclus de base
