### ISSUE TITLE
Mettre plus en avant l'AV sur le site semapps.org

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#689]
Pour l'instant il n'y a aucun lien vers l'AV, et le nom "Virtual Assembly" n'est mentionné que dans le copyright (copyright qui ne devrait d'ailleurs pas vraiment en être un, puisqu'on est sur de l'open source...)

A mon avis on aurait tout avantage à indiquer clairement que SemApps est hébergé par l'AV, avec un logo et un lien, car ça peut donner confiance à des personnes qui connaissent déjà l'AV et ça montre que SemApps ne sort pas de nulle part.

**Comment by GuillaumeAV** [comment]
En effet !

**Comment by srosset81** [comment]
Fait sur le nouveau site
