### ISSUE TITLE
Convergence des projets de cartographie en réseau

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#691]
**Description**
Ce chantier a pour objectif de trouver des convergence entre tous les projets de cartographie en réseau.

**Issues liées**
- [x] Faire le point sur les 3 projets de carto en réseau #596 
- [x] Rédiger une plaquette des projets de carto en réseau #692

**Estimation du temps de travail en JH**
- @fluidlog : 4h toutes les 2 semaines
- @scenaristeur : 4h toutes les 2 semaines
- Adrien : 4h toutes les 2 semaines

**Comment by fluidlog** [comment]
Nous avons décidé avec David et Adrien de nous faire toutes les 2 semaines des réunions le vendredi matin.
Le contenu des réunions se trouve sur le PAD : https://pad.lescommuns.org/k52s_XG-TMue-WTaCsy8Hg#

**Comment by scenaristeur** [comment]
Première lib à tester https://github.com/scenaristeur/ouiz/tree/main/examples/easy
L'idée étant d'avoir en commun la fonction ouiz.load() ensuite selon la librairie de visualisation, il faut décliner la fonction ouiz.toVis()

**Comment by srosset81** [comment]
Hors scope de SemApps, sentez-vous libre de faire des issues ailleurs
