### ISSUE TITLE
Rédiger une plaquette des projets de carto en réseau

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#692]
**Objectif**
Pouvoir présenter en une plaquette l'offre de cartographie liés à SemApps en réseau des différents projets de l'AV.

**Proposition**
Dans un premier temps, on parle des valeurs de l'AV, des briques techniques, et ensuite, on décline les possibilités graphiques des différents outils.

**Comment by fluidlog** [comment]
Adrien a commencé à rédiger un début de plaquette en mars 2021.

**Comment by srosset81** [comment]
Hors scope, je ferme
