### ISSUE TITLE
Importer des données d'autres instances SemApps

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#698]
![Interopérabilité entre instances SemApps (4)](https://user-images.githubusercontent.com/17931931/133049394-169937d3-188c-4648-b83e-028c98278b6a.png)

![Interopérabilité entre instances SemApps (5)](https://user-images.githubusercontent.com/17931931/133049403-31f44444-9f3f-460a-9a5a-a556947f75ab.png)

> Forké de https://github.com/assemblee-virtuelle/semapps/issues/43

Lorsqu'on crée une ressource, pouvoir choisir:
- soit de la créer à partir de zéro (mode actuel)
- soit d'indiquer un URI d'une ressource existant sur une autre instance SemApps (ou sur la même instance, si ça peut avoir du sens)

On aurait alors le choix entre deux modes de copie:
- Fork (on importe la donnée, on garde un lien vers la donnée originale)
- Synchronisation (même chose que Fork, mais un service Moleculer s'occupe de synchroniser régulièrement les données avec celles de l'original)

A voir comment on explicite ces 2 modes pour l'utilisateur lambda.

Ajouter automatiquement `semapps:forkedFrom` ou `semapps:synchronizedWith`.

On aurait ainsi quelque chose un peu similaire à l'import de profils de SemApps v1, sauf que l'import pourrait resté synchronisé avec l'original.

Dans un second temps, on pourrait indiquer des URLs avec d'autres modèles de données (Wikidata, OSM, Gogocarto) et un convertisseur (côté middleware ?) s'occuperait de faire le bon mapping.

**Comment by GuillaumeAV** [comment]
Oooh yeah !!!

**Comment by srosset81** [comment]
Avec @simonLouvet on avait pensé laisser tomber ça pour le moment car ça semblait ne pas être suffisamment compatible avec les concepts du web sémantique.

Cependant lors de la réunion SemApps de mercredi dernier ([CR ici](https://pad.lescommuns.org/3IQ_waK8QXy6Hh5yJPknCQ)) @bouviermullerp a réitéré le besoin de pouvoir ajouter des ressources d'autres instances SemApps.

Le cas d'usage: on a une instance Passerelle Normandie avec des événements. Une autre instance Chemins de la Transition aimerait ajouter certains événements (mais pas tous) de Passerelle Normandie sur sa propre instance, mais sans avoir à les copier. Idéalement il suffirait d'indiquer l'URI de l'événement et il serait ajouté à la liste des événements.

Il y a donc un choix éditorial, qui fait que c'est différent de l'issue https://github.com/assemblee-virtuelle/semapps/issues/794 où on se contente d'aggréger différentes sources.

Niveau UX, au lieu d'avoir un bouton "Créer" en haut des pages de type "liste", on pourrait avoir un bouton "Ajouter une ressource". Ensuite soit on peut créer une nouvelle ressource locale, soit ajouter une ressource distante (en entrant une URI, ou en faisant une recherche).

## Questions

- Est-ce que, dans les standards LDP, un container peut "contenir" une ressource d'un serveur distant ?
- Si oui, est-ce qu'on met juste l'URI ou est-ce qu'on copie toute la ressource distante dans le triple store local ? (avec les URIs originaux, a priori)

**1) Si on mets juste l'URI de la ressource distante dans le container**, cela obligerait à changer la manière dont on fait les requêtes. Car actuellement on fait des requêtes SPARQL qui retournent, en une fois, le contenu de toutes les ressources. On pourrait changer ça en retournant que l'URI des ressources, puis en faisant un GET. J'avais testé ça et noté une baisse des performances. On pourrait aussi le faire que pour les ressources qui ne sont pas locales.

Le problème avec cette solution, c'est que si on fait une recherche par mot-clé, ou par filtre, la requête SPARQL ne retournera pas les résultats pour les ressources distantes qui ont été importées. Cela pourrait avoir un gros impact au niveau fonctionnel. Ou alors il faudrait faire des requêtes SPARQL aggrégées, mais ce serait compliqué à gérer car on ne connaîtrait pas forcément l'endpoint SPARQL lié à la ressource distante (ou il pourrait ne pas exister).

**2) Si on importe toute la ressource distante dans le triple store local**, on aurait des meilleures performances et on pourrait faire des requêtes SPARQL. Pour rester dans l'esprit du web sémantique, on pourrait garder l'URI originel. Par contre on pourrait ajouter un triple avec le prédicat `semapps:synchronizedWith` afin que, régulièrement, un bot s'assure que les données sont toujours à jour avec l'original. *(Correctif: `semapps:synchronizedWith` n'est pas nécessaire car on connait l'URI original. Par contre on pourrait imaginer un prédicat `semapps:lastSynchronized` avec la date de la dernière synchronisation, ce qui aiderait le bot à identifier les ressources à synchroniser)*.

## Points annexes 

- Concernant **l'option "fork"** évoquée dans le message initial de cette issue, elle serait toujours envisageable. Si on crée un fork, cela signifie qu'on copie les données et qu'on crée un nouvel URI. On peut garder un prédicat `semapps:forkedFrom` pour information.

- Il y a aussi la question de la **modification** d'une donnée "synchronisée". Il ne faudrait pas modifier les données dans le triple store local. Par contre rien n'empêche de faire une PATCH ou un PUT sur la ressource distante. On pourrait vérifier les droits WebACL en amont. Une fois le PATCH/PUT fait et accepté, le bot pourrait resynchroniser les données localement.

- Concernant les **WebACL**, il y a un vrai sujet. Car si un utilisateur a le droit de voir une ressource distante, cette ressource n'est peut-être pas publique pour autant. Et en l'important, il pourrait rendre la visible à des utilisateurs qui n'ont pas le droit de la voir. De plus les droits WebACL de la ressource distante peuvent avoir changé depuis l'importation. Je pense qu'il y a des solutions mais il faudra y réfléchir sérieusement.

- Dernier point: les **données utilisateurs** sont une donnée particulière. Dans la v1 de SemApps, on pouvait importer son profil, mais en fait cela ne faisait que copier les données et créer un nouvel URI. Rien de très web sémantique. A priori on va plutôt se concentrer sur le respect du standard WebID-OIDC. Cependant il peut y avoir le besoin, sur une instance, d'importer des utilisateurs comme moyen de les rendre visibles.

@simonLouvet @tfrancart @nikoPLP je vous laisse prendre connaissance de ces réflexions. Vous pouvez y répondre ici, mais on peut aussi en reparler jeudi lors de la réunion dédiée au sujet de l'interopérabilité inter-SemApps.

**Comment by bouviermullerp** [comment]
Merci @srosset81 pour cette synthèse.

> Le cas d'usage: on a une instance Passerelle Normandie avec des événements. Une autre instance Chemins de la Transition aimerait ajouter certains événements (mais pas tous) de Passerelle Normandie sur sa propre instance, mais sans avoir à les copier. Idéalement il suffirait d'indiquer l'URI de l'événement et il serait ajouté à la liste des événements.

Je suis curieux d'avoir vos impressions sur ce sujet et si vous connaissez des pratiques dans des autres communautés ? car chaque site à sa stratégie éditoriale, et un site ne veut pas référencer tous les évènements Mobilizon, ou toutes les vidéos peertube. Comment sélectionner les éléments qu'on souhaite afficher sans cette fonctionnalité ? Quelle serait l'usage ?

J'ai l'impression qu'on peut commencer sur quelque chose de très simple "à la transiscope". Que les données d'une données importées soit copié dans un cache et que quand la données source est mise à jour, alors le cache de la nouvelle interface est aussi mis à jour.
L'affichage de cette donnée précise la source (la ou l'on doit la modifier pour la mettre à jour).

**Comment by srosset81** [comment]
> Je suis curieux d'avoir vos impressions sur ce sujet et si vous connaissez des pratiques dans des autres communautés ? car chaque site à sa stratégie éditoriale, et un site ne veut pas référencer tous les évènements Mobilizon, ou toutes les vidéos peertube. Comment sélectionner les éléments qu'on souhaite afficher sans cette fonctionnalité ? Quelle serait l'usage ?

J'avoue ne pas connaître les usages de Mobilizon ou Peertube concernant les liens avec les autres instances. Ce serait intéressant de prendre le temps de l'explorer.

> J'ai l'impression qu'on peut commencer sur quelque chose de très simple "à la transiscope". Que les données d'une données importées soit copié dans un cache et que quand la données source est mise à jour, alors le cache de la nouvelle interface est aussi mis à jour.
> L'affichage de cette donnée précise la source (la ou l'on doit la modifier pour la mettre à jour).

Il y a plein de solutions "à l'arrache", mais là l'enjeu c'est de faire les choses dans le respect des standards et des bonnes pratiques du web sémantique, afin que la solution soit pérenne et qu'on ne doive pas tout refaire 3 mois plus tard :-) D'où la discussion de jeudi, où tu es aussi le bienvenu.

**Comment by tfrancart** [comment]
Je vote pour la solution d'import des données avec resynchronisation périodique.

rdfs:isDefinedBy est une propriété définie dans le vocabulaire RDFS pour lier une URI au document qui définit cette URI : https://www.w3.org/TR/rdf-schema/#ch_isdefinedby
C'est l'équivalent du semapps:synchronizedWith proposé plus haut.
D'une façon générale, il pourrait être judicieux de conserver ce triplet de façon systématique sur toutes les ressources importées. La valeur serait le document RDF contenant la description de l'URI, qui n'est pas toujours à la même adresse que l'URI d'origine. Cela permettrait d'adresser le cas général d'import de données depuis autre chose que SemApps

`<http://domaine.fr/maRessource> rdfs:isDefinedBy <http://domaine.fr/maResource.ttl>`

**Comment by scenaristeur** [comment]
Si je peux me permettre ( on ne me demande pas mon avis, mais je suis toujours là où on ne m'attendais pas)...
J'aurais plutôt penché vers la création d'un resource dans le container, sans synchro, sans import, juste avec un rdfs:seeAlso qui à mon avis est là justement pour ça https://www.w3.org/wiki/UsingSeeAlso .
Ça évite les problèmes de synchro, de cache, de droits... 
La ressource décrivant l'événement existe à un seul endroit, sur une URL donnée, les autres instances peuvent avoir une référence vers cette ressource... C'est tout l'intérêt des données liées, non? Niveau Ui, si tu as rdfs:seeAlso tu agrégés, ou remplacé par les infos si l'utilisateur est autorisé...

**Comment by srosset81** [comment]
Commentaires suite à la réunion de ce jour ([voir le CR complet](https://pad.lescommuns.org/UVcvt8XGT5mUK6mvzlMCTg)):

- Pour synchroniser les données entre serveurs, Thomas fait des requêtes SPARQL. Cela peut marcher aussi bien qu'un GET sur la ressource LDP, sauf qu'il faut que le serveur ait un endpoint SPARQL disponible.
- Pour gérer les WebACL, le plus cohérent est d'importer les triplets WebACL en même temps que les triplets spécifiques à la ressource. On peut les mettre dans le graph spécifique aux WebACL. Cela sous-entend cependant que le serveur local peut gérer les WebACL.
  - Une alternative plus simple serait de ne permettre d'importer une ressource que s'il y a un droit acl:Read en tant qu'anonyme. Et si ce droit est supprimé, alors on supprime la ressource du container. On aurait un message d'erreur si on essaie d'importer une ressource qui n'est pas lisible.
- Concernant les prédicats, on va utiliser `dc:source` plutôt que `semapps:forkedFrom` (on a déjà prévu d'utiliser l'ontologie Dublin Core à d'autres endroits). Pour les données qui doivent être synchronisées, il suffit juste d'indiquer la date de la dernière synchronisation, p.ex avec le prédication `semapps:lastSynchronized` (pas d'équivalent dans des ontologies existantes a priori).

**Comment by srosset81** [comment]
Suite à la relecture de cette issue, j'ai une remarque par rapport à cette note:

> - Il y a aussi la question de la **modification** d'une donnée "synchronisée". Il ne faudrait pas modifier les données dans le triple store local. Par contre rien n'empêche de faire une PATCH ou un PUT sur la ressource distante. On pourrait vérifier les droits WebACL en amont. Une fois le PATCH/PUT fait et accepté, le bot pourrait resynchroniser les données localement.

A partir du moment où les WebACL sont activés sur la ressource distante, il faudra impérativement que WebID-OIDC soit utilisé pour pouvoir lire ou modifier des ressources distantes, car le JWT token qui permet de certifier le webId de l'utilisateur actuel ne pourra pas être compris par le serveur distant.

**Comment by srosset81** [comment]
## Implémentation

- Ajouter possibilité de faire un PATCH sur container LDP (on ne passe que l'URI)
- Si on détecte que le serveur B est miroir de A, il n'y a rien à faire (les données sont synchronisées)
- Sinon, il faut lancer un cron (p.ex. toutes les heures) pour aller fetcher les données distantes
- Les données sont enregistrées dans le graph miroir (sauf le `ldp:contains` avec l'URI de la ressource distante)
- Sur le LDP GET du container, il faut inclure le graph des données miroirs
