### ISSUE TITLE
Définir des ontologies core

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#701]
Il y a plusieurs ontologies que nous utilisons et sans lesquelles SemApps ne fonctionne pas.

Ce serait bien qu'elles soient rendues obligatoires, en définissant par exemple un fichier de core ontologies, qui serait fusionner avec les ontologies spécifiques à la plateforme (additionalOntologies ?)

**Comment by GuillaumeAV** [comment]
Quelles sont elles ? PAIR, FOAF ?

**Comment by srosset81** [comment]
Pas PAIR non, c'est spécifique.
FOAF, RDFS, LDP...

**Comment by GuillaumeAV** [comment]
C'est ce qu'il me semblait ! Coool !

**Comment by srosset81** [comment]
Pour info @tawytest n'arrivait pas à afficher des images uploadées car il n'avait pas l'ontologie http://semapps.org/ns/core# dans les fichiers ontologies.js et context.json

Il faudra trouver un moyen d'ajouter automatiquement les ontologies core au fichier de context JSON-LD.

**Comment by srosset81** [comment]
Ca va être géré ici: https://github.com/assemblee-virtuelle/semapps/pull/1212
Les services pourront définir les ontologies dont ils ont besoin. Donc la notion de "ontologies core" n'a plus trop de sens.
