### ISSUE TITLE
Modification des types et statuts 

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#703]
**Décrivez le bug**
Quand je veux modifier la classe d'appartenance d'un type ou d'un statut, ce n'est pas possible.

**Etapes pour reproduire**
1. Aller sur 'Type / Turoriel'
2. Essayer de changer la classe
3. Voir l'erreur
Sur firefox ..

**Comment by srosset81** [comment]
C'est intentionel. Si on crée un `pair:DocumentType` "Tutoriel" et qu'on le change ensuite pour `pair:AgentType`, les documents qui utiliseraient le type "Tutoriel" utiliseraient des types de la mauvaise classe et ça poserait problème.

Si on se trompe de classe à la création, il suffit d'effacer le type et d'en recréer un.
