### ISSUE TITLE
Ajouter les statuts aux organisations

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#706]
**Décrivez le bug**
J'ai créé des statuts AgentStatus pour pouvoir mettre les statuts suivants sur les orgas : 

- Membre AV
- Partenaire AV
- Sympathisant AV

Mais il n'est pas possible de mettre un statut sur une orga

**Etapes pour reproduire**
1. Aller sur une orga
2. Essayer de mettre un statut ... 
3. Voir l'erreur

**Comment by srosset81** [comment]
C'est pas un bug, juste une donnée qui n'est pas encore gérée.
Merci de réserver le label bug aux vrais bugs, pas aux choses qui manquent.
