### ISSUE TITLE
 Multiple Returns from a Routine

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#72]
Le fait de faire des retours multiples au cours d'une fonction me pose des problèmes de lisibilité et de maintenabilité. Bien que ce soit une pratique courante, j'ai déjà gaspillé plusieurs heures sur des projets complexes pour résoudre des bugs qui provenaient de ce genre de pratique car elles entraînaient une mauvaise compréhension du fonctionnement de la fonction. 

Cela se confirme dans le chapitre 17.1 de code complete qui est un peu la bible des bonne pratique de développement procédurale. 
17.1 Multiple Returns from a Routine
http://aroma.vn/web/wp-content/uploads/2016/11/code-complete-2nd-edition-v413hav.pdf

Je ne suis donc pas pour une pratique systématique d'un seul return par fonction/procédure mais cela ne me convient pas de dire qu'un clean up consiste à transformer un return finale en de multiples return.

**Comment by srosset81** [comment]
En lisant le chapitre de Code Complete, il me semble qu'ils ne sont pas si opposés que ça aux multiples retours. Par exemple ils donnent ça comme un exemple de bonne pratique en C++:
```
Comparison Compare( int value1, int value2 ) {
 if ( value1 < value2 ) {
 return Comparison_LessThan;
 }
 else if ( value1 > value2 ) {
 return Comparison_GreaterThan;
 }
 return Comparison_Equal;
}
```
Je pense que c'est surtout problématiques pour les grosses fonctions, qui font des returns là où on n'aurait pas imaginé. Si c'est vers la fin de la fonction, c'est déjà plus lisible.

Pour moi, le meilleure remède à ce type de problèmes, c'est de créer seulement des petites fonctions qui font des choses précises. J'ai lu plusieurs fois qu'une fonction qui fait plus de 20 lignes devrait être refactorée. Certains disent même 10 lignes !

En tout cas la prochaine fois que je fais un "clean up" de ce type, je ferai une PR pour qu'on en discute !

**Comment by simonLouvet** [comment]
ma conclusion était mal formulée.
