### ISSUE TITLE
Jena Fuseki n'affiche pas le contenu du dataset

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#720]
**Décrivez le bug**
Lorsque nous allons dans jena fuseki, dans le dataset, ce dernier n'affiche pas le contenu du triplestore ou de la requête.

**Etapes pour reproduire**
1. Aller sur http://localhost:3030 (admin/admin)
2. Cliquer sur l'onglet dataset
3. Soit vour allez sur Edit > List current graph ou si vous essauez de lancer la requête, rien ne se passe, ça tourne en boucle.

**Comportement attendu**
On souhaite voir les triplets.

**Comment by fluidlog** [comment]
La solution temporaire, en attendant un correctif sur Fuseki, est d'ajouter /localData/sparql dans le champ "SPARQL endpoint" de l'onglet query.

**Comment by srosset81** [comment]
Ce n'est pas un bug de SemApps, mais de Fuseki, du coup je ne pense pas que ça ait du sens de mettre une issue ici.

**Comment by fluidlog** [comment]
Je pensais juste alimenter notre future FAQ avec cette solution de contournement.

**Comment by srosset81** [comment]
Je propose plutôt de faire une page wiki. Les issues n'ont pas pour vocation de répertorier ce type de problèmes.
