### ISSUE TITLE
Permettre au navigateur de mettre en cache les images

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#729]
Les uploads n'ont aucun header de Cache-Control quand on les affiche.

https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Cache-Control

Cela a pour résultat que les images ne sont pas gardées en cache par le navigateur, et qu'elles sont rechargées à chaque fois.

**Comment by bouviermullerp** [comment]
lié à #762 ?

**Comment by srosset81** [comment]
Du tout :-)
