### ISSUE TITLE
Créer des issues avec les relations manquantes sur Archipel

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#738]
@capucinemasson et @sauvagemathilde ont du temps pour faire des améliorations sur Archipel.

@GuillaumeAV est-ce que tu pourrais faire un tour sur Archipel pour identifier les relations ou data properties qui seraient manquantes, et créer les issues correspondantes ? (une issue par classe à modifier STP)

**Comment by GuillaumeAV** [comment]
Helloo ! Ok super ! Malheureusement, je ne sais pas si vous vous servez d'archipel régulièrement, de mon côté, je n'arrive plus à l'utiliser depuis quelques semaines, ne pouvant plus renseigner de relations ... Je vais faire un vrai diagnostic et une vraie issue dans la foulée ...  
Et je proposerai ensuite des issues avec relations et data properties manquantes ..

**Comment by srosset81** [comment]
J'avais regardé pour les documents https://github.com/assemblee-virtuelle/semapps/issues/705
Si le navigateur s'emballe pour d'autres relations, merci de le dire (c'est sans doute la même chose, mais intéressant à identifier tout de même)
