### ISSUE TITLE
Possibilité de modifier une ressource dans être connecté sur dev.archipel

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#758]
**Décrivez le bug**
Je ne suis pas connecté et je suis sur l'instance DEV.
Je peux modifier les ressources "rôle" et "statut"

https://dev.archipel.assemblee-virtuelle.org/MembershipRole

**Comportement attendu**
Il n'est pas possible de sauvegarder.

ping @srosset81

**Comment by srosset81** [comment]
Fixé https://github.com/assemblee-virtuelle/semapps/commit/360affb09c54bd93e98acb4a2930584407f98603
