### ISSUE TITLE
Lorsqu'on édite une organisation, les données des organisations partenaires sont envoyées

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#759]
Ce bug pose un problème pour la gestion des permissions.

**Etapes pour reproduire**
1. Aller sur https://archipel.assemblee-virtuelle.org/Organization/https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2Fademe
2. Modifier quelque chose
3. Voir les données envoyées:

![Capture d’écran de 2021-05-14 11-05-35](https://user-images.githubusercontent.com/17931931/118248228-5c3bef00-b4a4-11eb-85c8-1cb43485aba2.png)

**Comportement attendu**
Envoyer juste l'ID des partenaires.

**Comment by srosset81** [comment]
Trouvé ! (3h plus tard...) Le problème est dû au framing JSON-LD qu'on fait lorsqu'on récupère les résultats SPARQL. Les organisations partenaires sont embeddés dans les résultats des organisations.

**Comment by srosset81** [comment]
Une solution serait de définir explicitement ce qu'on veut "embedder" dans le contexte, en utilisant le paramètre `dereference` qui est disponible dans le data provider. Cela marche bien comme ça:

```
        const compactJson = await jsonld.frame(json, {
          '@context': jsonContext || buildJsonContext(ontologies),
          '@type': resources[resourceId].types,
          '@embed': '@never',
          'pair:hasLocation': {
            '@embed': '@always',
            'pair:hasPostalAddress': {
              '@embed': '@always'
            }
          }
        });
```

Par contre ça ne va pas marcher avec le paramètre queryDepth :-/

**Comment by srosset81** [comment]
Je me demande s'il serait pas plus simple de faire une requête SPARQL juste pour récupérer l'ID des ressources, puis de faire un GET sur les ressources. Cela augmenterait le nombre de requête, mais on aurait l'avantage de pouvoir utiliser le cache Redis. On aurait pas à gérer toute la complication de dereferencer côté client. Même pour la pagination, ce serait plus simple, car on aurait pas à faire de GET sur les données qui ne sont visibles. Dernière cerise sur le gâteau: moins de permissions à vérifier pour Fuseki.

Un avis @simonLouvet ?

**Comment by srosset81** [comment]
Fixé ici https://github.com/assemblee-virtuelle/semapps/pull/764

**Comment by simonLouvet** [comment]
Si j'ai bien compris, tu veux dereferencer par des getter LDP plutôt que du SPARQL? @srosset81

**Comment by srosset81** [comment]
> Si j'ai bien compris, tu veux dereferencer par des getter LDP plutôt que du SPARQL? @srosset81

Oui j'ai essayé ça mais j'ai laissé tomber car ça posait des problèmes de perf. En fait ça faisait même crasher Fuseki. :-/ Je sais pas pourquoi, ce sera à creuser une autre fois, là je n'avais pas l'énergie, du coup je suis revenu à l'ancienne manière, en ajoutant les directives `@embed` sur le JSON-LD framing.
