### ISSUE TITLE
Les organisations ne chargent plus

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#760]
https://archipel.assemblee-virtuelle.org/Organization

**Comment by scenaristeur** [comment]
idem pour moi 
les users sont ok https://scenaristeur.github.io/ipgs/?url=https%3A%2F%2Fdata.virtual-assembly.org%2Fusers%2F
mais pas les orgas, https://scenaristeur.github.io/ipgs/?url=https%3A%2F%2Fdata.virtual-assembly.org%2Forganizations%2F

J'ai un blocage CORS / Bad Gateway 

![image](https://user-images.githubusercontent.com/4020744/118486725-3cadfc00-b71a-11eb-8cda-4b8dc49d9d4f.png)

**Comment by srosset81** [comment]
Il y avait des dizaines de blank nodes pour l'adresse de Data Players. En les effaçant ça passe :-)

Il va falloir mieux gérer l'effacement des blank nodes...
