### ISSUE TITLE
Abandonner le paramètre queryDepth

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#766]
Pour résoudre https://github.com/assemblee-virtuelle/semapps/issues/759 j'ai été obligé d'embedder explicitement les blank nodes au moment du framing JSON-LD. Cette technique ne marche pas avec le paramètre `queryDepth` car on ne sait pas où se trouvent les blank nodes.

@simonLouvet est-ce OK pour toi si on laisse tomber le paramètre `queryDepth` ? Personnellement je n'utilise plus que le paramètre `dereference`, qui est plus performant et plus clair.

**Comment by simonLouvet** [comment]
ok pour abandonner le queryDepth. Le déreference est beaucoup plus explicite.

**Comment by srosset81** [comment]
J'ai ajouté ça dans la milestone v0.4, car ça sera complémentaire avec https://github.com/assemblee-virtuelle/semapps/issues/909

**Comment by srosset81** [comment]
Pour finir ça a été réintroduit dans la v0.6 ;-)
