### ISSUE TITLE
Superposition du titre et des actions en version tablette

### ISSUE THREAD

**Issue by VincentFarcy** [assemblee-virtuelle/semapps#770]
**Décrivez le bug**
Lorsque l'on réduit la largeur d'écran autour de 700px le titre principal et les boutons d'action se superposent

**Etapes pour reproduire**
[https://archipel.assemblee-virtuelle.org/Organization](url)
passer en taille d'écran 700px 

**Comportement attendu**
Je propose de simplement masquer le titre en dessous d'une certaine taille d'écran.
Le titre est déjà masqué en version mobile.

**Captures d'écran**
![image](https://user-images.githubusercontent.com/55813208/118954109-be419c00-b95d-11eb-9977-8978a6fd3d21.png)

**Comment by VincentFarcy** [comment]
@srosset81 
Issue dont nous avons parlé Lundi. 
J'attend un avis sur la correction proposée avant de la mettre en place.
a+

**Comment by srosset81** [comment]
A mon avis le masquage du titre n'est pas souhaitable. Pour la liste des organisations ça peut encore passer, mais lorsqu'on consulte une ressource (mode Show), ne pas voir le titre signifie ne pas voir le nom de la ressource qu'on consulte.

Du coup c'est un truc qu'il faudrait aussi corriger sous mobile...

**Comment by bouviermullerp** [comment]
Yep, l'affichage mobile est assez différent, je suis limité à l'affichage en liste - pas possible de basculer en affichage carte.

++ pour le titre de la ressource (et des autres attributs), je pense que c'est important de le conserver. A mon avis, c'est plutôt sur les boutons d'action qu'il faut jouer (list, éditer, carte, exporter).

De manière un peu globale, j'ai l'impression que le bouton "exporter" n'a pour le moment aucun usage. Proposition de le supprimer. J'ai aussi un doute sur "actualiser".
Le bouton de création de ressource pourrait être mis en valeur d'une manière un peu différente (peut être un simple + à coté du titre de l'attribut ?)
