### ISSUE TITLE
LdpService: rediriger vers l'interface quand on visualise une donnée avec un Accept text/html

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#771]
Lorsqu'un navigateur va sur une URL comme https://data.virtual-assembly.org/users/srosset81 avec un Accept header `text/html` (consultation depuis un browser) ne pourrions-nous pas rediriger automatiquement sur l'interface "par défaut" (ou "préférée") définie dans le middleware ?

J'ai vu qu'ils font ça pour l'[ESCO](https://ec.europa.eu/esco/portal/api) (open data des compétences):

- Si on va sur http://data.europa.eu/esco/occupation/528f90ed-e250-48bd-aacc-ffb7b1de5654 on est redirigé sur [une page](https://ec.europa.eu/esco/portal/occupation?uri=http%3A%2F%2Fdata.europa.eu%2Fesco%2Foccupation%2F528f90ed-e250-48bd-aacc-ffb7b1de5654&conceptLanguage=fr&full=true#&uri=http://data.europa.eu/esco/occupation/528f90ed-e250-48bd-aacc-ffb7b1de5654) qui permet de visualiser la donnée.
- Par contre si on utilise Postman ou Insomnia avec un Accept header de type `text/turtle`, on voit les données sous forme de triple.

Est-ce que c'est possible selon les bonnes conceptions du web sémantique ? J'ai l'impression que oui, et que c'est le sens même du header Accept.

Cela devrait être une option bien sûr, pas d'obligation à définir une interface "préférée" côté middleware.

Ping @simonLouvet @tfrancart

**Comment by tfrancart** [comment]
Ha oui c'est de la négociation de contenu, le header Accept sert exactement à ca et c'est très bien :-)
Autre exemple au hasard sur les URI du thesaurus de l'UNESCO http://vocabularies.unesco.org/thesaurus/concept1179

**Comment by srosset81** [comment]
Commentaires suite à la réunion de ce jour ([voir le CR complet](https://pad.lescommuns.org/UVcvt8XGT5mUK6mvzlMCTg)):

- Autre alternative: obtenir l'URL de "l'interface préférée" via une requête Head, afin de pouvoir mettre tout de suite le bon lien ? (a priori on pourrait proposer les deux solutions)
- Voir si la notion d'interface préférée existe dans les standards du web ou du web sémantique.

**Comment by nikoPLP** [comment]
implemented as follow :

in your `ldp.service.js` file that bootstraps your LDP service, add this setting :
```
   preferredViewForResource : function(resourceUri, containerPreferredView) {
      if (!containerPreferredView) return resourceUri;
      return 'https://yourFrontEndServer.com'+containerPreferredView+encodeURIComponent(resourceUri)+'/show'
    }
```

and in your `containers.js` config file, for each container that you want a redirect for, add this setting (example for users): 
```
  {
    path: '/users',
    acceptedTypes: ['pair:Person'],
    preferredView: '/Person/',
    dereference: ['sec:publicKey', 'pair:hasLocation/pair:hasPostalAddress'],
  },
```
