### ISSUE TITLE
Erreur de version de React en lançant Lerna bootstrap

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#774]
Problème rencontré par @mathildesauvage sous Windows avec Node v12.19.1:

https://fr.reactjs.org/warnings/invalid-hook-call-warning.html

Il y avait deux versions de React (une pour le boilerplate archipelago, une autre pour les packages).

Le problème a été résolu en n'utilisant plus Lerna bootstrap, mais en faisant un `npm install` dans le boilerplate archipelago.

C'est un problème identifié ici et qui concerne autant Lerna bootstrap que NPM link:
https://github.com/facebook/react/issues/13991#issuecomment-435343455
Dans le commentaire, un hack est proposé, qui n'a pas été essayé.

Idéalement il faudrait être sûr que les deux versions de React soient les mêmes, ce qui n'est malheureusement pas évident.

**Comment by fluidlog** [comment]
@srosset81 Je propose de fermer cette issue depuis les derniers changements vers yarn ?
