### ISSUE TITLE
Supprimer le paramètre forceSemantic de ldp.resource.get

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#776]
Il suffirait de regarder le paramètre `accept` (header Accept) pour savoir si on renvoie un fichier ou une donnée sous format sémantique.

Ce paramètre est obscur et il est facile d'obtenir des bugs si on oublie de le passer.

A faire en même temps que https://github.com/assemblee-virtuelle/semapps/issues/576 et https://github.com/assemblee-virtuelle/semapps/issues/659

**Comment by fluidlog** [comment]
Je me la mets sous le coude...

**Comment by srosset81** [comment]
Done
