### ISSUE TITLE
Attacher une Inbox et une Outbox aux nouveaux utilisateurs

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#78]
A chaque fois qu'un utilisateur est créé, lui attacher ces endpoints:
```
{
  followers: "/users/{username}/followers",
  following: "/users/{username}/following",
  outbox: "/users/{username}/outbox",
  inbox: "/users/{username}/inbox"
}
```

**Comment by srosset81** [comment]
@simonLouvet  Pour que cela soit possible, il faudra émettre un événement à chaque fois qu'un nouvel utilisateur est créé, avec au minimum l'URI de l'utilisateur nouvellement créé, et si possible son username.

**Comment by simonLouvet** [comment]
@srosset81 si je comprends bien, tu parle d'un user qui serait ajouter par un post ldp? que le service ldo émette un message sur le broker pour que activity pub fasse une opération dédié à la gestion des inbox/outbox?
Si 'est bien cela, ok pour moi

**Comment by srosset81** [comment]
@simonLouvet Oui il s'agit d'émettre un message au broker. Au début cela sera sans doute fait par le service LDP, mais quand on aura un vrai système d'autentification, ce sera peut-être un autre service qui émettra l'événement. Tant que je peux le recevoir ça me va ;-)

**Comment by nikoPLP** [comment]
Donc il s'agirait de faire, coté LDP, un `broker.emit("user.created", user);` avec user qui est un objet contenant l'URI et le username.
Et coté activitypub, dans la definition du service ce serait cela:
```
events: {
        "user.created": {
            handler(ctx) {
                console.log("user created:", ctx.params);
            }
        }
    }
```
