### ISSUE TITLE
Le contexte JSON-LD local n'est pas accessible sous Docker 20.10.6

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#790]
**Problème**
Si j'ai un contexte local (typiquement https://mondomain.com/context.json), les outils de formattage JSON-LD n'arrivent pas aller récupérer le contexte à l'adresse indiquée. J'ai des erreurs de type `Failed to load remote context`.

> Docker engine version: 20.10.6
> Docker-compose version: 1.29.2 

**Pistes de résolution**
Si je fais un `nslookup mondomain.com` depuis le container Docker, il me renvoie une IP locale de type 127.0.1.1:53. Même chose si le domain est attaché à un autre container, mais sur le même serveur.
Il est possible que le container n'arrive pas à accéder à cette adresse IP ?
Peut-être un problème au niveau du network Docker ? J'en ai ajouté un mais ça ne semble pas avoir résolu le problème.
Sinon un problème au niveau de Traefik ?

**Solution temporaire**
En downgradant Docker vers 19.03.11 et Docker-compose vers 1.26.0, le problème a disparu.
Ce n'est pas satisfaisant car on ne peut pas imposer à nos utilisateurs d'utiliser une ancienne version de Docker :-/

**Comment by srosset81** [comment]
Ping @simonLouvet @fluidlog
A priori évitez Docker 20, sauf si vous voulez investiguer ce délicieux bug (il m'a coûté 2 journées)

**Comment by fluidlog** [comment]
Je n'avais pas vu cette issue ! Comme quoi, il est bon de les passer en revue au moins une fois ! :)
Je suis actuellement en docker 20.10;12. Je me l'affecte juste pour faire le test...

**Comment by srosset81** [comment]
Fixed some time ago
