### ISSUE TITLE
Etablir une roadmap pour le développement de SemApps sur les 6-12 mois à venir

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#793]
Comme nous en avons parlé récemment, cela pourrait être une information utile que le cercle "Développement" pourrait partager avec le reste de l'équipe, et aussi avec les acteurs extérieurs.

L'ajout de fonctionnalités dépend des budgets qu'on reçoit, mais comme on est une petite équipe (et qu'on le restera tant que d'autres développeurs expérimentés ne seront pas montés en compétence sur SemApps), les grosses fonctionnalités vont forcément prendre du temps à être implémentées.

A titre d'exemple, il a fallu presque 3 mois pour implémenter la gestion des WebACL, malgré le fort investissement de Niko et de moi-même.

Cette roadmap ne concernerait donc que les grosses fonctionnalités.

Elle pourrait faire l'objet de communication à l'extérieur.

Ping @simonLouvet @bouviermullerp @GuillaumeAV

**Comment by srosset81** [comment]
A titre d'exemple, l'interopérabilité inter-SemApps ne sera sans doute pas prête avant la fin de l'année. Cela dépend bien sûr de ce qu'on entend par interopérabilité. On pourra peut-être donner une estimation plus précise après la réunion qu'on a sur le sujet demain avec Thomas, Niko et Simon.

**Comment by bouviermullerp** [comment]
De ma vision, voici les éléments que j'ai dans le radar : 
- Les CDLT pourraient financer une partie de l'intéropérabilité entre SemApps #451 - si on a du RAB
- La prestation pour l'AFAUP va sans aucun doute permettre de financer ce chantier #451 
- La prestation pour le PETR Macon Bourgogne pourrait financer une partie de la recherche avancée avec Sparnatural #13

**Comment by srosset81** [comment]
Du point de vue des standards, je crois qu'on va aussi devoir s'occuper de WebID-OIDC (#434) car une fois qu'on aura des liens multi-instances, il va nécessairement se poser le problème de l'authentification. Cela me semble être une fonctionnalité coeur du web sémantique, et donc de SemApps.

J'avais pensé aussi à SHACL/SHEX (https://github.com/assemblee-virtuelle/semapps/issues/795) mais je crois qu'il vaut mieux attendre qu'un besoin émerge.
