### ISSUE TITLE
Pouvoir aggréger les ressources de plusieurs instances

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#794]
![Interopérabilité entre instances SemApps](https://user-images.githubusercontent.com/17931931/133048940-560a4e64-c573-48ea-bb3e-246046d2eb97.png)

**Besoin**
Sur une instance type Archipel, j'aimerais pouvoir afficher la liste des ressources de plusieurs instances. Par exemple, sur une carte géographique, lister des `pair:Organization` répertoriées par Archipel et par Glocal-Lowtech.

**Implémentation**
L'implémentation est très liée aux issues https://github.com/assemblee-virtuelle/semapps/issues/353 et https://github.com/assemblee-virtuelle/semapps/issues/461 car pour pouvoir faire une recherche aggrégée sur plusieurs instances via un input de type "autocomplete", il faut que le data provider de React-Admin puisse lister les ressources de plusieurs instances.

Cela va forcément passer par [l'amélioration du data model](https://github.com/assemblee-virtuelle/semapps/issues/686) afin de lui permettre d'indiquer plusieurs sources.

**Comment by srosset81** [comment]
Commentaires suite à la réunion de ce jour ([voir le CR complet](https://pad.lescommuns.org/UVcvt8XGT5mUK6mvzlMCTg)):

- On pourrait imaginer des containers LDP qui agrégerait dynamiquement des données de différents servers
- ActivityPub pourrait aussi être utilisé pour faire de l'agrégation, comme c'est fait pour Mobilizon ou Peertube

**Comment by srosset81** [comment]
## Implémentation
Il y aura plusieurs manières de définir les sources:
- Dans le fichier dataServers.js https://gist.github.com/srosset81/2bcf79ef2b5a01619a4e806ecc74db7f#file-ecosystem-js-L18 où l'on défini les serveurs par défaut
- Dans le composant List ou ListBase, où on pourra utiliser la props `filter`, en utilisant la propriété `_servers`
- Avec un composant de filtre (#855)

**Comment by fluidlog** [comment]
A relier aux travaux sur l'interop ?

**Comment by srosset81** [comment]
Ca fait partie du chantier oui #451

**Comment by srosset81** [comment]
Je vais implémenter maintenant cette option qui était prévue:

> - Dans le composant List ou ListBase, où on pourra utiliser la props filter, en utilisant la propriété _servers

Ca sera utilisé pour https://github.com/assemblee-virtuelle/semapps/issues/945. Lors de la recherche des données à importer, on veut pouvoir chercher sur tous les serveurs. Je vais passer un filter `{ server: "@all" }`
