### ISSUE TITLE
Bug sur la connexion les communs

### ISSUE THREAD

**Issue by GuillaumeAV** [assemblee-virtuelle/semapps#800]
**Décrivez le bug**
Une description claire et concise du bug.

**Etapes pour reproduire**
1. Aller sur 'archipel'
2. Cliquer sur 'se connecter'
3. S'inscrire, valider le mail et voir l'erreur ...  

**Comportement attendu**
Une fois qu'on valide la mail, on devrait pouvoir être connecté sur Archipel ..

**Comment by srosset81** [comment]
Résolu. J'avais oublé de mettre à jour le middleware avec la dernière version.
