### ISSUE TITLE
Bug de chargement des images dans Archipel / serveur GL

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#821]
**Décrivez le bug**
Suite au chargement d'une photo sur l'instance GLT, dans la fiche d'une personne ou orga, celle-ci ne se charge pas en entier et apparait tronquée toujours de la même manière.
Pas de problème sur l'instance Archipel de l'AV.

**Etapes pour reproduire**
1. Aller sur le serveur GL : https://semapps.gl.assemblee-virtuelle.org/Person
2. Cliquer sur Yannick (le problème apparait aussi sur la photo des orgas)
3. Aller dans "Editer", charger de nouveau une photo, elle s'affiche bien la première fois, et suite à l'action sur "Enregistrer", elle ne s'affiche plus correctement.

**Comportement attendu**
Affichage de la photo en entier

**Captures d'écran**
![tronquage photo](https://user-images.githubusercontent.com/6891994/124968778-33f4ea80-e026-11eb-9172-d26b69dbcfec.png)

**Système**
Reproduit sur Firefox et Chrome.

**Comment by fluidlog** [comment]
Constat de Simon Louvet : 
"Nous avons également des probleme d'image sur passerelle mais en upload et pas en download. Ce que nous avons pu constaté c'est que la quantité d'information (image complete ou pas) dépend du réseau et que un upload sur un réseau faiblard se fini souvent par une image à oitier chargé. Je soupçonne un timeout sur l'upload qui coupe le stream de réception coté serveur ou navigateur."

**Comment by srosset81** [comment]
J'ai la même chose côté Colibris. A priori oui c'est un problème de timeout.

**Comment by simonLouvet** [comment]
linked to #834
