### ISSUE TITLE
Gestion flexible des containers LDP standards

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#83]
Pour le serveur ActivityPub, j'ai besoin de pouvoir définir "à la volée" le container LDP dans lequel iront les objets, et j'ai besoin le nom de cet objet dépende du container.

> Cela concerne les containers "standards" (= enregistrés en triple store) et non pas les containers "automatiques".

Par exemple pour une ressource de type `ActivityStreams#Note`, j'ai besoin qu'elle soit enregistrée dans un container `/note` (défini par moi).
De plus, j'ai besoin que la ressource créée obtienne un URI de type `/note/{id}`, l'ID pouvant être soit un nombre incrémenté (si c'est pas trop compliqué à géré), soit un UUID.

Idéalement, il faudrait aussi que l'on puisse indiquer un slug pour la ressource, comme indiqué dans la section 2.4 du [LDP Primer](https://www.w3.org/TR/ldp-primer/). A la limite, le service pourrait "sluggifier" lui-même la string qui lui est passée si celle-ci n'est pas conforme (?)

Voilà à quoi ressemblerait idéalement l'appel:
```js
const note = {
 "@context": "https://www.w3.org/ns/activitystreams",
 "type": "Note",
 "name": "Mon premier message",
 "attributedTo": "http://localhost:3000/activitypub/actor/srosset81",
 "content": "Voilà mon premier message, très content de faire partie du fedivers !"
};

const resourceUri = ctx.call('ldp.postRessource', { 
  resource: note,
  containerUri: 'http://localhost:3000/note', 
  slug: note.name
});

// resourceUri = "http://localhost:3000/note/mon-premier-message"
```

**Comment by srosset81** [comment]
Pour le `GET http://localhost:3000/note` et `GET http://localhost:3000/note/mon-commentaire`, on peut utiliser un catch-all qui est appelé systématiquement si aucun autre path ne match. Express gère ça très bien, et sans doute aussi Moleculer (via un middleware peut-être ?).

**Comment by srosset81** [comment]
Qu'en pensez-vous @simonLouvet @nikoPLP ?

**Comment by simonLouvet** [comment]
@srosset81 pourquoi avoir besoin d'un slug. Un UUID ne te convient pas? Pas de problème pour gérer les slug pour un basic container à première vu mais je cherche le besoin.

**Comment by srosset81** [comment]
> @srosset81 pourquoi avoir besoin d'un slug. Un UUID ne te convient pas? Pas de problème pour gérer les slug pour un basic container à première vu mais je cherche le besoin.

C'est une possibilité évoquée dans le LDP primer (section 2.4). Cela peut avoir du sens. Par exemple si les utilisateurs sont gérés par LDP (ce dont je ne suis pas sûr sur le long terme, mais c'est un autre sujet ... !), on pourrait avoir l'username en slug, et ainsi avoir un URI de type `/user/srosset81` plutôt que `/user/5t15sdgtdc78`.
Des API claires, c'est mieux pour la DX, et ça peut aussi être mieux pour éviter des calculs supplémentaires (par exemple si on a l'username de l'utilisateur, on n'a pas besoin de faire une requête juste pour trouver son UUID).

**Comment by nikoPLP** [comment]
@srosset81 pas besoin de middleware, moleculer-web fait ça tres bien, voir ici pour des exemples:
https://moleculer.services/docs/0.14/moleculer-web.html#Aliases

**Comment by srosset81** [comment]
> @srosset81 pas besoin de middleware, moleculer-web fait ça tres bien, voir ici pour des exemples:
> https://moleculer.services/docs/0.14/moleculer-web.html#Aliases

Ah effectivement puisque ça gère path-to-regexp :-) Faudrait faire `GET :path` ou `GET *` ?

**Comment by simonLouvet** [comment]
++ pour le slug

**Comment by nikoPLP** [comment]
````
"GET users": "users.list",
"GET users/:slug": "users.get",
```
est un exemple de ton cas : un accès generique (premiere ligne), et un acces avec slug (seconde ligne) 
Dans l'action `users.get` tu auras donc un `ctx.params.slug`

**Comment by nikoPLP** [comment]
```
"GET users": "users.list",
"GET users/:slug": "users.get",
```
est un exemple de ton cas : un accès generique (premiere ligne), et un acces avec slug (seconde ligne) 
Dans l'action `users.get` tu auras donc un `ctx.params.slug`
