### ISSUE TITLE
Erreur aléatoire quand on POST des fichiers dans un container LDP

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#834]
Remonté par @tawytest

![unnamed](https://user-images.githubusercontent.com/17931931/128745891-37b01b68-dbf3-41a0-ba17-67bb90ca47b3.png)

L'erreur se produit ici:
https://github.com/assemblee-virtuelle/semapps/blob/master/src/middleware/packages/middlewares/index.js#L109

Une idée @simonLouvet ?

**Comment by srosset81** [comment]
Il semble que c'est lié à la librairie `dicer` utilisée par `busboy`. La librairie apparaît dans l'erreur.

https://github.com/mscdex/busboy/issues/250

Une PR a été proposée mais n'a pas été intégrée:

https://github.com/mscdex/dicer/pull/22

Malheureusement la librairie `busboy` n'est plus mise à jour depuis 2 ans :-( Mauvais choix de ce côté-là, on risque de n'avoir pas d'autre choix que de réécrire tout ce code avec une autre libriaire...

**Comment by simonLouvet** [comment]
Je vais refondre l'upload en changeant de librairie

**Comment by srosset81** [comment]
Pour info j'ai essayé de forcer l'usage de la PR en ajoutant cette ligne au package.json
```json
"dicer": "RolandHeinze/dicer#header-parser-bug",
```
Malheureusement cette technique ne marche pas. Le package est installé depuis Github mais busboy continue à utiliser la librairie publiée sur NPM (en la mettant dans son dossier propre node_modules). J'imagine qu'il doit y avoir une solution pour forcer l'usage d'un repo, mais je ne l'ai pas trouvée.

**Comment by srosset81** [comment]
> Je vais refondre l'upload en changeant de librairie

Dispo pour qu'on parle du choix de la librairie. J'avais regardé un peu et presque tout le monde semble utiliser busboy. :-/

**Comment by simonLouvet** [comment]
@srosset81 est ce que tu connais le pseudo de thomas? Archipelago n'utilise pas busboy par ce qu'il n'y a pas de multipart. de plus il est possible que #844 resolve le probleme car busboy pouvait ne pas apprécier que la request soit répondu au navigateur alors qu'il était en train d’écrire sur le disque.

**Comment by srosset81** [comment]
Thomas c'est @tawytest

Donc Archipelago utilise une autre méthode que Thomas pour uploader les fichiers ? Il suffirait au pire qu'il utilise la même méthode que nous pour que le problème se règle ? (si ton fix n'est pas suffisant)

**Comment by simonLouvet** [comment]
Oui a priori, s'il utilise la même manière d'upload (pas de multipart), ça contournera le problème. Je voudrais voir avec lui pour expliquer tout ça, essayer de conserver le multipart ; contourner au pire

**Comment by Spiff77** [comment]
Hello, @simonLouvet  C'est moi Thomas ;), l'autre pseudo n'est pas le bon, je viens juste de voir ce message la. Hésites pas a prendre contact sur ce compte la si besoin.

**Comment by simonLouvet** [comment]
salut @Spiff77 . Je ne sais pas ou prendre contact ailleurs que cette issue. Est ce que tu a un compte sur le chat de communs?
Concernant ce probleme d'upload, je suppose que tu passe par du multipart car busboy n'est utilisé que dans ce cas.
Il est probable qu'un fonctionnement inadéquat du container de fichier revoyait la requette http alors que l'upload n'etait pas terminé et que cela cause cette anomalie.
solution 1 : mettre à jour les dépendances @semapps essayer de reproduire l’anomalie
solution 2 : ne plus utiliser le multipart et poster en direct le fichier. voir les exemples.
- https://jsfiddle.net/zenate/ey8wu6zL/146/
- https://github.com/assemblee-virtuelle/semapps/blob/9a520c8544ac85b73ccb240fc084e856da962f65/src/frontend/packages/semantic-data-provider/src/dataProvider.js#L38

**Comment by Spiff77** [comment]
Hello,

Du coup nikel, ca fonctionne parfaitement:
`

    const file:any =  this.fileInput.nativeElement.files[0];
    const httpUploadOptions = {
      headers: new HttpHeaders({
        'Content-Type': file.type
      })
    }

    return this.dataService.postFile('files', file, httpUploadOptions)
`

Ne pas utiliser de FormData comme mentionné sur la plupart des exemples d'upload de fichier avec Angular.

Merci!
