### ISSUE TITLE
Permettre d'afficher les données méta de fichiers non-RDF

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#836]
Cela fait partie des spécifications Solid:
https://github.com/solid/solid-spec/blob/master/content-representation.md#metadata

**Comment by simonLouvet** [comment]
@srosset81 Est ce que tu sais sous quel forme doivent être retournées le metadata? Des triples (drf, ttl, json-ld) ou la structure initiale des metadata de fichier (que je ne connais pas)?

**Comment by srosset81** [comment]
Je pense que c'est libre, j'ai pas trouvé d'informations.
Pour l'instant on utilise une ontologie spécifique à SemApps, mais il faudrait voir si on peut pas utiliser l'ontologie DublinCore qui semble assez complète.

**Comment by srosset81** [comment]
Duplicate of https://github.com/assemblee-virtuelle/semapps/issues/1192
