### ISSUE TITLE
Finaliser les bases du serveur LDP

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#84]
Finaliser les bases du serveur LDP.
Avoir des conteners circonstanciés, à la racine.
S'assurer que les API répondent au besoin du front.

**Comment by simonLouvet** [comment]
J'ai commencé la spécification de LDP pour pouvoir se mettre d'accord.
https://hackmd.lescommuns.org/IwNgrAhgzCVQtADgGYFMAs90BN2PhGMgugOwQCcADKtsAEb0XBA=

**Comment by srosset81** [comment]
Merci pour le document.
Je ne trouve pas qu'un hackmd soit très adapté pour discuter puisqu'on ne peut pas mettre de commentaires, alors voici mes observations.

Je trouve tes différentes solutions plus rigides que nécessaires. Tu pars sur l'idée d'un URL unique (`/subject`) pour accéder à toutes les ressources alors que rien dans les spécifications LDP n'impose de faire ça, et que d'autres solutions plus souples sont facilement implémentables.
J'ai pour ma part [exprimé clairement mes besoins](https://github.com/assemblee-virtuelle/semapps/issues/83), si tu les as lu ? Cela concerne l'interaction entre le module LDP et le module ActivityPub, mais je suis sûr que dans le futur d'autres utilisateurs seront intéressés d'avoir des solutions souples.
Là aussi, à moins que je me trompe, il n'y a vraiment rien techniquement parlant qui empêche de faire les choses de cette manière. Cela m'intéresserait d'avoir ton retour là-dessus puisque je propose un cas d'usage concret.

Il me semble que tu restes globalement sur l'idée de containers automatiques, même si tu évoques une solution 3 avec des containers persistés :

> solution 3 (container persisté dans le triple store)
> En considerant le sujet demandé est un container, structurer la réponse sous la même forme que la solution 1
> GET /subject/{id}

Cependant pourquoi imposer le même URL `/subject` pour des containers ? Avec des containers persistés, il n'y a rien, vraiment rien, qui empêche aux différents services de créer leur propre path, type `/note`. En terme de requête SparQL, c'est super facile à aller rechercher.

Concernant la solution 4, je ne comprend pas ce que tu proposes. As-tu des exemples ?

Autre question, peux-tu clarifier le rapport avec OWL dans la partie "Read one" ?

> Doit fournir le sujet + les uri des sujets liés par Object Properties (OWL) + les containers correspondants Object Properties pour pouvoir les modifier

Je pense qu'il pourrait être pertinent de faire une visio pour parler de tout ça. Je suis disponible encore demain matin ou en début d'après-midi, après ça va être plus compliqué (potentiellement plus disponible avant le 1er janvier au soir).

**Comment by srosset81** [comment]
Ping @nikoPLP

**Comment by simonLouvet** [comment]
@srosset81 oui, je les ai lu mais je partais de la conception qui me paraissait la plus cohérente pour me permettre de vous l'exposer. Je suis ouvert à toutes critiques, évolution et aller vers les besoins tel que tu les a exprimé.
Ok pour changer de support et ne pas utiliser hackmd.
"OWL" c'est juste pour expliquer d'ou vient le terme Object Property
``/note`` sous entends que c'est un container ldp. Pourquois pas, cela remplacerai ``/container/note``
Je serai également en congé à partir du 24 midi jusqu'au 6 Janvier.
On peut se faire une visio demain (mardi) matin mais c'est un sujet complexe et je crains que nous n'ayons pas de conclusion définitive à l'issue de cette visio. Prenons le temps :-).
@nikoPLP, motivé pour demain matin?

**Comment by simonLouvet** [comment]
un subject en sémantique peut avoir plusieurs type. Comment gérer ce cas? le meme subject serait retourné par ``/ontology:class1`` et ``/ontology:class2``. Quel API utiliser en POST pour créer un objet dans ce cas la?

**Comment by simonLouvet** [comment]
deux ontologies peuvent contenir la même classe mais elle ne sont pas forcement équivalente. Il est donc nécessaire d'inclure l'ontologie dans l'url. ``/onotology1:note`` et ``/ontology2:note`` par exemple.

**Comment by simonLouvet** [comment]
spécification basique ici : https://github.com/assemblee-virtuelle/semapps/blob/master/docs/basicLDP.md

**Comment by simonLouvet** [comment]
Nous faisons le choix de ne pas implémenter les containers de properties (Direct Container & Indirect Container) pour le moment. Documentation ici : https://github.com/assemblee-virtuelle/semapps/blob/master/docs/PropertiesContainer.md

**Comment by simonLouvet** [comment]
en cours : https://github.com/assemblee-virtuelle/semapps/tree/_%2384

**Comment by srosset81** [comment]
@simonLouvet Je trouve quand même qu'un URL comme https://monserveur.com/pair:Event/ ça fait pas très "régulier". On pourrait pas plutôt utiliser https://monserveur.com/pair/Event ? De cette manière on aurait deux path distincts:
```
GET /:ontology/:class
GET /:alias
```
Par ailleurs on pourrait passer le mapping des ontologie comme paramètre du service LDP ?
```
ontologies: {
  pair: "http://virtual-assembly.org/ontologies/pair",
  as: "https://www.w3.org/ns/activitystreams"
}
```

**Comment by simonLouvet** [comment]
On est d'accord pour les alias comme spécifié dans la doc. J'ai pas creuser/spécifié complètement les alias et j'ai des propositions alternatives dans la tête. Pour le moment, je me concentre sur la syntaxe par défaut

**Comment by simonLouvet** [comment]
Je réfléchi à ta proposition de séparer ontologie et classe dans l'url. Idée intéressante à première vue mais plutôt en évolution.
