### ISSUE TITLE
Utiliser une ressource semapps:Account pour OIDC/CAS

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#841]
Enregistrer l'email et d'autres informations dans une ressource semapps:Account, lisible uniquement par l'utilisateur.

Voir le service `auth.account` qui a été ajouté pour la connexion locale.

Idéalement il faudrait que ce soit optionel, ou sinon il faut bien indiquer le breaking change et peut-être proposer un petit outil de migration.

**Comment by srosset81** [comment]
Il faudrait aussi ajouter une notion de status sur l'Account.
Par exemple "Invited", "EmailValidated", etc.

**Comment by fluidlog** [comment]
Cette issue doit-elle être fermée ?

**Comment by srosset81** [comment]
Oui c'est fait par https://github.com/assemblee-virtuelle/semapps/pull/873
