### ISSUE TITLE
Utiliser les named routes de moleculer-web

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#852]
Voir la release: https://github.com/moleculerjs/moleculer-web/releases/tag/v0.10.2

Il faut mettre à jour moleculer-web partout puis ajouter un nom UNIQUE pour tous les appels `api.addRoute` de tous les services.

Cela évitera que des routes soient écrasées par d'autres.

**Comment by BastienSig** [comment]
J'avoue ne pas avoir tout compris les enjeux de cette issue. Pour la mise à jour en 0.10.2 c'est bon, est ce que le 
moleculmar-web package de @semapps/auth doit être maj ? 
Et pour la mise en place des nom uniques, on parle bien du fichier : api.service.json ?

**Comment by srosset81** [comment]
Il faut mettre à jour moleculer-web sur tous les packages @semapps. Cela doit toujours être le même numéro de version.

Il faut rechercher tous les appels à l'action `api.addRoute`. C'est le service "api" qui gère les routes, mais les routes sont ajoutées par les différents services, selon leurs besoins.

**Comment by fluidlog** [comment]
@BastienSig Peux-tu nous dire où tu en es sur cette issue, peut-être que je peux t'aider ?
