### ISSUE TITLE
la base de données TDB2 peut devenir très volumineuse après de nombreux INSERTs

### ISSUE THREAD

**Issue by nikoPLP** [assemblee-virtuelle/semapps#854]
le backend des Chemins de la transition s'est retrouvé avec des [fichiers TDB2 de jena de plusieurs GB](https://github.com/chemins-de-la-transition/semapps/issues/110).

Jena a besoin qu'on lui dise de compacter les données de temps en temps.

La solution temporaire indiquée dans l'issue précédente doit etre transformée en une solution permanente.
Surement un cron qui va faire tourner un script pour le compactage, de maniere periodique.

Le probleme est que ce script doit tourner a l'interieur du docker ou tourne Jena.
et que Jena, contrairement a [ce qui est ecrit dans la doc "Compaction can be done on a live database"](https://jena.apache.org/documentation/tdb2/tdb2_admin.html), n'aime pas faire le `compact` lorsque le serveur tourne.
Il faut donc arreter le docker jena, puis le relancer avec  une option qui lui dira de faire le compact, puis arreter ce docker et relancer le docker en mode normal.

Il ya a aussi la possibilé de lancer le compact par [l'interface web d'admin de fuseki](https://jena.apache.org/documentation/fuseki2/fuseki-server-protocol.html#compact), mais Seb disait que ca ne fonctionnait pas, peut etre pour la meme raison (jena doit etre arreté)

**Comment by srosset81** [comment]
En terme de maintenance c'est assez lourd si on doit arrêter Jena Fuseki.
Mais j'imagine qu'il y a pas besoin de le faire chaque jour, l'idéal serait un cron lancé p.ex. une fois par semaine, la nuit.
