### ISSUE TITLE
Erreur à la creation de l'Image Docker Frontend 

### ISSUE THREAD

**Issue by ypilpre** [assemblee-virtuelle/semapps#884]
**Décrivez le bug**
Le Build du frontend echoue sur la branch Master avec une erreur de dépendance sur le package npm 'rollup-plugin-import-css'

**Etapes pour reproduire**
1. Faire un docker build . dans le dossier src/frontend à partir du Dockerfile.prod

**Comportement attendu**

Création d'un image docker du Frontend (sans erreur)

**Sortie du Log Docker**

```
> lerna run pre-publish && git add -A && git commit -m 'Build packages for distribution'

lerna notice cli v3.22.1
lerna info Executing command in 8 packages: "npm run pre-publish"
lerna ERR! npm run pre-publish exited 1 in '@semapps/date-components'
lerna ERR! npm run pre-publish stdout:

> @semapps/date-components@0.3.10 pre-publish /app/packages/date-components
> rollup --sourcemap --config


lerna ERR! npm run pre-publish stderr:
[!] Error: Cannot find module 'rollup-plugin-import-css'
Require stack:
- /app/packages/date-components/rollup.config.js
- /app/node_modules/rollup/dist/shared/loadConfigFile.js
- /app/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-plugin-import-css'
Require stack:
- /app/packages/date-components/rollup.config.js
- /app/node_modules/rollup/dist/shared/loadConfigFile.js
- /app/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/packages/date-components/rollup.config.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.require.extensions.<computed> [as .js] (/app/node_modules/rollup/dist/shared/loadConfigFile.js:513:20)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @semapps/date-components@0.3.10 pre-publish: `rollup --sourcemap --config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @semapps/date-components@0.3.10 pre-publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-15T10_58_21_520Z-debug.log

lerna ERR! npm run pre-publish exited 1 in '@semapps/date-components'
lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semapps-frontend@ build: `lerna run pre-publish && git add -A && git commit -m 'Build packages for distribution'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semapps-frontend@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-15T10_58_21_572Z-debug.log
```
**Système**
Docker version 20.10.7
Ubuntu 20.04

**Comment by ypilpre** [comment]
L'ajout de la ligne 
` "rollup-plugin-import-css": "^3.0.2"` 
dans le fichier package.json corrige le bug, mais le build ne fonctionne pas .

> @semapps/auth-provider@0.3.10 pre-publish /app/packages/auth-provider
> rollup --sourcemap --config

```
lerna success run Ran npm script 'pre-publish' in 8 packages in 14.8s:
lerna success - @semapps/activitypub-components
lerna success - @semapps/archipelago-layout
lerna success - @semapps/auth-provider
lerna success - @semapps/date-components
lerna success - @semapps/geo-components
lerna success - @semapps/markdown-components
lerna success - @semapps/react-admin
lerna success - @semapps/semantic-data-provider
fatal: not a git repository (or any of the parent directories): .git
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! semapps-frontend@ build: `lerna run pre-publish && git add -A && git commit -m 'Build packages for distribution'`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the semapps-frontend@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-16T08_39_36_784Z-debug.log
```

**Comment by fluidlog** [comment]
Bonjour, on peut prendre le temps de regarder ça ensemble si tu veux.
Je te propose de nous rejoindre sur https://chat.lescommuns.org/channel/semapps_dev :)
Merci,

**Comment by fluidlog** [comment]
Suite à l'investigation voici une explication de la différence de lancement entre @ypilpre et nous : 
De son côté, pour builder le frontend, il a renommé dans le répertoire src/frontend, le fichier Dockerfile.prod en Dockerfile, puis lancé la commande ```docker build .```, ce qui lance le script Dockerfile renommé, dans lequel il y a une variable $FRONTEND.

De notre côté, nous avons l'habitude d'utiliser docker-compose, qui lance une commande (voir le fichier docker-compose.yaml à la racine du projet Semapps) : 
```command: bash -c "npm rebuild && npm install && npm run bootstrap && npm start --prefix ./boilerplates/${FRONTEND}" ```.

Dans le cas du docker-compose, cela fait appel au fichier .env présent à la racine, dans lequel FRONTEND=archipelago.
Or, je pense que dans le cas du lancement qu'utilise @ypilpre , la variable FRONTEND est vide, ce qui créer une erreur (même si je ne la comprends pas).

Conclusion : solution de contournement : modifier le script Dockerfile avec : 
```COPY ./boilerplates/archipelago /app/```, pour ne pas utiliser la variable FRONTEND, et ça build.

@simonLouvet ou @srosset81 , je vous laisse corriger le script si vous le souhaitez, ou documenter...

**Comment by ypilpre** [comment]
Ok le build est correct (Je ferai une autre issue si l'appli a des comportements anormaux)

**Comment by simonLouvet** [comment]
@fluidlog pas si simple, il y a une bonne raison à ce ```${FRONTEND}``` : c'est pour choisir le boilerplate. ne plus l'utiliser ca veut dire maintenir seulement ce boilerplate (archipelago) je pense. @srosset81 ton point de vue?

**Comment by srosset81** [comment]
Merci pour les investigations @fluidlog 

En faisant un `docker build .`, tu peux quand même passer des variables d'environnement. Donc pas besoin de modifier le Dockerfile a priori, si les bons arguments sont passés.

https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

On pourrait aussi mettre "archipelago" comme valeur par défaut de la variable FRONTEND, ce qui éviterait ce type d'erreur tout en restant flexible:

https://docs.docker.com/engine/reference/builder/#default-values

```
ARG FRONTEND=archipelago
```

**Comment by simonLouvet** [comment]
> Merci pour les investigations @fluidlog
> 
> En faisant un `docker build .`, tu peux quand même passer des variables d'environnement. Donc pas besoin de modifier le Dockerfile a priori, si les bons arguments sont passés.
> 
> https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg
> 
> On pourrait aussi mettre "archipelago" comme valeur par défaut de la variable FRONTEND, ce qui éviterait ce type d'erreur tout en restant flexible:
> 
> https://docs.docker.com/engine/reference/builder/#default-values
> 
> ```
> ARG FRONTEND=archipelago
> ```

je suis pour la variable par défaut
