### ISSUE TITLE
Implémenter la condition where de SPARQL.js comme filtre

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#892]
**Problématique**
support du filtre react-admin classique
-> utilisation pour sparnatural
-> utilisation pour les filtre avancés

**Composants concernés**
Data Adapter

**Proposition**
supporter
```
filter=
{
   sparqlWhere : {
   }
}
```

**Comment by srosset81** [comment]
sparqlWhere plutôt que sparql_where

En principe, la ressource "racine" est identifiée avec la variable `?s1`. Il faudra garder cette convention (ou la faire évoluer) pour que la requête additionnelle fonctionne.

Cette issue implique de refactorer les fonctions buildSparqlQuery et buildDereferenceQuery (sur la branche next), afin d'utiliser SPARQL.js pour la construction de la requête SPARQL.
