### ISSUE TITLE
Ne pas automatiquement créer des datasets sécurisés

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#895]
Par défaut quand on utilise l'image Docker [semapps/jena-fuseki-webacl](https://hub.docker.com/repository/docker/semapps/jena-fuseki-webacl), cela crée deux datasets localData et testData qui sont sécurisés. Cela peut poser un problème car l'utilisateur peut vouloir utiliser cette image pour des datasets non-sécurisés, par exemple pour avoir la fonctionnalité compact (c'est sans doute le problème qu'a eu @simonLouvet)

@nikoPLP N'y aurait-il pas moyen de ne pas créer de datasets par défaut, ou alors donner le choix de créer des datasets sécurisés ou pas ?

**Comment by nikoPLP** [comment]
on pourrait peutre implementer ca... mais je ne comprend pas trop le besoin...
le docker s'appele jena-fuseki-webacl donc est un peu normal qu'il y ait les webacl dedans, non?
on pourrait a la rigueur ne pas cree rde dataset, et utiliser le middleware fuseki-admin pour creer le dataset localData, et lire la config de semapps pour savoir si le middleware webacl est chargé ?

**Comment by srosset81** [comment]
Le problème c'est qu'on a commencé à mettre des choses, en l'occurence le compactage, qui peuvent intéresser des personnes qui n'ont pas besoin des webacl. Donc soit on part de l'idée que cette image peut être utilisée avec ou sans datasets sécurisés (en l'occurence avec les activitypods, je crée un dataset non-sécurisé avec les comptes utilisateurs), soit on crée des images différentes ?

**Comment by srosset81** [comment]
Voilà déjà une solution intermédiaire:
https://github.com/assemblee-virtuelle/semapps/pull/897

**Comment by nikoPLP** [comment]
historiquement, il n'y avait pas de service fuseki-admin, et pas moyen de creer des dataset depuis le middleware. C'est pour cette raison que le docker jena-fuseki-webacl avait dans sa config, la creation de deux dataset dès le début, par defaut, avant meme que le middleware ne tourne au moins une fois.

Vu que le code du middleware a change depuis et qu'il y a un appel a fuseki-admin.createDataset au lancement, pour verifier si le CONFIG.MAIN_DATASET est bien présent (ceci est fait par le boilerplate...mais je viens de voir que tu veux les virer... donc ce code ne sera plus appeler ??), on pourrait enlever le localData qui se trouve dans le docker jena-fuseki-webacl.

A noter que le compact du docker officiel de fuseki devrait marcher sans problem sur un dataset qui n'est pas securisé ! on n'a pas essayé, mais je pense que ca marche. car le probleme qu on a eu avec le compact, vient surement du fait de la complexité de l árchitecture avec les webACL.

Si les integrateurs/sysadmins de semapps ne veulent pas des webacl, ils peuvent utiliser le docker officiel de fuseki.

je pourrais a la rigeur ajouter une securité dans le middleware des webacl, qui verifie la presence d'un graph securisé au lancement. aisni le cas de figure que tu decris dans la doc, d un service webacl qui est lancé, avec un fuseki sans webacl, qui "semble marcher" serait evité.

**Comment by srosset81** [comment]
Ah je pensais qu'on avait essayé un compact avec l'image Docker "officielle" de Fuseki. Si ça marche, effectivement il n'y a pas lieu de s'embêter.

> je pourrais a la rigeur ajouter une securité dans le middleware des webacl, qui verifie la presence d'un graph securisé au lancement. aisni le cas de figure que tu decris dans la doc, d un service webacl qui est lancé, avec un fuseki sans webacl, qui "semble marcher" serait evité.

S'il y a moyen de réduire les sources d'erreurs ce serait cool :)

**Comment by nikoPLP** [comment]
Tout est basé sur l'image officielle de fuseki, mais dan le docker-compose, si tu mets l'image officielle au lieu de la notre avec les webacl, alors il me semble qu'un dataset localData est deja présent et il ne contient pas de webacl, evidemment. (Mais en fait, je ne suis plu ssur de ça. est ce que la docker officiel crée un dataset par defaut? je ne sais plus)
En tout cas, en utilisant le docker officiel, et en lancant le middleware la premiere fois avec un appel a createDataset avec secure: false, alors tout est bon.

**Comment by simonLouvet** [comment]
Il n'y a pas de compact dans l'image docker stain/jena-fuseki qu'on utilisait précédemment. C'est pour cela que je veux utiliser  la nouvelle image que @nikoPLP  as réalisé pour 5 projet déjà déployés s qui sont en dataset non sécurisés. L'image stain/jena-fuseki  ne crée pas de datasets. Le service fuseki-admin a presque toujours existé mais il a été amélioré pour pouvoir générer de datasets sécurisés. Je continue de défendre ma position que le container fuseki idéal doit d'adapter aux besoins des projets et de pas créer de dataset pour laisser le middleware choisir ce dont il a besoin.

**Comment by simonLouvet** [comment]
> Ah je pensais qu'on avait essayé un compact avec l'image Docker "officielle" de Fuseki. Si ça marche, effectivement il n'y a pas lieu de s'embêter.
> 
> > je pourrais a la rigeur ajouter une securité dans le middleware des webacl, qui verifie la presence d'un graph securisé au lancement. aisni le cas de figure que tu decris dans la doc, d un service webacl qui est lancé, avec un fuseki sans webacl, qui "semble marcher" serait evité.
> 
> S'il y a moyen de réduire les sources d'erreurs ce serait cool :)

L'image stain/jena-fuseki ne contient pas de compact. C'est pour cela que j'ai été vers l'image semmaps qu'a créé @nikoPLP

**Comment by nikoPLP** [comment]
> L'image stain/jena-fuseki ne contient pas de compact. C'est pour cela que j'ai été vers l'image semmaps qu'a créé @nikoPLP

Oui c'est logique. C'est les fichiers binaires java qui n'ont pas le code necessaire. le compact est dansun autre package (jena, pas fuseki).

Donc je comprends que tu veuille utiliser l'image jena-fuseki-webacl.

Cela dit, dans cette image, si tu n'as pas de webacl (datset créé avec secure=false) tu dois pouvoir faire des comapct a chaud ! soit par l'interface web d'admin de fuseki, soit en lancant la commande `tdb2.tdbcompact` dans le shell du container docker, sans avoir besoin du mechanisme que j'ai créé l'autre jour. Car je pense que le comapct a chaud marche pour les dataset non sécurisés. tu peux essayer, tu me diras si ca marche
