### ISSUE TITLE
Enlever les boilerplates de ce repo

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#896]
Suite à la [discussion d'hier](https://forums.assemblee-virtuelle.org/t/compte-rendu-de-la-reunion-semapps-du-7-decembre/371), voilà ce que je vois comme actions à entreprendre:

- [x] Créer un repo assemblee-virtuelle/archipelago
- [x] Y déplacer les boilerplates frontend/archipelago et middleware/pair-ldp-server
- [x] Déplacer aussi la config Docker et la supprimer de ce repo
- [x] Supprimer les autres boilerplates qui ne sont plus mis à jour depuis plus d'une année
- [x] Supprimer le dossier deploy, qui n'est plus utilisé
- [x] Sur le site web, utiliser comme sous-titre "A toolbox for web semantic applications" plutôt que "Fostering interconnections between communities by creating synergies between their platforms" (ce sous-titre est plus adapté pour Archipelago)
- [x] Ajouter des liens vers les produits Archipelago et ActivityPods sur le repo
- [x] Déplacer les issues liées à archipelago vers le nouveau repo (il y a une fonctionnalité Github pour ça)
- [x] revoir la doc, notamment les [guides](https://github.com/assemblee-virtuelle/semapps/tree/master/website/docs/guides) et le README du [middleware](https://github.com/assemblee-virtuelle/semapps/blob/master/src/middleware/README.md)

**:warning: Mener ces actions depuis la branche next, pour éviter de futurs conflits.**

**Comment by nikoPLP** [comment]
"Déplacer aussi la config Docker et la supprimer de ce repo" ca veut dire quoi? quelle config Docker? il faut quand meme laisser mon travail sur les webacl, non?

**Comment by srosset81** [comment]
Oui on laissera le Dockerfile de fuseki.
Par contre on déplacerait ceux pour le frontend et le middleware, ainsi que les fichiers docker-compose.yml

**Comment by nikoPLP** [comment]
alors il faut laisser tout le dossier `fuseki-docker` car le Dockerfile se sert de tous ces fichiers.

**Comment by nikoPLP** [comment]
Sans les boilerplates, il ne sera plus possible de lancer facilement semapps, en clonant juste ce repo et lancant quelques commandes. Les nouveaux arrivants vont etre un peu deconcertés, non ?

**Comment by nikoPLP** [comment]
on integre ca a la milestone 0.4 ?

**Comment by srosset81** [comment]
Les nouveaux arrivants sont de toute façon déjà perdus ;-) A mon avis, on peut pas faire pire que maintenant...
Avec un repo dédiée à Archipelago, on pourra aussi lancer la stack en quelques lignes de commandes, sauf qu'on prendra les packages sur NPM.
Yep ça me semble être un bonne idée d'intégrer ça à la v0.4

**Comment by nikoPLP** [comment]
j ái rajoute une tache a propos de la doc, qui doit etre revue.

**Comment by nikoPLP** [comment]
je pense que ca serait quand meme bien d'avoir des images docker pretes a etre installées, ainsiq u'un guide pour lancer le middleware et le front depuis un environement de dev, juste pour pouvoir tester.
peut importe le nom ou le fait que ce soit tres customisé pour un client.
il faut que les devs et les sysadmins qui arrivent sur le site/github, puissent en quelques clicks, faire tourner le truc. et apres, bien evidemment, ils vont cusotmiser, configurer, creer des images docker pour leur propores besoins...

**Comment by fluidlog** [comment]
Quid du boilerplate pair-ldp-server, avez-vous tranché ?
Personnellement, j'attendrais bien un peu avant de rechanger des choses, histoire qu'on stabilise déjà les changements de la partie frontend, et qu'on en rediscute tous ensemble.

**Comment by srosset81** [comment]
Le boilerplate pair-ldp-server est déjà transféré sur archipelago (c'est le middleware).
Cette issue est terminée.

**Comment by fluidlog** [comment]
Ah, je comprends mieux, je regardais sur la mauvaise branche et je le voyais encore, du coup je pensais qu'il restait des choses à faire sur le middleware suite à vos échanges de décembre... OK
