### ISSUE TITLE
[Branche next] Erreur lors de la saisie d'une adresse (auto-complétion)

### ISSUE THREAD

**Issue by VincentFarcy** [assemblee-virtuelle/semapps#900]
**Décrivez le bug**
branche next : Lors de la saisie d'une adresse, une erreur apparaît dès le 1er caractère saisi.

**Etapes pour reproduire**
Branche next
Créer une nouvelle organisation
enregistrer
Saisir une adresse : 
```
TypeError: Cannot read property 'filter' of undefined
useAutocomplete
node_modules/@material-ui/lab/esm/useAutocomplete/useAutocomplete.js:225
  222 | 
  223 | var inputValueIsSelectedValue = !multiple && value != null && inputValue === getOptionLabel(value);
  224 | var popupOpen = open;
> 225 | var filteredOptions = popupOpen ? filterOptions(options.filter(function (option) {
      | ^  226 |   if (filterSelectedOptions && (multiple ? value : [value]).some(function (value2) {
  227 |     return value2 !== null && getOptionSelected(option, value2);
  228 |   })) {
```

**Captures d'écran**
![image](https://user-images.githubusercontent.com/55813208/145376340-d77e80e8-cad8-491b-9d03-d6c65ce8cc29.png)

**Système**
Google Chrome Version 91.0.4472.114 (Build officiel) (64 bits)

**Comment by VincentFarcy** [comment]
le problème était dû à l'absence de token mapbox en yarn link sur la branche next

**Comment by srosset81** [comment]
Faudrait peut-être un meilleur message d'erreur dans ces cas...
