### ISSUE TITLE
Pass multiple users to `webacl.resource.addRights`

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#908]
Currently, to give several users rights to the same resource, we have to call the `webacl.resource.addRights` action once per user.

This is costly in terms of performance, as the addRights action performs a lot of checks (locally, it takes almost 1 second per user).

My suggestion would be to allow multiple users to be passed in this way:

```js
await ctx.call('webacl.resource.addRights', {
  resourceUri,
  additionalRights: {
    user: {
      uri: [user1, user2],
      read: true
    }
  },
  webId: 'system'
});
```

If I'm not mistaken, all we need to do is change these lines:
https://github.com/assemblee-virtuelle/semapps/blob/master/src/middleware/packages/webacl/utils.js#L257-L262

**Comment by Laurin-W** [comment]
I suppose this has changed to those lines:

https://github.com/assemblee-virtuelle/semapps/blob/19eb214e9d5cd6593e5a2e7fe7e2fbb7b863bbd4/src/middleware/packages/webacl/utils.js#L277C2-L282C4

Will create a PR :)
