### ISSUE TITLE
Industrialisation du déploiement : DevOps

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#913]
**Description**
DevOps: industrialiser le déploiement des instances et créer une _ferme_ à SemApps.

Au stade d'idée pour le moment, à discuter, brainstormer, spécifier : 
1/ Une ferme à SemApps qui permette de déployer des instances en fonction d'un template (organigraphe, archipelago, activity pods).
Avec la possibilité de choisir son URL.

2/ Une ferme à SemApps V2 qui permette de déployer une instance en fonction d'une ontologie et de choisir les attributs et liens qu'on souhaite cartographier ? Et la manière de visualiser les data ? (SemViz? ) 

**Prérequis avant chiffrage**
- [ ]   

**Issues liées**
- [ ] https://github.com/assemblee-virtuelle/archipelago/issues/23

**Estimation du temps de travail en JH**
- @srosset81:
- @simonLouvet:

**Comment by srosset81** [comment]
Intéressant de penser tout de suite à un choix entre différents produits, ça va nous aider à organiser les repo correctement.

Je serai pour supprimer la v2 de ce chantier. On est des années-lumières de ça. Autant se concentrer sur ce qui est envisageable à moyen terme.

**Comment by srosset81** [comment]
La notion de "ferme à SemApps" n'a plus de sens. A voir si on veut faire ça pour Archipelago, mais l'architecture en pods pourrait le rendre obsolète.
