### ISSUE TITLE
Gérer la connexion CAS

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#92]
Le SSO de Colibris est de type CAS. 
https://monprofil.colibris-lemouvement.org/

Voir quel librairie est la plus adaptée :
https://github.com/AceMetrix/connect-cas
https://github.com/TencentWSRD/connect-cas2
https://github.com/jmarca/cas_validate
https://github.com/kylepixel/cas-authentication
https://github.com/kcbanner/node-cas

Adapter la connexion OIDC afin de permettre plusieurs types de connexions.

**Comment by srosset81** [comment]
Il y a aussi une librairie pour PassportJS.
https://github.com/appdevdesigns/passport-cas

@simonLouvet est-ce que tu comptes utiliser PassportJS pour la connexion OIDC ? J'ai vu qu'il y a une librairie pour ça aussi http://www.passportjs.org/docs/openid/. Cela permettrait d'utiliser une seule interface pour tous les types de connexions, ce qui aiderait sans doute pour la modularité.

**Comment by simonLouvet** [comment]
@srosset81 pour OIDC je compte bien utiliser passeport comme ce boilerplate qui doit être opérationnel : https://github.com/simonLouvet/OIDC-LesCommuns
