### ISSUE TITLE
Semapps > v0.3.17:  Dereference vide sur les fetchAll.

### ISSUE THREAD

**Issue by Spiff77** [assemblee-virtuelle/semapps#921]
Lors de la migration de semapps. Les dereferences ne fonctionnent plus:

Call sur middleware `localhost:3000/organizations`
 `0.3.17:`
<img width="651" alt="Capture d’écran 2021-12-30 à 17 28 37" src="https://user-images.githubusercontent.com/600608/147770199-9e5813c2-ebd6-4cbd-ad71-702fa8e53519.png">

`0.3.18`ou `0.4.0-alpha.6`:
<img width="880" alt="Capture d’écran 2021-12-30 à 17 32 32" src="https://user-images.githubusercontent.com/600608/147770480-5b18d94d-bc4f-4cc0-9e0d-d749c388be00.png">

Par contre des que je requête un seul item ça fonctionne!  
`http://localhost:3000/organizations/61658b26acf8a44a60fe1a31`
<img width="687" alt="Capture d’écran 2021-12-30 à 17 34 21" src="https://user-images.githubusercontent.com/600608/147770666-9ef3d012-d374-4135-9215-52864dbc58e3.png">

**Comment by simonLouvet** [comment]
same as #933
