### ISSUE TITLE
Avoir accès simplement aux versions d'un serveur SemApps

### ISSUE THREAD

**Issue by fluidlog** [assemblee-virtuelle/semapps#927]
**Tension**
Difficulté de savoir si un serveur SemApps est en dernière version.

**Proposition**
Il faudrait pouvoir afficher quelque part, soit sur l'interface (en bas comme dans d'autres logiciels) ou à un endpoint spéficique les versions du middleware utilisé, et du front.

**Alternatives**
Seb propose de nous inspirer de cette autre issue assez proche : https://github.com/assemblee-virtuelle/semapps/issues/914

**Comment by srosset81** [comment]
https://github.com/assemblee-virtuelle/semapps/issues/914 n'est pas une question d'inspiration mais de nécessité. Pas moyen de connaître la version du middleware sans ça.

Attention, avec la v0.4, il peut y avoir plusieurs middleware. Donc pas évident à afficher clairement.

Pour afficher la version du frontend, pourquoi pas, je ne sais pas trop comment il faudrait s'y prendre, sachant que c'est la version des packages SemApps qu'il faut prendre en compte.
