### ISSUE TITLE
harmoniser et centraliser les procedures de migrations de donné

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#928]
**Tension**
Lors d'un changement de version, d'un changement de gestion des utilisateurs, d'un changement de gestion des droits ou d'autres opération de ce type, des opérations sont nécessaires sur les données existantes. Ces opérations sont dispersé et leur usage est assez peu documenté.
https://github.com/assemblee-virtuelle/archipelago/blob/master/middleware/services/migration.service.js
https://github.com/assemblee-virtuelle/semapps/blob/next/src/middleware/packages/auth/services/migration.js

**Proposition**
Centraliser et documenter l'usage de ces procédures.

**Comment by srosset81** [comment]
Off topic for SemApps but it was implemented in Archipelago https://github.com/assemblee-virtuelle/archipelago/blob/master/middleware/dbMigrate.js
