### ISSUE TITLE
Extraire le package @semapps/archipelago-layout

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#937]
Comme vu à la réunion aujourd'hui, le nom de ce package apporte de la confusion par rapport au projet Archipelago.

## Analyse du package 

Des composants (principalement dans le dossier /layout) qui sont vraiment spécifiques au design d'Archipelago et qui ne peuvent plus être utilisés dès qu'on s'éloigne de ce design:
- Layout
- AppBar
- TopToolbar
- TreeMenu
- SearchForm
- theme
- Hero
- ...

> Il y a un DefaultLayout et un SimpleLayout, le deuxième étant l'ancien design gardé pour éviter les breaking changes.

Des composants deprecated:
- Column (remplacé par Grid)
- ColumShowLayout
- MarkdownField (maintenant dans package @semapps/markdown-components)
- UserIcon (remplacé par AvatarField)

Certains composants sont des modifications très mineures des composants de React-Admin. Je pense qu'on pourrait éventuellement utiliser les composants de React-Admin directement:
- Create et CreateActions
- Edit et EditActions
- List et ListActions
- Show et ShowActions

Beaucoup de composants pour faire des listes, des fields ou des inputs (voir plus bas)

Des composants hors catégorie:
- ReferenceFilter (utile)
- TabsMenu (utilisé seulement par OrganiGraph pour le menu)
- InverseReferenceShowLayout (utilisé seulement par Colibris Pays Creillois pour le filtrage par type de resource)
- RedirectByType (utile)

## Usage actuel en dehors d'Archipelago

CDLT utilise seulement _(sauf pour le backoffice, qui est un fork de Archipelago)_
- MainList
- SeparatedListField
- ReferenceFilter 
 
OrganiGraph utilise seulement:
- GridList
- AvatarField

ActivityPods utilise seulement:
- GridList
- AvatarField

> Note: Je ne compte pas Colibris Pays Creillois et classe-dehors.org car ce sont des forks d'Archipelago. Ils importent la plupart des composants du package (sauf le Layout, qui est custom).

@simonLouvet D'autres usages pour des projets qui ne sont pas des forks d'Archipelago ? Prats p.ex. ?

## Proposition

- Créer un nouveau package @semapps/list-components avec:
  - MasonryList
  - MultiViewsList
  - GridList

- Créer un nouveau package @semapps/field-components avec:
  - AvatarField
  - SeparatedListField
  - MultiUrlField (utilisé par OrganiGraph, pas encore mis en commun)

- Créer un nouveau package @semapps/input-components avec:
  - ~~ReferenceQuickCreateInput~~
  - MultiLinesInput (utilisé par OrganiGraph, pas encore mis en commun)
  
- Bouger les fields et inputs du package @semapps/semantic-data-provider vers ces deux derniers packages.

- Supprimer:
  - les composants deprecated depuis de longs mois
  - Create / Edit / Show / List (si c'est facile d'utiliser directement les composants React-Admin)
  - Le SimpleLayout historique

- Créer un nouveau package @archipelago/layout avec tous les composants qui concernent vraiment l'affichage. Mettre ce package dans le repo d'Archipelago afin que cela ne pollue pas SemApps.

## Alternative

Ne pas créer de package @archipelago/layout et juste inclure les composants spécifiques à Archipelago dans le code source d'Archipelago. Cela pourrait simplifier, mais par contre ça rendra plus compliqué le fait de garder les forks synchronisés (cela dit, ce n'est pas vraiment notre problème non plus...)

**Comment by srosset81** [comment]
Après réflexion, je ne pense plus que ce soit une bonne idée de publier un package `@archipelago/layout`
Ca va être beaucoup de maintenance en plus (versioning, publication, synchronisation avec lerna...) sans beaucoup d'avantages, puisque les forks devront de toute façon se synchroniser avec le reste du code. En plus il faudrait écrire une documentation, ce qui impliquerait de faire un site web ou de trouver d'autres moyens de publier la documentation. A mon avis, on sort du périmètre du projet Archipelago, qui est de proposer un produit, pas une boîte à outil.

**Comment by simonLouvet** [comment]
totalement d'accord, un renommage du package existant style @semapps/common-layout me parait plus cohérente

**Comment by srosset81** [comment]
> totalement d'accord, un renommage du package existant style @semapps/common-layout me parait plus cohérente

Hmm ce n'est pas vraiment la proposition ci-dessus. Le package existant serait éclaté sur plusieurs packages (list-components, input-components, field-components...), et ce qui est spécifique au layout Archipelago ne sera plus dans un package, mais simplement dans le repo d'Archipelago.

La notion de "Common Layout" n'a pas de sens. Il n'y a pas de layout commun. Il y a un layout Archipelago, et après il y a pleins de sites qui utilisent leur propre layout (Colibris, Classe-dehors, ActivityPods...)

**Comment by simonLouvet** [comment]
Ça me va très bien

**Comment by srosset81** [comment]
Je vais commencer à créer les packages `@semapps/list-components`, `@semapps/field-components` et `@semapps/input-components` et y mettre les composants que j'ai développé pour #955
