### ISSUE TITLE
Renommer le service "fuseki-admin" en "dataset"

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#949]
Le service fuseki-admin ne gère en fait que les dataset: création, backup, list... 

Ce serait plus clair s'il était renommé en "dataset". On pourrait profiter du passage à la v0.4 pour le faire.

Si un jour on n'utilise plus fuseki, ou si on propose d'autre datastores, il suffirait de faire un autre service avec les mêmes fonctionnalités (comme on devrait le faire de toute façon pour le service triplestore)

**Comment by simonLouvet** [comment]
pas d'objection. J'avais baptisé "admin" par ce que d'autre opération d'admin pourrait être assumé par ce service

**Comment by srosset81** [comment]
@simonLouvet J'ai fait une PR sur #1036 mais je me demande quand même si ça serait pas logique que ce service soit un sous-service du TripleStoreService. Car après tout, la gestion de dataset concerne à 100% le triple store.

**Comment by srosset81** [comment]
Pour finir j'ai donc mis le service dans le package `triplestore` et il est initié automatiquement par le service `triplestore`.

Ce qui m'a décidé c'est le fait qu'on doive passer exactement les même settings aux deux services.
