### ISSUE TITLE
Imposible de se connecter avec le user simon.louvet.zen sur archipelago

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#954]
**Décrivez le bug**
sur https://archipel.assemblee-virtuelle.org/
"se connecter"
Le retour su sso ne redirige pas vers le front.
suspition de bug au retour du SSO

**Etapes pour reproduire**
1. navigation privée
2. "se connecter"
3. retour sur le choix de la méthode de login mais resté bloqué
4. pas de token dans le localstorage

**Comment by mguihal** [comment]
Est-ce que ce ticket correspond au problème corrigé ici : https://github.com/assemblee-virtuelle/semapps/pull/1106 ?
