### ISSUE TITLE
L'ontologie FOAF ne marche pas

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#97]
Si je poste sur http://localhost:3000/ldp/foaf:Person le JSON ci-dessous ça n'enregistre rien:

```json
{
  "@context": "http://xmlns.com/foaf/0.1/",
  "type": "Person",
  "name": "Sébastien ROSSET",
  "givenName": "Sébastien",
  "familyName": "ROSSET",
  "mbox": "mailto:srosset81@gmail.com"
}
```

L'erreur suivante apparait dans les logs:

`Request error! jsonld.InvalidUrl : Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.`

Apparemment c'est jsonld.toRDF (dans l'action triplestore.insert) qui retourne rien.

J'ai bien ajouté FOAF dans les ontologies :

```js
    settings: {
      sparqlEndpoint: config.sparqlEndpoint,
      mainDataset: config.mainDataset,
      homeUrl: config.homeUrl,
      ontologies: [
        ...config.ontologies,
        {
          prefix: 'foaf',
          url: 'http://xmlns.com/foaf/0.1/'
        }
      ]
    }
```

**Comment by GuillaumeAV** [comment]
Tu pourrais utiliser l'ontologie Pair aussi ?
http://virtual-assembly.org/ontologies/pair/index-fr.html


Le mar. 7 janv. 2020 à 22:52, Sébastien Rosset <notifications@github.com> a
écrit :

**Comment by simonLouvet** [comment]
Je n'ai pas réussi à reproduire le bug mais j'ai eu d'autres problèmes qui doivent être liés.
J'ai pas vraiment compris pourquoi mais l'ontologie foaf ne peut pas être directement la valeur de @context. Je pense que il existe une liste d'ontologie directement reconnus en json-ld (as, schema...) qui peuvent être directement la valeur de @context et que les autre ontologies doivent respecter un pattern plus strict. J'ai donc réussi à post des foaf:personnes avec ces body

```javascript
{
  "@context": {
    "@vocab": "http://xmlns.com/foaf/0.1/"
  },
 "@type": "Person",
 "name": "Sebastien ROSSET",
 "givenName": "Sébastien",
 "familyName": "ROSSET",
 "mbox": "mailto:srosset81@gmail.com"
}
```
```javascript
{
 "@context":{
   "foaf": "http://xmlns.com/foaf/0.1/"
 } ,
 "@type": "foaf:Person",
 "foaf:name": "Sebastien ROSSET",
 "foaf:givenName": "Sébastien",
 "foaf:familyName": "ROSSET",
 "foaf:mbox": "mailto:srosset81@gmail.com"
}
```
j'ai eu un problème d'id avec ces pattern que j'ai corrigé dans ce bugfix
https://github.com/assemblee-virtuelle/semapps/pull/110

**Comment by srosset81** [comment]
Même en utilisant `@id` au lieu de `id`, cela ne marche pas :
```
{
  '@context': 'http://xmlns.com/foaf/0.1/',
  '@id': 'http://localhost:3000/ldp/foaf:Person/1e5a8330',
  nick: 'srosset81',
  email: 'srosset81@gmail.com',
  name: 'Sébastien',
  familyName: 'Rosset'
}
```
Tandis que ça ça marche effectivement bien:
```
{
  '@context': { foaf: 'http://xmlns.com/foaf/0.1/' },
  '@id': 'http://localhost:3000/ldp/foaf:Person/1e5a8330',
  'foaf:nick': nick,
  'foaf:email': email,
  'foaf:name': name,
  'foaf:familyName': familyName
}
```
Pour moi le bug est toujours là, alors je réouvre l'issue pour qu'on en reste conscients.

**Comment by simonLouvet** [comment]
Comme écrit ci dessus un json-ld foaf avec l'ontologie directemetn dans le @context, ce n'est pas valide.
Tu peux le tester sur  https://json-ld.org/playground/
```javascript
{
  "@context": "http://xmlns.com/foaf/0.1/",
  "@type": "Person",
  "nick": "srosset81",
  "email": "srosset81@gmail.com",
  "name": "Sébastien",
  "familyName": "Rosset"
}
```
n'est pas valide

```javascript
{
 "@context": "https://www.w3.org/ns/activitystreams",
 "@type": "Note",
 "name": "Hello World",
 "content": "Voilà mon premier message, très content de faire partie du fedivers !",
 "published": "2019-05-28T12:12:12Z"
}
```
est valide

**Comment by srosset81** [comment]
@simonLouvet OK je comprend, mais comment on fait pour le gérer proprement avec SemApps ? Il faudrait que le @context auto-généré par LDP service (via `getPrefixJSON`) utilise @vocab comme tu suggérais dans ton précédent post, non ? Du coup ajouter peut-être un paramètre sur le fichier `ontologies.json` pour indiquer cette particularité de FOAF.

Si on ne le fais pas, on va régulièrement avoir ce type de problèmes qui vont remonter.

**Comment by simonLouvet** [comment]
solution 1 : utiliser systématiquement @vocab
solution 2 : utiliser @vocab en fonction d'un paramètre de config des otologies

Préférence pour l'option 1.
@nikoPLP ton avis?

**Comment by tfrancart** [comment]
@context dans un JSON-LD doit référencer une URI qui retourne un fichier JSON-LD valide décrivant un @context. Ce qui n'est pas le cas pour l'URI de l'ontologie FOAF.
Effectivement, il ne faut pas confondre @context et @vocab, qui déclare simplement l'espace de nom par défaut de toutes les clés qui ne pourraient pas être mappées sur des URIs via un préfixes ou qui ne sont pas elles-mêmes déjà des URIs.

Il ne faut pas chercher un fichier de context générique à FOAF, car chaque application pourrait choisir de mapper la même ontologie sur des clés JSON spécifiques. D'après https://github.com/json-ld/json-ld.org/wiki/existing-contexts, un context JSON-LD pour FOAF est accessible à http://xmlns.com/foaf/context, cependant ce context semble très incomplet par rapport à FOAF.

Par rapport à l'écosystème d'ontologies couramment utilisées, une possibilité serait d'utiliser le context des vocabulaires par défaut de RDFa, accessible à https://www.w3.org/2013/json-ld-context/rdfa11, et donc d'utiliser ces préfixes pour les ontologies les plus courantes.

**Comment by srosset81** [comment]
Merci pour les précisions qui ont le mérite d'être clairs !

> Par rapport à l'écosystème d'ontologies couramment utilisées, une possibilité serait d'utiliser le context des vocabulaires par défaut de RDFa, accessible à https://www.w3.org/2013/json-ld-context/rdfa11, et donc d'utiliser ces préfixes pour les ontologies les plus courantes.

Assez partant pour ma part pour utiliser ces préfixes "standardisés".
