### ISSUE TITLE
LDP PATCH gère mal les mise à jour de named Node

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#977]
**Décrivez le bug**
LDP PATCH gère mal les mise à jour de named Node.
Les prédicats de named Node ne sont pas mis à jour.

**Etapes pour reproduire**
1. vérifier une donnée par un Get
```
{
	"@context": "http://localhost:3000/context.json",
	"id": "http://localhost:3000/organizations/first-orga",
	"type": "pair:Organization",
	"dc:created": "2022-05-23T16:05:17.609Z",
	"dc:creator": "http://localhost:3000/users/simon.louvet.zen",
	"dc:modified": "2022-05-23T22:40:30.953Z",
	"pair:hasTopic": [
		"http://localhost:3000/themes/theme-2",
		"http://localhost:3000/themes/theme-1"
	],
	"pair:label": "first orga"
}
```
2. Faire un Patch sur cette ressource
```
{
	"@context": "http://localhost:3000/context.json",
	"pair:hasTopic": [
		"http://localhost:3000/themes/theme-1"
	],
}
```
3 vérifier la modification en faisant de nouveau un Get
```
{
	"@context": "http://localhost:3000/context.json",
	"id": "http://localhost:3000/organizations/first-orga",
	"type": "pair:Organization",
	"dc:created": "2022-05-23T16:05:17.609Z",
	"dc:creator": "http://localhost:3000/users/simon.louvet.zen",
	"dc:modified": "2022-05-23T22:40:30.953Z",
	"pair:hasTopic": [
		"http://localhost:3000/themes/theme-2",
		"http://localhost:3000/themes/theme-1"
	],
	"pair:label": "first orga"
}
```

Le predicat `pair:hasTopic` n'a pas été modifié

**Comportement attendu**
prise en compte du predicat à modifier
```
{
	"@context": "http://localhost:3000/context.json",
	"id": "http://localhost:3000/organizations/first-orga",
	"type": "pair:Organization",
	"dc:created": "2022-05-23T16:05:17.609Z",
	"dc:creator": "http://localhost:3000/users/simon.louvet.zen",
	"dc:modified": "2022-05-23T22:40:30.953Z",
	"pair:hasTopic": [
		"http://localhost:3000/themes/theme-1"
	],
	"pair:label": "first orga"
}
```

**Comment by srosset81** [comment]
@simonLouvet Attention, ce n'est pas un bug mais le comportement attendu pour la méthode PATCH !
En effet, si certaines données ne sont pas indiquées dans la requête PATCH, on assume qu'on veut les garder. Leur absence ne signifie pas une volonté d'effacer. Dans ton exemple, si le `pair:label` n'était pas indiqué dans la requête PATCH, celui-ci resterait inchangé. Si on veut effacer une donnée, il faut donc obligatoirement passer par un PUT.
La méthode PATCH fonctionne de cette manière pour les arrays (qui ne sont que plusieurs triplets...) depuis le début. Modifier ce comportement casserait le code sur de nombreux projets.

**Comment by simonLouvet** [comment]
@srosset81 Je n'ai pas besoin d'un comportement différent pour le moment donc on laisse tel quel. Cependant les sp"cification ne sont pas claire concernant LDP PATH :
https://www.w3.org/2012/ldp/hg/ldp.html#ldpr-resource
https://datatracker.ietf.org/doc/html/rfc5789

Il est essentiellement question du cycle de vie de la donnée et que un PUT remplace alors qu'un PATCH modifie. Rien ne spécifie comment modifier.
Je suis d'accord que une absence de prédicat indique qu'il n'y a pas de changement attendu sur l'ancienne valeur/objet de ce prédicat (`pair:label` que tu prends en exemple). Cependant lors ce que un prédicat est transmis dans le body du patch avec une/des valeurs/objets il me semble que la logique voudrait que les valeurs/objets de ce prédicat soi mis à jour. J'ai modifié l'exemple  pour éviter les confusions (`pair:hasTopic`).

On laisse en l'état et je reviens sur cette issue si ce comportement pose problème (dépendances d'autres issues).

**Comment by srosset81** [comment]
@simonLouvet C'est parce que tu considères

```
"pair:hasTopic": [
  "http://localhost:3000/themes/theme-2",
  "http://localhost:3000/themes/theme-1"
]
```

... comme **une** donnée sous forme d'array alors qu'il s'agit en réalité de **deux** triplets différents, qui sont combinés parce que c'est comme ça que JSON-LD formatte les données.

Si tu passais la même requête en format Turtle, tu ne t'attendrais pas à ce que http://localhost:3000/themes/theme-2 soit effacé.

Tu parles de "named node" mais il ne s'agit pas de ça. Un named node c'est juste une ressource avec un ID, en opposé à un blank node. Ici il n'y a ni named node, ni blank node (il y aurait un blank node si on utilisait un objet au lieu d'un array).

Je ne vois aucune ambiguité et propose de fermer cette issue afin de ne pas nous charger inutilement.

**Comment by simonLouvet** [comment]
Je suis d’accord avec l'argument de raisonner en triplet et d'imaginer le comportement attendu si le body était sérialisé en Turtle et je suis d'accord avec le résultat attendu avec ce paradigme.
