### ISSUE TITLE
Quand on efface un utilisateur, aussi effacer tous les droits ACL associés

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#980]
A implémenter dans le WebAclMiddleware ?

**Comment by nikoPLP** [comment]
From https://semapps.org/docs/others/ACL

> If one day you program an action to delete a user profile, after deleting the user resource, please also call the removeAgentGroupOrAgentFromAuthorizations method, with a isGroup=false parameter.

**Comment by srosset81** [comment]
Je ferme car duplicate de #982
