### ISSUE TITLE
Le POST et PUT en Turtle ne fonctionne plus

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#995]
C'est pourtant nécessaire si on veut être compatible LDP.

Voir discussions https://github.com/assemblee-virtuelle/semapps/pull/987#discussion_r895910826

Il faudra sans doute revoir le code fait par Niko afin d'utiliser à nouveau `resource` directement (sans `resource.body`)

Ajouter des tests pour éviter des régressions.

**Comment by nikoPLP** [comment]
Il n'y a plus rien dans le code qui pourrait faire amrcher du Turtle dans les POST et PUT.
je ne sais pas a quel moment le code a disparu.
Quand vous aurez décider de quoi faire, en effet il faudra harmoniser `ldp.resource.create` et peut etre aussi le PATCh sur container, qui utilisent tous les deux le `resource.body`

**Comment by srosset81** [comment]
> Il n'y a plus rien dans le code qui pourrait faire amrcher du Turtle dans les POST et PUT.

Faut pas dramatiser non plus :smile: Le problème est apparu sans doute quand j'ai séparé `ldp.container.post` et `ldp.resource.create`. Je crois avoir refactoré les actions put et patch à ce moment, en assumant avoir un objet. Je pense pas que c'est un gros travail de revenir à ce qui marchait avant.

**Comment by srosset81** [comment]
Closed in favor of https://github.com/assemblee-virtuelle/semapps/issues/1226
