### ISSUE TITLE
Le paramètre excludeFromMirror cache les containers de l'endpoint VOID

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#998]
C'est embêtant que le nouveau paramètre `excludeFromMirror` introduit dans https://github.com/assemblee-virtuelle/semapps/pull/987 a pour effet de ne pas afficher les containers dans l'endpoint VOID.

On peut vouloir qu'un container ne soit pas "mirroirable" mais tout de même avoir besoin qu'il apparaisse sur l'endpoint VOID, surtout pour le frontend puisse connaître son existence.

Cela pourrait être cohérent de différencier `excludeFromMirror` de `excludeFromVoid` ... mais en même temps, je ne suis pas sûr que `excludeFromVoid` soit nécessaire.

@nikoPLP Est-ce qu'il n'y a pas un autre moyen d'informer les autres serveurs qu'il ne faut pas "refléter" (ce serait l'équivalent français du verbe "mirror") un container, sans pour autant l'exclure de l'endpoint VOID ?

**Comment by nikoPLP** [comment]
il faudrait rajouter un triple dans la reponse VOID qui indique a semapps de ne pas prendre ce container. 
Ce triple sera forcement avec un prédicat de l'ontologie semapps, et pas void.
Je ne pense pas que ce soit un probleme.
par exemple `http://semapps.org/ns/core#doNotMirror` pourrait etre ajouté dans les classPartitions de la reponse void, pour tous les containers qui auraient le setting `excludeFromMirror`

**Comment by srosset81** [comment]
Ca me semble être une bonne solution :+1:

**Comment by srosset81** [comment]
@nikoPLP Tu veux que je m'en occupe ou tu le fais en même temps que #1004 ?

**Comment by srosset81** [comment]
Ping @nikoPLP

**Comment by nikoPLP** [comment]
oui je m'en occuperai avec l'autre issue
